import type { ExportWordTemplates } from "./types";

/** Български: the fixed words in exports. */
export const bg: ExportWordTemplates = {
  beforeYouStart: "Преди да започнете",
  youreDone: "Готово",
  madeWith: "Създадено със Steps",
  preparedBy: "Изготвено от {name}",
  page: "Страница {current} от {total}",
  output: "Изход",
  outputLines: { one: "{count} ред", other: "{count} реда" },
  shortened: "съкратено",
  copy: "Копирай",
  copied: "Копирано",
  contents: "Съдържание",
  firstSteps: "Първи стъпки",
  untitledSection: "Раздел без заглавие",
  step: "Стъпка {number}",
  steps: "Стъпки {first}–{last}",
  documentControl: "Контрол на документа",
  control: {
    title: "Заглавие",
    owner: "Собственик",
    preparedBy: "Изготвено от",
    created: "Създадено",
    updated: "Последна актуализация",
    reviewBy: "Преглед до",
    exported: "Експортирано",
    notSet: "Не е зададено",
    history: "История на версиите",
    date: "Дата",
    by: "От",
    note: "Версия",
    steps: "Стъпки",
    noVersions: "Все още няма запазени версии.",
  },
  dateBy: "{date} от {by}",
  stepCount: { one: "{count} стъпка", other: "{count} стъпки" },
  minutes: "около {minutes} мин",
  untitledGuide: "Ръководство без заглавие",
  screenshotFor: "Екранна снимка за стъпка {number}: {text}",
  callouts: { note: "ЗАБЕЛЕЖКА", tip: "СЪВЕТ", warning: "ПРЕДУПРЕЖДЕНИЕ", important: "ВАЖНО" },
  codeLabels: { cmd: "Команден ред", excel: "Формула на Excel" },
  player: {
    play: "Възпроизвеждане",
    pause: "Пауза",
    speed: "Скорост",
    reduceMotion: "Намаляване на движението",
    allSteps: "Преглед на всички стъпки",
    backToPlayer: "Обратно към ръководството",
    fullScreen: "Цял екран",
    thumbnails: "Стъпки",
    back: "Назад",
    next: "Напред",
    start: "Начало",
    startAgain: "Започни отначало",
    goToStep: "Към стъпка {number}",
    percentDone: "{percent}% готово",
    stepCard: "Текуща стъпка",
    announce: "Стъпка {number} от {total}: {text}. {alt}",
    language: "Език",
  },
};
