import type { ExportWordTemplates } from "./types";

/** Català: the words exports use, in Catalan ("vós", «» quotes). */
export const ca: ExportWordTemplates = {
  beforeYouStart: "Abans de començar",
  youreDone: "Ja heu acabat",
  madeWith: "Fet amb Steps",
  preparedBy: "Preparat per {name}",
  page: "Pàgina {current} de {total}",
  output: "Sortida",
  outputLines: { one: "{count} línia", many: "{count} línies", other: "{count} línies" },
  shortened: "escurçada",
  copy: "Copia",
  copied: "Copiat",
  contents: "Índex",
  firstSteps: "Primers passos",
  untitledSection: "Secció sense títol",
  step: "Pas {number}",
  steps: "Passos {first}–{last}",
  documentControl: "Control del document",
  control: {
    title: "Títol",
    owner: "Propietari",
    preparedBy: "Preparat per",
    created: "Data de creació",
    updated: "Darrera actualització",
    reviewBy: "Data de revisió",
    exported: "Data d'exportació",
    notSet: "Sense definir",
    history: "Historial de versions",
    date: "Data",
    by: "Per",
    note: "Versió",
    steps: "Passos",
    noVersions: "Encara no s'ha desat cap versió.",
  },
  dateBy: "{date}, per {by}",
  stepCount: { one: "{count} pas", many: "{count} passos", other: "{count} passos" },
  minutes: "uns {minutes} min",
  untitledGuide: "Guia sense títol",
  screenshotFor: "Captura de pantalla del pas {number}: {text}",
  callouts: { note: "NOTA", tip: "CONSELL", warning: "ADVERTIMENT", important: "IMPORTANT" },
  codeLabels: { cmd: "Indicador d'ordres", excel: "Fórmula de l'Excel" },
  player: {
    play: "Reprodueix",
    pause: "Pausa",
    speed: "Velocitat",
    reduceMotion: "Redueix el moviment",
    allSteps: "Mostra tots els passos",
    backToPlayer: "Torna a la demostració",
    fullScreen: "Pantalla completa",
    thumbnails: "Passos",
    back: "Enrere",
    next: "Següent",
    start: "Comença",
    startAgain: "Torna a començar",
    goToStep: "Ves al pas {number}",
    percentDone: "{percent} % fet",
    stepCard: "Pas actual",
    announce: "Pas {number} de {total}: {text}. {alt}",
    language: "Idioma",
  },
};
