import type { ExportWordTemplates } from "./types";

/** Čeština: the words exports use, with the reader addressed formally as Windows does („Než začnete“). */
export const cs: ExportWordTemplates = {
  beforeYouStart: "Než začnete",
  youreDone: "Hotovo",
  madeWith: "Vytvořeno v aplikaci Steps",
  preparedBy: "Zpracovatel: {name}",
  page: "Stránka {current} z {total}",
  output: "Výstup",
  outputLines: {
    one: "{count} řádek",
    few: "{count} řádky",
    many: "{count} řádků",
    other: "{count} řádků",
  },
  shortened: "zkráceno",
  copy: "Kopírovat",
  copied: "Zkopírováno",
  contents: "Obsah",
  firstSteps: "První kroky",
  untitledSection: "Oddíl bez názvu",
  step: "Krok {number}",
  steps: "Kroky {first}–{last}",
  documentControl: "Údaje o dokumentu",
  control: {
    title: "Název",
    owner: "Vlastník",
    preparedBy: "Zpracovatel",
    created: "Vytvořeno",
    updated: "Poslední aktualizace",
    reviewBy: "Revize do",
    exported: "Exportováno",
    notSet: "Nenastaveno",
    history: "Historie verzí",
    date: "Datum",
    by: "Autor",
    note: "Verze",
    steps: "Kroky",
    noVersions: "Zatím nejsou uložené žádné verze.",
  },
  dateBy: "{date}, {by}",
  stepCount: {
    one: "{count} krok",
    few: "{count} kroky",
    many: "{count} kroků",
    other: "{count} kroků",
  },
  minutes: "asi {minutes} min",
  untitledGuide: "Návod bez názvu",
  screenshotFor: "Snímek obrazovky ke kroku {number}: {text}",
  callouts: { note: "POZNÁMKA", tip: "TIP", warning: "UPOZORNĚNÍ", important: "DŮLEŽITÉ" },
  codeLabels: { cmd: "Příkazový řádek", excel: "Vzorec Excelu" },
  player: {
    play: "Přehrát",
    pause: "Pozastavit",
    speed: "Rychlost",
    reduceMotion: "Omezit animace",
    allSteps: "Zobrazit všechny kroky",
    backToPlayer: "Zpět k přehrávání",
    fullScreen: "Celá obrazovka",
    thumbnails: "Kroky",
    back: "Zpět",
    next: "Další",
    start: "Začít",
    startAgain: "Začít znovu",
    goToStep: "Přejít na krok {number}",
    percentDone: "Hotovo {percent} %",
    stepCard: "Aktuální krok",
    announce: "Krok {number} z {total}: {text}. {alt}",
    language: "Jazyk",
  },
};
