import type { ExportWordTemplates } from "./types";

/** Dansk: the words every export uses. */
export const da: ExportWordTemplates = {
  beforeYouStart: "Før du starter",
  youreDone: "Så er du færdig",
  madeWith: "Lavet med Steps",
  preparedBy: "Udarbejdet af {name}",
  page: "Side {current} af {total}",
  output: "Output",
  outputLines: { one: "{count} linje", other: "{count} linjer" },
  shortened: "forkortet",
  copy: "Kopiér",
  copied: "Kopieret",
  contents: "Indhold",
  firstSteps: "De første trin",
  untitledSection: "Afsnit uden titel",
  step: "Trin {number}",
  steps: "Trin {first}–{last}",
  documentControl: "Dokumentstyring",
  control: {
    title: "Titel",
    owner: "Ejer",
    preparedBy: "Udarbejdet af",
    created: "Oprettet",
    updated: "Senest opdateret",
    reviewBy: "Gennemgås senest",
    exported: "Eksporteret",
    notSet: "Ikke angivet",
    history: "Versionshistorik",
    date: "Dato",
    by: "Af",
    note: "Version",
    steps: "Trin",
    noVersions: "Der er ikke gemt nogen versioner endnu.",
  },
  dateBy: "{date} af {by}",
  stepCount: { one: "{count} trin", other: "{count} trin" },
  minutes: "ca. {minutes} min.",
  untitledGuide: "Vejledning uden titel",
  screenshotFor: "Skærmbillede til trin {number}: {text}",
  callouts: { note: "BEMÆRK", tip: "TIP", warning: "ADVARSEL", important: "VIGTIGT" },
  codeLabels: { cmd: "Kommandoprompt", excel: "Excel-formel" },
  player: {
    play: "Afspil",
    pause: "Pause",
    speed: "Hastighed",
    reduceMotion: "Reducer bevægelse",
    allSteps: "Vis alle trin",
    backToPlayer: "Tilbage til gennemgangen",
    fullScreen: "Fuld skærm",
    thumbnails: "Trin",
    back: "Tilbage",
    next: "Næste",
    start: "Start",
    startAgain: "Start forfra",
    goToStep: "Gå til trin {number}",
    percentDone: "{percent} % færdig",
    stepCard: "Aktuelt trin",
    announce: "Trin {number} af {total}: {text}. {alt}",
    language: "Sprog",
  },
};
