import type { ExportWordTemplates } from "./types";

/** Deutsch: the words in exported guides, addressing the reader as "Sie". */
export const de: ExportWordTemplates = {
  beforeYouStart: "Bevor Sie beginnen",
  youreDone: "Fertig",
  madeWith: "Erstellt mit Steps",
  preparedBy: "Erstellt von {name}",
  page: "Seite {current} von {total}",
  output: "Ausgabe",
  outputLines: { one: "{count} Zeile", other: "{count} Zeilen" },
  shortened: "gekürzt",
  copy: "Kopieren",
  copied: "Kopiert",
  contents: "Inhalt",
  firstSteps: "Erste Schritte",
  untitledSection: "Abschnitt ohne Titel",
  step: "Schritt {number}",
  steps: "Schritte {first}–{last}",
  documentControl: "Dokumentenlenkung",
  control: {
    title: "Titel",
    owner: "Verantwortlich",
    preparedBy: "Erstellt von",
    created: "Erstellt am",
    updated: "Zuletzt aktualisiert",
    reviewBy: "Prüfen bis",
    exported: "Exportiert am",
    notSet: "Nicht festgelegt",
    history: "Versionsverlauf",
    date: "Datum",
    by: "Von",
    note: "Version",
    steps: "Schritte",
    noVersions: "Noch keine Versionen gespeichert.",
  },
  dateBy: "{date} von {by}",
  stepCount: { one: "{count} Schritt", other: "{count} Schritte" },
  minutes: "ca. {minutes} Min.",
  untitledGuide: "Anleitung ohne Titel",
  screenshotFor: "Screenshot zu Schritt {number}: {text}",
  callouts: { note: "HINWEIS", tip: "TIPP", warning: "WARNUNG", important: "WICHTIG" },
  codeLabels: { cmd: "Eingabeaufforderung", excel: "Excel-Formel" },
  player: {
    play: "Abspielen",
    pause: "Pause",
    speed: "Geschwindigkeit",
    reduceMotion: "Bewegung reduzieren",
    allSteps: "Alle Schritte anzeigen",
    backToPlayer: "Zurück zur Wiedergabe",
    fullScreen: "Vollbild",
    thumbnails: "Schritte",
    back: "Zurück",
    next: "Weiter",
    start: "Starten",
    startAgain: "Von vorn beginnen",
    goToStep: "Zu Schritt {number}",
    percentDone: "{percent} % erledigt",
    stepCard: "Aktueller Schritt",
    announce: "Schritt {number} von {total}: {text}. {alt}",
    language: "Sprache",
  },
};
