import type { ExportWordTemplates } from "./types";

/** Ελληνικά: the words exports use, with Greek quotation marks and the polite plural. */
export const el: ExportWordTemplates = {
  beforeYouStart: "Πριν ξεκινήσετε",
  youreDone: "Τελειώσατε",
  madeWith: "Δημιουργήθηκε με το Steps",
  preparedBy: "Συντάχθηκε από: {name}",
  page: "Σελίδα {current} από {total}",
  output: "Έξοδος",
  outputLines: { one: "{count} γραμμή", other: "{count} γραμμές" },
  shortened: "συντομευμένο",
  copy: "Αντιγραφή",
  copied: "Αντιγράφηκε",
  contents: "Περιεχόμενα",
  firstSteps: "Πρώτα βήματα",
  untitledSection: "Ενότητα χωρίς τίτλο",
  step: "Βήμα {number}",
  steps: "Βήματα {first}–{last}",
  documentControl: "Έλεγχος εγγράφου",
  control: {
    title: "Τίτλος",
    owner: "Κάτοχος",
    preparedBy: "Συντάχθηκε από",
    created: "Δημιουργία",
    updated: "Τελευταία ενημέρωση",
    reviewBy: "Αναθεώρηση έως",
    exported: "Εξαγωγή",
    notSet: "Δεν έχει οριστεί",
    history: "Ιστορικό εκδόσεων",
    date: "Ημερομηνία",
    by: "Από",
    note: "Έκδοση",
    steps: "Βήματα",
    noVersions: "Δεν έχουν αποθηκευτεί εκδόσεις ακόμα.",
  },
  dateBy: "{date}, από {by}",
  stepCount: { one: "{count} βήμα", other: "{count} βήματα" },
  minutes: "περίπου {minutes} λεπτά",
  untitledGuide: "Οδηγός χωρίς τίτλο",
  screenshotFor: "Στιγμιότυπο οθόνης για το βήμα {number}: {text}",
  callouts: {
    note: "ΣΗΜΕΙΩΣΗ",
    tip: "ΣΥΜΒΟΥΛΗ",
    warning: "ΠΡΟΕΙΔΟΠΟΙΗΣΗ",
    important: "ΣΗΜΑΝΤΙΚΟ",
  },
  codeLabels: { cmd: "Γραμμή εντολών", excel: "Τύπος Excel" },
  player: {
    play: "Αναπαραγωγή",
    pause: "Παύση",
    speed: "Ταχύτητα",
    reduceMotion: "Λιγότερη κίνηση",
    allSteps: "Προβολή όλων των βημάτων",
    backToPlayer: "Επιστροφή στην παρουσίαση",
    fullScreen: "Πλήρης οθόνη",
    thumbnails: "Βήματα",
    back: "Πίσω",
    next: "Επόμενο",
    start: "Έναρξη",
    startAgain: "Έναρξη από την αρχή",
    goToStep: "Μετάβαση στο βήμα {number}",
    percentDone: "Ολοκληρώθηκε {percent}%",
    stepCard: "Τρέχον βήμα",
    announce: "Βήμα {number} από {total}: {text}. {alt}",
    language: "Γλώσσα",
  },
};
