import type { ExportWordTemplates } from "./types";

/**
 * English: the words exports have always used. Other languages translate these
 * (packages/export/src/words/<code>.ts); `{slots}` are filled in, and counted words have a form
 * per plural category (Intl.PluralRules).
 */
export const en: ExportWordTemplates = {
  beforeYouStart: "Before you start",
  youreDone: "You're done",
  madeWith: "Made with Steps",
  preparedBy: "Prepared by {name}",
  page: "Page {current} of {total}",
  output: "Output",
  outputLines: { one: "{count} line", other: "{count} lines" },
  shortened: "shortened",
  copy: "Copy",
  copied: "Copied",
  contents: "Contents",
  firstSteps: "First steps",
  untitledSection: "Untitled section",
  step: "Step {number}",
  steps: "Steps {first}–{last}",
  documentControl: "Document control",
  control: {
    title: "Title",
    owner: "Owner",
    preparedBy: "Prepared by",
    created: "Created",
    updated: "Last updated",
    reviewBy: "Review by",
    exported: "Exported",
    notSet: "Not set",
    history: "Version history",
    date: "Date",
    by: "By",
    note: "Version",
    steps: "Steps",
    noVersions: "No versions saved yet.",
  },
  dateBy: "{date} by {by}",
  stepCount: { one: "{count} step", other: "{count} steps" },
  minutes: "about {minutes} min",
  untitledGuide: "Untitled guide",
  screenshotFor: "Screenshot for step {number}: {text}",
  callouts: { note: "NOTE", tip: "TIP", warning: "WARNING", important: "IMPORTANT" },
  codeLabels: { cmd: "Command Prompt", excel: "Excel formula" },
  player: {
    play: "Play",
    pause: "Pause",
    speed: "Speed",
    reduceMotion: "Reduce motion",
    allSteps: "View all steps",
    backToPlayer: "Back to the walkthrough",
    fullScreen: "Full screen",
    thumbnails: "Steps",
    back: "Back",
    next: "Next",
    start: "Start",
    startAgain: "Start again",
    goToStep: "Go to step {number}",
    percentDone: "{percent}% done",
    stepCard: "Current step",
    announce: "Step {number} of {total}: {text}. {alt}",
    language: "Language",
  },
};
