import type { ExportWordTemplates } from "./types";

/** Español: the words every export uses, speaking to the reader as "tú" like the app. */
export const es: ExportWordTemplates = {
  beforeYouStart: "Antes de empezar",
  youreDone: "Has terminado",
  madeWith: "Hecho con Steps",
  preparedBy: "Elaborado por {name}",
  page: "Página {current} de {total}",
  output: "Salida",
  outputLines: { one: "{count} línea", many: "{count} líneas", other: "{count} líneas" },
  shortened: "acortada",
  copy: "Copiar",
  copied: "Copiado",
  contents: "Índice",
  firstSteps: "Primeros pasos",
  untitledSection: "Sección sin título",
  step: "Paso {number}",
  steps: "Pasos {first}–{last}",
  documentControl: "Control del documento",
  control: {
    title: "Título",
    owner: "Propietario",
    preparedBy: "Elaborado por",
    created: "Creado",
    updated: "Última actualización",
    reviewBy: "Fecha de revisión",
    exported: "Exportado",
    notSet: "Sin definir",
    history: "Historial de versiones",
    date: "Fecha",
    by: "Autor",
    note: "Versión",
    steps: "Pasos",
    noVersions: "Aún no hay versiones guardadas.",
  },
  dateBy: "{date} por {by}",
  stepCount: { one: "{count} paso", many: "{count} pasos", other: "{count} pasos" },
  minutes: "unos {minutes} min",
  untitledGuide: "Guía sin título",
  screenshotFor: "Captura del paso {number}: {text}",
  callouts: {
    note: "NOTA",
    tip: "SUGERENCIA",
    warning: "ADVERTENCIA",
    important: "IMPORTANTE",
  },
  codeLabels: { cmd: "Símbolo del sistema", excel: "Fórmula de Excel" },
  player: {
    play: "Reproducir",
    pause: "Pausar",
    speed: "Velocidad",
    reduceMotion: "Reducir movimiento",
    allSteps: "Ver todos los pasos",
    backToPlayer: "Volver al recorrido",
    fullScreen: "Pantalla completa",
    thumbnails: "Pasos",
    back: "Atrás",
    next: "Siguiente",
    start: "Empezar",
    startAgain: "Empezar de nuevo",
    goToStep: "Ir al paso {number}",
    percentDone: "{percent} % completado",
    stepCard: "Paso actual",
    announce: "Paso {number} de {total}: {text}. {alt}",
    language: "Idioma",
  },
};
