import type { ExportWordTemplates } from "./types";

/** Eesti: the fixed words of exports, in the polite form of address used across Steps. */
export const et: ExportWordTemplates = {
  beforeYouStart: "Enne alustamist",
  youreDone: "Valmis",
  madeWith: "Tehtud Stepsiga",
  preparedBy: "Koostaja: {name}",
  page: "Leht {current}/{total}",
  output: "Väljund",
  outputLines: { one: "{count} rida", other: "{count} rida" },
  shortened: "lühendatud",
  copy: "Kopeeri",
  copied: "Kopeeritud",
  contents: "Sisukord",
  firstSteps: "Esimesed sammud",
  untitledSection: "Pealkirjata jaotis",
  step: "Samm {number}",
  steps: "Sammud {first}–{last}",
  documentControl: "Dokumendi andmed",
  control: {
    title: "Pealkiri",
    owner: "Omanik",
    preparedBy: "Koostaja",
    created: "Loodud",
    updated: "Viimati uuendatud",
    reviewBy: "Ülevaatamise tähtaeg",
    exported: "Eksporditud",
    notSet: "Määramata",
    history: "Versiooniajalugu",
    date: "Kuupäev",
    by: "Autor",
    note: "Versioon",
    steps: "Sammud",
    noVersions: "Versioone pole veel salvestatud.",
  },
  dateBy: "{date}, {by}",
  stepCount: { one: "{count} samm", other: "{count} sammu" },
  minutes: "umbes {minutes} min",
  untitledGuide: "Pealkirjata juhend",
  screenshotFor: "Sammu {number} kuvatõmmis: {text}",
  callouts: { note: "MÄRKUS", tip: "NÕUANNE", warning: "HOIATUS", important: "OLULINE" },
  codeLabels: { cmd: "Käsuviip", excel: "Exceli valem" },
  player: {
    play: "Esita",
    pause: "Peata",
    speed: "Kiirus",
    reduceMotion: "Vähenda liikumist",
    allSteps: "Vaata kõiki samme",
    backToPlayer: "Tagasi läbimängimise juurde",
    fullScreen: "Täisekraan",
    thumbnails: "Sammud",
    back: "Tagasi",
    next: "Edasi",
    start: "Alusta",
    startAgain: "Alusta uuesti",
    goToStep: "Mine sammu {number} juurde",
    percentDone: "{percent}% tehtud",
    stepCard: "Praegune samm",
    announce: "Samm {number}/{total}: {text}. {alt}",
    language: "Keel",
  },
};
