import type { ExportWordTemplates } from "./types";

/** Suomi: the words every export uses. */
export const fi: ExportWordTemplates = {
  beforeYouStart: "Ennen kuin aloitat",
  youreDone: "Valmista tuli",
  madeWith: "Tehty Stepsillä",
  preparedBy: "Laatinut: {name}",
  page: "Sivu {current}/{total}",
  output: "Tuloste",
  outputLines: { one: "{count} rivi", other: "{count} riviä" },
  shortened: "lyhennetty",
  copy: "Kopioi",
  copied: "Kopioitu",
  contents: "Sisällys",
  firstSteps: "Ensimmäiset vaiheet",
  untitledSection: "Nimetön osio",
  step: "Vaihe {number}",
  steps: "Vaiheet {first}–{last}",
  documentControl: "Asiakirjan hallinta",
  control: {
    title: "Otsikko",
    owner: "Omistaja",
    preparedBy: "Laatinut",
    created: "Luotu",
    updated: "Päivitetty viimeksi",
    reviewBy: "Tarkistettava viimeistään",
    exported: "Viety",
    notSet: "Ei määritetty",
    history: "Versiohistoria",
    date: "Päivämäärä",
    by: "Tekijä",
    note: "Versio",
    steps: "Vaiheet",
    noVersions: "Versioita ei ole vielä tallennettu.",
  },
  dateBy: "{date}, {by}",
  stepCount: { one: "{count} vaihe", other: "{count} vaihetta" },
  minutes: "noin {minutes} min",
  untitledGuide: "Nimetön ohje",
  screenshotFor: "Näyttökuva vaiheeseen {number}: {text}",
  callouts: { note: "HUOMAUTUS", tip: "VIHJE", warning: "VAROITUS", important: "TÄRKEÄÄ" },
  codeLabels: { cmd: "Komentokehote", excel: "Excel-kaava" },
  player: {
    play: "Toista",
    pause: "Keskeytä",
    speed: "Nopeus",
    reduceMotion: "Vähennä liikettä",
    allSteps: "Näytä kaikki vaiheet",
    backToPlayer: "Takaisin esitykseen",
    fullScreen: "Koko näyttö",
    thumbnails: "Vaiheet",
    back: "Takaisin",
    next: "Seuraava",
    start: "Aloita",
    startAgain: "Aloita alusta",
    goToStep: "Siirry vaiheeseen {number}",
    percentDone: "{percent} % valmiina",
    stepCard: "Nykyinen vaihe",
    announce: "Vaihe {number}/{total}: {text}. {alt}",
    language: "Kieli",
  },
};
