import type { ExportWordTemplates } from "./types";

/** Français: the words exports use, in French ("vous", « » quotes, no-break spaces before : and %). */
export const fr: ExportWordTemplates = {
  beforeYouStart: "Avant de commencer",
  youreDone: "Vous avez terminé",
  madeWith: "Créé avec Steps",
  preparedBy: "Préparé par {name}",
  page: "Page {current} sur {total}",
  output: "Sortie",
  outputLines: { one: "{count} ligne", many: "{count} lignes", other: "{count} lignes" },
  shortened: "raccourcie",
  copy: "Copier",
  copied: "Copié",
  contents: "Table des matières",
  firstSteps: "Premières étapes",
  untitledSection: "Section sans titre",
  step: "Étape {number}",
  steps: "Étapes {first} à {last}",
  documentControl: "Suivi du document",
  control: {
    title: "Titre",
    owner: "Propriétaire",
    preparedBy: "Préparé par",
    created: "Date de création",
    updated: "Dernière mise à jour",
    reviewBy: "Date de révision",
    exported: "Date d'exportation",
    notSet: "Non défini",
    history: "Historique des versions",
    date: "Date",
    by: "Par",
    note: "Version",
    steps: "Étapes",
    noVersions: "Aucune version enregistrée pour l'instant.",
  },
  dateBy: "{date} par {by}",
  stepCount: { one: "{count} étape", many: "{count} étapes", other: "{count} étapes" },
  minutes: "environ {minutes} min",
  untitledGuide: "Guide sans titre",
  screenshotFor: "Capture d'écran de l'étape {number} : {text}",
  callouts: {
    note: "REMARQUE",
    tip: "CONSEIL",
    warning: "AVERTISSEMENT",
    important: "IMPORTANT",
  },
  codeLabels: { cmd: "Invite de commandes", excel: "Formule Excel" },
  player: {
    play: "Lire",
    pause: "Pause",
    speed: "Vitesse",
    reduceMotion: "Réduire les animations",
    allSteps: "Voir toutes les étapes",
    backToPlayer: "Retour à la démonstration",
    fullScreen: "Plein écran",
    thumbnails: "Étapes",
    back: "Précédent",
    next: "Suivant",
    start: "Commencer",
    startAgain: "Recommencer",
    goToStep: "Aller à l'étape {number}",
    percentDone: "{percent} % terminé",
    stepCard: "Étape en cours",
    announce: "Étape {number} sur {total} : {text}. {alt}",
    language: "Langue",
  },
};
