import type { ExportWordTemplates } from "./types";

/** Gaeilge: the words exports use; counted words take the mutation each number needs. */
export const ga: ExportWordTemplates = {
  beforeYouStart: "Sula dtosaíonn tú",
  youreDone: "Tá tú réidh",
  madeWith: "Déanta le Steps",
  preparedBy: "Ullmhaithe ag {name}",
  page: "Leathanach {current} as {total}",
  output: "Aschur",
  outputLines: {
    one: "{count} líne",
    two: "{count} líne",
    few: "{count} líne",
    many: "{count} líne",
    other: "{count} líne",
  },
  shortened: "giorraithe",
  copy: "Cóipeáil",
  copied: "Cóipeáladh",
  contents: "Clár ábhair",
  firstSteps: "Na chéad chéimeanna",
  untitledSection: "Rannán gan teideal",
  step: "Céim {number}",
  steps: "Céimeanna {first}–{last}",
  documentControl: "Rialú cáipéise",
  control: {
    title: "Teideal",
    owner: "Úinéir",
    preparedBy: "Ullmhaithe ag",
    created: "Cruthaithe",
    updated: "Nuashonraithe go deireanach",
    reviewBy: "Athbhreithnigh faoi",
    exported: "Easpórtáilte",
    notSet: "Gan socrú",
    history: "Stair na leaganacha",
    date: "Dáta",
    by: "Ag",
    note: "Leagan",
    steps: "Céimeanna",
    noVersions: "Níl aon leagan sábháilte fós.",
  },
  dateBy: "{date} ag {by}",
  stepCount: {
    one: "{count} chéim",
    two: "{count} chéim",
    few: "{count} chéim",
    many: "{count} gcéim",
    other: "{count} céim",
  },
  minutes: "thart ar {minutes} nóim.",
  untitledGuide: "Treoir gan teideal",
  screenshotFor: "Gabháil scáileáin do chéim {number}: {text}",
  callouts: { note: "NÓTA", tip: "LEID", warning: "RABHADH", important: "TÁBHACHTACH" },
  codeLabels: { cmd: "Leid Ordaithe", excel: "Foirmle Excel" },
  player: {
    play: "Seinn",
    pause: "Cuir ar sos",
    speed: "Luas",
    reduceMotion: "Laghdaigh an ghluaiseacht",
    allSteps: "Féach ar gach céim",
    backToPlayer: "Ar ais chuig an tsiúlóid",
    fullScreen: "Lánscáileán",
    thumbnails: "Céimeanna",
    back: "Siar",
    next: "Ar aghaidh",
    start: "Tosaigh",
    startAgain: "Tosaigh arís",
    goToStep: "Téigh go céim {number}",
    percentDone: "{percent}% déanta",
    stepCard: "An chéim reatha",
    announce: "Céim {number} as {total}: {text}. {alt}",
    language: "Teanga",
  },
};
