import type { ExportWordTemplates } from "./types";

/** Hrvatski: the fixed words in exports. */
export const hr: ExportWordTemplates = {
  beforeYouStart: "Prije nego što počnete",
  youreDone: "Završili ste",
  madeWith: "Izrađeno pomoću aplikacije Steps",
  preparedBy: "Autor: {name}",
  page: "Stranica {current} od {total}",
  output: "Izlaz",
  outputLines: { one: "{count} redak", few: "{count} retka", other: "{count} redaka" },
  shortened: "skraćeno",
  copy: "Kopiraj",
  copied: "Kopirano",
  contents: "Sadržaj",
  firstSteps: "Prvi koraci",
  untitledSection: "Odjeljak bez naslova",
  step: "Korak {number}",
  steps: "Koraci {first}–{last}",
  documentControl: "Kontrola dokumenta",
  control: {
    title: "Naslov",
    owner: "Vlasnik",
    preparedBy: "Autor",
    created: "Izrađeno",
    updated: "Posljednje ažuriranje",
    reviewBy: "Pregledati do",
    exported: "Izvezeno",
    notSet: "Nije postavljeno",
    history: "Povijest verzija",
    date: "Datum",
    by: "Autor",
    note: "Verzija",
    steps: "Koraci",
    noVersions: "Još nema spremljenih verzija.",
  },
  dateBy: "{date}, {by}",
  stepCount: { one: "{count} korak", few: "{count} koraka", other: "{count} koraka" },
  minutes: "oko {minutes} min",
  untitledGuide: "Vodič bez naslova",
  screenshotFor: "Snimka zaslona za korak {number}: {text}",
  callouts: { note: "NAPOMENA", tip: "SAVJET", warning: "UPOZORENJE", important: "VAŽNO" },
  codeLabels: { cmd: "Naredbeni redak", excel: "Excel formula" },
  player: {
    play: "Reproduciraj",
    pause: "Pauziraj",
    speed: "Brzina",
    reduceMotion: "Smanji pokrete",
    allSteps: "Prikaži sve korake",
    backToPlayer: "Natrag na prikaz",
    fullScreen: "Cijeli zaslon",
    thumbnails: "Koraci",
    back: "Natrag",
    next: "Dalje",
    start: "Započni",
    startAgain: "Počni ponovno",
    goToStep: "Idi na korak {number}",
    percentDone: "Dovršeno {percent}%",
    stepCard: "Trenutačni korak",
    announce: "Korak {number} od {total}: {text}. {alt}",
    language: "Jezik",
  },
};
