import type { ExportWordTemplates } from "./types";

/** Magyar: the words every export uses. */
export const hu: ExportWordTemplates = {
  beforeYouStart: "Mielőtt elkezdené",
  youreDone: "Kész is van",
  madeWith: "Készült a Steps segítségével",
  preparedBy: "Készítette: {name}",
  page: "{current}/{total}. oldal",
  output: "Kimenet",
  outputLines: { one: "{count} sor", other: "{count} sor" },
  shortened: "rövidítve",
  copy: "Másolás",
  copied: "Másolva",
  contents: "Tartalom",
  firstSteps: "Első lépések",
  untitledSection: "Névtelen szakasz",
  step: "{number}. lépés",
  steps: "{first}–{last}. lépés",
  documentControl: "Dokumentumadatok",
  control: {
    title: "Cím",
    owner: "Tulajdonos",
    preparedBy: "Készítette",
    created: "Létrehozva",
    updated: "Utoljára frissítve",
    reviewBy: "Felülvizsgálat határideje",
    exported: "Exportálva",
    notSet: "Nincs megadva",
    history: "Verzióelőzmények",
    date: "Dátum",
    by: "Szerző",
    note: "Verzió",
    steps: "Lépések",
    noVersions: "Még nincs mentett verzió.",
  },
  dateBy: "{date}, {by}",
  stepCount: { one: "{count} lépés", other: "{count} lépés" },
  minutes: "kb. {minutes} perc",
  untitledGuide: "Névtelen útmutató",
  screenshotFor: "Képernyőkép a(z) {number}. lépéshez: {text}",
  callouts: {
    note: "MEGJEGYZÉS",
    tip: "TIPP",
    warning: "FIGYELMEZTETÉS",
    important: "FONTOS",
  },
  codeLabels: { cmd: "Parancssor", excel: "Excel-képlet" },
  player: {
    play: "Lejátszás",
    pause: "Szünet",
    speed: "Sebesség",
    reduceMotion: "Kevesebb animáció",
    allSteps: "Minden lépés megtekintése",
    backToPlayer: "Vissza a bemutatóhoz",
    fullScreen: "Teljes képernyő",
    thumbnails: "Lépések",
    back: "Vissza",
    next: "Tovább",
    start: "Indítás",
    startAgain: "Újrakezdés",
    goToStep: "Ugrás a(z) {number}. lépésre",
    percentDone: "{percent}% kész",
    stepCard: "Aktuális lépés",
    announce: "{number}/{total}. lépés: {text}. {alt}",
    language: "Nyelv",
  },
};
