import type { ExportWordTemplates } from "./types";

/** Bahasa Indonesia: the words exports use, in the app's own terms ("panduan", "langkah"). */
export const id: ExportWordTemplates = {
  beforeYouStart: "Sebelum memulai",
  youreDone: "Selesai",
  madeWith: "Dibuat dengan Steps",
  preparedBy: "Disiapkan oleh {name}",
  page: "Halaman {current} dari {total}",
  output: "Output",
  outputLines: { other: "{count} baris" },
  shortened: "dipersingkat",
  copy: "Salin",
  copied: "Disalin",
  contents: "Daftar isi",
  firstSteps: "Langkah pertama",
  untitledSection: "Bagian tanpa judul",
  step: "Langkah {number}",
  steps: "Langkah {first}–{last}",
  documentControl: "Kontrol dokumen",
  control: {
    title: "Judul",
    owner: "Pemilik",
    preparedBy: "Disiapkan oleh",
    created: "Dibuat",
    updated: "Terakhir diperbarui",
    reviewBy: "Tinjau sebelum",
    exported: "Diekspor",
    notSet: "Belum diatur",
    history: "Riwayat versi",
    date: "Tanggal",
    by: "Oleh",
    note: "Versi",
    steps: "Langkah",
    noVersions: "Belum ada versi yang disimpan.",
  },
  dateBy: "{date} oleh {by}",
  stepCount: { other: "{count} langkah" },
  minutes: "sekitar {minutes} mnt",
  untitledGuide: "Panduan tanpa judul",
  screenshotFor: "Cuplikan layar untuk langkah {number}: {text}",
  callouts: { note: "CATATAN", tip: "TIPS", warning: "PERINGATAN", important: "PENTING" },
  codeLabels: { cmd: "Prompt Perintah", excel: "Rumus Excel" },
  player: {
    play: "Putar",
    pause: "Jeda",
    speed: "Kecepatan",
    reduceMotion: "Kurangi gerakan",
    allSteps: "Lihat semua langkah",
    backToPlayer: "Kembali ke panduan interaktif",
    fullScreen: "Layar penuh",
    thumbnails: "Langkah",
    back: "Kembali",
    next: "Berikutnya",
    start: "Mulai",
    startAgain: "Mulai dari awal",
    goToStep: "Buka langkah {number}",
    percentDone: "{percent}% selesai",
    stepCard: "Langkah saat ini",
    announce: "Langkah {number} dari {total}: {text}. {alt}",
    language: "Bahasa",
  },
};
