import type { ExportWordTemplates } from "./types";

/** Italiano: the words every export uses, speaking to the reader as "tu" like the app. */
export const it: ExportWordTemplates = {
  beforeYouStart: "Prima di iniziare",
  youreDone: "Hai finito",
  madeWith: "Realizzato con Steps",
  preparedBy: "Redatto da {name}",
  page: "Pagina {current} di {total}",
  output: "Output",
  outputLines: { one: "{count} riga", many: "{count} righe", other: "{count} righe" },
  shortened: "abbreviato",
  copy: "Copia",
  copied: "Copiato",
  contents: "Sommario",
  firstSteps: "Primi passaggi",
  untitledSection: "Sezione senza titolo",
  step: "Passaggio {number}",
  steps: "Passaggi {first}–{last}",
  documentControl: "Controllo del documento",
  control: {
    title: "Titolo",
    owner: "Proprietario",
    preparedBy: "Redatto da",
    created: "Creato",
    updated: "Ultimo aggiornamento",
    reviewBy: "Data di revisione",
    exported: "Esportato",
    notSet: "Non impostato",
    history: "Cronologia delle versioni",
    date: "Data",
    by: "Autore",
    note: "Versione",
    steps: "Passaggi",
    noVersions: "Ancora nessuna versione salvata.",
  },
  dateBy: "{date} da {by}",
  stepCount: { one: "{count} passaggio", many: "{count} passaggi", other: "{count} passaggi" },
  minutes: "circa {minutes} min",
  untitledGuide: "Guida senza titolo",
  screenshotFor: "Screenshot del passaggio {number}: {text}",
  callouts: {
    note: "NOTA",
    tip: "SUGGERIMENTO",
    warning: "AVVISO",
    important: "IMPORTANTE",
  },
  codeLabels: { cmd: "Prompt dei comandi", excel: "Formula di Excel" },
  player: {
    play: "Riproduci",
    pause: "Pausa",
    speed: "Velocità",
    reduceMotion: "Riduci animazioni",
    allSteps: "Vedi tutti i passaggi",
    backToPlayer: "Torna alla presentazione",
    fullScreen: "Schermo intero",
    thumbnails: "Passaggi",
    back: "Indietro",
    next: "Avanti",
    start: "Inizia",
    startAgain: "Ricomincia",
    goToStep: "Vai al passaggio {number}",
    percentDone: "{percent}% completato",
    stepCard: "Passaggio corrente",
    announce: "Passaggio {number} di {total}: {text}. {alt}",
    language: "Lingua",
  },
};
