import type { ExportWordTemplates } from "./types";

/** 日本語: the words exports use, in Microsoft's Japanese style (です/ます, 「」). */
export const ja: ExportWordTemplates = {
  beforeYouStart: "始める前に",
  youreDone: "これで完了です",
  madeWith: "Steps で作成",
  preparedBy: "作成者: {name}",
  page: "{current}/{total} ページ",
  output: "出力",
  outputLines: { other: "{count} 行" },
  shortened: "短縮済み",
  copy: "コピー",
  copied: "コピーしました",
  contents: "目次",
  firstSteps: "最初のステップ",
  untitledSection: "無題のセクション",
  step: "ステップ {number}",
  steps: "ステップ {first}～{last}",
  documentControl: "文書管理",
  control: {
    title: "タイトル",
    owner: "所有者",
    preparedBy: "作成者",
    created: "作成日",
    updated: "最終更新日",
    reviewBy: "レビュー期限",
    exported: "エクスポート日",
    notSet: "未設定",
    history: "バージョン履歴",
    date: "日付",
    by: "更新者",
    note: "バージョン",
    steps: "ステップ",
    noVersions: "保存されたバージョンはまだありません。",
  },
  dateBy: "{date}（{by}）",
  stepCount: { other: "{count} ステップ" },
  minutes: "約 {minutes} 分",
  untitledGuide: "無題のガイド",
  screenshotFor: "ステップ {number} のスクリーンショット: {text}",
  callouts: { note: "注", tip: "ヒント", warning: "警告", important: "重要" },
  codeLabels: { cmd: "コマンド プロンプト", excel: "Excel の数式" },
  player: {
    play: "再生",
    pause: "一時停止",
    speed: "速度",
    reduceMotion: "動きを減らす",
    allSteps: "すべてのステップを表示",
    backToPlayer: "ウォークスルーに戻る",
    fullScreen: "全画面表示",
    thumbnails: "ステップ",
    back: "戻る",
    next: "次へ",
    start: "開始",
    startAgain: "最初から",
    goToStep: "ステップ {number} に移動",
    percentDone: "{percent}% 完了",
    stepCard: "現在のステップ",
    announce: "ステップ {number}/{total}: {text}。{alt}",
    language: "言語",
  },
};
