import type { ExportWordTemplates } from "./types";

/** 한국어: the words exports use, in the app's own terms (가이드, 단계, 흐리게 처리). */
export const ko: ExportWordTemplates = {
  beforeYouStart: "시작하기 전에",
  youreDone: "완료",
  madeWith: "Steps로 만듦",
  preparedBy: "작성자: {name}",
  page: "{current}/{total}페이지",
  output: "출력",
  outputLines: { other: "{count}줄" },
  shortened: "줄임",
  copy: "복사",
  copied: "복사됨",
  contents: "목차",
  firstSteps: "첫 단계",
  untitledSection: "제목 없는 섹션",
  step: "{number}단계",
  steps: "{first}–{last}단계",
  documentControl: "문서 관리",
  control: {
    title: "제목",
    owner: "소유자",
    preparedBy: "작성자",
    created: "만든 날짜",
    updated: "마지막 업데이트",
    reviewBy: "검토 기한",
    exported: "내보낸 날짜",
    notSet: "설정 안 됨",
    history: "버전 기록",
    date: "날짜",
    by: "작성자",
    note: "버전",
    steps: "단계",
    noVersions: "아직 저장된 버전이 없습니다.",
  },
  dateBy: "{date}, {by}",
  stepCount: { other: "단계 {count}개" },
  minutes: "약 {minutes}분",
  untitledGuide: "제목 없는 가이드",
  screenshotFor: "{number}단계 스크린샷: {text}",
  callouts: { note: "참고", tip: "팁", warning: "경고", important: "중요" },
  codeLabels: { cmd: "명령 프롬프트", excel: "Excel 수식" },
  player: {
    play: "재생",
    pause: "일시 중지",
    speed: "속도",
    reduceMotion: "동작 줄이기",
    allSteps: "모든 단계 보기",
    backToPlayer: "안내로 돌아가기",
    fullScreen: "전체 화면",
    thumbnails: "단계",
    back: "뒤로",
    next: "다음",
    start: "시작",
    startAgain: "처음부터 다시",
    goToStep: "{number}단계로 이동",
    percentDone: "{percent}% 완료",
    stepCard: "현재 단계",
    announce: "{number}/{total}단계: {text}. {alt}",
    language: "언어",
  },
};
