import type { ExportWordTemplates } from "./types";

/** Lietuvių: the fixed words in exports, in Lithuanian. */
export const lt: ExportWordTemplates = {
  beforeYouStart: "Prieš pradėdami",
  youreDone: "Baigta",
  madeWith: "Sukurta naudojant Steps",
  preparedBy: "Parengė {name}",
  page: "{current} puslapis iš {total}",
  output: "Išvestis",
  outputLines: {
    one: "{count} eilutė",
    few: "{count} eilutės",
    many: "{count} eilučių",
    other: "{count} eilučių",
  },
  shortened: "sutrumpinta",
  copy: "Kopijuoti",
  copied: "Nukopijuota",
  contents: "Turinys",
  firstSteps: "Pirmieji žingsniai",
  untitledSection: "Skyrius be pavadinimo",
  step: "{number} žingsnis",
  steps: "{first}–{last} žingsniai",
  documentControl: "Dokumento kontrolė",
  control: {
    title: "Pavadinimas",
    owner: "Savininkas",
    preparedBy: "Parengė",
    created: "Sukurta",
    updated: "Paskutinį kartą atnaujinta",
    reviewBy: "Peržiūrėti iki",
    exported: "Eksportuota",
    notSet: "Nenustatyta",
    history: "Versijų istorija",
    date: "Data",
    by: "Autorius",
    note: "Versija",
    steps: "Žingsniai",
    noVersions: "Išsaugotų versijų dar nėra.",
  },
  dateBy: "{date}, {by}",
  stepCount: {
    one: "{count} žingsnis",
    few: "{count} žingsniai",
    many: "{count} žingsnių",
    other: "{count} žingsnių",
  },
  minutes: "apie {minutes} min.",
  untitledGuide: "Instrukcija be pavadinimo",
  screenshotFor: "{number} žingsnio ekrano kopija: {text}",
  callouts: { note: "PASTABA", tip: "PATARIMAS", warning: "ĮSPĖJIMAS", important: "SVARBU" },
  codeLabels: { cmd: "Komandų eilutė", excel: "Excel formulė" },
  player: {
    play: "Leisti",
    pause: "Pristabdyti",
    speed: "Greitis",
    reduceMotion: "Mažinti animaciją",
    allSteps: "Rodyti visus žingsnius",
    backToPlayer: "Grįžti į pristatymą",
    fullScreen: "Visas ekranas",
    thumbnails: "Žingsniai",
    back: "Atgal",
    next: "Toliau",
    start: "Pradėti",
    startAgain: "Pradėti iš naujo",
    goToStep: "Eiti į {number} žingsnį",
    percentDone: "Atlikta {percent} %",
    stepCard: "Dabartinis žingsnis",
    announce: "{number} žingsnis iš {total}: {text}. {alt}",
    language: "Kalba",
  },
};
