import type { ExportWordTemplates } from "./types";

/** Latviešu: the fixed words in exports, in Latvian. */
export const lv: ExportWordTemplates = {
  beforeYouStart: "Pirms sākat",
  youreDone: "Viss paveikts",
  madeWith: "Izveidots ar Steps",
  preparedBy: "Sagatavoja {name}",
  page: "{current}. lappuse no {total}",
  output: "Izvade",
  outputLines: { zero: "{count} rindiņu", one: "{count} rindiņa", other: "{count} rindiņas" },
  shortened: "saīsināts",
  copy: "Kopēt",
  copied: "Nokopēts",
  contents: "Saturs",
  firstSteps: "Pirmie soļi",
  untitledSection: "Sadaļa bez nosaukuma",
  step: "{number}. solis",
  steps: "{first}.–{last}. solis",
  documentControl: "Dokumenta kontrole",
  control: {
    title: "Nosaukums",
    owner: "Īpašnieks",
    preparedBy: "Sagatavoja",
    created: "Izveidots",
    updated: "Pēdējoreiz atjaunināts",
    reviewBy: "Pārskatīt līdz",
    exported: "Eksportēts",
    notSet: "Nav iestatīts",
    history: "Versiju vēsture",
    date: "Datums",
    by: "Autors",
    note: "Versija",
    steps: "Soļi",
    noVersions: "Saglabātu versiju vēl nav.",
  },
  dateBy: "{date}, {by}",
  stepCount: { zero: "{count} soļu", one: "{count} solis", other: "{count} soļi" },
  minutes: "apm. {minutes} min",
  untitledGuide: "Pamācība bez nosaukuma",
  screenshotFor: "{number}. soļa ekrānuzņēmums: {text}",
  callouts: { note: "PIEZĪME", tip: "PADOMS", warning: "BRĪDINĀJUMS", important: "SVARĪGI" },
  codeLabels: { cmd: "Komandu uzvedne", excel: "Excel formula" },
  player: {
    play: "Atskaņot",
    pause: "Pauzēt",
    speed: "Ātrums",
    reduceMotion: "Samazināt kustību",
    allSteps: "Skatīt visus soļus",
    backToPlayer: "Atpakaļ uz demonstrāciju",
    fullScreen: "Pilnekrāna režīms",
    thumbnails: "Soļi",
    back: "Atpakaļ",
    next: "Tālāk",
    start: "Sākt",
    startAgain: "Sākt no jauna",
    goToStep: "Pāriet uz {number}. soli",
    percentDone: "Paveikti {percent}%",
    stepCard: "Pašreizējais solis",
    announce: "{number}. solis no {total}: {text}. {alt}",
    language: "Valoda",
  },
};
