import type { ExportWordTemplates } from "./types";

/** Malti: the words exports use, in the imperative singular as the app's screens are. */
export const mt: ExportWordTemplates = {
  beforeYouStart: "Qabel tibda",
  youreDone: "Lest",
  madeWith: "Magħmul b’Steps",
  preparedBy: "Ippreparat minn {name}",
  page: "Paġna {current} minn {total}",
  output: "Eżitu",
  outputLines: {
    one: "{count} linja",
    two: "{count} linji",
    few: "{count} linji",
    many: "{count}-il linja",
    other: "{count} linja",
  },
  shortened: "imqassar",
  copy: "Ikkopja",
  copied: "Ikkupjat",
  contents: "Werrej",
  firstSteps: "L-ewwel passi",
  untitledSection: "Taqsima mingħajr titlu",
  step: "Pass {number}",
  steps: "Passi {first}–{last}",
  documentControl: "Kontroll tad-dokument",
  control: {
    title: "Titlu",
    owner: "Sid",
    preparedBy: "Ippreparat minn",
    created: "Maħluq",
    updated: "Aġġornat l-aħħar",
    reviewBy: "Reviżjoni sa",
    exported: "Esportat",
    notSet: "Mhux issettjat",
    history: "Storja tal-verżjonijiet",
    date: "Data",
    by: "Minn",
    note: "Verżjoni",
    steps: "Passi",
    noVersions: "Għadhom ma ġew issejvjati l-ebda verżjonijiet.",
  },
  dateBy: "{date} minn {by}",
  stepCount: {
    one: "{count} pass",
    two: "{count} passi",
    few: "{count} passi",
    many: "{count}-il pass",
    other: "{count} pass",
  },
  minutes: "madwar {minutes} min",
  untitledGuide: "Gwida mingħajr titlu",
  screenshotFor: "Screenshot għall-pass {number}: {text}",
  callouts: { note: "NOTA", tip: "SUĠĠERIMENT", warning: "TWISSIJA", important: "IMPORTANTI" },
  codeLabels: { cmd: "Command Prompt", excel: "Formula tal-Excel" },
  player: {
    play: "Ħaddem",
    pause: "Waqqaf",
    speed: "Veloċità",
    reduceMotion: "Naqqas il-moviment",
    allSteps: "Ara l-passi kollha",
    backToPlayer: "Lura għall-mixja",
    fullScreen: "Skrin sħiħ",
    thumbnails: "Passi",
    back: "Lura",
    next: "Li jmiss",
    start: "Ibda",
    startAgain: "Ibda mill-ġdid",
    goToStep: "Mur fuq il-pass {number}",
    percentDone: "{percent}% lest",
    stepCard: "Il-pass attwali",
    announce: "Pass {number} minn {total}: {text}. {alt}",
    language: "Lingwa",
  },
};
