import type { ExportWordTemplates } from "./types";

/** Norsk bokmål: the words every export uses. */
export const nb: ExportWordTemplates = {
  beforeYouStart: "Før du begynner",
  youreDone: "Da er du ferdig",
  madeWith: "Laget med Steps",
  preparedBy: "Utarbeidet av {name}",
  page: "Side {current} av {total}",
  output: "Utdata",
  outputLines: { one: "{count} linje", other: "{count} linjer" },
  shortened: "forkortet",
  copy: "Kopier",
  copied: "Kopiert",
  contents: "Innhold",
  firstSteps: "Første trinn",
  untitledSection: "Del uten tittel",
  step: "Trinn {number}",
  steps: "Trinn {first}–{last}",
  documentControl: "Dokumentkontroll",
  control: {
    title: "Tittel",
    owner: "Eier",
    preparedBy: "Utarbeidet av",
    created: "Opprettet",
    updated: "Sist oppdatert",
    reviewBy: "Gjennomgås innen",
    exported: "Eksportert",
    notSet: "Ikke angitt",
    history: "Versjonslogg",
    date: "Dato",
    by: "Av",
    note: "Versjon",
    steps: "Trinn",
    noVersions: "Ingen versjoner er lagret ennå.",
  },
  dateBy: "{date} av {by}",
  stepCount: { one: "{count} trinn", other: "{count} trinn" },
  minutes: "ca. {minutes} min",
  untitledGuide: "Veiledning uten tittel",
  screenshotFor: "Skjermbilde for trinn {number}: {text}",
  callouts: { note: "MERK", tip: "TIPS", warning: "ADVARSEL", important: "VIKTIG" },
  codeLabels: { cmd: "Ledetekst", excel: "Excel-formel" },
  player: {
    play: "Spill av",
    pause: "Pause",
    speed: "Hastighet",
    reduceMotion: "Reduser bevegelse",
    allSteps: "Vis alle trinn",
    backToPlayer: "Tilbake til gjennomgangen",
    fullScreen: "Fullskjerm",
    thumbnails: "Trinn",
    back: "Tilbake",
    next: "Neste",
    start: "Start",
    startAgain: "Start på nytt",
    goToStep: "Gå til trinn {number}",
    percentDone: "{percent} % fullført",
    stepCard: "Gjeldende trinn",
    announce: "Trinn {number} av {total}: {text}. {alt}",
    language: "Språk",
  },
};
