import type { ExportWordTemplates } from "./types";

/** Nederlands: the words in exported guides, addressing the reader as "je". */
export const nl: ExportWordTemplates = {
  beforeYouStart: "Voordat je begint",
  youreDone: "Klaar",
  madeWith: "Gemaakt met Steps",
  preparedBy: "Opgesteld door {name}",
  page: "Pagina {current} van {total}",
  output: "Uitvoer",
  outputLines: { one: "{count} regel", other: "{count} regels" },
  shortened: "ingekort",
  copy: "Kopiëren",
  copied: "Gekopieerd",
  contents: "Inhoud",
  firstSteps: "Eerste stappen",
  untitledSection: "Sectie zonder titel",
  step: "Stap {number}",
  steps: "Stappen {first}–{last}",
  documentControl: "Documentbeheer",
  control: {
    title: "Titel",
    owner: "Eigenaar",
    preparedBy: "Opgesteld door",
    created: "Gemaakt",
    updated: "Laatst bijgewerkt",
    reviewBy: "Controleren vóór",
    exported: "Geëxporteerd",
    notSet: "Niet ingesteld",
    history: "Versiegeschiedenis",
    date: "Datum",
    by: "Door",
    note: "Versie",
    steps: "Stappen",
    noVersions: "Nog geen versies opgeslagen.",
  },
  dateBy: "{date} door {by}",
  stepCount: { one: "{count} stap", other: "{count} stappen" },
  minutes: "ca. {minutes} min",
  untitledGuide: "Handleiding zonder titel",
  screenshotFor: "Schermopname bij stap {number}: {text}",
  callouts: { note: "OPMERKING", tip: "TIP", warning: "WAARSCHUWING", important: "BELANGRIJK" },
  codeLabels: { cmd: "Opdrachtprompt", excel: "Excel-formule" },
  player: {
    play: "Afspelen",
    pause: "Pauzeren",
    speed: "Snelheid",
    reduceMotion: "Minder beweging",
    allSteps: "Alle stappen bekijken",
    backToPlayer: "Terug naar de doorloop",
    fullScreen: "Volledig scherm",
    thumbnails: "Stappen",
    back: "Vorige",
    next: "Volgende",
    start: "Starten",
    startAgain: "Opnieuw beginnen",
    goToStep: "Ga naar stap {number}",
    percentDone: "{percent}% klaar",
    stepCard: "Huidige stap",
    announce: "Stap {number} van {total}: {text}. {alt}",
    language: "Taal",
  },
};
