import type { ExportWordTemplates } from "./types";

/** Polski: the words exports use, with the reader addressed as Windows does („Zanim zaczniesz”). */
export const pl: ExportWordTemplates = {
  beforeYouStart: "Zanim zaczniesz",
  youreDone: "Gotowe",
  madeWith: "Utworzono w Steps",
  preparedBy: "Opracowanie: {name}",
  page: "Strona {current} z {total}",
  output: "Wynik",
  outputLines: {
    one: "{count} wiersz",
    few: "{count} wiersze",
    many: "{count} wierszy",
    other: "{count} wierszy",
  },
  shortened: "skrócono",
  copy: "Kopiuj",
  copied: "Skopiowano",
  contents: "Spis treści",
  firstSteps: "Pierwsze kroki",
  untitledSection: "Sekcja bez tytułu",
  step: "Krok {number}",
  steps: "Kroki {first}–{last}",
  documentControl: "Metryka dokumentu",
  control: {
    title: "Tytuł",
    owner: "Właściciel",
    preparedBy: "Opracowanie",
    created: "Utworzono",
    updated: "Ostatnia aktualizacja",
    reviewBy: "Przegląd do",
    exported: "Wyeksportowano",
    notSet: "Nie ustawiono",
    history: "Historia wersji",
    date: "Data",
    by: "Autor",
    note: "Wersja",
    steps: "Kroki",
    noVersions: "Nie zapisano jeszcze żadnych wersji.",
  },
  dateBy: "{date}, {by}",
  stepCount: {
    one: "{count} krok",
    few: "{count} kroki",
    many: "{count} kroków",
    other: "{count} kroków",
  },
  minutes: "ok. {minutes} min",
  untitledGuide: "Instrukcja bez tytułu",
  screenshotFor: "Zrzut ekranu do kroku {number}: {text}",
  callouts: { note: "UWAGA", tip: "PORADA", warning: "OSTRZEŻENIE", important: "WAŻNE" },
  codeLabels: { cmd: "Wiersz polecenia", excel: "Formuła programu Excel" },
  player: {
    play: "Odtwórz",
    pause: "Wstrzymaj",
    speed: "Szybkość",
    reduceMotion: "Ogranicz animacje",
    allSteps: "Pokaż wszystkie kroki",
    backToPlayer: "Wróć do odtwarzania",
    fullScreen: "Pełny ekran",
    thumbnails: "Kroki",
    back: "Wstecz",
    next: "Dalej",
    start: "Rozpocznij",
    startAgain: "Zacznij od nowa",
    goToStep: "Przejdź do kroku {number}",
    percentDone: "Ukończono {percent}%",
    stepCard: "Bieżący krok",
    announce: "Krok {number} z {total}: {text}. {alt}",
    language: "Język",
  },
};
