import type { ExportWordTemplates } from "./types";

/** Português (Brasil): the words exports use, addressing the reader as Microsoft's Brazilian style does. */
export const ptBR: ExportWordTemplates = {
  beforeYouStart: "Antes de começar",
  youreDone: "Tudo pronto",
  madeWith: "Feito com o Steps",
  preparedBy: "Preparado por {name}",
  page: "Página {current} de {total}",
  output: "Saída",
  outputLines: { one: "{count} linha", many: "{count} linhas", other: "{count} linhas" },
  shortened: "reduzida",
  copy: "Copiar",
  copied: "Copiado",
  contents: "Sumário",
  firstSteps: "Primeiros passos",
  untitledSection: "Seção sem título",
  step: "Passo {number}",
  steps: "Passos {first}–{last}",
  documentControl: "Controle do documento",
  control: {
    title: "Título",
    owner: "Responsável",
    preparedBy: "Preparado por",
    created: "Criado em",
    updated: "Última atualização",
    reviewBy: "Revisar até",
    exported: "Exportado em",
    notSet: "Não definido",
    history: "Histórico de versões",
    date: "Data",
    by: "Por",
    note: "Versão",
    steps: "Passos",
    noVersions: "Nenhuma versão salva ainda.",
  },
  dateBy: "{date} por {by}",
  stepCount: { one: "{count} passo", many: "{count} passos", other: "{count} passos" },
  minutes: "cerca de {minutes} min",
  untitledGuide: "Guia sem título",
  screenshotFor: "Captura de tela do passo {number}: {text}",
  callouts: { note: "NOTA", tip: "DICA", warning: "AVISO", important: "IMPORTANTE" },
  codeLabels: { cmd: "Prompt de Comando", excel: "Fórmula do Excel" },
  player: {
    play: "Reproduzir",
    pause: "Pausar",
    speed: "Velocidade",
    reduceMotion: "Reduzir movimento",
    allSteps: "Ver todos os passos",
    backToPlayer: "Voltar ao tutorial",
    fullScreen: "Tela inteira",
    thumbnails: "Passos",
    back: "Voltar",
    next: "Avançar",
    start: "Começar",
    startAgain: "Recomeçar",
    goToStep: "Ir para o passo {number}",
    percentDone: "{percent}% concluído",
    stepCard: "Passo atual",
    announce: "Passo {number} de {total}: {text}. {alt}",
    language: "Idioma",
  },
};
