import type { ExportWordTemplates } from "./types";

/** Português (Portugal): the words exports use, as Microsoft's European Portuguese style writes them. */
export const ptPT: ExportWordTemplates = {
  beforeYouStart: "Antes de começar",
  youreDone: "Concluído",
  madeWith: "Feito com o Steps",
  preparedBy: "Preparado por {name}",
  page: "Página {current} de {total}",
  output: "Saída",
  outputLines: { one: "{count} linha", many: "{count} linhas", other: "{count} linhas" },
  shortened: "abreviada",
  copy: "Copiar",
  copied: "Copiado",
  contents: "Índice",
  firstSteps: "Primeiros passos",
  untitledSection: "Secção sem título",
  step: "Passo {number}",
  steps: "Passos {first}–{last}",
  documentControl: "Controlo do documento",
  control: {
    title: "Título",
    owner: "Responsável",
    preparedBy: "Preparado por",
    created: "Criado em",
    updated: "Última atualização",
    reviewBy: "Rever até",
    exported: "Exportado em",
    notSet: "Não definido",
    history: "Histórico de versões",
    date: "Data",
    by: "Por",
    note: "Versão",
    steps: "Passos",
    noVersions: "Ainda não há versões guardadas.",
  },
  dateBy: "{date} por {by}",
  stepCount: { one: "{count} passo", many: "{count} passos", other: "{count} passos" },
  minutes: "cerca de {minutes} min",
  untitledGuide: "Guia sem título",
  screenshotFor: "Captura de ecrã do passo {number}: {text}",
  callouts: { note: "NOTA", tip: "SUGESTÃO", warning: "AVISO", important: "IMPORTANTE" },
  codeLabels: { cmd: "Linha de Comandos", excel: "Fórmula do Excel" },
  player: {
    play: "Reproduzir",
    pause: "Pausar",
    speed: "Velocidade",
    reduceMotion: "Reduzir movimento",
    allSteps: "Ver todos os passos",
    backToPlayer: "Voltar à demonstração",
    fullScreen: "Ecrã inteiro",
    thumbnails: "Passos",
    back: "Anterior",
    next: "Seguinte",
    start: "Começar",
    startAgain: "Recomeçar",
    goToStep: "Ir para o passo {number}",
    percentDone: "{percent}% concluído",
    stepCard: "Passo atual",
    announce: "Passo {number} de {total}: {text}. {alt}",
    language: "Idioma",
  },
};
