import type { ExportWordTemplates } from "./types";

/** Română: the words exports use, with Romanian's three plural forms ("2 pași", "20 de pași"). */
export const ro: ExportWordTemplates = {
  beforeYouStart: "Înainte de a începe",
  youreDone: "Ați terminat",
  madeWith: "Realizat cu Steps",
  preparedBy: "Întocmit de {name}",
  page: "Pagina {current} din {total}",
  output: "Rezultat",
  outputLines: { one: "{count} linie", few: "{count} linii", other: "{count} de linii" },
  shortened: "scurtat",
  copy: "Copiere",
  copied: "Copiat",
  contents: "Cuprins",
  firstSteps: "Primii pași",
  untitledSection: "Secțiune fără titlu",
  step: "Pasul {number}",
  steps: "Pașii {first}–{last}",
  documentControl: "Controlul documentului",
  control: {
    title: "Titlu",
    owner: "Proprietar",
    preparedBy: "Întocmit de",
    created: "Creat",
    updated: "Ultima actualizare",
    reviewBy: "Revizuire până la",
    exported: "Exportat",
    notSet: "Nesetat",
    history: "Istoricul versiunilor",
    date: "Dată",
    by: "De",
    note: "Versiune",
    steps: "Pași",
    noVersions: "Nicio versiune salvată încă.",
  },
  dateBy: "{date}, de {by}",
  stepCount: { one: "{count} pas", few: "{count} pași", other: "{count} de pași" },
  minutes: "aprox. {minutes} min",
  untitledGuide: "Ghid fără titlu",
  screenshotFor: "Captură de ecran pentru pasul {number}: {text}",
  callouts: { note: "NOTĂ", tip: "SFAT", warning: "AVERTISMENT", important: "IMPORTANT" },
  codeLabels: { cmd: "Linie de comandă", excel: "Formulă Excel" },
  player: {
    play: "Redare",
    pause: "Pauză",
    speed: "Viteză",
    reduceMotion: "Reducere animații",
    allSteps: "Vedeți toți pașii",
    backToPlayer: "Înapoi la ghidul interactiv",
    fullScreen: "Ecran complet",
    thumbnails: "Pași",
    back: "Înapoi",
    next: "Următorul",
    start: "Începeți",
    startAgain: "Începeți din nou",
    goToStep: "Mergeți la pasul {number}",
    percentDone: "{percent}% finalizat",
    stepCard: "Pasul curent",
    announce: "Pasul {number} din {total}: {text}. {alt}",
    language: "Limbă",
  },
};
