import type { ExportWordTemplates } from "./types";

/** Русский: the fixed words in exports. */
export const ru: ExportWordTemplates = {
  beforeYouStart: "Прежде чем начать",
  youreDone: "Готово",
  madeWith: "Сделано в Steps",
  preparedBy: "Подготовлено: {name}",
  page: "Страница {current} из {total}",
  output: "Вывод",
  outputLines: {
    one: "{count} строка",
    few: "{count} строки",
    many: "{count} строк",
    other: "{count} строк",
  },
  shortened: "сокращено",
  copy: "Копировать",
  copied: "Скопировано",
  contents: "Содержание",
  firstSteps: "Первые шаги",
  untitledSection: "Раздел без названия",
  step: "Шаг {number}",
  steps: "Шаги {first}–{last}",
  documentControl: "Контроль документа",
  control: {
    title: "Название",
    owner: "Владелец",
    preparedBy: "Подготовлено",
    created: "Создано",
    updated: "Последнее обновление",
    reviewBy: "Пересмотреть до",
    exported: "Экспортировано",
    notSet: "Не задано",
    history: "История версий",
    date: "Дата",
    by: "Автор",
    note: "Версия",
    steps: "Шаги",
    noVersions: "Сохраненных версий пока нет.",
  },
  dateBy: "{date}, {by}",
  stepCount: {
    one: "{count} шаг",
    few: "{count} шага",
    many: "{count} шагов",
    other: "{count} шагов",
  },
  minutes: "около {minutes} мин",
  untitledGuide: "Инструкция без названия",
  screenshotFor: "Снимок экрана для шага {number}: {text}",
  callouts: {
    note: "ПРИМЕЧАНИЕ",
    tip: "СОВЕТ",
    warning: "ПРЕДУПРЕЖДЕНИЕ",
    important: "ВАЖНО",
  },
  codeLabels: { cmd: "Командная строка", excel: "Формула Excel" },
  player: {
    play: "Воспроизвести",
    pause: "Пауза",
    speed: "Скорость",
    reduceMotion: "Уменьшить движение",
    allSteps: "Посмотреть все шаги",
    backToPlayer: "Назад к пошаговому просмотру",
    fullScreen: "Во весь экран",
    thumbnails: "Шаги",
    back: "Назад",
    next: "Далее",
    start: "Начать",
    startAgain: "Начать заново",
    goToStep: "Перейти к шагу {number}",
    percentDone: "Выполнено {percent}%",
    stepCard: "Текущий шаг",
    announce: "Шаг {number} из {total}: {text}. {alt}",
    language: "Язык",
  },
};
