import type { ExportWordTemplates } from "./types";

/** Slovenčina: the words exports use, with the reader addressed formally as Windows does („Skôr než začnete“). */
export const sk: ExportWordTemplates = {
  beforeYouStart: "Skôr než začnete",
  youreDone: "Hotovo",
  madeWith: "Vytvorené v aplikácii Steps",
  preparedBy: "Spracovateľ: {name}",
  page: "Strana {current} z {total}",
  output: "Výstup",
  outputLines: {
    one: "{count} riadok",
    few: "{count} riadky",
    many: "{count} riadka",
    other: "{count} riadkov",
  },
  shortened: "skrátené",
  copy: "Kopírovať",
  copied: "Skopírované",
  contents: "Obsah",
  firstSteps: "Prvé kroky",
  untitledSection: "Oddiel bez názvu",
  step: "Krok {number}",
  steps: "Kroky {first}–{last}",
  documentControl: "Údaje o dokumente",
  control: {
    title: "Názov",
    owner: "Vlastník",
    preparedBy: "Spracovateľ",
    created: "Vytvorené",
    updated: "Posledná aktualizácia",
    reviewBy: "Revízia do",
    exported: "Exportované",
    notSet: "Nenastavené",
    history: "História verzií",
    date: "Dátum",
    by: "Autor",
    note: "Verzia",
    steps: "Kroky",
    noVersions: "Zatiaľ nie sú uložené žiadne verzie.",
  },
  dateBy: "{date}, {by}",
  stepCount: {
    one: "{count} krok",
    few: "{count} kroky",
    many: "{count} kroku",
    other: "{count} krokov",
  },
  minutes: "asi {minutes} min",
  untitledGuide: "Návod bez názvu",
  screenshotFor: "Snímka obrazovky ku kroku {number}: {text}",
  callouts: { note: "POZNÁMKA", tip: "TIP", warning: "UPOZORNENIE", important: "DÔLEŽITÉ" },
  codeLabels: { cmd: "Príkazový riadok", excel: "Vzorec Excelu" },
  player: {
    play: "Prehrať",
    pause: "Pozastaviť",
    speed: "Rýchlosť",
    reduceMotion: "Obmedziť animácie",
    allSteps: "Zobraziť všetky kroky",
    backToPlayer: "Späť na prehrávanie",
    fullScreen: "Celá obrazovka",
    thumbnails: "Kroky",
    back: "Späť",
    next: "Ďalej",
    start: "Začať",
    startAgain: "Začať znova",
    goToStep: "Prejsť na krok {number}",
    percentDone: "Hotovo: {percent} %",
    stepCard: "Aktuálny krok",
    announce: "Krok {number} z {total}: {text}. {alt}",
    language: "Jazyk",
  },
};
