import type { ExportWordTemplates } from "./types";

/** Slovenščina: the polite "vi" form, as Windows uses it. */
export const sl: ExportWordTemplates = {
  beforeYouStart: "Preden začnete",
  youreDone: "Končali ste",
  madeWith: "Izdelano z aplikacijo Steps",
  preparedBy: "Pripravil(a): {name}",
  page: "Stran {current} od {total}",
  output: "Izpis",
  outputLines: {
    one: "{count} vrstica",
    two: "{count} vrstici",
    few: "{count} vrstice",
    other: "{count} vrstic",
  },
  shortened: "skrajšano",
  copy: "Kopiraj",
  copied: "Kopirano",
  contents: "Kazalo",
  firstSteps: "Prvi koraki",
  untitledSection: "Razdelek brez naslova",
  step: "Korak {number}",
  steps: "Koraki {first}–{last}",
  documentControl: "Nadzor dokumenta",
  control: {
    title: "Naslov",
    owner: "Lastnik",
    preparedBy: "Pripravil(a)",
    created: "Ustvarjeno",
    updated: "Nazadnje posodobljeno",
    reviewBy: "Pregled do",
    exported: "Izvoženo",
    notSet: "Ni nastavljeno",
    history: "Zgodovina različic",
    date: "Datum",
    by: "Avtor",
    note: "Različica",
    steps: "Koraki",
    noVersions: "Shranjena še ni nobena različica.",
  },
  dateBy: "{date}, {by}",
  stepCount: {
    one: "{count} korak",
    two: "{count} koraka",
    few: "{count} koraki",
    other: "{count} korakov",
  },
  minutes: "približno {minutes} min",
  untitledGuide: "Vodnik brez naslova",
  screenshotFor: "Posnetek zaslona za korak {number}: {text}",
  callouts: { note: "OPOMBA", tip: "NASVET", warning: "OPOZORILO", important: "POMEMBNO" },
  codeLabels: { cmd: "Ukazni poziv", excel: "Excelova formula" },
  player: {
    play: "Predvajaj",
    pause: "Začasno ustavi",
    speed: "Hitrost",
    reduceMotion: "Zmanjšaj gibanje",
    allSteps: "Prikaži vse korake",
    backToPlayer: "Nazaj na vodeni ogled",
    fullScreen: "Celozaslonski način",
    thumbnails: "Koraki",
    back: "Nazaj",
    next: "Naprej",
    start: "Začni",
    startAgain: "Začni znova",
    goToStep: "Pojdi na korak {number}",
    percentDone: "Dokončano: {percent} %",
    stepCard: "Trenutni korak",
    announce: "Korak {number} od {total}: {text}. {alt}",
    language: "Jezik",
  },
};
