import type { ExportWordTemplates } from "./types";

/** Српски (ћирилица): the fixed words in exports. */
export const srCyrl: ExportWordTemplates = {
  beforeYouStart: "Пре него што почнете",
  youreDone: "Завршили сте",
  madeWith: "Направљено помоћу апликације Steps",
  preparedBy: "Аутор: {name}",
  page: "Страница {current} од {total}",
  output: "Излаз",
  outputLines: { one: "{count} ред", few: "{count} реда", other: "{count} редова" },
  shortened: "скраћено",
  copy: "Копирај",
  copied: "Копирано",
  contents: "Садржај",
  firstSteps: "Први кораци",
  untitledSection: "Одељак без наслова",
  step: "Корак {number}",
  steps: "Кораци {first}–{last}",
  documentControl: "Контрола документа",
  control: {
    title: "Наслов",
    owner: "Власник",
    preparedBy: "Аутор",
    created: "Направљено",
    updated: "Последње ажурирање",
    reviewBy: "Прегледати до",
    exported: "Извезено",
    notSet: "Није подешено",
    history: "Историја верзија",
    date: "Датум",
    by: "Аутор",
    note: "Верзија",
    steps: "Кораци",
    noVersions: "Још нема сачуваних верзија.",
  },
  dateBy: "{date}, {by}",
  stepCount: { one: "{count} корак", few: "{count} корака", other: "{count} корака" },
  minutes: "око {minutes} мин",
  untitledGuide: "Водич без наслова",
  screenshotFor: "Снимак екрана за корак {number}: {text}",
  callouts: { note: "НАПОМЕНА", tip: "САВЕТ", warning: "УПОЗОРЕЊЕ", important: "ВАЖНО" },
  codeLabels: { cmd: "Командна линија", excel: "Excel формула" },
  player: {
    play: "Пусти",
    pause: "Паузирај",
    speed: "Брзина",
    reduceMotion: "Смањи покрете",
    allSteps: "Прикажи све кораке",
    backToPlayer: "Назад на приказ",
    fullScreen: "Цео екран",
    thumbnails: "Кораци",
    back: "Назад",
    next: "Даље",
    start: "Почни",
    startAgain: "Почни поново",
    goToStep: "Иди на корак {number}",
    percentDone: "Довршено {percent}%",
    stepCard: "Тренутни корак",
    announce: "Корак {number} од {total}: {text}. {alt}",
    language: "Језик",
  },
};
