import type { ExportWordTemplates } from "./types";

/** Srpski (latinica): the fixed words in exports. */
export const srLatn: ExportWordTemplates = {
  beforeYouStart: "Pre nego što počnete",
  youreDone: "Završili ste",
  madeWith: "Napravljeno pomoću aplikacije Steps",
  preparedBy: "Autor: {name}",
  page: "Stranica {current} od {total}",
  output: "Izlaz",
  outputLines: { one: "{count} red", few: "{count} reda", other: "{count} redova" },
  shortened: "skraćeno",
  copy: "Kopiraj",
  copied: "Kopirano",
  contents: "Sadržaj",
  firstSteps: "Prvi koraci",
  untitledSection: "Odeljak bez naslova",
  step: "Korak {number}",
  steps: "Koraci {first}–{last}",
  documentControl: "Kontrola dokumenta",
  control: {
    title: "Naslov",
    owner: "Vlasnik",
    preparedBy: "Autor",
    created: "Napravljeno",
    updated: "Poslednje ažuriranje",
    reviewBy: "Pregledati do",
    exported: "Izvezeno",
    notSet: "Nije podešeno",
    history: "Istorija verzija",
    date: "Datum",
    by: "Autor",
    note: "Verzija",
    steps: "Koraci",
    noVersions: "Još nema sačuvanih verzija.",
  },
  dateBy: "{date}, {by}",
  stepCount: { one: "{count} korak", few: "{count} koraka", other: "{count} koraka" },
  minutes: "oko {minutes} min",
  untitledGuide: "Vodič bez naslova",
  screenshotFor: "Snimak ekrana za korak {number}: {text}",
  callouts: { note: "NAPOMENA", tip: "SAVET", warning: "UPOZORENJE", important: "VAŽNO" },
  codeLabels: { cmd: "Komandna linija", excel: "Excel formula" },
  player: {
    play: "Pusti",
    pause: "Pauziraj",
    speed: "Brzina",
    reduceMotion: "Smanji pokrete",
    allSteps: "Prikaži sve korake",
    backToPlayer: "Nazad na prikaz",
    fullScreen: "Ceo ekran",
    thumbnails: "Koraci",
    back: "Nazad",
    next: "Dalje",
    start: "Počni",
    startAgain: "Počni ponovo",
    goToStep: "Idi na korak {number}",
    percentDone: "Dovršeno {percent}%",
    stepCard: "Trenutni korak",
    announce: "Korak {number} od {total}: {text}. {alt}",
    language: "Jezik",
  },
};
