import type { ExportWordTemplates } from "./types";

/** Svenska: the words every export uses. */
export const sv: ExportWordTemplates = {
  beforeYouStart: "Innan du börjar",
  youreDone: "Nu är du klar",
  madeWith: "Gjord med Steps",
  preparedBy: "Upprättad av {name}",
  page: "Sida {current} av {total}",
  output: "Utdata",
  outputLines: { one: "{count} rad", other: "{count} rader" },
  shortened: "förkortad",
  copy: "Kopiera",
  copied: "Kopierat",
  contents: "Innehåll",
  firstSteps: "Första stegen",
  untitledSection: "Namnlöst avsnitt",
  step: "Steg {number}",
  steps: "Steg {first}–{last}",
  documentControl: "Dokumentkontroll",
  control: {
    title: "Rubrik",
    owner: "Ägare",
    preparedBy: "Upprättad av",
    created: "Skapad",
    updated: "Senast uppdaterad",
    reviewBy: "Granska senast",
    exported: "Exporterad",
    notSet: "Inte angivet",
    history: "Versionshistorik",
    date: "Datum",
    by: "Av",
    note: "Version",
    steps: "Steg",
    noVersions: "Inga versioner har sparats än.",
  },
  dateBy: "{date} av {by}",
  stepCount: { one: "{count} steg", other: "{count} steg" },
  minutes: "cirka {minutes} min",
  untitledGuide: "Namnlös guide",
  screenshotFor: "Skärmbild för steg {number}: {text}",
  callouts: { note: "OBS", tip: "TIPS", warning: "VARNING", important: "VIKTIGT" },
  codeLabels: { cmd: "Kommandotolken", excel: "Excel-formel" },
  player: {
    play: "Spela upp",
    pause: "Pausa",
    speed: "Hastighet",
    reduceMotion: "Minska rörelser",
    allSteps: "Visa alla steg",
    backToPlayer: "Tillbaka till genomgången",
    fullScreen: "Helskärm",
    thumbnails: "Steg",
    back: "Tillbaka",
    next: "Nästa",
    start: "Starta",
    startAgain: "Börja om",
    goToStep: "Gå till steg {number}",
    percentDone: "{percent} % klart",
    stepCard: "Aktuellt steg",
    announce: "Steg {number} av {total}: {text}. {alt}",
    language: "Språk",
  },
};
