import type { ExportWordTemplates } from "./types";

/** Türkçe: the words exports use, in the app's own terms ("kılavuz", "adım", "Komut İstemi"). */
export const tr: ExportWordTemplates = {
  beforeYouStart: "Başlamadan önce",
  youreDone: "Tamamlandı",
  madeWith: "Steps ile hazırlandı",
  preparedBy: "Hazırlayan: {name}",
  page: "Sayfa {current}/{total}",
  output: "Çıktı",
  outputLines: { one: "{count} satır", other: "{count} satır" },
  shortened: "kısaltıldı",
  copy: "Kopyala",
  copied: "Kopyalandı",
  contents: "İçindekiler",
  firstSteps: "İlk adımlar",
  untitledSection: "Başlıksız bölüm",
  step: "Adım {number}",
  steps: "Adım {first}–{last}",
  documentControl: "Belge denetimi",
  control: {
    title: "Başlık",
    owner: "Sahip",
    preparedBy: "Hazırlayan",
    created: "Oluşturulma",
    updated: "Son güncelleştirme",
    reviewBy: "Gözden geçirme tarihi",
    exported: "Dışarı aktarılma",
    notSet: "Ayarlanmadı",
    history: "Sürüm geçmişi",
    date: "Tarih",
    by: "Yapan",
    note: "Sürüm",
    steps: "Adımlar",
    noVersions: "Henüz kaydedilmiş sürüm yok.",
  },
  dateBy: "{date}, {by}",
  stepCount: { one: "{count} adım", other: "{count} adım" },
  minutes: "yaklaşık {minutes} dk",
  untitledGuide: "Başlıksız kılavuz",
  screenshotFor: "Adım {number} ekran görüntüsü: {text}",
  callouts: { note: "NOT", tip: "İPUCU", warning: "UYARI", important: "ÖNEMLİ" },
  codeLabels: { cmd: "Komut İstemi", excel: "Excel formülü" },
  player: {
    play: "Oynat",
    pause: "Duraklat",
    speed: "Hız",
    reduceMotion: "Hareketi azalt",
    allSteps: "Tüm adımları görüntüle",
    backToPlayer: "Anlatıma dön",
    fullScreen: "Tam ekran",
    thumbnails: "Adımlar",
    back: "Geri",
    next: "İleri",
    start: "Başla",
    startAgain: "Baştan başla",
    goToStep: "{number}. adıma git",
    percentDone: "%{percent} tamamlandı",
    stepCard: "Geçerli adım",
    announce: "Adım {number}/{total}: {text}. {alt}",
    language: "Dil",
  },
};
