import type { ExportWordTemplates } from "./types";

/** Українська: the fixed words in exports. */
export const uk: ExportWordTemplates = {
  beforeYouStart: "Перш ніж почати",
  youreDone: "Усе готово",
  madeWith: "Зроблено в Steps",
  preparedBy: "Підготовлено: {name}",
  page: "Сторінка {current} з {total}",
  output: "Вивід",
  outputLines: {
    one: "{count} рядок",
    few: "{count} рядки",
    many: "{count} рядків",
    other: "{count} рядків",
  },
  shortened: "скорочено",
  copy: "Копіювати",
  copied: "Скопійовано",
  contents: "Зміст",
  firstSteps: "Перші кроки",
  untitledSection: "Розділ без назви",
  step: "Крок {number}",
  steps: "Кроки {first}–{last}",
  documentControl: "Контроль документа",
  control: {
    title: "Назва",
    owner: "Власник",
    preparedBy: "Підготовлено",
    created: "Створено",
    updated: "Останнє оновлення",
    reviewBy: "Переглянути до",
    exported: "Експортовано",
    notSet: "Не задано",
    history: "Історія версій",
    date: "Дата",
    by: "Автор",
    note: "Версія",
    steps: "Кроки",
    noVersions: "Збережених версій ще немає.",
  },
  dateBy: "{date}, {by}",
  stepCount: {
    one: "{count} крок",
    few: "{count} кроки",
    many: "{count} кроків",
    other: "{count} кроків",
  },
  minutes: "близько {minutes} хв",
  untitledGuide: "Інструкція без назви",
  screenshotFor: "Знімок екрана для кроку {number}: {text}",
  callouts: { note: "ПРИМІТКА", tip: "ПОРАДА", warning: "ПОПЕРЕДЖЕННЯ", important: "ВАЖЛИВО" },
  codeLabels: { cmd: "Командний рядок", excel: "Формула Excel" },
  player: {
    play: "Відтворити",
    pause: "Пауза",
    speed: "Швидкість",
    reduceMotion: "Зменшити рух",
    allSteps: "Переглянути всі кроки",
    backToPlayer: "Назад до покрокового перегляду",
    fullScreen: "На весь екран",
    thumbnails: "Кроки",
    back: "Назад",
    next: "Далі",
    start: "Почати",
    startAgain: "Почати знову",
    goToStep: "Перейти до кроку {number}",
    percentDone: "Виконано {percent}%",
    stepCard: "Поточний крок",
    announce: "Крок {number} з {total}: {text}. {alt}",
    language: "Мова",
  },
};
