import type { ExportWordTemplates } from "./types";

/** Tiếng Việt: the words exports use, in the app's own terms (hướng dẫn, bước, làm mờ). */
export const vi: ExportWordTemplates = {
  beforeYouStart: "Trước khi bắt đầu",
  youreDone: "Bạn đã hoàn tất",
  madeWith: "Tạo bằng Steps",
  preparedBy: "Người soạn: {name}",
  page: "Trang {current}/{total}",
  output: "Kết quả",
  outputLines: { other: "{count} dòng" },
  shortened: "đã rút gọn",
  copy: "Sao chép",
  copied: "Đã sao chép",
  contents: "Mục lục",
  firstSteps: "Các bước đầu tiên",
  untitledSection: "Mục chưa có tiêu đề",
  step: "Bước {number}",
  steps: "Bước {first}–{last}",
  documentControl: "Kiểm soát tài liệu",
  control: {
    title: "Tiêu đề",
    owner: "Chủ sở hữu",
    preparedBy: "Người soạn",
    created: "Ngày tạo",
    updated: "Cập nhật lần cuối",
    reviewBy: "Xem xét trước ngày",
    exported: "Ngày xuất",
    notSet: "Chưa đặt",
    history: "Lịch sử phiên bản",
    date: "Ngày",
    by: "Người thực hiện",
    note: "Phiên bản",
    steps: "Số bước",
    noVersions: "Chưa lưu phiên bản nào.",
  },
  dateBy: "{date}, bởi {by}",
  stepCount: { other: "{count} bước" },
  minutes: "khoảng {minutes} phút",
  untitledGuide: "Hướng dẫn chưa có tiêu đề",
  screenshotFor: "Ảnh chụp màn hình của bước {number}: {text}",
  callouts: { note: "LƯU Ý", tip: "MẸO", warning: "CẢNH BÁO", important: "QUAN TRỌNG" },
  codeLabels: { cmd: "Dấu nhắc Lệnh", excel: "Công thức Excel" },
  player: {
    play: "Phát",
    pause: "Tạm dừng",
    speed: "Tốc độ",
    reduceMotion: "Giảm chuyển động",
    allSteps: "Xem tất cả các bước",
    backToPlayer: "Quay lại phần trình diễn",
    fullScreen: "Toàn màn hình",
    thumbnails: "Các bước",
    back: "Quay lại",
    next: "Tiếp",
    start: "Bắt đầu",
    startAgain: "Bắt đầu lại",
    goToStep: "Đến bước {number}",
    percentDone: "Đã xong {percent}%",
    stepCard: "Bước hiện tại",
    announce: "Bước {number}/{total}: {text}. {alt}",
    language: "Ngôn ngữ",
  },
};
