import type { ExportWordTemplates } from "./types";

/**
 * 繁體中文 (Taiwan): the words exports use, in the style of Microsoft's zh-TW documentation
 * (corner brackets 「…」, Taiwan's own terms, a space between Chinese and Latin text or numbers,
 * Microsoft Learn's box labels).
 */
export const zhHant: ExportWordTemplates = {
  beforeYouStart: "開始之前",
  youreDone: "大功告成",
  madeWith: "以 Steps 製作",
  preparedBy: "編寫者：{name}",
  page: "第 {current} 頁，共 {total} 頁",
  output: "輸出",
  outputLines: { other: "{count} 行" },
  shortened: "已縮短",
  copy: "複製",
  copied: "已複製",
  contents: "目錄",
  firstSteps: "起始步驟",
  untitledSection: "未命名章節",
  step: "步驟 {number}",
  steps: "步驟 {first}–{last}",
  documentControl: "文件管制",
  control: {
    title: "標題",
    owner: "負責人",
    preparedBy: "編寫者",
    created: "建立日期",
    updated: "上次更新",
    reviewBy: "審閱日期",
    exported: "匯出日期",
    notSet: "未設定",
    history: "版本歷程記錄",
    date: "日期",
    by: "修改者",
    note: "版本",
    steps: "步驟",
    noVersions: "還沒有儲存的版本。",
  },
  dateBy: "{date}（{by}）",
  stepCount: { other: "{count} 個步驟" },
  minutes: "約 {minutes} 分鐘",
  untitledGuide: "未命名指南",
  screenshotFor: "步驟 {number} 的螢幕擷取畫面：{text}",
  callouts: { note: "注意", tip: "提示", warning: "警告", important: "重要" },
  codeLabels: { cmd: "命令提示字元", excel: "Excel 公式" },
  player: {
    play: "播放",
    pause: "暫停",
    speed: "速度",
    reduceMotion: "減少動畫",
    allSteps: "檢視所有步驟",
    backToPlayer: "返回逐步解說",
    fullScreen: "全螢幕",
    thumbnails: "步驟",
    back: "上一步",
    next: "下一步",
    start: "開始",
    startAgain: "重新開始",
    goToStep: "前往步驟 {number}",
    percentDone: "已完成 {percent}%",
    stepCard: "目前步驟",
    announce: "步驟 {number}/{total}：{text}。{alt}",
    language: "語言",
  },
};
