import type { ExportWordTemplates } from "./types";

/**
 * 简体中文: the words exports use, in the style of Microsoft's zh-CN documentation (quotation
 * marks “…”, a space between Chinese and Latin text or numbers, Microsoft Learn's box labels).
 */
export const zhHans: ExportWordTemplates = {
  beforeYouStart: "开始之前",
  youreDone: "大功告成",
  madeWith: "使用 Steps 制作",
  preparedBy: "编写人：{name}",
  page: "第 {current} 页，共 {total} 页",
  output: "输出",
  outputLines: { other: "{count} 行" },
  shortened: "已缩短",
  copy: "复制",
  copied: "已复制",
  contents: "目录",
  firstSteps: "起始步骤",
  untitledSection: "未命名部分",
  step: "步骤 {number}",
  steps: "步骤 {first}–{last}",
  documentControl: "文档控制",
  control: {
    title: "标题",
    owner: "负责人",
    preparedBy: "编写人",
    created: "创建日期",
    updated: "上次更新",
    reviewBy: "审阅日期",
    exported: "导出日期",
    notSet: "未设置",
    history: "版本历史记录",
    date: "日期",
    by: "修改人",
    note: "版本",
    steps: "步骤",
    noVersions: "还没有保存的版本。",
  },
  dateBy: "{date}（{by}）",
  stepCount: { other: "{count} 个步骤" },
  minutes: "约 {minutes} 分钟",
  untitledGuide: "未命名指南",
  screenshotFor: "步骤 {number} 的截图：{text}",
  callouts: { note: "备注", tip: "提示", warning: "警告", important: "重要" },
  codeLabels: { cmd: "命令提示符", excel: "Excel 公式" },
  player: {
    play: "播放",
    pause: "暂停",
    speed: "速度",
    reduceMotion: "减少动画",
    allSteps: "查看所有步骤",
    backToPlayer: "返回演示",
    fullScreen: "全屏",
    thumbnails: "步骤",
    back: "上一步",
    next: "下一步",
    start: "开始",
    startAgain: "重新开始",
    goToStep: "转到步骤 {number}",
    percentDone: "已完成 {percent}%",
    stepCard: "当前步骤",
    announce: "步骤 {number}/{total}：{text}。{alt}",
    language: "语言",
  },
};
