; The Bulgarian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_BULGARIAN} "Добавяне или преинсталиране на компоненти"
LangString alreadyInstalled ${LANG_BULGARIAN} "Вече е инсталирано"
LangString alreadyInstalledLong ${LANG_BULGARIAN} "${PRODUCTNAME} ${VERSION} вече е инсталирано. Изберете действието, което искате да извършите, и щракнете върху „Напред“, за да продължите."
LangString appRunning ${LANG_BULGARIAN} "{{product_name}} все още е отворено. Затворете го и опитайте отново."
LangString appRunningOkKill ${LANG_BULGARIAN} "{{product_name}} е отворено и първо трябва да бъде затворено.$\n$\nРъководствата ви вече са запазени. Ако записвате, записаното дотук се запазва и Steps ще ви го предложи следващия път, когато се отвори.$\n$\nИзберете „OK“, за да затворите {{product_name}} сега, или „Отказ“, за да спрете."
LangString chooseMaintenanceOption ${LANG_BULGARIAN} "Изберете действие по поддръжката."
LangString choowHowToInstall ${LANG_BULGARIAN} "Изберете как искате да инсталирате ${PRODUCTNAME}."
LangString createDesktop ${LANG_BULGARIAN} "Създай пряк път на работния плот"
LangString dontUninstall ${LANG_BULGARIAN} "Не деинсталирай"
LangString dontUninstallDowngrade ${LANG_BULGARIAN} "Не деинсталирай (инсталирането на по-стара версия без деинсталиране е забранено за този инсталатор)"
LangString failedToKillApp ${LANG_BULGARIAN} "{{product_name}} не можа да бъде затворено. Затворете го сами и опитайте отново."
LangString installingWebview2 ${LANG_BULGARIAN} "Инсталиране на WebView2..."
LangString newerVersionInstalled ${LANG_BULGARIAN} "Вече е инсталирана по-нова версия на ${PRODUCTNAME}! Не се препоръчва да инсталирате по-стара версия. Ако наистина искате да инсталирате тази по-стара версия, по-добре първо деинсталирайте текущата. Изберете действието, което искате да извършите, и щракнете върху „Напред“, за да продължите."
LangString older ${LANG_BULGARIAN} "по-стара"
LangString olderOrUnknownVersionInstalled ${LANG_BULGARIAN} "В системата ви е инсталирана $R4 версия на ${PRODUCTNAME}. Препоръчва се да деинсталирате текущата версия преди инсталирането. Изберете действието, което искате да извършите, и щракнете върху „Напред“, за да продължите."
LangString silentDowngrades ${LANG_BULGARIAN} "Инсталирането на по-стари версии е забранено за този инсталатор, затова безшумното инсталиране не може да продължи. Използвайте графичния инсталатор.$\n"
LangString unableToUninstall ${LANG_BULGARIAN} "Деинсталирането не е възможно!"
LangString uninstallApp ${LANG_BULGARIAN} "Деинсталиране на ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_BULGARIAN} "Деинсталирай преди инсталиране"
LangString unknown ${LANG_BULGARIAN} "неизвестна"
LangString webview2AbortError ${LANG_BULGARIAN} "Инсталирането на WebView2 не бе успешно! Приложението не може да работи без него. Опитайте да рестартирате инсталатора."
LangString webview2DownloadError ${LANG_BULGARIAN} "Грешка: изтеглянето на WebView2 не бе успешно - $0"
LangString webview2DownloadSuccess ${LANG_BULGARIAN} "Инсталаторът на WebView2 е изтеглен успешно"
LangString webview2Downloading ${LANG_BULGARIAN} "Изтегляне на инсталатора на WebView2..."
LangString webview2InstallError ${LANG_BULGARIAN} "Грешка: инсталирането на WebView2 не бе успешно, код на изход $1"
LangString webview2InstallSuccess ${LANG_BULGARIAN} "WebView2 е инсталиран успешно"
LangString deleteAppData ${LANG_BULGARIAN} "Изтрий данните на приложението"
