; The Catalan translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_CATALAN} "Afegeix o reinstal·la components"
LangString alreadyInstalled ${LANG_CATALAN} "Ja està instal·lat"
LangString alreadyInstalledLong ${LANG_CATALAN} "${PRODUCTNAME} ${VERSION} ja està instal·lat. Seleccioneu l'operació que voleu fer i feu clic a Següent per continuar."
LangString appRunning ${LANG_CATALAN} "{{product_name}} encara està obert. Tanqueu-lo i torneu-ho a provar."
LangString appRunningOkKill ${LANG_CATALAN} "{{product_name}} està obert i primer s'ha de tancar.$\n$\nLes guies ja estan desades. Si esteu enregistrant, el que heu enregistrat fins ara es conserva, i Steps us ho tornarà a oferir la propera vegada que s'obri.$\n$\nSeleccioneu D'acord per tancar {{product_name}} ara, o Cancel·la per aturar."
LangString chooseMaintenanceOption ${LANG_CATALAN} "Trieu l'opció de manteniment que voleu fer."
LangString choowHowToInstall ${LANG_CATALAN} "Trieu com voleu instal·lar ${PRODUCTNAME}."
LangString createDesktop ${LANG_CATALAN} "Crea una drecera a l'escriptori"
LangString dontUninstall ${LANG_CATALAN} "No el desinstal·lis"
LangString dontUninstallDowngrade ${LANG_CATALAN} "No el desinstal·lis (en aquest instal·lador no es pot tornar a una versió anterior sense desinstal·lar)"
LangString failedToKillApp ${LANG_CATALAN} "No s'ha pogut tancar {{product_name}}. Tanqueu-lo manualment i torneu-ho a provar."
LangString installingWebview2 ${LANG_CATALAN} "S'està instal·lant WebView2..."
LangString newerVersionInstalled ${LANG_CATALAN} "Ja hi ha instal·lada una versió més nova de ${PRODUCTNAME}. No es recomana instal·lar una versió anterior. Si realment voleu instal·lar aquesta versió anterior, és millor que primer desinstal·leu la versió actual. Seleccioneu l'operació que voleu fer i feu clic a Següent per continuar."
LangString older ${LANG_CATALAN} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_CATALAN} "Hi ha instal·lada al sistema una versió $R4 de ${PRODUCTNAME}. Es recomana desinstal·lar la versió actual abans d'instal·lar. Seleccioneu l'operació que voleu fer i feu clic a Següent per continuar."
LangString silentDowngrades ${LANG_CATALAN} "En aquest instal·lador no es pot tornar a una versió anterior, així que no es pot continuar amb la instal·lació silenciosa. Feu servir l'instal·lador amb interfície gràfica.$\n"
LangString unableToUninstall ${LANG_CATALAN} "No s'ha pogut desinstal·lar."
LangString uninstallApp ${LANG_CATALAN} "Desinstal·la ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CATALAN} "Desinstal·la abans d'instal·lar"
LangString unknown ${LANG_CATALAN} "desconeguda"
LangString webview2AbortError ${LANG_CATALAN} "No s'ha pogut instal·lar WebView2. L'aplicació no pot funcionar sense. Proveu de reiniciar l'instal·lador."
LangString webview2DownloadError ${LANG_CATALAN} "Error: no s'ha pogut baixar WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_CATALAN} "S'ha baixat correctament el programa d'arrencada de WebView2"
LangString webview2Downloading ${LANG_CATALAN} "S'està baixant el programa d'arrencada de WebView2..."
LangString webview2InstallError ${LANG_CATALAN} "Error: la instal·lació de WebView2 ha fallat amb el codi de sortida $1"
LangString webview2InstallSuccess ${LANG_CATALAN} "S'ha instal·lat correctament WebView2"
LangString deleteAppData ${LANG_CATALAN} "Suprimeix les dades de l'aplicació"
