; The Croatian translation of English.nsh, the setup .exe's own messages.
; Every string English.nsh has must be here too, with the same LangString ids.
LangString addOrReinstall ${LANG_CROATIAN} "Dodaj ili ponovno instaliraj komponente"
LangString alreadyInstalled ${LANG_CROATIAN} "Već instalirano"
LangString alreadyInstalledLong ${LANG_CROATIAN} "${PRODUCTNAME} ${VERSION} već je instaliran. Odaberite radnju koju želite izvršiti i kliknite „Dalje” da biste nastavili."
LangString appRunning ${LANG_CROATIAN} "{{product_name}} je još otvoren. Zatvorite ga, a zatim pokušajte ponovno."
LangString appRunningOkKill ${LANG_CROATIAN} "{{product_name}} je otvoren i najprije se mora zatvoriti.$\n$\nVaši su vodiči već spremljeni. Ako snimate, ono što ste dosad snimili zadržava se, a Steps vam to nudi sljedeći put kad se otvori.$\n$\nOdaberite „U redu” da biste sada zatvorili {{product_name}} ili „Odustani” da biste prekinuli."
LangString chooseMaintenanceOption ${LANG_CROATIAN} "Odaberite radnju održavanja koju želite izvršiti."
LangString choowHowToInstall ${LANG_CROATIAN} "Odaberite kako želite instalirati ${PRODUCTNAME}."
LangString createDesktop ${LANG_CROATIAN} "Stvori prečac na radnoj površini"
LangString dontUninstall ${LANG_CROATIAN} "Nemoj deinstalirati"
LangString dontUninstallDowngrade ${LANG_CROATIAN} "Nemoj deinstalirati (instaliranje starije verzije bez deinstalacije onemogućeno je za ovaj instalacijski program)"
LangString failedToKillApp ${LANG_CROATIAN} "{{product_name}} nije moguće zatvoriti. Zatvorite ga sami, a zatim pokušajte ponovno."
LangString installingWebview2 ${LANG_CROATIAN} "Instaliranje komponente WebView2..."
LangString newerVersionInstalled ${LANG_CROATIAN} "Novija verzija programa ${PRODUCTNAME} već je instalirana! Ne preporučuje se instaliranje starije verzije. Ako zaista želite instalirati ovu stariju verziju, bolje je najprije deinstalirati trenutačnu. Odaberite radnju koju želite izvršiti i kliknite „Dalje” da biste nastavili."
LangString older ${LANG_CROATIAN} "starija"
LangString olderOrUnknownVersionInstalled ${LANG_CROATIAN} "Na sustavu je instalirana $R4 verzija programa ${PRODUCTNAME}. Preporučuje se da prije instalacije deinstalirate trenutačnu verziju. Odaberite radnju koju želite izvršiti i kliknite „Dalje” da biste nastavili."
LangString silentDowngrades ${LANG_CROATIAN} "Instaliranje starije verzije onemogućeno je za ovaj instalacijski program pa se tiha instalacija ne može nastaviti. Umjesto toga upotrijebite grafički instalacijski program.$\n"
LangString unableToUninstall ${LANG_CROATIAN} "Deinstalacija nije uspjela!"
LangString uninstallApp ${LANG_CROATIAN} "Deinstaliraj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CROATIAN} "Deinstaliraj prije instalacije"
LangString unknown ${LANG_CROATIAN} "nepoznata"
LangString webview2AbortError ${LANG_CROATIAN} "Instaliranje komponente WebView2 nije uspjelo! Aplikacija ne može raditi bez nje. Pokušajte ponovno pokrenuti instalacijski program."
LangString webview2DownloadError ${LANG_CROATIAN} "Pogreška: preuzimanje komponente WebView2 nije uspjelo – $0"
LangString webview2DownloadSuccess ${LANG_CROATIAN} "Program za pokretanje instalacije WebView2 uspješno je preuzet"
LangString webview2Downloading ${LANG_CROATIAN} "Preuzimanje programa za pokretanje instalacije WebView2..."
LangString webview2InstallError ${LANG_CROATIAN} "Pogreška: instaliranje komponente WebView2 nije uspjelo, izlazni kôd $1"
LangString webview2InstallSuccess ${LANG_CROATIAN} "WebView2 uspješno je instaliran"
LangString deleteAppData ${LANG_CROATIAN} "Izbriši podatke aplikacije"
