; The Czech translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_CZECH} "Přidat nebo přeinstalovat součásti"
LangString alreadyInstalled ${LANG_CZECH} "Již nainstalováno"
LangString alreadyInstalledLong ${LANG_CZECH} "${PRODUCTNAME} ${VERSION} je již nainstalován. Vyberte operaci, kterou chcete provést, a pokračujte kliknutím na Další."
LangString appRunning ${LANG_CZECH} "Aplikace {{product_name}} je stále otevřená. Zavřete ji a zkuste to znovu."
LangString appRunningOkKill ${LANG_CZECH} "Aplikace {{product_name}} je otevřená a musí se nejdřív zavřít.$\n$\nVaše návody jsou už uložené. Pokud právě nahráváte, dosud nahraný záznam se zachová a Steps vám ho při příštím spuštění znovu nabídne.$\n$\nKliknutím na OK aplikaci {{product_name}} teď zavřete, kliknutím na Zrušit akci ukončíte."
LangString chooseMaintenanceOption ${LANG_CZECH} "Vyberte možnost údržby, kterou chcete provést."
LangString choowHowToInstall ${LANG_CZECH} "Vyberte, jak chcete nainstalovat ${PRODUCTNAME}."
LangString createDesktop ${LANG_CZECH} "Vytvořit zástupce na ploše"
LangString dontUninstall ${LANG_CZECH} "Neodinstalovat"
LangString dontUninstallDowngrade ${LANG_CZECH} "Neodinstalovat (přechod na starší verzi bez odinstalace je u tohoto instalačního programu zakázán)"
LangString failedToKillApp ${LANG_CZECH} "Aplikaci {{product_name}} se nepodařilo zavřít. Zavřete ji ručně a zkuste to znovu."
LangString installingWebview2 ${LANG_CZECH} "Instaluje se WebView2..."
LangString newerVersionInstalled ${LANG_CZECH} "Novější verze ${PRODUCTNAME} je již nainstalovaná! Instalovat starší verzi se nedoporučuje. Pokud opravdu chcete nainstalovat tuto starší verzi, je lepší nejdřív odinstalovat aktuální verzi. Vyberte operaci, kterou chcete provést, a pokračujte kliknutím na Další."
LangString older ${LANG_CZECH} "starší"
LangString olderOrUnknownVersionInstalled ${LANG_CZECH} "V systému je nainstalovaná $R4 verze ${PRODUCTNAME}. Před instalací se doporučuje aktuální verzi odinstalovat. Vyberte operaci, kterou chcete provést, a pokračujte kliknutím na Další."
LangString silentDowngrades ${LANG_CZECH} "Přechod na starší verzi je u tohoto instalačního programu zakázán, takže tichou instalaci nelze dokončit. Použijte prosím instalační program s grafickým rozhraním.$\n"
LangString unableToUninstall ${LANG_CZECH} "Odinstalace se nezdařila!"
LangString uninstallApp ${LANG_CZECH} "Odinstalovat ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CZECH} "Před instalací odinstalovat"
LangString unknown ${LANG_CZECH} "neznámá"
LangString webview2AbortError ${LANG_CZECH} "Instalace WebView2 se nezdařila! Aplikace bez něj nemůže běžet. Zkuste instalační program spustit znovu."
LangString webview2DownloadError ${LANG_CZECH} "Chyba: Stažení WebView2 se nezdařilo - $0"
LangString webview2DownloadSuccess ${LANG_CZECH} "Zaváděcí program WebView2 byl úspěšně stažen"
LangString webview2Downloading ${LANG_CZECH} "Stahuje se zaváděcí program WebView2..."
LangString webview2InstallError ${LANG_CZECH} "Chyba: Instalace WebView2 se nezdařila s ukončovacím kódem $1"
LangString webview2InstallSuccess ${LANG_CZECH} "WebView2 byl úspěšně nainstalován"
LangString deleteAppData ${LANG_CZECH} "Odstranit data aplikace"
