; The Danish translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_DANISH} "Tilføj/geninstaller komponenter"
LangString alreadyInstalled ${LANG_DANISH} "Allerede installeret"
LangString alreadyInstalledLong ${LANG_DANISH} "${PRODUCTNAME} ${VERSION} er allerede installeret. Vælg, hvad du vil gøre, og klik på Næste for at fortsætte."
LangString appRunning ${LANG_DANISH} "{{product_name}} er stadig åben. Luk programmet, og prøv så igen."
LangString appRunningOkKill ${LANG_DANISH} "{{product_name}} er åben og skal lukkes først.$\n$\nDine vejledninger er allerede gemt. Hvis du er ved at optage, bevares det, du har optaget indtil nu, og Steps tilbyder dig det, næste gang programmet åbnes.$\n$\nVælg OK for at lukke {{product_name}} nu, eller Annuller for at stoppe."
LangString chooseMaintenanceOption ${LANG_DANISH} "Vælg den vedligeholdelseshandling, du vil udføre."
LangString choowHowToInstall ${LANG_DANISH} "Vælg, hvordan du vil installere ${PRODUCTNAME}."
LangString createDesktop ${LANG_DANISH} "Opret genvej på skrivebordet"
LangString dontUninstall ${LANG_DANISH} "Afinstaller ikke"
LangString dontUninstallDowngrade ${LANG_DANISH} "Afinstaller ikke (nedgradering uden afinstallation er deaktiveret for dette installationsprogram)"
LangString failedToKillApp ${LANG_DANISH} "{{product_name}} kunne ikke lukkes. Luk programmet selv, og prøv så igen."
LangString installingWebview2 ${LANG_DANISH} "Installerer WebView2..."
LangString newerVersionInstalled ${LANG_DANISH} "En nyere version af ${PRODUCTNAME} er allerede installeret! Det anbefales ikke at installere en ældre version. Hvis du virkelig vil installere denne ældre version, er det bedre at afinstallere den nuværende version først. Vælg, hvad du vil gøre, og klik på Næste for at fortsætte."
LangString older ${LANG_DANISH} "ældre"
LangString olderOrUnknownVersionInstalled ${LANG_DANISH} "En $R4 version af ${PRODUCTNAME} er installeret på dit system. Det anbefales, at du afinstallerer den nuværende version, før du installerer. Vælg, hvad du vil gøre, og klik på Næste for at fortsætte."
LangString silentDowngrades ${LANG_DANISH} "Nedgraderinger er deaktiveret for dette installationsprogram, så den lydløse installation kan ikke fortsætte. Brug det grafiske installationsprogram i stedet.$\n"
LangString unableToUninstall ${LANG_DANISH} "Afinstallationen kunne ikke gennemføres!"
LangString uninstallApp ${LANG_DANISH} "Afinstaller ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_DANISH} "Afinstaller før installation"
LangString unknown ${LANG_DANISH} "ukendt"
LangString webview2AbortError ${LANG_DANISH} "WebView2 kunne ikke installeres! Appen kan ikke køre uden. Prøv at genstarte installationsprogrammet."
LangString webview2DownloadError ${LANG_DANISH} "Fejl: Download af WebView2 mislykkedes – $0"
LangString webview2DownloadSuccess ${LANG_DANISH} "Installationsprogrammet til WebView2 er downloadet"
LangString webview2Downloading ${LANG_DANISH} "Downloader installationsprogrammet til WebView2..."
LangString webview2InstallError ${LANG_DANISH} "Fejl: Installation af WebView2 mislykkedes med afslutningskoden $1"
LangString webview2InstallSuccess ${LANG_DANISH} "WebView2 er installeret"
LangString deleteAppData ${LANG_DANISH} "Slet appens data"
