; The Dutch translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_DUTCH} "Onderdelen toevoegen/opnieuw installeren"
LangString alreadyInstalled ${LANG_DUTCH} "Al geïnstalleerd"
LangString alreadyInstalledLong ${LANG_DUTCH} "${PRODUCTNAME} ${VERSION} is al geïnstalleerd. Kies wat je wilt doen en klik op Volgende om door te gaan."
LangString appRunning ${LANG_DUTCH} "{{product_name}} is nog geopend. Sluit het en probeer het dan opnieuw."
LangString appRunningOkKill ${LANG_DUTCH} "{{product_name}} is geopend en moet eerst worden gesloten.$\n$\nJe handleidingen zijn al opgeslagen. Als je aan het opnemen bent, blijft wat je tot nu toe hebt opgenomen bewaard, en biedt Steps het de volgende keer dat het wordt geopend weer aan.$\n$\nKies OK om {{product_name}} nu te sluiten, of Annuleren om te stoppen."
LangString chooseMaintenanceOption ${LANG_DUTCH} "Kies welk onderhoud je wilt uitvoeren."
LangString choowHowToInstall ${LANG_DUTCH} "Kies hoe je ${PRODUCTNAME} wilt installeren."
LangString createDesktop ${LANG_DUTCH} "Snelkoppeling op bureaublad maken"
LangString dontUninstall ${LANG_DUTCH} "Niet verwijderen"
LangString dontUninstallDowngrade ${LANG_DUTCH} "Niet verwijderen (downgraden zonder verwijderen is uitgeschakeld voor dit installatieprogramma)"
LangString failedToKillApp ${LANG_DUTCH} "{{product_name}} kon niet worden gesloten. Sluit het zelf en probeer het dan opnieuw."
LangString installingWebview2 ${LANG_DUTCH} "WebView2 installeren..."
LangString newerVersionInstalled ${LANG_DUTCH} "Er is al een nieuwere versie van ${PRODUCTNAME} geïnstalleerd. Het wordt afgeraden om een oudere versie te installeren. Als je deze oudere versie echt wilt installeren, kun je beter eerst de huidige versie verwijderen. Kies wat je wilt doen en klik op Volgende om door te gaan."
LangString older ${LANG_DUTCH} "oudere"
LangString olderOrUnknownVersionInstalled ${LANG_DUTCH} "Er is een $R4 versie van ${PRODUCTNAME} op je systeem geïnstalleerd. Het wordt aanbevolen om de huidige versie te verwijderen voordat je installeert. Kies wat je wilt doen en klik op Volgende om door te gaan."
LangString silentDowngrades ${LANG_DUTCH} "Downgraden is uitgeschakeld voor dit installatieprogramma. De stille installatie kan niet doorgaan. Gebruik in plaats daarvan het installatieprogramma met grafische interface.$\n"
LangString unableToUninstall ${LANG_DUTCH} "Kan niet verwijderen!"
LangString uninstallApp ${LANG_DUTCH} "${PRODUCTNAME} verwijderen"
LangString uninstallBeforeInstalling ${LANG_DUTCH} "Verwijderen voor het installeren"
LangString unknown ${LANG_DUTCH} "onbekende"
LangString webview2AbortError ${LANG_DUTCH} "Kan WebView2 niet installeren! De app kan niet worden uitgevoerd zonder WebView2. Start het installatieprogramma opnieuw."
LangString webview2DownloadError ${LANG_DUTCH} "Fout: downloaden van WebView2 mislukt - $0"
LangString webview2DownloadSuccess ${LANG_DUTCH} "WebView2-bootstrapper gedownload"
LangString webview2Downloading ${LANG_DUTCH} "WebView2-bootstrapper downloaden..."
LangString webview2InstallError ${LANG_DUTCH} "Fout: installeren van WebView2 mislukt met afsluitcode $1"
LangString webview2InstallSuccess ${LANG_DUTCH} "WebView2 geïnstalleerd"
LangString deleteAppData ${LANG_DUTCH} "De appgegevens verwijderen"
