; The Finnish translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same ids, in the same order.
LangString addOrReinstall ${LANG_FINNISH} "Lisää tai asenna osia uudelleen"
LangString alreadyInstalled ${LANG_FINNISH} "On jo asennettu"
LangString alreadyInstalledLong ${LANG_FINNISH} "${PRODUCTNAME} ${VERSION} on jo asennettu. Valitse haluamasi toiminto ja jatka valitsemalla Seuraava."
LangString appRunning ${LANG_FINNISH} "{{product_name}} on yhä auki. Sulje se ja yritä sitten uudelleen."
LangString appRunningOkKill ${LANG_FINNISH} "{{product_name}} on auki, ja se on suljettava ensin.$\n$\nOhjeesi on jo tallennettu. Jos nauhoitus on käynnissä, tähän mennessä nauhoitettu säilyy, ja Steps tarjoaa sitä takaisin, kun se seuraavan kerran avataan.$\n$\nSulje {{product_name}} nyt valitsemalla OK, tai lopeta valitsemalla Peruuta."
LangString chooseMaintenanceOption ${LANG_FINNISH} "Valitse suoritettava ylläpitotoiminto."
LangString choowHowToInstall ${LANG_FINNISH} "Valitse, miten haluat asentaa sovelluksen ${PRODUCTNAME}."
LangString createDesktop ${LANG_FINNISH} "Luo pikakuvake työpöydälle"
LangString dontUninstall ${LANG_FINNISH} "Älä poista asennusta"
LangString dontUninstallDowngrade ${LANG_FINNISH} "Älä poista asennusta (vanhempaan versioon siirtyminen ilman asennuksen poistoa ei ole käytössä tässä asennusohjelmassa)"
LangString failedToKillApp ${LANG_FINNISH} "Sovellusta {{product_name}} ei voitu sulkea. Sulje se itse ja yritä sitten uudelleen."
LangString installingWebview2 ${LANG_FINNISH} "Asennetaan WebView2:ta..."
LangString newerVersionInstalled ${LANG_FINNISH} "Sovelluksesta ${PRODUCTNAME} on jo asennettu uudempi versio! Vanhemman version asentamista ei suositella. Jos todella haluat asentaa tämän vanhemman version, on parempi poistaa nykyisen version asennus ensin. Valitse haluamasi toiminto ja jatka valitsemalla Seuraava."
LangString older ${LANG_FINNISH} "vanhempi"
LangString olderOrUnknownVersionInstalled ${LANG_FINNISH} "Järjestelmääsi on asennettu sovelluksen ${PRODUCTNAME} $R4 versio. On suositeltavaa poistaa nykyisen version asennus ennen asentamista. Valitse haluamasi toiminto ja jatka valitsemalla Seuraava."
LangString silentDowngrades ${LANG_FINNISH} "Vanhempaan versioon siirtyminen ei ole käytössä tässä asennusohjelmassa, joten hiljaista asennusta ei voi jatkaa. Käytä sen sijaan graafista asennusohjelmaa.$\n"
LangString unableToUninstall ${LANG_FINNISH} "Asennuksen poistaminen ei onnistunut!"
LangString uninstallApp ${LANG_FINNISH} "Poista sovelluksen ${PRODUCTNAME} asennus"
LangString uninstallBeforeInstalling ${LANG_FINNISH} "Poista asennus ennen asentamista"
LangString unknown ${LANG_FINNISH} "tuntematon"
LangString webview2AbortError ${LANG_FINNISH} "WebView2:n asentaminen epäonnistui! Sovellus ei toimi ilman sitä. Yritä käynnistää asennusohjelma uudelleen."
LangString webview2DownloadError ${LANG_FINNISH} "Virhe: WebView2:n lataaminen epäonnistui - $0"
LangString webview2DownloadSuccess ${LANG_FINNISH} "WebView2-käynnistysohjelma ladattiin onnistuneesti"
LangString webview2Downloading ${LANG_FINNISH} "Ladataan WebView2-käynnistysohjelmaa..."
LangString webview2InstallError ${LANG_FINNISH} "Virhe: WebView2:n asentaminen epäonnistui, lopetuskoodi $1"
LangString webview2InstallSuccess ${LANG_FINNISH} "WebView2 asennettiin onnistuneesti"
LangString deleteAppData ${LANG_FINNISH} "Poista sovelluksen tiedot"
