; The French translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_FRENCH} "Ajouter/Réinstaller des composants"
LangString alreadyInstalled ${LANG_FRENCH} "Déjà installé"
LangString alreadyInstalledLong ${LANG_FRENCH} "${PRODUCTNAME} ${VERSION} est déjà installé. Sélectionnez l'opération que vous souhaitez effectuer, puis cliquez sur Suivant pour continuer."
LangString appRunning ${LANG_FRENCH} "{{product_name}} est toujours ouvert. Fermez-le, puis réessayez."
LangString appRunningOkKill ${LANG_FRENCH} "{{product_name}} est ouvert et doit d'abord être fermé.$\n$\nVos guides sont déjà enregistrés. Si un enregistrement est en cours, ce que vous avez enregistré jusqu'ici est conservé, et Steps vous le proposera à sa prochaine ouverture.$\n$\nSélectionnez OK pour fermer {{product_name}} maintenant, ou Annuler pour arrêter."
LangString chooseMaintenanceOption ${LANG_FRENCH} "Choisissez l'opération de maintenance à effectuer."
LangString choowHowToInstall ${LANG_FRENCH} "Choisissez comment vous souhaitez installer ${PRODUCTNAME}."
LangString createDesktop ${LANG_FRENCH} "Créer un raccourci sur le Bureau"
LangString dontUninstall ${LANG_FRENCH} "Ne pas désinstaller"
LangString dontUninstallDowngrade ${LANG_FRENCH} "Ne pas désinstaller (le retour à une version antérieure sans désinstallation est désactivé pour ce programme d'installation)"
LangString failedToKillApp ${LANG_FRENCH} "Impossible de fermer {{product_name}}. Fermez-le vous-même, puis réessayez."
LangString installingWebview2 ${LANG_FRENCH} "Installation de WebView2..."
LangString newerVersionInstalled ${LANG_FRENCH} "Une version plus récente de ${PRODUCTNAME} est déjà installée ! Il n'est pas recommandé d'installer une version plus ancienne. Si vous voulez vraiment installer cette version plus ancienne, il est préférable de désinstaller d'abord la version actuelle. Sélectionnez l'opération que vous souhaitez effectuer, puis cliquez sur Suivant pour continuer."
LangString older ${LANG_FRENCH} "plus ancienne"
LangString olderOrUnknownVersionInstalled ${LANG_FRENCH} "Une version $R4 de ${PRODUCTNAME} est installée sur votre système. Il est recommandé de désinstaller la version actuelle avant l'installation. Sélectionnez l'opération que vous souhaitez effectuer, puis cliquez sur Suivant pour continuer."
LangString silentDowngrades ${LANG_FRENCH} "Le retour à une version antérieure est désactivé pour ce programme d'installation : impossible de poursuivre l'installation silencieuse. Utilisez plutôt le programme d'installation avec interface graphique.$\n"
LangString unableToUninstall ${LANG_FRENCH} "Impossible de désinstaller !"
LangString uninstallApp ${LANG_FRENCH} "Désinstaller ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_FRENCH} "Désinstaller avant l'installation"
LangString unknown ${LANG_FRENCH} "inconnue"
LangString webview2AbortError ${LANG_FRENCH} "Échec de l'installation de WebView2 ! L'application ne peut pas fonctionner sans lui. Essayez de relancer le programme d'installation."
LangString webview2DownloadError ${LANG_FRENCH} "Erreur : échec du téléchargement de WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_FRENCH} "Programme d'amorçage WebView2 téléchargé"
LangString webview2Downloading ${LANG_FRENCH} "Téléchargement du programme d'amorçage WebView2..."
LangString webview2InstallError ${LANG_FRENCH} "Erreur : l'installation de WebView2 a échoué avec le code de sortie $1"
LangString webview2InstallSuccess ${LANG_FRENCH} "WebView2 installé"
LangString deleteAppData ${LANG_FRENCH} "Supprimer les données de l'application"
