; The German translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_GERMAN} "Komponenten hinzufügen/neu installieren"
LangString alreadyInstalled ${LANG_GERMAN} "Bereits installiert"
LangString alreadyInstalledLong ${LANG_GERMAN} "${PRODUCTNAME} ${VERSION} ist bereits installiert. Wählen Sie den gewünschten Vorgang aus, und klicken Sie auf „Weiter“, um fortzufahren."
LangString appRunning ${LANG_GERMAN} "{{product_name}} ist noch geöffnet. Schließen Sie es, und versuchen Sie es dann noch einmal."
LangString appRunningOkKill ${LANG_GERMAN} "{{product_name}} ist geöffnet und muss zuerst geschlossen werden.$\n$\nIhre Anleitungen sind bereits gespeichert. Falls Sie gerade aufzeichnen, bleibt das bisher Aufgezeichnete erhalten, und Steps bietet es Ihnen beim nächsten Öffnen wieder an.$\n$\nKlicken Sie auf „OK“, um {{product_name}} jetzt zu schließen, oder auf „Abbrechen“, um aufzuhören."
LangString chooseMaintenanceOption ${LANG_GERMAN} "Wählen Sie den gewünschten Wartungsvorgang aus."
LangString choowHowToInstall ${LANG_GERMAN} "Wählen Sie aus, wie ${PRODUCTNAME} installiert werden soll."
LangString createDesktop ${LANG_GERMAN} "Desktopverknüpfung erstellen"
LangString dontUninstall ${LANG_GERMAN} "Nicht deinstallieren"
LangString dontUninstallDowngrade ${LANG_GERMAN} "Nicht deinstallieren (ein Downgrade ohne Deinstallation ist bei diesem Installationsprogramm deaktiviert)"
LangString failedToKillApp ${LANG_GERMAN} "{{product_name}} konnte nicht geschlossen werden. Schließen Sie es selbst, und versuchen Sie es dann noch einmal."
LangString installingWebview2 ${LANG_GERMAN} "WebView2 wird installiert..."
LangString newerVersionInstalled ${LANG_GERMAN} "Eine neuere Version von ${PRODUCTNAME} ist bereits installiert. Es wird nicht empfohlen, eine ältere Version zu installieren. Wenn Sie diese ältere Version wirklich installieren möchten, deinstallieren Sie besser zuerst die aktuelle Version. Wählen Sie den gewünschten Vorgang aus, und klicken Sie auf „Weiter“, um fortzufahren."
LangString older ${LANG_GERMAN} "ältere"
LangString olderOrUnknownVersionInstalled ${LANG_GERMAN} "Auf Ihrem System ist eine $R4 Version von ${PRODUCTNAME} installiert. Es wird empfohlen, die aktuelle Version vor der Installation zu deinstallieren. Wählen Sie den gewünschten Vorgang aus, und klicken Sie auf „Weiter“, um fortzufahren."
LangString silentDowngrades ${LANG_GERMAN} "Downgrades sind bei diesem Installationsprogramm deaktiviert. Die automatische Installation kann nicht fortgesetzt werden. Verwenden Sie stattdessen das Installationsprogramm mit grafischer Oberfläche.$\n"
LangString unableToUninstall ${LANG_GERMAN} "Deinstallation nicht möglich!"
LangString uninstallApp ${LANG_GERMAN} "${PRODUCTNAME} deinstallieren"
LangString uninstallBeforeInstalling ${LANG_GERMAN} "Vor der Installation deinstallieren"
LangString unknown ${LANG_GERMAN} "unbekannte"
LangString webview2AbortError ${LANG_GERMAN} "WebView2 konnte nicht installiert werden! Die App kann ohne WebView2 nicht ausgeführt werden. Starten Sie das Installationsprogramm erneut."
LangString webview2DownloadError ${LANG_GERMAN} "Fehler: Download von WebView2 fehlgeschlagen - $0"
LangString webview2DownloadSuccess ${LANG_GERMAN} "WebView2-Bootstrapper erfolgreich heruntergeladen"
LangString webview2Downloading ${LANG_GERMAN} "WebView2-Bootstrapper wird heruntergeladen..."
LangString webview2InstallError ${LANG_GERMAN} "Fehler: Installation von WebView2 mit Exitcode $1 fehlgeschlagen"
LangString webview2InstallSuccess ${LANG_GERMAN} "WebView2 erfolgreich installiert"
LangString deleteAppData ${LANG_GERMAN} "App-Daten löschen"
