; The Greek translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id and in the same order.
LangString addOrReinstall ${LANG_GREEK} "Προσθήκη/επανεγκατάσταση στοιχείων"
LangString alreadyInstalled ${LANG_GREEK} "Είναι ήδη εγκατεστημένο"
LangString alreadyInstalledLong ${LANG_GREEK} "Το ${PRODUCTNAME} ${VERSION} είναι ήδη εγκατεστημένο. Επιλέξτε την ενέργεια που θέλετε να εκτελέσετε και κάντε κλικ στο Επόμενο για να συνεχίσετε."
LangString appRunning ${LANG_GREEK} "Το {{product_name}} είναι ακόμα ανοιχτό. Κλείστε το και δοκιμάστε ξανά."
LangString appRunningOkKill ${LANG_GREEK} "Το {{product_name}} είναι ανοιχτό και πρέπει πρώτα να κλείσει.$\n$\nΟι οδηγοί σας είναι ήδη αποθηκευμένοι. Αν κάνετε εγγραφή, ό,τι έχετε καταγράψει μέχρι τώρα διατηρείται και το Steps σας το προσφέρει ξανά την επόμενη φορά που θα ανοίξει.$\n$\nΕπιλέξτε OK για να κλείσει τώρα το {{product_name}} ή Άκυρο για διακοπή."
LangString chooseMaintenanceOption ${LANG_GREEK} "Επιλέξτε την ενέργεια συντήρησης που θέλετε να εκτελέσετε."
LangString choowHowToInstall ${LANG_GREEK} "Επιλέξτε πώς θέλετε να εγκαταστήσετε το ${PRODUCTNAME}."
LangString createDesktop ${LANG_GREEK} "Δημιουργία συντόμευσης στην επιφάνεια εργασίας"
LangString dontUninstall ${LANG_GREEK} "Χωρίς κατάργηση εγκατάστασης"
LangString dontUninstallDowngrade ${LANG_GREEK} "Χωρίς κατάργηση εγκατάστασης (η υποβάθμιση χωρίς κατάργηση εγκατάστασης είναι απενεργοποιημένη για αυτό το πρόγραμμα εγκατάστασης)"
LangString failedToKillApp ${LANG_GREEK} "Δεν ήταν δυνατό να κλείσει το {{product_name}}. Κλείστε το μόνοι σας και δοκιμάστε ξανά."
LangString installingWebview2 ${LANG_GREEK} "Εγκατάσταση του WebView2..."
LangString newerVersionInstalled ${LANG_GREEK} "Μια νεότερη έκδοση του ${PRODUCTNAME} είναι ήδη εγκατεστημένη! Δεν συνιστάται να εγκαταστήσετε παλαιότερη έκδοση. Αν θέλετε πραγματικά να εγκαταστήσετε αυτήν την παλαιότερη έκδοση, είναι καλύτερα να καταργήσετε πρώτα την εγκατάσταση της τρέχουσας έκδοσης. Επιλέξτε την ενέργεια που θέλετε να εκτελέσετε και κάντε κλικ στο Επόμενο για να συνεχίσετε."
LangString older ${LANG_GREEK} "παλαιότερη"
LangString olderOrUnknownVersionInstalled ${LANG_GREEK} "Μια $R4 έκδοση του ${PRODUCTNAME} είναι εγκατεστημένη στο σύστημά σας. Συνιστάται να καταργήσετε την εγκατάσταση της τρέχουσας έκδοσης πριν από την εγκατάσταση. Επιλέξτε την ενέργεια που θέλετε να εκτελέσετε και κάντε κλικ στο Επόμενο για να συνεχίσετε."
LangString silentDowngrades ${LANG_GREEK} "Η υποβάθμιση είναι απενεργοποιημένη για αυτό το πρόγραμμα εγκατάστασης, οπότε η αθόρυβη εγκατάσταση δεν μπορεί να συνεχιστεί. Χρησιμοποιήστε το πρόγραμμα εγκατάστασης με γραφικό περιβάλλον.$\n"
LangString unableToUninstall ${LANG_GREEK} "Δεν ήταν δυνατή η κατάργηση της εγκατάστασης!"
LangString uninstallApp ${LANG_GREEK} "Κατάργηση εγκατάστασης του ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_GREEK} "Κατάργηση εγκατάστασης πριν από την εγκατάσταση"
LangString unknown ${LANG_GREEK} "άγνωστη"
LangString webview2AbortError ${LANG_GREEK} "Η εγκατάσταση του WebView2 απέτυχε! Η εφαρμογή δεν μπορεί να εκτελεστεί χωρίς αυτό. Δοκιμάστε να εκκινήσετε ξανά το πρόγραμμα εγκατάστασης."
LangString webview2DownloadError ${LANG_GREEK} "Σφάλμα: Η λήψη του WebView2 απέτυχε - $0"
LangString webview2DownloadSuccess ${LANG_GREEK} "Η λήψη του προγράμματος εγκατάστασης WebView2 ολοκληρώθηκε"
LangString webview2Downloading ${LANG_GREEK} "Λήψη του προγράμματος εγκατάστασης WebView2..."
LangString webview2InstallError ${LANG_GREEK} "Σφάλμα: Η εγκατάσταση του WebView2 απέτυχε με κωδικό εξόδου $1"
LangString webview2InstallSuccess ${LANG_GREEK} "Το WebView2 εγκαταστάθηκε"
LangString deleteAppData ${LANG_GREEK} "Διαγραφή των δεδομένων της εφαρμογής"
