; The Hungarian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same ids, in the same order.
LangString addOrReinstall ${LANG_HUNGARIAN} "Összetevők hozzáadása/újratelepítése"
LangString alreadyInstalled ${LANG_HUNGARIAN} "Már telepítve van"
LangString alreadyInstalledLong ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} ${VERSION} már telepítve van. Válassza ki a végrehajtandó műveletet, majd a folytatáshoz kattintson a Tovább gombra."
LangString appRunning ${LANG_HUNGARIAN} "A(z) {{product_name}} még meg van nyitva. Zárja be, majd próbálja újra."
LangString appRunningOkKill ${LANG_HUNGARIAN} "A(z) {{product_name}} meg van nyitva, és előbb be kell zárni.$\n$\nAz útmutatói már mentve vannak. Ha éppen felvételt készít, az eddig rögzítettek megmaradnak, és a Steps a következő megnyitáskor felajánlja őket.$\n$\nAz OK gombbal most bezárja a(z) {{product_name}} alkalmazást, a Mégse gombbal pedig leállítja a műveletet."
LangString chooseMaintenanceOption ${LANG_HUNGARIAN} "Válassza ki a végrehajtandó karbantartási műveletet."
LangString choowHowToInstall ${LANG_HUNGARIAN} "Válassza ki, hogyan szeretné telepíteni a(z) ${PRODUCTNAME} alkalmazást."
LangString createDesktop ${LANG_HUNGARIAN} "Asztali parancsikon létrehozása"
LangString dontUninstall ${LANG_HUNGARIAN} "Ne legyen eltávolítva"
LangString dontUninstallDowngrade ${LANG_HUNGARIAN} "Ne legyen eltávolítva (ebben a telepítőben a régebbi verzióra váltás eltávolítás nélkül le van tiltva)"
LangString failedToKillApp ${LANG_HUNGARIAN} "A(z) {{product_name}} alkalmazást nem sikerült bezárni. Zárja be saját maga, majd próbálja újra."
LangString installingWebview2 ${LANG_HUNGARIAN} "A WebView2 telepítése..."
LangString newerVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} egy újabb verziója már telepítve van! Régebbi verzió telepítése nem ajánlott. Ha mégis ezt a régebbi verziót szeretné telepíteni, jobb előbb eltávolítani a jelenlegi verziót. Válassza ki a végrehajtandó műveletet, majd a folytatáshoz kattintson a Tovább gombra."
LangString older ${LANG_HUNGARIAN} "régebbi"
LangString olderOrUnknownVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} egy $R4 verziója van telepítve a rendszeren. Telepítés előtt ajánlott eltávolítani a jelenlegi verziót. Válassza ki a végrehajtandó műveletet, majd a folytatáshoz kattintson a Tovább gombra."
LangString silentDowngrades ${LANG_HUNGARIAN} "Ebben a telepítőben a régebbi verzióra váltás le van tiltva, ezért a csendes telepítés nem folytatható. Használja helyette a grafikus telepítőt.$\n"
LangString unableToUninstall ${LANG_HUNGARIAN} "Az eltávolítás nem sikerült!"
LangString uninstallApp ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} eltávolítása"
LangString uninstallBeforeInstalling ${LANG_HUNGARIAN} "Eltávolítás telepítés előtt"
LangString unknown ${LANG_HUNGARIAN} "ismeretlen"
LangString webview2AbortError ${LANG_HUNGARIAN} "A WebView2 telepítése nem sikerült! Az alkalmazás nem futtatható nélküle. Próbálja újraindítani a telepítőt."
LangString webview2DownloadError ${LANG_HUNGARIAN} "Hiba: a WebView2 letöltése nem sikerült - $0"
LangString webview2DownloadSuccess ${LANG_HUNGARIAN} "A WebView2 telepítőindítója sikeresen letöltve"
LangString webview2Downloading ${LANG_HUNGARIAN} "A WebView2 telepítőindítójának letöltése..."
LangString webview2InstallError ${LANG_HUNGARIAN} "Hiba: a WebView2 telepítése nem sikerült, kilépési kód: $1"
LangString webview2InstallSuccess ${LANG_HUNGARIAN} "A WebView2 sikeresen telepítve"
LangString deleteAppData ${LANG_HUNGARIAN} "Az alkalmazásadatok törlése"
