; The Indonesian translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_INDONESIAN} "Tambah/Instal ulang komponen"
LangString alreadyInstalled ${LANG_INDONESIAN} "Sudah Terinstal"
LangString alreadyInstalledLong ${LANG_INDONESIAN} "${PRODUCTNAME} ${VERSION} sudah terinstal. Pilih tindakan yang ingin Anda lakukan, lalu klik Berikutnya untuk melanjutkan."
LangString appRunning ${LANG_INDONESIAN} "{{product_name}} masih terbuka. Tutup aplikasinya, lalu coba lagi."
LangString appRunningOkKill ${LANG_INDONESIAN} "{{product_name}} sedang terbuka dan perlu ditutup terlebih dahulu.$\n$\nPanduan Anda sudah tersimpan. Jika Anda sedang merekam, apa yang sudah direkam tetap disimpan, dan Steps akan menawarkannya kembali saat dibuka berikutnya.$\n$\nPilih OK untuk menutup {{product_name}} sekarang, atau Batal untuk berhenti."
LangString chooseMaintenanceOption ${LANG_INDONESIAN} "Pilih opsi pemeliharaan yang akan dijalankan."
LangString choowHowToInstall ${LANG_INDONESIAN} "Pilih cara Anda ingin menginstal ${PRODUCTNAME}."
LangString createDesktop ${LANG_INDONESIAN} "Buat pintasan desktop"
LangString dontUninstall ${LANG_INDONESIAN} "Jangan hapus instalan"
LangString dontUninstallDowngrade ${LANG_INDONESIAN} "Jangan hapus instalan (Menurunkan versi tanpa menghapus instalan dinonaktifkan untuk penginstal ini)"
LangString failedToKillApp ${LANG_INDONESIAN} "{{product_name}} tidak dapat ditutup. Tutup sendiri, lalu coba lagi."
LangString installingWebview2 ${LANG_INDONESIAN} "Menginstal WebView2..."
LangString newerVersionInstalled ${LANG_INDONESIAN} "Versi ${PRODUCTNAME} yang lebih baru sudah terinstal! Menginstal versi yang lebih lama tidak disarankan. Jika Anda benar-benar ingin menginstal versi lama ini, sebaiknya hapus instalan versi saat ini terlebih dahulu. Pilih tindakan yang ingin Anda lakukan, lalu klik Berikutnya untuk melanjutkan."
LangString older ${LANG_INDONESIAN} "lebih lama"
LangString olderOrUnknownVersionInstalled ${LANG_INDONESIAN} "Versi ${PRODUCTNAME} yang $R4 terinstal di sistem Anda. Sebaiknya hapus instalan versi saat ini sebelum menginstal. Pilih tindakan yang ingin Anda lakukan, lalu klik Berikutnya untuk melanjutkan."
LangString silentDowngrades ${LANG_INDONESIAN} "Penurunan versi dinonaktifkan untuk penginstal ini, sehingga penginstal senyap tidak dapat dilanjutkan. Gunakan penginstal dengan antarmuka grafis.$\n"
LangString unableToUninstall ${LANG_INDONESIAN} "Tidak dapat menghapus instalan!"
LangString uninstallApp ${LANG_INDONESIAN} "Hapus instalan ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_INDONESIAN} "Hapus instalan sebelum menginstal"
LangString unknown ${LANG_INDONESIAN} "tidak dikenal"
LangString webview2AbortError ${LANG_INDONESIAN} "Gagal menginstal WebView2! Aplikasi tidak dapat berjalan tanpanya. Coba mulai ulang penginstal."
LangString webview2DownloadError ${LANG_INDONESIAN} "Kesalahan: Gagal mengunduh WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_INDONESIAN} "Bootstrapper WebView2 berhasil diunduh"
LangString webview2Downloading ${LANG_INDONESIAN} "Mengunduh bootstrapper WebView2..."
LangString webview2InstallError ${LANG_INDONESIAN} "Kesalahan: Penginstalan WebView2 gagal dengan kode keluar $1"
LangString webview2InstallSuccess ${LANG_INDONESIAN} "WebView2 berhasil diinstal"
LangString deleteAppData ${LANG_INDONESIAN} "Hapus data aplikasi"
