; The Irish translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_IRISH} "Cuir comhpháirteanna leis/Athshuiteáil"
LangString alreadyInstalled ${LANG_IRISH} "Suiteáilte cheana"
LangString alreadyInstalledLong ${LANG_IRISH} "Tá ${PRODUCTNAME} ${VERSION} suiteáilte cheana. Roghnaigh an oibríocht is mian leat a dhéanamh agus cliceáil Ar Aghaidh chun leanúint ar aghaidh."
LangString appRunning ${LANG_IRISH} "Tá {{product_name}} fós oscailte. Dún é, ansin bain triail eile as."
LangString appRunningOkKill ${LANG_IRISH} "Tá {{product_name}} oscailte agus ní mór é a dhúnadh ar dtús.$\n$\nTá do chuid treoracha sábháilte cheana. Má tá tú ag taifeadadh, coinnítear an méid atá taifeadta agat go dtí seo, agus tairgeann Steps ar ais duit é an chéad uair eile a osclaítear é.$\n$\nRoghnaigh OK chun {{product_name}} a dhúnadh anois, nó Cealaigh chun stopadh."
LangString chooseMaintenanceOption ${LANG_IRISH} "Roghnaigh an rogha chothabhála is mian leat a dhéanamh."
LangString choowHowToInstall ${LANG_IRISH} "Roghnaigh conas is mian leat ${PRODUCTNAME} a shuiteáil."
LangString createDesktop ${LANG_IRISH} "Cruthaigh aicearra deisce"
LangString dontUninstall ${LANG_IRISH} "Ná díshuiteáil"
LangString dontUninstallDowngrade ${LANG_IRISH} "Ná díshuiteáil (tá íosghrádú gan díshuiteáil díchumasaithe don suiteálaí seo)"
LangString failedToKillApp ${LANG_IRISH} "Níorbh fhéidir {{product_name}} a dhúnadh. Dún féin é, ansin bain triail eile as."
LangString installingWebview2 ${LANG_IRISH} "WebView2 á shuiteáil..."
LangString newerVersionInstalled ${LANG_IRISH} "Tá leagan níos nuaí de ${PRODUCTNAME} suiteáilte cheana! Ní mholtar leagan níos sine a shuiteáil. Más mian leat an leagan níos sine seo a shuiteáil i ndáiríre, is fearr an leagan reatha a dhíshuiteáil ar dtús. Roghnaigh an oibríocht is mian leat a dhéanamh agus cliceáil Ar Aghaidh chun leanúint ar aghaidh."
LangString older ${LANG_IRISH} "níos sine"
LangString olderOrUnknownVersionInstalled ${LANG_IRISH} "Tá leagan $R4 de ${PRODUCTNAME} suiteáilte ar do chóras. Moltar an leagan reatha a dhíshuiteáil sula suiteálann tú. Roghnaigh an oibríocht is mian leat a dhéanamh agus cliceáil Ar Aghaidh chun leanúint ar aghaidh."
LangString silentDowngrades ${LANG_IRISH} "Tá íosghráduithe díchumasaithe don suiteálaí seo, ní féidir leanúint ar aghaidh leis an suiteálaí ciúin; úsáid an suiteálaí grafach ina ionad sin.$\n"
LangString unableToUninstall ${LANG_IRISH} "Ní féidir díshuiteáil!"
LangString uninstallApp ${LANG_IRISH} "Díshuiteáil ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_IRISH} "Díshuiteáil sula suiteálfar"
LangString unknown ${LANG_IRISH} "anaithnid"
LangString webview2AbortError ${LANG_IRISH} "Theip ar WebView2 a shuiteáil! Ní féidir leis an aip rith gan é. Bain triail as an suiteálaí a atosú."
LangString webview2DownloadError ${LANG_IRISH} "Earráid: Theip ar íoslódáil WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_IRISH} "Íoslódáladh tosaitheoir WebView2"
LangString webview2Downloading ${LANG_IRISH} "Tosaitheoir WebView2 á íoslódáil..."
LangString webview2InstallError ${LANG_IRISH} "Earráid: Theip ar shuiteáil WebView2 le cód scoir $1"
LangString webview2InstallSuccess ${LANG_IRISH} "Suiteáladh WebView2"
LangString deleteAppData ${LANG_IRISH} "Scrios sonraí an fheidhmchláir"
