; The Italian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_ITALIAN} "Aggiungi o reinstalla componenti"
LangString alreadyInstalled ${LANG_ITALIAN} "Già installato"
LangString alreadyInstalledLong ${LANG_ITALIAN} "${PRODUCTNAME} ${VERSION} è già installato. Seleziona l'operazione che vuoi eseguire e fai clic su Avanti per continuare."
LangString appRunning ${LANG_ITALIAN} "{{product_name}} è ancora aperto. Chiudilo e riprova."
LangString appRunningOkKill ${LANG_ITALIAN} "{{product_name}} è aperto e deve prima essere chiuso.$\n$\nLe tue guide sono già salvate. Se stai registrando, ciò che hai registrato finora viene conservato e Steps te lo riproporrà alla prossima apertura.$\n$\nSeleziona OK per chiudere ora {{product_name}}, oppure Annulla per non continuare."
LangString chooseMaintenanceOption ${LANG_ITALIAN} "Scegli l'operazione di manutenzione da eseguire."
LangString choowHowToInstall ${LANG_ITALIAN} "Scegli come vuoi installare ${PRODUCTNAME}."
LangString createDesktop ${LANG_ITALIAN} "Crea un collegamento sul desktop"
LangString dontUninstall ${LANG_ITALIAN} "Non disinstallare"
LangString dontUninstallDowngrade ${LANG_ITALIAN} "Non disinstallare (questo programma di installazione non consente di tornare a una versione precedente senza disinstallare)"
LangString failedToKillApp ${LANG_ITALIAN} "Impossibile chiudere {{product_name}}. Chiudilo tu e riprova."
LangString installingWebview2 ${LANG_ITALIAN} "Installazione di WebView2..."
LangString newerVersionInstalled ${LANG_ITALIAN} "È già installata una versione più recente di ${PRODUCTNAME}. Non è consigliabile installare una versione precedente. Se vuoi davvero installare questa versione precedente, è meglio disinstallare prima la versione attuale. Seleziona l'operazione che vuoi eseguire e fai clic su Avanti per continuare."
LangString older ${LANG_ITALIAN} "precedente"
LangString olderOrUnknownVersionInstalled ${LANG_ITALIAN} "Nel sistema è installata una versione $R4 di ${PRODUCTNAME}. È consigliabile disinstallare la versione attuale prima di installare. Seleziona l'operazione che vuoi eseguire e fai clic su Avanti per continuare."
LangString silentDowngrades ${LANG_ITALIAN} "Questo programma di installazione non consente di tornare a una versione precedente, quindi l'installazione invisibile non può continuare. Usa invece il programma di installazione con interfaccia grafica.$\n"
LangString unableToUninstall ${LANG_ITALIAN} "Impossibile disinstallare."
LangString uninstallApp ${LANG_ITALIAN} "Disinstalla ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ITALIAN} "Disinstalla prima di installare"
LangString unknown ${LANG_ITALIAN} "sconosciuta"
LangString webview2AbortError ${LANG_ITALIAN} "Impossibile installare WebView2. L'app non può funzionare senza. Prova a riavviare il programma di installazione."
LangString webview2DownloadError ${LANG_ITALIAN} "Errore: download di WebView2 non riuscito - $0"
LangString webview2DownloadSuccess ${LANG_ITALIAN} "Programma di avvio di WebView2 scaricato correttamente"
LangString webview2Downloading ${LANG_ITALIAN} "Download del programma di avvio di WebView2..."
LangString webview2InstallError ${LANG_ITALIAN} "Errore: installazione di WebView2 non riuscita con codice di uscita $1"
LangString webview2InstallSuccess ${LANG_ITALIAN} "WebView2 installato correttamente"
LangString deleteAppData ${LANG_ITALIAN} "Elimina i dati dell'applicazione"
