; The Japanese translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same id and in the same order.
LangString addOrReinstall ${LANG_JAPANESE} "コンポーネントの追加/再インストール"
LangString alreadyInstalled ${LANG_JAPANESE} "インストール済み"
LangString alreadyInstalledLong ${LANG_JAPANESE} "${PRODUCTNAME} ${VERSION} は既にインストールされています。実行する操作を選択し、「次へ」をクリックして続行してください。"
LangString appRunning ${LANG_JAPANESE} "{{product_name}} はまだ開いています。閉じてから、もう一度お試しください。"
LangString appRunningOkKill ${LANG_JAPANESE} "{{product_name}} が開いているため、先に閉じる必要があります。$\n$\nガイドは既に保存されています。記録中の場合も、それまでに記録した内容は保持され、次回 Steps を開いたときに表示されます。$\n$\n{{product_name}} を今すぐ閉じるには「OK」を、中止するには「キャンセル」を選択してください。"
LangString chooseMaintenanceOption ${LANG_JAPANESE} "実行するメンテナンス オプションを選択してください。"
LangString choowHowToInstall ${LANG_JAPANESE} "${PRODUCTNAME} のインストール方法を選択してください。"
LangString createDesktop ${LANG_JAPANESE} "デスクトップ ショートカットを作成する"
LangString dontUninstall ${LANG_JAPANESE} "アンインストールしない"
LangString dontUninstallDowngrade ${LANG_JAPANESE} "アンインストールしない（このインストーラーでは、アンインストールせずにダウングレードすることはできません）"
LangString failedToKillApp ${LANG_JAPANESE} "{{product_name}} を閉じられませんでした。手動で閉じてから、もう一度お試しください。"
LangString installingWebview2 ${LANG_JAPANESE} "WebView2 をインストールしています..."
LangString newerVersionInstalled ${LANG_JAPANESE} "${PRODUCTNAME} の新しいバージョンが既にインストールされています。古いバージョンをインストールすることはお勧めしません。どうしてもこの古いバージョンをインストールする場合は、先に現在のバージョンをアンインストールしてください。実行する操作を選択し、「次へ」をクリックして続行してください。"
LangString older ${LANG_JAPANESE} "古い"
LangString olderOrUnknownVersionInstalled ${LANG_JAPANESE} "$R4バージョンの ${PRODUCTNAME} がシステムにインストールされています。インストールする前に、現在のバージョンをアンインストールすることをお勧めします。実行する操作を選択し、「次へ」をクリックして続行してください。"
LangString silentDowngrades ${LANG_JAPANESE} "このインストーラーではダウングレードが無効になっているため、サイレント インストールを続行できません。代わりに、グラフィカル インターフェイスのインストーラーを使用してください。$\n"
LangString unableToUninstall ${LANG_JAPANESE} "アンインストールできません。"
LangString uninstallApp ${LANG_JAPANESE} "${PRODUCTNAME} のアンインストール"
LangString uninstallBeforeInstalling ${LANG_JAPANESE} "インストールする前にアンインストールする"
LangString unknown ${LANG_JAPANESE} "不明な"
LangString webview2AbortError ${LANG_JAPANESE} "WebView2 をインストールできませんでした。アプリの実行には WebView2 が必要です。インストーラーを再起動してみてください。"
LangString webview2DownloadError ${LANG_JAPANESE} "エラー: WebView2 のダウンロードに失敗しました - $0"
LangString webview2DownloadSuccess ${LANG_JAPANESE} "WebView2 ブートストラッパーを正常にダウンロードしました"
LangString webview2Downloading ${LANG_JAPANESE} "WebView2 ブートストラッパーをダウンロードしています..."
LangString webview2InstallError ${LANG_JAPANESE} "エラー: WebView2 のインストールに失敗しました。終了コード: $1"
LangString webview2InstallSuccess ${LANG_JAPANESE} "WebView2 を正常にインストールしました"
LangString deleteAppData ${LANG_JAPANESE} "アプリケーション データを削除する"
