; The Korean translation of English.nsh, the setup .exe's own messages.
; Every string English.nsh has must be here, with the same id, in the same order.
LangString addOrReinstall ${LANG_KOREAN} "구성 요소 추가/다시 설치"
LangString alreadyInstalled ${LANG_KOREAN} "이미 설치됨"
LangString alreadyInstalledLong ${LANG_KOREAN} "${PRODUCTNAME} ${VERSION}이(가) 이미 설치되어 있습니다. 수행할 작업을 선택하고 다음을 클릭해 계속하세요."
LangString appRunning ${LANG_KOREAN} "{{product_name}}이(가) 아직 열려 있습니다. 닫은 다음 다시 시도하세요."
LangString appRunningOkKill ${LANG_KOREAN} "{{product_name}}이(가) 열려 있어 먼저 닫아야 합니다.$\n$\n가이드는 이미 저장되어 있습니다. 녹화 중이었다면 지금까지 녹화한 내용이 보관되며, 다음에 Steps를 열 때 다시 제공됩니다.$\n$\n지금 {{product_name}}을(를) 닫으려면 확인을, 중단하려면 취소를 선택하세요."
LangString chooseMaintenanceOption ${LANG_KOREAN} "수행할 유지 관리 옵션을 선택하세요."
LangString choowHowToInstall ${LANG_KOREAN} "${PRODUCTNAME} 설치 방법을 선택하세요."
LangString createDesktop ${LANG_KOREAN} "바탕 화면 바로 가기 만들기"
LangString dontUninstall ${LANG_KOREAN} "제거하지 않음"
LangString dontUninstallDowngrade ${LANG_KOREAN} "제거하지 않음(이 설치 프로그램에서는 제거하지 않고 이전 버전으로 바꿀 수 없습니다)"
LangString failedToKillApp ${LANG_KOREAN} "{{product_name}}을(를) 닫지 못했습니다. 직접 닫은 다음 다시 시도하세요."
LangString installingWebview2 ${LANG_KOREAN} "WebView2 설치 중..."
LangString newerVersionInstalled ${LANG_KOREAN} "${PRODUCTNAME}의 최신 버전이 이미 설치되어 있습니다! 이전 버전은 설치하지 않는 것이 좋습니다. 꼭 이 이전 버전을 설치하려면 먼저 현재 버전을 제거하는 것이 좋습니다. 수행할 작업을 선택하고 다음을 클릭해 계속하세요."
LangString older ${LANG_KOREAN} "이전"
LangString olderOrUnknownVersionInstalled ${LANG_KOREAN} "시스템에 ${PRODUCTNAME}의 $R4 버전이 설치되어 있습니다. 설치하기 전에 현재 버전을 제거하는 것이 좋습니다. 수행할 작업을 선택하고 다음을 클릭해 계속하세요."
LangString silentDowngrades ${LANG_KOREAN} "이 설치 프로그램에서는 이전 버전으로 바꿀 수 없으므로 자동 설치를 계속할 수 없습니다. 그래픽 인터페이스 설치 프로그램을 사용하세요.$\n"
LangString unableToUninstall ${LANG_KOREAN} "제거할 수 없습니다!"
LangString uninstallApp ${LANG_KOREAN} "${PRODUCTNAME} 제거"
LangString uninstallBeforeInstalling ${LANG_KOREAN} "설치하기 전에 제거"
LangString unknown ${LANG_KOREAN} "알 수 없는"
LangString webview2AbortError ${LANG_KOREAN} "WebView2를 설치하지 못했습니다! WebView2가 없으면 앱을 실행할 수 없습니다. 설치 프로그램을 다시 시작해 보세요."
LangString webview2DownloadError ${LANG_KOREAN} "오류: WebView2 다운로드 실패 - $0"
LangString webview2DownloadSuccess ${LANG_KOREAN} "WebView2 부트스트래퍼를 다운로드했습니다"
LangString webview2Downloading ${LANG_KOREAN} "WebView2 부트스트래퍼 다운로드 중..."
LangString webview2InstallError ${LANG_KOREAN} "오류: WebView2 설치 실패, 종료 코드 $1"
LangString webview2InstallSuccess ${LANG_KOREAN} "WebView2를 설치했습니다"
LangString deleteAppData ${LANG_KOREAN} "애플리케이션 데이터 삭제"
