; The Latvian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_LATVIAN} "Pievienot vai atkārtoti instalēt komponentus"
LangString alreadyInstalled ${LANG_LATVIAN} "Jau instalēts"
LangString alreadyInstalledLong ${LANG_LATVIAN} "${PRODUCTNAME} ${VERSION} jau ir instalēta. Atlasiet veicamo darbību un noklikšķiniet uz “Tālāk”, lai turpinātu."
LangString appRunning ${LANG_LATVIAN} "{{product_name}} joprojām ir atvērta. Aizveriet to un mēģiniet vēlreiz."
LangString appRunningOkKill ${LANG_LATVIAN} "{{product_name}} ir atvērta, un vispirms tā ir jāaizver.$\n$\nJūsu pamācības jau ir saglabātas. Ja pašlaik ierakstāt, līdz šim ierakstītais tiek saglabāts, un nākamreiz, kad Steps tiks atvērta, tā to piedāvās atjaunot.$\n$\nAtlasiet “Labi”, lai tūlīt aizvērtu {{product_name}}, vai “Atcelt”, lai apturētu."
LangString chooseMaintenanceOption ${LANG_LATVIAN} "Izvēlieties veicamo apkopes darbību."
LangString choowHowToInstall ${LANG_LATVIAN} "Izvēlieties, kā vēlaties instalēt ${PRODUCTNAME}."
LangString createDesktop ${LANG_LATVIAN} "Izveidot darbvirsmas saīsni"
LangString dontUninstall ${LANG_LATVIAN} "Neatinstalēt"
LangString dontUninstallDowngrade ${LANG_LATVIAN} "Neatinstalēt (šajā instalēšanas programmā vecākas versijas instalēšana bez atinstalēšanas ir atspējota)"
LangString failedToKillApp ${LANG_LATVIAN} "{{product_name}} nevarēja aizvērt. Aizveriet to paši un mēģiniet vēlreiz."
LangString installingWebview2 ${LANG_LATVIAN} "Notiek WebView2 instalēšana..."
LangString newerVersionInstalled ${LANG_LATVIAN} "Jau ir instalēta jaunāka ${PRODUCTNAME} versija! Vecākas versijas instalēšana nav ieteicama. Ja tiešām vēlaties instalēt šo vecāko versiju, vispirms ieteicams atinstalēt pašreizējo versiju. Atlasiet veicamo darbību un noklikšķiniet uz “Tālāk”, lai turpinātu."
LangString older ${LANG_LATVIAN} "vecāka"
LangString olderOrUnknownVersionInstalled ${LANG_LATVIAN} "Jūsu sistēmā ir instalēta $R4 ${PRODUCTNAME} versija. Pirms instalēšanas ieteicams atinstalēt pašreizējo versiju. Atlasiet veicamo darbību un noklikšķiniet uz “Tālāk”, lai turpinātu."
LangString silentDowngrades ${LANG_LATVIAN} "Šajā instalēšanas programmā vecākas versijas instalēšana ir atspējota, tāpēc kluso instalēšanu nevar turpināt. Lūdzu, izmantojiet grafisko instalēšanas programmu.$\n"
LangString unableToUninstall ${LANG_LATVIAN} "Nevar atinstalēt!"
LangString uninstallApp ${LANG_LATVIAN} "Atinstalēt ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_LATVIAN} "Atinstalēt pirms instalēšanas"
LangString unknown ${LANG_LATVIAN} "nezināma"
LangString webview2AbortError ${LANG_LATVIAN} "Neizdevās instalēt WebView2! Programma bez tā nevar darboties. Mēģiniet restartēt instalēšanas programmu."
LangString webview2DownloadError ${LANG_LATVIAN} "Kļūda: neizdevās lejupielādēt WebView2 — $0"
LangString webview2DownloadSuccess ${LANG_LATVIAN} "WebView2 palaidējprogramma veiksmīgi lejupielādēta"
LangString webview2Downloading ${LANG_LATVIAN} "Notiek WebView2 palaidējprogrammas lejupielāde..."
LangString webview2InstallError ${LANG_LATVIAN} "Kļūda: WebView2 instalēšana neizdevās, izejas kods $1"
LangString webview2InstallSuccess ${LANG_LATVIAN} "WebView2 veiksmīgi instalēts"
LangString deleteAppData ${LANG_LATVIAN} "Dzēst programmas datus"
