; The Lithuanian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_LITHUANIAN} "Pridėti arba iš naujo įdiegti komponentus"
LangString alreadyInstalled ${LANG_LITHUANIAN} "Jau įdiegta"
LangString alreadyInstalledLong ${LANG_LITHUANIAN} "${PRODUCTNAME} ${VERSION} jau įdiegta. Pasirinkite norimą veiksmą ir spustelėkite „Toliau“, kad tęstumėte."
LangString appRunning ${LANG_LITHUANIAN} "{{product_name}} vis dar atidaryta. Uždarykite ją ir bandykite dar kartą."
LangString appRunningOkKill ${LANG_LITHUANIAN} "{{product_name}} atidaryta, todėl pirmiausia ją reikia uždaryti.$\n$\nJūsų instrukcijos jau išsaugotos. Jei šiuo metu įrašote, tai, ką įrašėte iki šiol, išlaikoma, o kitą kartą atsidariusi Steps tai pasiūlys.$\n$\nPasirinkite „Gerai“, kad dabar uždarytumėte {{product_name}}, arba „Atšaukti“, kad sustabdytumėte."
LangString chooseMaintenanceOption ${LANG_LITHUANIAN} "Pasirinkite norimą atlikti priežiūros veiksmą."
LangString choowHowToInstall ${LANG_LITHUANIAN} "Pasirinkite, kaip norite įdiegti ${PRODUCTNAME}."
LangString createDesktop ${LANG_LITHUANIAN} "Sukurti darbalaukio nuorodą"
LangString dontUninstall ${LANG_LITHUANIAN} "Nešalinti"
LangString dontUninstallDowngrade ${LANG_LITHUANIAN} "Nešalinti (šioje diegimo programoje negalima įdiegti senesnės versijos, nepašalinus esamos)"
LangString failedToKillApp ${LANG_LITHUANIAN} "Nepavyko uždaryti {{product_name}}. Uždarykite ją patys ir bandykite dar kartą."
LangString installingWebview2 ${LANG_LITHUANIAN} "Diegiama WebView2..."
LangString newerVersionInstalled ${LANG_LITHUANIAN} "Jau įdiegta naujesnė ${PRODUCTNAME} versija! Diegti senesnę versiją nerekomenduojama. Jei tikrai norite įdiegti šią senesnę versiją, pirmiausia geriau pašalinkite dabartinę. Pasirinkite norimą veiksmą ir spustelėkite „Toliau“, kad tęstumėte."
LangString older ${LANG_LITHUANIAN} "senesnė"
LangString olderOrUnknownVersionInstalled ${LANG_LITHUANIAN} "Jūsų sistemoje įdiegta $R4 ${PRODUCTNAME} versija. Prieš diegiant rekomenduojama pašalinti dabartinę versiją. Pasirinkite norimą veiksmą ir spustelėkite „Toliau“, kad tęstumėte."
LangString silentDowngrades ${LANG_LITHUANIAN} "Šioje diegimo programoje negalima įdiegti senesnės versijos, todėl tyliojo diegimo tęsti negalima. Naudokite grafinę diegimo programą.$\n"
LangString unableToUninstall ${LANG_LITHUANIAN} "Nepavyko pašalinti!"
LangString uninstallApp ${LANG_LITHUANIAN} "Pašalinti ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_LITHUANIAN} "Pašalinti prieš diegiant"
LangString unknown ${LANG_LITHUANIAN} "nežinoma"
LangString webview2AbortError ${LANG_LITHUANIAN} "Nepavyko įdiegti WebView2! Be jo programa negali veikti. Pabandykite iš naujo paleisti diegimo programą."
LangString webview2DownloadError ${LANG_LITHUANIAN} "Klaida: nepavyko atsisiųsti WebView2 – $0"
LangString webview2DownloadSuccess ${LANG_LITHUANIAN} "WebView2 paleidyklė sėkmingai atsisiųsta"
LangString webview2Downloading ${LANG_LITHUANIAN} "Atsisiunčiama WebView2 paleidyklė..."
LangString webview2InstallError ${LANG_LITHUANIAN} "Klaida: nepavyko įdiegti WebView2, išėjimo kodas $1"
LangString webview2InstallSuccess ${LANG_LITHUANIAN} "WebView2 sėkmingai įdiegtas"
LangString deleteAppData ${LANG_LITHUANIAN} "Naikinti programos duomenis"
