; The Norwegian (Bokmål) translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_NORWEGIAN} "Legg til / installer komponenter på nytt"
LangString alreadyInstalled ${LANG_NORWEGIAN} "Allerede installert"
LangString alreadyInstalledLong ${LANG_NORWEGIAN} "${PRODUCTNAME} ${VERSION} er allerede installert. Velg hva du vil gjøre, og klikk på Neste for å fortsette."
LangString appRunning ${LANG_NORWEGIAN} "{{product_name}} er fortsatt åpent. Lukk det, og prøv deretter på nytt."
LangString appRunningOkKill ${LANG_NORWEGIAN} "{{product_name}} er åpent og må lukkes først.$\n$\nVeiledningene dine er allerede lagret. Hvis du tar opp, beholdes det du har tatt opp så langt, og Steps tilbyr det til deg neste gang det åpnes.$\n$\nVelg OK for å lukke {{product_name}} nå, eller Avbryt for å stoppe."
LangString chooseMaintenanceOption ${LANG_NORWEGIAN} "Velg vedlikeholdsalternativet du vil utføre."
LangString choowHowToInstall ${LANG_NORWEGIAN} "Velg hvordan du vil installere ${PRODUCTNAME}."
LangString createDesktop ${LANG_NORWEGIAN} "Opprett snarvei på skrivebordet"
LangString dontUninstall ${LANG_NORWEGIAN} "Ikke avinstaller"
LangString dontUninstallDowngrade ${LANG_NORWEGIAN} "Ikke avinstaller (nedgradering uten avinstallering er deaktivert for dette installasjonsprogrammet)"
LangString failedToKillApp ${LANG_NORWEGIAN} "{{product_name}} kunne ikke lukkes. Lukk det selv, og prøv deretter på nytt."
LangString installingWebview2 ${LANG_NORWEGIAN} "Installerer WebView2..."
LangString newerVersionInstalled ${LANG_NORWEGIAN} "En nyere versjon av ${PRODUCTNAME} er allerede installert! Det anbefales ikke å installere en eldre versjon. Hvis du virkelig vil installere denne eldre versjonen, er det best å avinstallere den gjeldende versjonen først. Velg hva du vil gjøre, og klikk på Neste for å fortsette."
LangString older ${LANG_NORWEGIAN} "eldre"
LangString olderOrUnknownVersionInstalled ${LANG_NORWEGIAN} "En $R4 versjon av ${PRODUCTNAME} er installert på systemet ditt. Det anbefales at du avinstallerer den gjeldende versjonen før du installerer. Velg hva du vil gjøre, og klikk på Neste for å fortsette."
LangString silentDowngrades ${LANG_NORWEGIAN} "Nedgraderinger er deaktivert for dette installasjonsprogrammet, så den stille installasjonen kan ikke fortsette. Bruk det grafiske installasjonsprogrammet i stedet.$\n"
LangString unableToUninstall ${LANG_NORWEGIAN} "Kan ikke avinstallere!"
LangString uninstallApp ${LANG_NORWEGIAN} "Avinstaller ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_NORWEGIAN} "Avinstaller før installering"
LangString unknown ${LANG_NORWEGIAN} "ukjent"
LangString webview2AbortError ${LANG_NORWEGIAN} "Kunne ikke installere WebView2! Appen kan ikke kjøre uten. Prøv å starte installasjonsprogrammet på nytt."
LangString webview2DownloadError ${LANG_NORWEGIAN} "Feil: Nedlasting av WebView2 mislyktes – $0"
LangString webview2DownloadSuccess ${LANG_NORWEGIAN} "Oppstartsprogrammet for WebView2 er lastet ned"
LangString webview2Downloading ${LANG_NORWEGIAN} "Laster ned oppstartsprogrammet for WebView2..."
LangString webview2InstallError ${LANG_NORWEGIAN} "Feil: Installasjonen av WebView2 mislyktes med avslutningskode $1"
LangString webview2InstallSuccess ${LANG_NORWEGIAN} "WebView2 er installert"
LangString deleteAppData ${LANG_NORWEGIAN} "Slett appdataene"
