; The Polish translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_POLISH} "Dodaj lub zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "Już zainstalowano"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowany. Wybierz operację, którą chcesz wykonać, i kliknij przycisk Dalej, aby kontynuować."
LangString appRunning ${LANG_POLISH} "Aplikacja {{product_name}} jest nadal otwarta. Zamknij ją, a następnie spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "Aplikacja {{product_name}} jest otwarta i trzeba ją najpierw zamknąć.$\n$\nTwoje instrukcje są już zapisane. Jeśli trwa nagrywanie, to, co zostało dotąd nagrane, zostanie zachowane, a Steps zaproponuje to przy następnym uruchomieniu.$\n$\nWybierz OK, aby teraz zamknąć aplikację {{product_name}}, lub Anuluj, aby przerwać."
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz operację konserwacji do wykonania."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz, jak chcesz zainstalować ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (instalacja starszej wersji bez odinstalowania jest wyłączona w tym instalatorze)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zamknąć aplikacji {{product_name}}. Zamknij ją samodzielnie, a następnie spróbuj ponownie."
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2..."
LangString newerVersionInstalled ${LANG_POLISH} "Nowsza wersja ${PRODUCTNAME} jest już zainstalowana! Instalowanie starszej wersji nie jest zalecane. Jeśli naprawdę chcesz zainstalować tę starszą wersję, lepiej najpierw odinstalować bieżącą wersję. Wybierz operację, którą chcesz wykonać, i kliknij przycisk Dalej, aby kontynuować."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "W systemie jest zainstalowana $R4 wersja ${PRODUCTNAME}. Przed instalacją zaleca się odinstalowanie bieżącej wersji. Wybierz operację, którą chcesz wykonać, i kliknij przycisk Dalej, aby kontynuować."
LangString silentDowngrades ${LANG_POLISH} "Instalowanie starszych wersji jest wyłączone w tym instalatorze, więc nie można kontynuować instalacji w trybie cichym. Użyj instalatora z interfejsem graficznym.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie można odinstalować!"
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2! Aplikacja nie może działać bez tego składnika. Spróbuj ponownie uruchomić instalator."
LangString webview2DownloadError ${LANG_POLISH} "Błąd: nie udało się pobrać WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pomyślnie pobrano program inicjujący WebView2"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie programu inicjującego WebView2..."
LangString webview2InstallError ${LANG_POLISH} "Błąd: instalacja WebView2 nie powiodła się, kod zakończenia $1"
LangString webview2InstallSuccess ${LANG_POLISH} "Pomyślnie zainstalowano WebView2"
LangString deleteAppData ${LANG_POLISH} "Usuń dane aplikacji"
