; The Portuguese (Portugal) translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_PORTUGUESE} "Adicionar/reinstalar componentes"
LangString alreadyInstalled ${LANG_PORTUGUESE} "Já instalado"
LangString alreadyInstalledLong ${LANG_PORTUGUESE} "O ${PRODUCTNAME} ${VERSION} já está instalado. Selecione a operação que pretende efetuar e clique em Seguinte para continuar."
LangString appRunning ${LANG_PORTUGUESE} "O {{product_name}} ainda está aberto. Feche-o e tente novamente."
LangString appRunningOkKill ${LANG_PORTUGUESE} "O {{product_name}} está aberto e tem de ser fechado primeiro.$\n$\nOs seus guias já estão guardados. Se estiver a gravar, o que foi gravado até agora é mantido, e o Steps volta a disponibilizá-lo da próxima vez que for aberto.$\n$\nSelecione OK para fechar o {{product_name}} agora ou Cancelar para parar."
LangString chooseMaintenanceOption ${LANG_PORTUGUESE} "Escolha a opção de manutenção a efetuar."
LangString choowHowToInstall ${LANG_PORTUGUESE} "Escolha como pretende instalar o ${PRODUCTNAME}."
LangString createDesktop ${LANG_PORTUGUESE} "Criar atalho no ambiente de trabalho"
LangString dontUninstall ${LANG_PORTUGUESE} "Não desinstalar"
LangString dontUninstallDowngrade ${LANG_PORTUGUESE} "Não desinstalar (este instalador não permite instalar uma versão anterior sem desinstalar)"
LangString failedToKillApp ${LANG_PORTUGUESE} "Não foi possível fechar o {{product_name}}. Feche-o manualmente e tente novamente."
LangString installingWebview2 ${LANG_PORTUGUESE} "A instalar o WebView2..."
LangString newerVersionInstalled ${LANG_PORTUGUESE} "Já está instalada uma versão mais recente do ${PRODUCTNAME}! Não é recomendado instalar uma versão mais antiga. Se pretender mesmo instalar esta versão mais antiga, é preferível desinstalar primeiro a versão atual. Selecione a operação que pretende efetuar e clique em Seguinte para continuar."
LangString older ${LANG_PORTUGUESE} "mais antiga"
LangString olderOrUnknownVersionInstalled ${LANG_PORTUGUESE} "Está instalada no seu sistema uma versão $R4 do ${PRODUCTNAME}. É recomendado desinstalar a versão atual antes de instalar. Selecione a operação que pretende efetuar e clique em Seguinte para continuar."
LangString silentDowngrades ${LANG_PORTUGUESE} "Este instalador não permite instalar versões anteriores, por isso não é possível continuar com a instalação silenciosa. Utilize o instalador com interface gráfica.$\n"
LangString unableToUninstall ${LANG_PORTUGUESE} "Não foi possível desinstalar!"
LangString uninstallApp ${LANG_PORTUGUESE} "Desinstalar o ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_PORTUGUESE} "Desinstalar antes de instalar"
LangString unknown ${LANG_PORTUGUESE} "desconhecida"
LangString webview2AbortError ${LANG_PORTUGUESE} "Falha ao instalar o WebView2! A aplicação não funciona sem ele. Experimente reiniciar o instalador."
LangString webview2DownloadError ${LANG_PORTUGUESE} "Erro: falha ao transferir o WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_PORTUGUESE} "Instalador do WebView2 transferido com êxito"
LangString webview2Downloading ${LANG_PORTUGUESE} "A transferir o instalador do WebView2..."
LangString webview2InstallError ${LANG_PORTUGUESE} "Erro: a instalação do WebView2 falhou com o código de saída $1"
LangString webview2InstallSuccess ${LANG_PORTUGUESE} "WebView2 instalado com êxito"
LangString deleteAppData ${LANG_PORTUGUESE} "Eliminar os dados da aplicação"
