; The Portuguese (Brazil) translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_PORTUGUESEBR} "Adicionar/reinstalar componentes"
LangString alreadyInstalled ${LANG_PORTUGUESEBR} "Já instalado"
LangString alreadyInstalledLong ${LANG_PORTUGUESEBR} "O ${PRODUCTNAME} ${VERSION} já está instalado. Selecione a operação que deseja realizar e clique em Próximo para continuar."
LangString appRunning ${LANG_PORTUGUESEBR} "O {{product_name}} ainda está aberto. Feche-o e tente novamente."
LangString appRunningOkKill ${LANG_PORTUGUESEBR} "O {{product_name}} está aberto e precisa ser fechado primeiro.$\n$\nSeus guias já estão salvos. Se você estiver gravando, o que foi gravado até agora é mantido, e o Steps o oferece de volta na próxima vez que for aberto.$\n$\nSelecione OK para fechar o {{product_name}} agora ou Cancelar para parar."
LangString chooseMaintenanceOption ${LANG_PORTUGUESEBR} "Escolha a opção de manutenção a realizar."
LangString choowHowToInstall ${LANG_PORTUGUESEBR} "Escolha como deseja instalar o ${PRODUCTNAME}."
LangString createDesktop ${LANG_PORTUGUESEBR} "Criar atalho na área de trabalho"
LangString dontUninstall ${LANG_PORTUGUESEBR} "Não desinstalar"
LangString dontUninstallDowngrade ${LANG_PORTUGUESEBR} "Não desinstalar (este instalador não permite instalar uma versão anterior sem desinstalar)"
LangString failedToKillApp ${LANG_PORTUGUESEBR} "Não foi possível fechar o {{product_name}}. Feche-o você mesmo e tente novamente."
LangString installingWebview2 ${LANG_PORTUGUESEBR} "Instalando o WebView2..."
LangString newerVersionInstalled ${LANG_PORTUGUESEBR} "Uma versão mais recente do ${PRODUCTNAME} já está instalada! Não é recomendável instalar uma versão mais antiga. Se você realmente quiser instalar esta versão mais antiga, é melhor desinstalar a versão atual primeiro. Selecione a operação que deseja realizar e clique em Próximo para continuar."
LangString older ${LANG_PORTUGUESEBR} "mais antiga"
LangString olderOrUnknownVersionInstalled ${LANG_PORTUGUESEBR} "Uma versão $R4 do ${PRODUCTNAME} está instalada no seu sistema. É recomendável desinstalar a versão atual antes de instalar. Selecione a operação que deseja realizar e clique em Próximo para continuar."
LangString silentDowngrades ${LANG_PORTUGUESEBR} "Este instalador não permite instalar versões anteriores, então não é possível continuar com a instalação silenciosa. Use o instalador com interface gráfica.$\n"
LangString unableToUninstall ${LANG_PORTUGUESEBR} "Não foi possível desinstalar!"
LangString uninstallApp ${LANG_PORTUGUESEBR} "Desinstalar o ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_PORTUGUESEBR} "Desinstalar antes de instalar"
LangString unknown ${LANG_PORTUGUESEBR} "desconhecida"
LangString webview2AbortError ${LANG_PORTUGUESEBR} "Falha ao instalar o WebView2! O aplicativo não funciona sem ele. Tente reiniciar o instalador."
LangString webview2DownloadError ${LANG_PORTUGUESEBR} "Erro: falha ao baixar o WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_PORTUGUESEBR} "Instalador do WebView2 baixado com êxito"
LangString webview2Downloading ${LANG_PORTUGUESEBR} "Baixando o instalador do WebView2..."
LangString webview2InstallError ${LANG_PORTUGUESEBR} "Erro: a instalação do WebView2 falhou com o código de saída $1"
LangString webview2InstallSuccess ${LANG_PORTUGUESEBR} "WebView2 instalado com êxito"
LangString deleteAppData ${LANG_PORTUGUESEBR} "Excluir os dados do aplicativo"
