; The Romanian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id and in the same order.
LangString addOrReinstall ${LANG_ROMANIAN} "Adăugare/reinstalare componente"
LangString alreadyInstalled ${LANG_ROMANIAN} "Deja instalat"
LangString alreadyInstalledLong ${LANG_ROMANIAN} "${PRODUCTNAME} ${VERSION} este deja instalat. Selectați operațiunea dorită și faceți clic pe Înainte pentru a continua."
LangString appRunning ${LANG_ROMANIAN} "{{product_name}} este încă deschis. Închideți-l, apoi încercați din nou."
LangString appRunningOkKill ${LANG_ROMANIAN} "{{product_name}} este deschis și trebuie închis mai întâi.$\n$\nGhidurile dvs. sunt deja salvate. Dacă înregistrați, ce ați înregistrat până acum se păstrează, iar Steps vi-l oferă data viitoare când se deschide.$\n$\nSelectați OK pentru a închide acum {{product_name}} sau Anulare pentru a opri."
LangString chooseMaintenanceOption ${LANG_ROMANIAN} "Alegeți operațiunea de întreținere pe care doriți să o efectuați."
LangString choowHowToInstall ${LANG_ROMANIAN} "Alegeți cum doriți să instalați ${PRODUCTNAME}."
LangString createDesktop ${LANG_ROMANIAN} "Creare comandă rapidă pe desktop"
LangString dontUninstall ${LANG_ROMANIAN} "Nu se dezinstalează"
LangString dontUninstallDowngrade ${LANG_ROMANIAN} "Nu se dezinstalează (trecerea la o versiune mai veche fără dezinstalare este dezactivată pentru acest program de instalare)"
LangString failedToKillApp ${LANG_ROMANIAN} "{{product_name}} nu a putut fi închis. Închideți-l manual, apoi încercați din nou."
LangString installingWebview2 ${LANG_ROMANIAN} "Se instalează WebView2..."
LangString newerVersionInstalled ${LANG_ROMANIAN} "O versiune mai nouă de ${PRODUCTNAME} este deja instalată! Nu este recomandat să instalați o versiune mai veche. Dacă doriți totuși să instalați această versiune mai veche, este mai bine să dezinstalați mai întâi versiunea curentă. Selectați operațiunea dorită și faceți clic pe Înainte pentru a continua."
LangString older ${LANG_ROMANIAN} "mai veche"
LangString olderOrUnknownVersionInstalled ${LANG_ROMANIAN} "O versiune $R4 de ${PRODUCTNAME} este instalată pe sistem. Este recomandat să dezinstalați versiunea curentă înainte de instalare. Selectați operațiunea dorită și faceți clic pe Înainte pentru a continua."
LangString silentDowngrades ${LANG_ROMANIAN} "Trecerea la o versiune mai veche este dezactivată pentru acest program de instalare, deci instalarea silențioasă nu poate continua. Folosiți în schimb programul de instalare cu interfață grafică.$\n"
LangString unableToUninstall ${LANG_ROMANIAN} "Dezinstalarea nu a reușit!"
LangString uninstallApp ${LANG_ROMANIAN} "Dezinstalare ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ROMANIAN} "Dezinstalare înainte de instalare"
LangString unknown ${LANG_ROMANIAN} "necunoscută"
LangString webview2AbortError ${LANG_ROMANIAN} "Instalarea WebView2 nu a reușit! Aplicația nu poate rula fără el. Încercați să reporniți programul de instalare."
LangString webview2DownloadError ${LANG_ROMANIAN} "Eroare: descărcarea WebView2 nu a reușit - $0"
LangString webview2DownloadSuccess ${LANG_ROMANIAN} "Programul de instalare WebView2 a fost descărcat"
LangString webview2Downloading ${LANG_ROMANIAN} "Se descarcă programul de instalare WebView2..."
LangString webview2InstallError ${LANG_ROMANIAN} "Eroare: instalarea WebView2 nu a reușit, cu codul de ieșire $1"
LangString webview2InstallSuccess ${LANG_ROMANIAN} "WebView2 a fost instalat"
LangString deleteAppData ${LANG_ROMANIAN} "Ștergeți datele aplicației"
