; The Russian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_RUSSIAN} "Добавить или переустановить компоненты"
LangString alreadyInstalled ${LANG_RUSSIAN} "Уже установлено"
LangString alreadyInstalledLong ${LANG_RUSSIAN} "${PRODUCTNAME} ${VERSION} уже установлен. Выберите нужное действие и нажмите «Далее», чтобы продолжить."
LangString appRunning ${LANG_RUSSIAN} "{{product_name}} все еще открыт. Закройте программу и повторите попытку."
LangString appRunningOkKill ${LANG_RUSSIAN} "Программа {{product_name}} открыта, и сначала ее нужно закрыть.$\n$\nВаши инструкции уже сохранены. Если идет запись, все, что уже записано, сохранится, и Steps предложит вернуться к этому при следующем открытии.$\n$\nНажмите «ОК», чтобы закрыть {{product_name}} сейчас, или «Отмена», чтобы прервать."
LangString chooseMaintenanceOption ${LANG_RUSSIAN} "Выберите действие по обслуживанию."
LangString choowHowToInstall ${LANG_RUSSIAN} "Выберите способ установки ${PRODUCTNAME}."
LangString createDesktop ${LANG_RUSSIAN} "Создать ярлык на рабочем столе"
LangString dontUninstall ${LANG_RUSSIAN} "Не удалять"
LangString dontUninstallDowngrade ${LANG_RUSSIAN} "Не удалять (установка более старой версии без удаления отключена для этого установщика)"
LangString failedToKillApp ${LANG_RUSSIAN} "Не удалось закрыть {{product_name}}. Закройте программу вручную и повторите попытку."
LangString installingWebview2 ${LANG_RUSSIAN} "Установка WebView2..."
LangString newerVersionInstalled ${LANG_RUSSIAN} "Уже установлена более новая версия ${PRODUCTNAME}! Устанавливать более старую версию не рекомендуется. Если вы действительно хотите установить эту более старую версию, лучше сначала удалить текущую. Выберите нужное действие и нажмите «Далее», чтобы продолжить."
LangString older ${LANG_RUSSIAN} "более старая"
LangString olderOrUnknownVersionInstalled ${LANG_RUSSIAN} "В системе установлена $R4 версия ${PRODUCTNAME}. Перед установкой рекомендуется удалить текущую версию. Выберите нужное действие и нажмите «Далее», чтобы продолжить."
LangString silentDowngrades ${LANG_RUSSIAN} "Установка более старой версии отключена для этого установщика, поэтому продолжить тихую установку нельзя. Используйте графический установщик.$\n"
LangString unableToUninstall ${LANG_RUSSIAN} "Не удалось удалить!"
LangString uninstallApp ${LANG_RUSSIAN} "Удалить ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_RUSSIAN} "Удалить перед установкой"
LangString unknown ${LANG_RUSSIAN} "неизвестная"
LangString webview2AbortError ${LANG_RUSSIAN} "Не удалось установить WebView2! Без него приложение не может работать. Попробуйте перезапустить установщик."
LangString webview2DownloadError ${LANG_RUSSIAN} "Ошибка: не удалось скачать WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_RUSSIAN} "Установщик WebView2 успешно скачан"
LangString webview2Downloading ${LANG_RUSSIAN} "Скачивание установщика WebView2..."
LangString webview2InstallError ${LANG_RUSSIAN} "Ошибка: не удалось установить WebView2, код выхода $1"
LangString webview2InstallSuccess ${LANG_RUSSIAN} "WebView2 успешно установлен"
LangString deleteAppData ${LANG_RUSSIAN} "Удалить данные приложения"
