; The Serbian (Cyrillic) translation of English.nsh, the setup .exe's own messages.
; Every string English.nsh has must be here too, with the same LangString ids.
LangString addOrReinstall ${LANG_SERBIAN} "Додај или поново инсталирај компоненте"
LangString alreadyInstalled ${LANG_SERBIAN} "Већ инсталирано"
LangString alreadyInstalledLong ${LANG_SERBIAN} "${PRODUCTNAME} ${VERSION} је већ инсталиран. Изаберите радњу коју желите да извршите и кликните на „Даље“ да бисте наставили."
LangString appRunning ${LANG_SERBIAN} "{{product_name}} је још отворен. Затворите га, па покушајте поново."
LangString appRunningOkKill ${LANG_SERBIAN} "{{product_name}} је отворен и прво мора да се затвори.$\n$\nВаши водичи су већ сачувани. Ако снимате, оно што сте до сада снимили се задржава, а Steps вам то нуди следећи пут када се отвори.$\n$\nИзаберите „У реду“ да бисте сада затворили {{product_name}} или „Откажи“ да бисте прекинули."
LangString chooseMaintenanceOption ${LANG_SERBIAN} "Изаберите радњу одржавања коју желите да извршите."
LangString choowHowToInstall ${LANG_SERBIAN} "Изаберите како желите да инсталирате ${PRODUCTNAME}."
LangString createDesktop ${LANG_SERBIAN} "Направи пречицу на радној површини"
LangString dontUninstall ${LANG_SERBIAN} "Немој да деинсталираш"
LangString dontUninstallDowngrade ${LANG_SERBIAN} "Немој да деинсталираш (инсталирање старије верзије без деинсталирања онемогућено је за овај инсталациони програм)"
LangString failedToKillApp ${LANG_SERBIAN} "{{product_name}} није могао да се затвори. Затворите га сами, па покушајте поново."
LangString installingWebview2 ${LANG_SERBIAN} "Инсталирање компоненте WebView2..."
LangString newerVersionInstalled ${LANG_SERBIAN} "Новија верзија програма ${PRODUCTNAME} је већ инсталирана! Не препоручује се инсталирање старије верзије. Ако заиста желите да инсталирате ову старију верзију, боље је да прво деинсталирате тренутну. Изаберите радњу коју желите да извршите и кликните на „Даље“ да бисте наставили."
LangString older ${LANG_SERBIAN} "старија"
LangString olderOrUnknownVersionInstalled ${LANG_SERBIAN} "На систему је инсталирана $R4 верзија програма ${PRODUCTNAME}. Препоручује се да пре инсталирања деинсталирате тренутну верзију. Изаберите радњу коју желите да извршите и кликните на „Даље“ да бисте наставили."
LangString silentDowngrades ${LANG_SERBIAN} "Инсталирање старије верзије онемогућено је за овај инсталациони програм, па тиха инсталација не може да се настави. Уместо тога користите графички инсталациони програм.$\n"
LangString unableToUninstall ${LANG_SERBIAN} "Деинсталирање није успело!"
LangString uninstallApp ${LANG_SERBIAN} "Деинсталирај ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SERBIAN} "Деинсталирај пре инсталирања"
LangString unknown ${LANG_SERBIAN} "непозната"
LangString webview2AbortError ${LANG_SERBIAN} "Инсталирање компоненте WebView2 није успело! Апликација не може да ради без ње. Покушајте поново да покренете инсталациони програм."
LangString webview2DownloadError ${LANG_SERBIAN} "Грешка: преузимање компоненте WebView2 није успело – $0"
LangString webview2DownloadSuccess ${LANG_SERBIAN} "Програм за покретање инсталације WebView2 је успешно преузет"
LangString webview2Downloading ${LANG_SERBIAN} "Преузимање програма за покретање инсталације WebView2..."
LangString webview2InstallError ${LANG_SERBIAN} "Грешка: инсталирање компоненте WebView2 није успело, излазни кôд $1"
LangString webview2InstallSuccess ${LANG_SERBIAN} "WebView2 је успешно инсталиран"
LangString deleteAppData ${LANG_SERBIAN} "Избриши податке апликације"
