; The Serbian (Latin) translation of English.nsh, the setup .exe's own messages.
; Every string English.nsh has must be here too, with the same LangString ids.
LangString addOrReinstall ${LANG_SERBIANLATIN} "Dodaj ili ponovo instaliraj komponente"
LangString alreadyInstalled ${LANG_SERBIANLATIN} "Već instalirano"
LangString alreadyInstalledLong ${LANG_SERBIANLATIN} "${PRODUCTNAME} ${VERSION} je već instaliran. Izaberite radnju koju želite da izvršite i kliknite na „Dalje“ da biste nastavili."
LangString appRunning ${LANG_SERBIANLATIN} "{{product_name}} je još otvoren. Zatvorite ga, pa pokušajte ponovo."
LangString appRunningOkKill ${LANG_SERBIANLATIN} "{{product_name}} je otvoren i prvo mora da se zatvori.$\n$\nVaši vodiči su već sačuvani. Ako snimate, ono što ste do sada snimili se zadržava, a Steps vam to nudi sledeći put kada se otvori.$\n$\nIzaberite „U redu“ da biste sada zatvorili {{product_name}} ili „Otkaži“ da biste prekinuli."
LangString chooseMaintenanceOption ${LANG_SERBIANLATIN} "Izaberite radnju održavanja koju želite da izvršite."
LangString choowHowToInstall ${LANG_SERBIANLATIN} "Izaberite kako želite da instalirate ${PRODUCTNAME}."
LangString createDesktop ${LANG_SERBIANLATIN} "Napravi prečicu na radnoj površini"
LangString dontUninstall ${LANG_SERBIANLATIN} "Nemoj da deinstaliraš"
LangString dontUninstallDowngrade ${LANG_SERBIANLATIN} "Nemoj da deinstaliraš (instaliranje starije verzije bez deinstaliranja onemogućeno je za ovaj instalacioni program)"
LangString failedToKillApp ${LANG_SERBIANLATIN} "{{product_name}} nije mogao da se zatvori. Zatvorite ga sami, pa pokušajte ponovo."
LangString installingWebview2 ${LANG_SERBIANLATIN} "Instaliranje komponente WebView2..."
LangString newerVersionInstalled ${LANG_SERBIANLATIN} "Novija verzija programa ${PRODUCTNAME} je već instalirana! Ne preporučuje se instaliranje starije verzije. Ako zaista želite da instalirate ovu stariju verziju, bolje je da prvo deinstalirate trenutnu. Izaberite radnju koju želite da izvršite i kliknite na „Dalje“ da biste nastavili."
LangString older ${LANG_SERBIANLATIN} "starija"
LangString olderOrUnknownVersionInstalled ${LANG_SERBIANLATIN} "Na sistemu je instalirana $R4 verzija programa ${PRODUCTNAME}. Preporučuje se da pre instaliranja deinstalirate trenutnu verziju. Izaberite radnju koju želite da izvršite i kliknite na „Dalje“ da biste nastavili."
LangString silentDowngrades ${LANG_SERBIANLATIN} "Instaliranje starije verzije onemogućeno je za ovaj instalacioni program, pa tiha instalacija ne može da se nastavi. Umesto toga koristite grafički instalacioni program.$\n"
LangString unableToUninstall ${LANG_SERBIANLATIN} "Deinstaliranje nije uspelo!"
LangString uninstallApp ${LANG_SERBIANLATIN} "Deinstaliraj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SERBIANLATIN} "Deinstaliraj pre instaliranja"
LangString unknown ${LANG_SERBIANLATIN} "nepoznata"
LangString webview2AbortError ${LANG_SERBIANLATIN} "Instaliranje komponente WebView2 nije uspelo! Aplikacija ne može da radi bez nje. Pokušajte ponovo da pokrenete instalacioni program."
LangString webview2DownloadError ${LANG_SERBIANLATIN} "Greška: preuzimanje komponente WebView2 nije uspelo – $0"
LangString webview2DownloadSuccess ${LANG_SERBIANLATIN} "Program za pokretanje instalacije WebView2 je uspešno preuzet"
LangString webview2Downloading ${LANG_SERBIANLATIN} "Preuzimanje programa za pokretanje instalacije WebView2..."
LangString webview2InstallError ${LANG_SERBIANLATIN} "Greška: instaliranje komponente WebView2 nije uspelo, izlazni kôd $1"
LangString webview2InstallSuccess ${LANG_SERBIANLATIN} "WebView2 je uspešno instaliran"
LangString deleteAppData ${LANG_SERBIANLATIN} "Izbriši podatke aplikacije"
