; The Simplified Chinese translation of English.nsh, the setup .exe's own messages.
; Every string English.nsh has must be here, with the same id, in the same order.
LangString addOrReinstall ${LANG_SIMPCHINESE} "添加/重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已安装。请选择要执行的操作，然后单击“下一步”继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 仍处于打开状态。请将其关闭，然后重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 已打开，需要先将其关闭。$\n$\n你的指南已经保存。如果你正在录制，目前已录制的内容会保留，下次打开 Steps 时会再次提供给你。$\n$\n选择“确定”立即关闭 {{product_name}}，或选择“取消”停止。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的维护选项。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择 ${PRODUCTNAME} 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（此安装程序不允许在不卸载的情况下降级）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法关闭 {{product_name}}。请自行将其关闭，然后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "已安装更新版本的 ${PRODUCTNAME}！不建议安装旧版本。如果确实要安装此旧版本，最好先卸载当前版本。请选择要执行的操作，然后单击“下一步”继续。"
LangString older ${LANG_SIMPCHINESE} "较旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "你的系统上已安装$R4版本的 ${PRODUCTNAME}。建议先卸载当前版本，然后再安装。请选择要执行的操作，然后单击“下一步”继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "此安装程序不允许降级，无法继续静默安装，请改用图形界面安装程序。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "安装前先卸载"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "无法安装 WebView2！没有它，应用将无法运行。请尝试重新启动安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：下载 WebView2 失败 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "已成功下载 WebView2 引导程序"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 引导程序..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：安装 WebView2 失败，退出代码为 $1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "已成功安装 WebView2"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除应用程序数据"
