; The Spanish translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_SPANISH} "Añadir o reinstalar componentes"
LangString alreadyInstalled ${LANG_SPANISH} "Ya está instalado"
LangString alreadyInstalledLong ${LANG_SPANISH} "${PRODUCTNAME} ${VERSION} ya está instalado. Selecciona la operación que quieres realizar y haz clic en Siguiente para continuar."
LangString appRunning ${LANG_SPANISH} "{{product_name}} sigue abierto. Ciérralo y vuelve a intentarlo."
LangString appRunningOkKill ${LANG_SPANISH} "{{product_name}} está abierto y debe cerrarse primero.$\n$\nTus guías ya están guardadas. Si estás grabando, lo que llevas grabado se conserva y Steps te lo ofrecerá la próxima vez que se abra.$\n$\nSelecciona Aceptar para cerrar {{product_name}} ahora, o Cancelar para no continuar."
LangString chooseMaintenanceOption ${LANG_SPANISH} "Elige la operación de mantenimiento que quieres realizar."
LangString choowHowToInstall ${LANG_SPANISH} "Elige cómo quieres instalar ${PRODUCTNAME}."
LangString createDesktop ${LANG_SPANISH} "Crear un acceso directo en el escritorio"
LangString dontUninstall ${LANG_SPANISH} "No desinstalar"
LangString dontUninstallDowngrade ${LANG_SPANISH} "No desinstalar (este instalador no permite volver a una versión anterior sin desinstalar)"
LangString failedToKillApp ${LANG_SPANISH} "No se ha podido cerrar {{product_name}}. Ciérralo tú y vuelve a intentarlo."
LangString installingWebview2 ${LANG_SPANISH} "Instalando WebView2..."
LangString newerVersionInstalled ${LANG_SPANISH} "Ya hay instalada una versión más reciente de ${PRODUCTNAME}. No se recomienda instalar una versión anterior. Si de verdad quieres instalar esta versión anterior, es mejor desinstalar primero la versión actual. Selecciona la operación que quieres realizar y haz clic en Siguiente para continuar."
LangString older ${LANG_SPANISH} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_SPANISH} "Hay instalada en tu sistema una versión $R4 de ${PRODUCTNAME}. Se recomienda desinstalar la versión actual antes de instalar. Selecciona la operación que quieres realizar y haz clic en Siguiente para continuar."
LangString silentDowngrades ${LANG_SPANISH} "Este instalador no permite volver a una versión anterior, así que la instalación silenciosa no puede continuar. Usa el instalador con interfaz gráfica.$\n"
LangString unableToUninstall ${LANG_SPANISH} "No se ha podido desinstalar."
LangString uninstallApp ${LANG_SPANISH} "Desinstalar ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SPANISH} "Desinstalar antes de instalar"
LangString unknown ${LANG_SPANISH} "desconocida"
LangString webview2AbortError ${LANG_SPANISH} "No se ha podido instalar WebView2. La aplicación no puede funcionar sin él. Prueba a reiniciar el instalador."
LangString webview2DownloadError ${LANG_SPANISH} "Error: no se ha podido descargar WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_SPANISH} "El programa de arranque de WebView2 se ha descargado correctamente"
LangString webview2Downloading ${LANG_SPANISH} "Descargando el programa de arranque de WebView2..."
LangString webview2InstallError ${LANG_SPANISH} "Error: la instalación de WebView2 ha fallado con el código de salida $1"
LangString webview2InstallSuccess ${LANG_SPANISH} "WebView2 se ha instalado correctamente"
LangString deleteAppData ${LANG_SPANISH} "Eliminar los datos de la aplicación"
