; The Swedish translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_SWEDISH} "Lägg till/installera om komponenter"
LangString alreadyInstalled ${LANG_SWEDISH} "Redan installerat"
LangString alreadyInstalledLong ${LANG_SWEDISH} "${PRODUCTNAME} ${VERSION} är redan installerat. Välj vad du vill göra och klicka på Nästa för att fortsätta."
LangString appRunning ${LANG_SWEDISH} "{{product_name}} är fortfarande öppet. Stäng det och försök sedan igen."
LangString appRunningOkKill ${LANG_SWEDISH} "{{product_name}} är öppet och måste stängas först.$\n$\nDina guider är redan sparade. Om du spelar in behålls det du har spelat in hittills, och Steps erbjuder dig det nästa gång det öppnas.$\n$\nVälj OK för att stänga {{product_name}} nu, eller Avbryt för att avbryta."
LangString chooseMaintenanceOption ${LANG_SWEDISH} "Välj vilket underhållsalternativ du vill använda."
LangString choowHowToInstall ${LANG_SWEDISH} "Välj hur du vill installera ${PRODUCTNAME}."
LangString createDesktop ${LANG_SWEDISH} "Skapa genväg på skrivbordet"
LangString dontUninstall ${LANG_SWEDISH} "Avinstallera inte"
LangString dontUninstallDowngrade ${LANG_SWEDISH} "Avinstallera inte (nedgradering utan avinstallation är inaktiverad för det här installationsprogrammet)"
LangString failedToKillApp ${LANG_SWEDISH} "Det gick inte att stänga {{product_name}}. Stäng det själv och försök sedan igen."
LangString installingWebview2 ${LANG_SWEDISH} "Installerar WebView2..."
LangString newerVersionInstalled ${LANG_SWEDISH} "En nyare version av ${PRODUCTNAME} är redan installerad! Vi rekommenderar inte att du installerar en äldre version. Om du verkligen vill installera den här äldre versionen är det bättre att först avinstallera den aktuella versionen. Välj vad du vill göra och klicka på Nästa för att fortsätta."
LangString older ${LANG_SWEDISH} "äldre"
LangString olderOrUnknownVersionInstalled ${LANG_SWEDISH} "En $R4 version av ${PRODUCTNAME} är installerad på datorn. Vi rekommenderar att du avinstallerar den aktuella versionen innan du installerar. Välj vad du vill göra och klicka på Nästa för att fortsätta."
LangString silentDowngrades ${LANG_SWEDISH} "Nedgraderingar är inaktiverade för det här installationsprogrammet, så den tysta installationen kan inte fortsätta. Använd det grafiska installationsprogrammet i stället.$\n"
LangString unableToUninstall ${LANG_SWEDISH} "Det gick inte att avinstallera!"
LangString uninstallApp ${LANG_SWEDISH} "Avinstallera ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SWEDISH} "Avinstallera före installation"
LangString unknown ${LANG_SWEDISH} "okänd"
LangString webview2AbortError ${LANG_SWEDISH} "Det gick inte att installera WebView2! Appen kan inte köras utan det. Prova att starta om installationsprogrammet."
LangString webview2DownloadError ${LANG_SWEDISH} "Fel: Det gick inte att ladda ned WebView2 – $0"
LangString webview2DownloadSuccess ${LANG_SWEDISH} "Startprogrammet för WebView2 har laddats ned"
LangString webview2Downloading ${LANG_SWEDISH} "Laddar ned startprogrammet för WebView2..."
LangString webview2InstallError ${LANG_SWEDISH} "Fel: Installationen av WebView2 misslyckades med slutkoden $1"
LangString webview2InstallSuccess ${LANG_SWEDISH} "WebView2 har installerats"
LangString deleteAppData ${LANG_SWEDISH} "Ta bort appens data"
