; The Traditional Chinese (Taiwan) translation of English.nsh, the setup .exe's own messages.
; Every string English.nsh has must be here, with the same id, in the same order.
LangString addOrReinstall ${LANG_TRADCHINESE} "新增/重新安裝元件"
LangString alreadyInstalled ${LANG_TRADCHINESE} "已安裝"
LangString alreadyInstalledLong ${LANG_TRADCHINESE} "${PRODUCTNAME} ${VERSION} 已安裝。請選取要執行的操作，然後按一下「下一步」繼續。"
LangString appRunning ${LANG_TRADCHINESE} "{{product_name}} 仍在開啟中。請將它關閉，然後再試一次。"
LangString appRunningOkKill ${LANG_TRADCHINESE} "{{product_name}} 已開啟，必須先關閉。$\n$\n您的指南都已儲存。如果您正在錄製，目前已錄製的內容會保留，下次開啟 Steps 時會再提供給您。$\n$\n選取「確定」立即關閉 {{product_name}}，或選取「取消」停止。"
LangString chooseMaintenanceOption ${LANG_TRADCHINESE} "請選擇要執行的維護選項。"
LangString choowHowToInstall ${LANG_TRADCHINESE} "請選擇 ${PRODUCTNAME} 的安裝方式。"
LangString createDesktop ${LANG_TRADCHINESE} "建立桌面捷徑"
LangString dontUninstall ${LANG_TRADCHINESE} "不要解除安裝"
LangString dontUninstallDowngrade ${LANG_TRADCHINESE} "不要解除安裝（此安裝程式不允許在未解除安裝的情況下降級）"
LangString failedToKillApp ${LANG_TRADCHINESE} "無法關閉 {{product_name}}。請自行將它關閉，然後再試一次。"
LangString installingWebview2 ${LANG_TRADCHINESE} "正在安裝 WebView2..."
LangString newerVersionInstalled ${LANG_TRADCHINESE} "已安裝較新版本的 ${PRODUCTNAME}！不建議安裝較舊的版本。如果您確實要安裝此較舊版本，最好先解除安裝目前的版本。請選取要執行的操作，然後按一下「下一步」繼續。"
LangString older ${LANG_TRADCHINESE} "較舊"
LangString olderOrUnknownVersionInstalled ${LANG_TRADCHINESE} "您的系統上已安裝$R4版本的 ${PRODUCTNAME}。建議您先解除安裝目前的版本，再進行安裝。請選取要執行的操作，然後按一下「下一步」繼續。"
LangString silentDowngrades ${LANG_TRADCHINESE} "此安裝程式不允許降級，無法繼續進行無訊息安裝，請改用圖形介面安裝程式。$\n"
LangString unableToUninstall ${LANG_TRADCHINESE} "無法解除安裝！"
LangString uninstallApp ${LANG_TRADCHINESE} "解除安裝 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_TRADCHINESE} "安裝前先解除安裝"
LangString unknown ${LANG_TRADCHINESE} "未知"
LangString webview2AbortError ${LANG_TRADCHINESE} "無法安裝 WebView2！沒有它，應用程式就無法執行。請嘗試重新啟動安裝程式。"
LangString webview2DownloadError ${LANG_TRADCHINESE} "錯誤：下載 WebView2 失敗 - $0"
LangString webview2DownloadSuccess ${LANG_TRADCHINESE} "已成功下載 WebView2 啟動載入器"
LangString webview2Downloading ${LANG_TRADCHINESE} "正在下載 WebView2 啟動載入器..."
LangString webview2InstallError ${LANG_TRADCHINESE} "錯誤：安裝 WebView2 失敗，結束代碼為 $1"
LangString webview2InstallSuccess ${LANG_TRADCHINESE} "已成功安裝 WebView2"
LangString deleteAppData ${LANG_TRADCHINESE} "刪除應用程式資料"
