; The Turkish translation of English.nsh: the setup .exe's own messages.
; Every string English.nsh has must be here, with the same ids in the same order.
LangString addOrReinstall ${LANG_TURKISH} "Bileşen ekle/yeniden yükle"
LangString alreadyInstalled ${LANG_TURKISH} "Zaten yüklü"
LangString alreadyInstalledLong ${LANG_TURKISH} "${PRODUCTNAME} ${VERSION} zaten yüklü. Yapmak istediğiniz işlemi seçin ve devam etmek için İleri'ye tıklayın."
LangString appRunning ${LANG_TURKISH} "{{product_name}} hâlâ açık. Kapatın, sonra yeniden deneyin."
LangString appRunningOkKill ${LANG_TURKISH} "{{product_name}} açık ve önce kapanması gerekiyor.$\n$\nKılavuzlarınız zaten kaydedildi. Kayıt yapıyorsanız, şimdiye kadar kaydettikleriniz saklanır ve Steps bir sonraki açılışında bunları size yeniden sunar.$\n$\n{{product_name}} uygulamasını şimdi kapatmak için Tamam'ı, vazgeçmek için İptal'i seçin."
LangString chooseMaintenanceOption ${LANG_TURKISH} "Yapılacak bakım işlemini seçin."
LangString choowHowToInstall ${LANG_TURKISH} "${PRODUCTNAME} uygulamasını nasıl yüklemek istediğinizi seçin."
LangString createDesktop ${LANG_TURKISH} "Masaüstü kısayolu oluştur"
LangString dontUninstall ${LANG_TURKISH} "Kaldırma"
LangString dontUninstallDowngrade ${LANG_TURKISH} "Kaldırma (Bu yükleyicide, kaldırmadan eski sürüme geçiş devre dışı bırakıldı)"
LangString failedToKillApp ${LANG_TURKISH} "{{product_name}} kapatılamadı. Kendiniz kapatın, sonra yeniden deneyin."
LangString installingWebview2 ${LANG_TURKISH} "WebView2 yükleniyor..."
LangString newerVersionInstalled ${LANG_TURKISH} "${PRODUCTNAME} uygulamasının daha yeni bir sürümü zaten yüklü! Daha eski bir sürümü yüklemeniz önerilmez. Bu eski sürümü gerçekten yüklemek istiyorsanız, önce geçerli sürümü kaldırmanız daha iyi olur. Yapmak istediğiniz işlemi seçin ve devam etmek için İleri'ye tıklayın."
LangString older ${LANG_TURKISH} "daha eski"
LangString olderOrUnknownVersionInstalled ${LANG_TURKISH} "Sisteminizde ${PRODUCTNAME} uygulamasının $R4 bir sürümü yüklü. Yüklemeden önce geçerli sürümü kaldırmanız önerilir. Yapmak istediğiniz işlemi seçin ve devam etmek için İleri'ye tıklayın."
LangString silentDowngrades ${LANG_TURKISH} "Bu yükleyicide eski sürüme geçişler devre dışı bırakıldı, sessiz yükleyiciyle devam edilemiyor. Lütfen bunun yerine grafik arabirimli yükleyiciyi kullanın.$\n"
LangString unableToUninstall ${LANG_TURKISH} "Kaldırılamıyor!"
LangString uninstallApp ${LANG_TURKISH} "${PRODUCTNAME} uygulamasını kaldır"
LangString uninstallBeforeInstalling ${LANG_TURKISH} "Yüklemeden önce kaldır"
LangString unknown ${LANG_TURKISH} "bilinmeyen"
LangString webview2AbortError ${LANG_TURKISH} "WebView2 yüklenemedi! Uygulama onsuz çalışamaz. Yükleyiciyi yeniden başlatmayı deneyin."
LangString webview2DownloadError ${LANG_TURKISH} "Hata: WebView2 indirilemedi - $0"
LangString webview2DownloadSuccess ${LANG_TURKISH} "WebView2 önyükleyicisi başarıyla indirildi"
LangString webview2Downloading ${LANG_TURKISH} "WebView2 önyükleyicisi indiriliyor..."
LangString webview2InstallError ${LANG_TURKISH} "Hata: WebView2 yüklemesi $1 çıkış koduyla başarısız oldu"
LangString webview2InstallSuccess ${LANG_TURKISH} "WebView2 başarıyla yüklendi"
LangString deleteAppData ${LANG_TURKISH} "Uygulama verilerini sil"
