; The Ukrainian translation of English.nsh: the setup .exe's own messages, in place of Tauri's.
; Every string English.nsh has must be here, with the same id.
LangString addOrReinstall ${LANG_UKRAINIAN} "Додати або перевстановити компоненти"
LangString alreadyInstalled ${LANG_UKRAINIAN} "Уже встановлено"
LangString alreadyInstalledLong ${LANG_UKRAINIAN} "${PRODUCTNAME} ${VERSION} уже встановлено. Виберіть потрібну дію та натисніть «Далі», щоб продовжити."
LangString appRunning ${LANG_UKRAINIAN} "{{product_name}} досі відкрито. Закрийте програму й спробуйте ще раз."
LangString appRunningOkKill ${LANG_UKRAINIAN} "Програму {{product_name}} відкрито, і спершу її потрібно закрити.$\n$\nВаші інструкції вже збережено. Якщо триває запис, усе, що вже записано, буде збережено, і Steps запропонує продовжити з ним під час наступного відкриття.$\n$\nНатисніть «OK», щоб закрити {{product_name}} зараз, або «Скасувати», щоб перервати."
LangString chooseMaintenanceOption ${LANG_UKRAINIAN} "Виберіть дію з обслуговування."
LangString choowHowToInstall ${LANG_UKRAINIAN} "Виберіть спосіб установлення ${PRODUCTNAME}."
LangString createDesktop ${LANG_UKRAINIAN} "Створити ярлик на робочому столі"
LangString dontUninstall ${LANG_UKRAINIAN} "Не видаляти"
LangString dontUninstallDowngrade ${LANG_UKRAINIAN} "Не видаляти (установлення старішої версії без видалення вимкнено для цього інсталятора)"
LangString failedToKillApp ${LANG_UKRAINIAN} "Не вдалося закрити {{product_name}}. Закрийте програму вручну й спробуйте ще раз."
LangString installingWebview2 ${LANG_UKRAINIAN} "Установлення WebView2..."
LangString newerVersionInstalled ${LANG_UKRAINIAN} "Новішу версію ${PRODUCTNAME} уже встановлено! Не рекомендується встановлювати старішу версію. Якщо ви справді хочете встановити цю старішу версію, краще спершу видалити поточну. Виберіть потрібну дію та натисніть «Далі», щоб продовжити."
LangString older ${LANG_UKRAINIAN} "старішу"
LangString olderOrUnknownVersionInstalled ${LANG_UKRAINIAN} "У системі встановлено $R4 версію ${PRODUCTNAME}. Рекомендується видалити поточну версію перед установленням. Виберіть потрібну дію та натисніть «Далі», щоб продовжити."
LangString silentDowngrades ${LANG_UKRAINIAN} "Установлення старішої версії вимкнено для цього інсталятора, тому тихе встановлення неможливе. Скористайтеся графічним інсталятором.$\n"
LangString unableToUninstall ${LANG_UKRAINIAN} "Не вдалося видалити!"
LangString uninstallApp ${LANG_UKRAINIAN} "Видалити ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_UKRAINIAN} "Видалити перед установленням"
LangString unknown ${LANG_UKRAINIAN} "невідому"
LangString webview2AbortError ${LANG_UKRAINIAN} "Не вдалося встановити WebView2! Без нього програма не може працювати. Спробуйте перезапустити інсталятор."
LangString webview2DownloadError ${LANG_UKRAINIAN} "Помилка: не вдалося завантажити WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_UKRAINIAN} "Інсталятор WebView2 успішно завантажено"
LangString webview2Downloading ${LANG_UKRAINIAN} "Завантаження інсталятора WebView2..."
LangString webview2InstallError ${LANG_UKRAINIAN} "Помилка: не вдалося встановити WebView2, код виходу $1"
LangString webview2InstallSuccess ${LANG_UKRAINIAN} "WebView2 успішно встановлено"
LangString deleteAppData ${LANG_UKRAINIAN} "Видалити дані програми"
