; The Vietnamese translation of English.nsh, the setup .exe's own messages.
; Every string English.nsh has must be here, with the same id, in the same order.
LangString addOrReinstall ${LANG_VIETNAMESE} "Thêm/Cài đặt lại thành phần"
LangString alreadyInstalled ${LANG_VIETNAMESE} "Đã được cài đặt"
LangString alreadyInstalledLong ${LANG_VIETNAMESE} "${PRODUCTNAME} ${VERSION} đã được cài đặt. Hãy chọn thao tác bạn muốn thực hiện rồi bấm Tiếp để tiếp tục."
LangString appRunning ${LANG_VIETNAMESE} "{{product_name}} vẫn đang mở. Hãy đóng ứng dụng rồi thử lại."
LangString appRunningOkKill ${LANG_VIETNAMESE} "{{product_name}} đang mở và cần được đóng trước.$\n$\nCác hướng dẫn của bạn đã được lưu. Nếu bạn đang ghi, những gì đã ghi đến lúc này sẽ được giữ lại và Steps sẽ đưa ra lại vào lần mở tiếp theo.$\n$\nChọn OK để đóng {{product_name}} ngay, hoặc Hủy để dừng."
LangString chooseMaintenanceOption ${LANG_VIETNAMESE} "Chọn tùy chọn bảo trì cần thực hiện."
LangString choowHowToInstall ${LANG_VIETNAMESE} "Chọn cách bạn muốn cài đặt ${PRODUCTNAME}."
LangString createDesktop ${LANG_VIETNAMESE} "Tạo lối tắt trên màn hình nền"
LangString dontUninstall ${LANG_VIETNAMESE} "Không gỡ cài đặt"
LangString dontUninstallDowngrade ${LANG_VIETNAMESE} "Không gỡ cài đặt (trình cài đặt này không cho phép hạ cấp mà không gỡ cài đặt)"
LangString failedToKillApp ${LANG_VIETNAMESE} "Không thể đóng {{product_name}}. Hãy tự đóng ứng dụng rồi thử lại."
LangString installingWebview2 ${LANG_VIETNAMESE} "Đang cài đặt WebView2..."
LangString newerVersionInstalled ${LANG_VIETNAMESE} "Một phiên bản mới hơn của ${PRODUCTNAME} đã được cài đặt! Bạn không nên cài phiên bản cũ hơn. Nếu thật sự muốn cài phiên bản cũ hơn này, tốt nhất hãy gỡ cài đặt phiên bản hiện tại trước. Hãy chọn thao tác bạn muốn thực hiện rồi bấm Tiếp để tiếp tục."
LangString older ${LANG_VIETNAMESE} "cũ hơn"
LangString olderOrUnknownVersionInstalled ${LANG_VIETNAMESE} "Một phiên bản $R4 của ${PRODUCTNAME} đang được cài trên hệ thống. Bạn nên gỡ cài đặt phiên bản hiện tại trước khi cài. Hãy chọn thao tác bạn muốn thực hiện rồi bấm Tiếp để tiếp tục."
LangString silentDowngrades ${LANG_VIETNAMESE} "Trình cài đặt này không cho phép hạ cấp, không thể tiếp tục cài đặt im lặng. Vui lòng dùng trình cài đặt có giao diện đồ họa.$\n"
LangString unableToUninstall ${LANG_VIETNAMESE} "Không thể gỡ cài đặt!"
LangString uninstallApp ${LANG_VIETNAMESE} "Gỡ cài đặt ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_VIETNAMESE} "Gỡ cài đặt trước khi cài"
LangString unknown ${LANG_VIETNAMESE} "không xác định"
LangString webview2AbortError ${LANG_VIETNAMESE} "Không cài đặt được WebView2! Ứng dụng không thể chạy nếu thiếu WebView2. Hãy thử khởi động lại trình cài đặt."
LangString webview2DownloadError ${LANG_VIETNAMESE} "Lỗi: Tải xuống WebView2 không thành công - $0"
LangString webview2DownloadSuccess ${LANG_VIETNAMESE} "Đã tải xuống trình khởi động WebView2"
LangString webview2Downloading ${LANG_VIETNAMESE} "Đang tải xuống trình khởi động WebView2..."
LangString webview2InstallError ${LANG_VIETNAMESE} "Lỗi: Cài đặt WebView2 không thành công, mã thoát $1"
LangString webview2InstallSuccess ${LANG_VIETNAMESE} "Đã cài đặt WebView2"
LangString deleteAppData ${LANG_VIETNAMESE} "Xóa dữ liệu ứng dụng"
