import type { LanguagePhrases } from "../phrase.ts";

/**
 * Български: „…“ round names, the polite plural imperative in every tone (as Microsoft's
 * Bulgarian documentation addresses the reader); casual is the shortest label ("Щракнете върху
 * „…“"), plain uses the neutral "Изберете" and everyday words, formal follows Microsoft's
 * procedures ("Щракнете върху бутона „…“.").
 */
export const bg: LanguagePhrases = {
  casual: {
    click: {
      field: "Щракнете в полето „{name}“",
      namedField: "Щракнете върху „{name}“",
      textArea: "Щракнете върху „{name}“",
      other: "Щракнете върху „{name}“",
    },
    clickIn: "Щракнете в прозореца „{title}“",
    clickBare: "Щракнете",
    clickTaskbar: "Щракнете върху „{name}“ в лентата на задачите",
    typeValueInField: "Въведете „{value}“ в полето „{field}“",
    typeInField: "Въведете текст в полето „{field}“",
    chooseValueIn: "Изберете „{value}“ в полето „{field}“",
    chooseIn: "Изберете в полето „{field}“",
    typeValue: "Въведете „{value}“",
    type: "Въведете текст",
    typeValueInCell: "Въведете „{value}“ в клетка {cell}",
    typeInCell: "Въведете данни в клетка {cell}",
    press: "Натиснете „{keys}“",
    goTo: "Отидете на „{site}“",
    open: "Отворете „{app}“",
    runIn: "Изпълнете в {where}",
    runInTerminal: "Изпълнете в терминала",
    formulaInCell: "Въведете формулата в клетка {cell}",
    formulaInSelected: "Въведете формулата в избраната клетка",
    code: "Въведете този код",
    missed: {
      one: "Тук е пропуснато {count} щракване",
      other: "Тук са пропуснати {count} щраквания",
    },
    touch: {
      one: "Действия с докосване или писалка може да не са записани ({count} събитие)",
      other: "Действия с докосване или писалка може да не са записани ({count} събития)",
    },
    captureNow: "Заснемете този екран",
  },
  plain: {
    click: {
      button: "Изберете бутона „{name}“",
      link: "Изберете връзката „{name}“",
      menuItem: "Изберете „{name}“ в менюто",
      tab: "Изберете раздела „{name}“",
      field: "Изберете полето „{name}“",
      checkbox: "Отметнете „{name}“",
      radio: "Изберете „{name}“",
      dropdown: "Отворете списъка „{name}“",
      switch: "Изберете превключвателя „{name}“",
      picture: "Изберете изображението „{name}“",
      other: "Изберете „{name}“",
    },
    clickIn: "Натиснете в прозореца „{title}“",
    clickBare: "Натиснете тук",
    clickTaskbar: "Изберете „{name}“ в лентата на задачите",
    typeValueInField: "Въведете „{value}“ в полето „{field}“",
    typeInField: "Попълнете полето „{field}“",
    chooseValueIn: "Изберете „{value}“ от списъка „{field}“",
    chooseIn: "Изберете от списъка „{field}“",
    typeValue: "Въведете „{value}“",
    type: "Въведете текста",
    typeValueInCell: "Въведете „{value}“ в клетка {cell}",
    typeInCell: "Попълнете клетка {cell}",
    press: "Натиснете {keys}",
    goTo: "Отидете на {site}",
    open: "Отворете {app}",
    runIn: "Изпълнете това в {where}",
    runInTerminal: "Изпълнете това в терминала",
    formulaInCell: "Въведете тази формула в клетка {cell}",
    formulaInSelected: "Въведете тази формула в избраната клетка",
    code: "Въведете този код",
    missed: {
      one: "Тук е пропуснато {count} щракване",
      other: "Тук са пропуснати {count} щраквания",
    },
    touch: {
      one: "Тук може да липсват докосвания или писалка ({count} събитие)",
      other: "Тук може да липсват докосвания или писалка ({count} събития)",
    },
    captureNow: "Разгледайте този екран",
  },
  formal: {
    click: {
      button: "Щракнете върху бутона „{name}“.",
      link: "Щракнете върху връзката „{name}“.",
      menuItem: "Щракнете върху „{name}“ в менюто.",
      tab: "Щракнете върху раздела „{name}“.",
      field: "Щракнете в полето „{name}“.",
      checkbox: "Поставете отметка в квадратчето „{name}“.",
      radio: "Изберете опцията „{name}“.",
      dropdown: "Щракнете върху падащия списък „{name}“.",
      switch: "Щракнете върху превключвателя „{name}“.",
      picture: "Щракнете върху изображението „{name}“.",
      other: "Щракнете върху „{name}“.",
    },
    clickIn: "Щракнете в прозореца „{title}“.",
    clickBare: "Щракнете.",
    clickTaskbar: "Щракнете върху „{name}“ в лентата на задачите.",
    typeValueInField: "В полето „{field}“ въведете „{value}“.",
    typeInField: "Попълнете полето „{field}“.",
    chooseValueIn: "В списъка „{field}“ изберете „{value}“.",
    chooseIn: "Изберете опция от списъка „{field}“.",
    typeValue: "Въведете „{value}“.",
    type: "Въведете текста.",
    typeValueInCell: "В клетка {cell} въведете „{value}“.",
    typeInCell: "Попълнете клетка {cell}.",
    press: "Натиснете {keys}.",
    goTo: "Отидете на {site}.",
    open: "Отворете {app}.",
    runIn: "Изпълнете следната команда в {where}.",
    runInTerminal: "Изпълнете следната команда в терминала.",
    formulaInCell: "В клетка {cell} въведете следната формула.",
    formulaInSelected: "В избраната клетка въведете следната формула.",
    code: "Въведете следния код.",
    missed: {
      one: "Тук не е записано {count} щракване.",
      other: "Тук не са записани {count} щраквания.",
    },
    touch: {
      one: "Тук може да не е записано въвеждане с докосване или писалка ({count} събитие).",
      other: "Тук може да не е записано въвеждане с докосване или писалка ({count} събития).",
    },
    captureNow: "Прегледайте този екран.",
  },
  terminals: { powershell: "PowerShell", cmd: "Команден ред", bash: "Bash" },
};
