import type { LanguagePhrases } from "../phrase.ts";

/**
 * Català: «…» quotes with no spaces; the casual tone uses the infinitive ("Fer clic a «Desa»"),
 * plain language addresses the reader as "vós" with the neutral "Seleccioneu", and formal writes
 * full "vós" sentences in the style of Microsoft's Catalan procedures ("Feu clic al botó «Desa».").
 * Keys and web addresses aren't quoted outside the casual tone.
 */
export const ca: LanguagePhrases = {
  casual: {
    click: {
      field: "Fer clic al camp «{name}»",
      namedField: "Fer clic a «{name}»",
      textArea: "Fer clic a «{name}»",
      other: "Fer clic a «{name}»",
    },
    clickIn: "Fer clic a «{title}»",
    clickBare: "Fer clic",
    clickTaskbar: "Fer clic a «{name}» a la barra de tasques",
    typeValueInField: "Escriure «{value}» al camp «{field}»",
    typeInField: "Escriure al camp «{field}»",
    chooseValueIn: "Triar «{value}» a «{field}»",
    chooseIn: "Triar a «{field}»",
    typeValue: "Escriure «{value}»",
    type: "Escriure",
    typeValueInCell: "Escriure «{value}» a la cel·la {cell}",
    typeInCell: "Escriure a la cel·la {cell}",
    press: "Prémer {keys}",
    goTo: "Anar a «{site}»",
    open: "Obrir «{app}»",
    runIn: "Executar a {where}",
    runInTerminal: "Executar al terminal",
    formulaInCell: "Escriure la fórmula a la cel·la {cell}",
    formulaInSelected: "Escriure la fórmula a la cel·la seleccionada",
    code: "Escriure aquest codi",
    missed: {
      one: "{count} clic perdut aquí",
      many: "{count} clics perduts aquí",
      other: "{count} clics perduts aquí",
    },
    touch: {
      one: "Potser no s'ha enregistrat l'activitat tàctil o de llapis ({count} avís)",
      many: "Potser no s'ha enregistrat l'activitat tàctil o de llapis ({count} avisos)",
      other: "Potser no s'ha enregistrat l'activitat tàctil o de llapis ({count} avisos)",
    },
    captureNow: "Capturar aquesta pantalla",
  },
  plain: {
    click: {
      button: "Seleccioneu el botó «{name}»",
      link: "Seleccioneu l'enllaç «{name}»",
      menuItem: "Seleccioneu «{name}» al menú",
      tab: "Seleccioneu la pestanya «{name}»",
      field: "Seleccioneu el quadre «{name}»",
      checkbox: "Marqueu la casella «{name}»",
      radio: "Trieu «{name}»",
      dropdown: "Obriu la llista «{name}»",
      switch: "Seleccioneu l'interruptor «{name}»",
      picture: "Seleccioneu la imatge «{name}»",
      other: "Seleccioneu «{name}»",
    },
    clickIn: "Seleccioneu aquest punt de la finestra «{title}»",
    clickBare: "Seleccioneu aquest punt",
    clickTaskbar: "Seleccioneu «{name}» a la barra de tasques",
    typeValueInField: "Escriviu «{value}» al quadre «{field}»",
    typeInField: "Ompliu el quadre «{field}»",
    chooseValueIn: "Trieu «{value}» a la llista «{field}»",
    chooseIn: "Trieu a la llista «{field}»",
    typeValue: "Escriviu «{value}»",
    type: "Escriviu el text",
    typeValueInCell: "Escriviu «{value}» a la cel·la {cell}",
    typeInCell: "Ompliu la cel·la {cell}",
    press: "Premeu {keys}",
    goTo: "Aneu a {site}",
    open: "Obriu {app}",
    runIn: "Executeu això a {where}",
    runInTerminal: "Executeu això al terminal",
    formulaInCell: "Escriviu aquesta fórmula a la cel·la {cell}",
    formulaInSelected: "Escriviu aquesta fórmula a la cel·la seleccionada",
    code: "Escriviu aquest codi",
    missed: {
      one: "Aquí s'ha perdut {count} clic",
      many: "Aquí s'han perdut {count} clics",
      other: "Aquí s'han perdut {count} clics",
    },
    touch: {
      one: "Aquí pot faltar l'ús tàctil o del llapis ({count} avís)",
      many: "Aquí pot faltar l'ús tàctil o del llapis ({count} avisos)",
      other: "Aquí pot faltar l'ús tàctil o del llapis ({count} avisos)",
    },
    captureNow: "Mireu aquesta pantalla",
  },
  formal: {
    click: {
      button: "Feu clic al botó «{name}».",
      link: "Feu clic a l'enllaç «{name}».",
      menuItem: "Al menú, feu clic a «{name}».",
      tab: "Feu clic a la pestanya «{name}».",
      field: "Feu clic al camp «{name}».",
      checkbox: "Marqueu la casella de selecció «{name}».",
      radio: "Seleccioneu l'opció «{name}».",
      dropdown: "Feu clic a la llista desplegable «{name}».",
      switch: "Feu clic al commutador «{name}».",
      picture: "Feu clic a la imatge «{name}».",
      other: "Feu clic a «{name}».",
    },
    clickIn: "Feu clic a la finestra «{title}».",
    clickBare: "Feu clic en aquest punt.",
    clickTaskbar: "Feu clic a «{name}» a la barra de tasques.",
    typeValueInField: "Al camp «{field}», escriviu «{value}».",
    typeInField: "Empleneu el camp «{field}».",
    chooseValueIn: "A la llista «{field}», seleccioneu «{value}».",
    chooseIn: "A la llista «{field}», seleccioneu una opció.",
    typeValue: "Escriviu «{value}».",
    type: "Escriviu el text.",
    typeValueInCell: "A la cel·la {cell}, escriviu «{value}».",
    typeInCell: "Empleneu la cel·la {cell}.",
    press: "Premeu {keys}.",
    goTo: "Aneu a {site}.",
    open: "Obriu {app}.",
    runIn: "Executeu l'ordre següent a {where}.",
    runInTerminal: "Executeu l'ordre següent al terminal.",
    formulaInCell: "A la cel·la {cell}, escriviu la fórmula següent.",
    formulaInSelected: "A la cel·la seleccionada, escriviu la fórmula següent.",
    code: "Escriviu el codi següent.",
    missed: {
      one: "Aquí no s'ha enregistrat {count} clic.",
      many: "Aquí no s'han enregistrat {count} clics.",
      other: "Aquí no s'han enregistrat {count} clics.",
    },
    touch: {
      one: "És possible que aquí no s'hagi enregistrat l'entrada tàctil o de llapis ({count} avís).",
      many: "És possible que aquí no s'hagi enregistrat l'entrada tàctil o de llapis ({count} avisos).",
      other:
        "És possible que aquí no s'hagi enregistrat l'entrada tàctil o de llapis ({count} avisos).",
    },
    captureNow: "Reviseu aquesta pantalla.",
  },
  terminals: { powershell: "PowerShell", cmd: "l'Indicador d'ordres", bash: "Bash" },
};
