import type { LanguagePhrases } from "../phrase.ts";

/**
 * Čeština: names in „…“; every tone addresses the reader formally (vykání) as Windows does, with
 * the imperative: casual „Klikněte na …“, plain the neutral „Vyberte …“, formal full sentences in
 * the style of Microsoft's procedures.
 */
export const cs: LanguagePhrases = {
  casual: {
    click: {
      field: "Klikněte do pole „{name}“",
      namedField: "Klikněte na „{name}“",
      textArea: "Klikněte na „{name}“",
      other: "Klikněte na „{name}“",
    },
    clickIn: "Klikněte do okna „{title}“",
    clickBare: "Klikněte",
    clickTaskbar: "Klikněte na „{name}“ na hlavním panelu",
    rightClick: "Klikněte pravým tlačítkem na „{name}“",
    rightClickIn: "Klikněte pravým tlačítkem v okně „{title}“",
    rightClickBare: "Klikněte pravým tlačítkem",
    selectRange: "Vyberte „{range}“",
    fillDown: "Vyplňte „{from}“ dolů do „{to}“",
    fillTo: "Vyplňte „{from}“ do „{to}“",
    fillColumn: "Vyplňte „{from}“ dolů ve sloupci",
    typeValueInField: "Zadejte „{value}“ do pole „{field}“",
    typeInField: "Zadejte text do pole „{field}“",
    chooseValueIn: "Vyberte „{value}“ v poli „{field}“",
    chooseIn: "Vyberte v poli „{field}“",
    typeValue: "Zadejte „{value}“",
    type: "Zadejte text",
    typeValueInCell: "Zadejte „{value}“ do buňky {cell}",
    typeInCell: "Zadejte text do buňky {cell}",
    press: "Stiskněte „{keys}“",
    pressNamed: "Stiskněte „{keys}“ ({name})",
    goTo: "Přejděte na „{site}“",
    open: "Otevřete „{app}“",
    runIn: "Spusťte v aplikaci {where}",
    runInTerminal: "Spusťte v terminálu",
    formulaInCell: "Zadejte vzorec do buňky {cell}",
    formulaInSelected: "Zadejte vzorec do vybrané buňky",
    code: "Zadejte tento kód",
    missed: {
      one: "Tady bylo vynecháno {count} kliknutí",
      few: "Tady byla vynechána {count} kliknutí",
      many: "Tady bylo vynecháno {count} kliknutí",
      other: "Tady bylo vynecháno {count} kliknutí",
    },
    touch: {
      one: "Dotyk nebo pero se možná nenahrály ({count} hlášení)",
      few: "Dotyk nebo pero se možná nenahrály ({count} hlášení)",
      many: "Dotyk nebo pero se možná nenahrály ({count} hlášení)",
      other: "Dotyk nebo pero se možná nenahrály ({count} hlášení)",
    },
    captureNow: "Zachyťte tuto obrazovku",
  },
  plain: {
    click: {
      button: "Vyberte tlačítko „{name}“",
      link: "Vyberte odkaz „{name}“",
      menuItem: "V nabídce vyberte „{name}“",
      tab: "Vyberte kartu „{name}“",
      field: "Vyberte pole „{name}“",
      checkbox: "Zaškrtněte políčko „{name}“",
      radio: "Zvolte „{name}“",
      dropdown: "Otevřete seznam „{name}“",
      switch: "Vyberte přepínač „{name}“",
      picture: "Vyberte obrázek „{name}“",
      other: "Vyberte „{name}“",
    },
    clickIn: "Vyberte místo v okně „{title}“",
    clickBare: "Vyberte toto místo",
    clickTaskbar: "Vyberte „{name}“ na hlavním panelu",
    rightClick: "Klikněte pravým tlačítkem na „{name}“",
    rightClickIn: "Klikněte pravým tlačítkem uvnitř okna „{title}“",
    rightClickBare: "Klikněte zde pravým tlačítkem",
    selectRange: "Vyberte buňky {range}",
    fillDown: "Vyplňte buňku {from} dolů do buňky {to}",
    fillTo: "Vyplňte buňku {from} do buňky {to}",
    fillColumn: "Vyplňte buňku {from} dolů ve sloupci",
    typeValueInField: "Do pole „{field}“ napište „{value}“",
    typeInField: "Vyplňte pole „{field}“",
    chooseValueIn: "Ze seznamu „{field}“ vyberte „{value}“",
    chooseIn: "Vyberte ze seznamu „{field}“",
    typeValue: "Napište „{value}“",
    type: "Napište text",
    typeValueInCell: "Do buňky {cell} napište „{value}“",
    typeInCell: "Vyplňte buňku {cell}",
    press: "Stiskněte {keys}",
    pressNamed: "Stiskněte {keys} ({name})",
    goTo: "Přejděte na {site}",
    open: "Otevřete {app}",
    runIn: "Spusťte to v aplikaci {where}",
    runInTerminal: "Spusťte to v terminálu",
    formulaInCell: "Do buňky {cell} napište tento vzorec",
    formulaInSelected: "Do vybrané buňky napište tento vzorec",
    code: "Napište tento kód",
    missed: {
      one: "Tady bylo vynecháno {count} kliknutí",
      few: "Tady byla vynechána {count} kliknutí",
      many: "Tady bylo vynecháno {count} kliknutí",
      other: "Tady bylo vynecháno {count} kliknutí",
    },
    touch: {
      one: "Tady možná chybí použití dotyku nebo pera ({count} hlášení)",
      few: "Tady možná chybí použití dotyku nebo pera ({count} hlášení)",
      many: "Tady možná chybí použití dotyku nebo pera ({count} hlášení)",
      other: "Tady možná chybí použití dotyku nebo pera ({count} hlášení)",
    },
    captureNow: "Podívejte se na tuto obrazovku",
  },
  formal: {
    click: {
      button: "Klikněte na tlačítko „{name}“.",
      link: "Klikněte na odkaz „{name}“.",
      menuItem: "V nabídce klikněte na položku „{name}“.",
      tab: "Klikněte na kartu „{name}“.",
      field: "Klikněte do pole „{name}“.",
      checkbox: "Zaškrtněte políčko „{name}“.",
      radio: "Vyberte možnost „{name}“.",
      dropdown: "Klikněte na rozevírací seznam „{name}“.",
      switch: "Klikněte na přepínač „{name}“.",
      picture: "Klikněte na obrázek „{name}“.",
      other: "Klikněte na „{name}“.",
    },
    clickIn: "Klikněte do okna „{title}“.",
    clickBare: "Klikněte.",
    clickTaskbar: "Klikněte na „{name}“ na hlavním panelu.",
    rightClick: "Klikněte pravým tlačítkem na „{name}“.",
    rightClickIn: "Klikněte pravým tlačítkem uvnitř okna „{title}“.",
    rightClickBare: "Klikněte pravým tlačítkem.",
    selectRange: "Vyberte buňky {range}.",
    fillDown: "Vyplňte buňku {from} dolů do buňky {to}.",
    fillTo: "Vyplňte buňku {from} do buňky {to}.",
    fillColumn: "Vyplňte buňku {from} dolů ve sloupci.",
    typeValueInField: "Do pole „{field}“ zadejte „{value}“.",
    typeInField: "Vyplňte pole „{field}“.",
    chooseValueIn: "V seznamu „{field}“ vyberte „{value}“.",
    chooseIn: "Vyberte možnost v seznamu „{field}“.",
    typeValue: "Zadejte „{value}“.",
    type: "Zadejte text.",
    typeValueInCell: "Do buňky {cell} zadejte „{value}“.",
    typeInCell: "Vyplňte buňku {cell}.",
    press: "Stiskněte {keys}.",
    pressNamed: "Stiskněte {keys} ({name}).",
    goTo: "Přejděte na web {site}.",
    open: "Otevřete aplikaci {app}.",
    runIn: "Spusťte následující příkaz v aplikaci {where}.",
    runInTerminal: "Spusťte následující příkaz v terminálu.",
    formulaInCell: "Do buňky {cell} zadejte následující vzorec.",
    formulaInSelected: "Do vybrané buňky zadejte následující vzorec.",
    code: "Zadejte následující kód.",
    missed: {
      one: "Na tomto místě nebylo zaznamenáno {count} kliknutí.",
      few: "Na tomto místě nebyla zaznamenána {count} kliknutí.",
      many: "Na tomto místě nebylo zaznamenáno {count} kliknutí.",
      other: "Na tomto místě nebylo zaznamenáno {count} kliknutí.",
    },
    touch: {
      one: "Na tomto místě se možná nezaznamenal vstup dotykem nebo perem ({count} hlášení).",
      few: "Na tomto místě se možná nezaznamenal vstup dotykem nebo perem ({count} hlášení).",
      many: "Na tomto místě se možná nezaznamenal vstup dotykem nebo perem ({count} hlášení).",
      other: "Na tomto místě se možná nezaznamenal vstup dotykem nebo perem ({count} hlášení).",
    },
    captureNow: "Zkontrolujte tuto obrazovku.",
  },
  terminals: { powershell: "PowerShell", cmd: "Příkazový řádek", bash: "Bash" },
  shortcuts: {
    selectAll: "Vybrat vše",
    copy: "Kopírovat",
    cut: "Vyjmout",
    paste: "Vložit",
    save: "Uložit",
    print: "Tisk",
    find: "Najít",
    close: "Zavřít",
    taskManager: "Správce úloh",
    showDesktop: "Zobrazit plochu",
    fileExplorer: "Průzkumník souborů",
    settings: "Nastavení",
    lock: "Zamknout",
    run: "Spustit",
    clipboardHistory: "Historie schránky",
    snippingTool: "Nástroj Výstřižky",
  },
};
