import type { LanguagePhrases } from "../phrase.ts";

/**
 * Dansk: quotation marks ”…” and the imperative with "du" implied throughout; casual is short
 * ("Klik på ”Gem”"), plain uses everyday words and the neutral "Vælg" as Danish plain-language
 * guides recommend, and formal writes full sentences as Microsoft's Danish procedures do
 * ("Klik på knappen ”Gem”.").
 */
export const da: LanguagePhrases = {
  casual: {
    click: {
      field: "Klik i feltet ”{name}”",
      namedField: "Klik på ”{name}”",
      textArea: "Klik på ”{name}”",
      other: "Klik på ”{name}”",
    },
    clickIn: "Klik i ”{title}”",
    clickBare: "Klik",
    clickTaskbar: "Klik på ”{name}” på proceslinjen",
    typeValueInField: "Skriv ”{value}” i feltet ”{field}”",
    typeInField: "Skriv i feltet ”{field}”",
    chooseValueIn: "Vælg ”{value}” i ”{field}”",
    chooseIn: "Vælg i ”{field}”",
    typeValue: "Skriv ”{value}”",
    type: "Skriv",
    typeValueInCell: "Skriv ”{value}” i celle {cell}",
    typeInCell: "Skriv i celle {cell}",
    press: "Tryk på ”{keys}”",
    goTo: "Gå til ”{site}”",
    open: "Åbn ”{app}”",
    runIn: "Kør i {where}",
    runInTerminal: "Kør i terminalen",
    formulaInCell: "Skriv formlen i celle {cell}",
    formulaInSelected: "Skriv formlen i den markerede celle",
    code: "Skriv denne kode",
    missed: { one: "{count} klik overset her", other: "{count} klik overset her" },
    touch: {
      one: "Berørings- eller penaktivitet er måske ikke optaget ({count} rapport)",
      other: "Berørings- eller penaktivitet er måske ikke optaget ({count} rapporter)",
    },
    captureNow: "Tag et billede af denne skærm",
  },
  plain: {
    click: {
      button: "Vælg knappen ”{name}”",
      link: "Vælg linket ”{name}”",
      menuItem: "Vælg ”{name}” i menuen",
      tab: "Vælg fanen ”{name}”",
      field: "Vælg feltet ”{name}”",
      checkbox: "Vælg afkrydsningsfeltet ”{name}”",
      radio: "Vælg ”{name}”",
      dropdown: "Åbn listen ”{name}”",
      switch: "Vælg kontakten ”{name}”",
      picture: "Vælg billedet ”{name}”",
      other: "Vælg ”{name}”",
    },
    clickIn: "Vælg i vinduet ”{title}”",
    clickBare: "Vælg her",
    clickTaskbar: "Vælg ”{name}” på proceslinjen",
    typeValueInField: "Skriv ”{value}” i feltet ”{field}”",
    typeInField: "Udfyld feltet ”{field}”",
    chooseValueIn: "Vælg ”{value}” på listen ”{field}”",
    chooseIn: "Vælg på listen ”{field}”",
    typeValue: "Skriv ”{value}”",
    type: "Skriv teksten",
    typeValueInCell: "Skriv ”{value}” i celle {cell}",
    typeInCell: "Udfyld celle {cell}",
    press: "Tryk på {keys}",
    goTo: "Gå til {site}",
    open: "Åbn {app}",
    runIn: "Kør dette i {where}",
    runInTerminal: "Kør dette i terminalen",
    formulaInCell: "Skriv denne formel i celle {cell}",
    formulaInSelected: "Skriv denne formel i den markerede celle",
    code: "Skriv denne kode",
    missed: { one: "{count} klik blev overset her", other: "{count} klik blev overset her" },
    touch: {
      one: "Brug af berøring eller pen kan mangle her ({count} rapport)",
      other: "Brug af berøring eller pen kan mangle her ({count} rapporter)",
    },
    captureNow: "Se på denne skærm",
  },
  formal: {
    click: {
      button: "Klik på knappen ”{name}”.",
      link: "Klik på linket ”{name}”.",
      menuItem: "Klik på ”{name}” i menuen.",
      tab: "Klik på fanen ”{name}”.",
      field: "Klik i feltet ”{name}”.",
      checkbox: "Markér afkrydsningsfeltet ”{name}”.",
      radio: "Vælg indstillingen ”{name}”.",
      dropdown: "Klik på rullelisten ”{name}”.",
      switch: "Klik på til/fra-knappen ”{name}”.",
      picture: "Klik på billedet ”{name}”.",
      other: "Klik på ”{name}”.",
    },
    clickIn: "Klik i vinduet ”{title}”.",
    clickBare: "Klik.",
    clickTaskbar: "Klik på ”{name}” på proceslinjen.",
    typeValueInField: "Skriv ”{value}” i feltet ”{field}”.",
    typeInField: "Udfyld feltet ”{field}”.",
    chooseValueIn: "Vælg ”{value}” på listen ”{field}”.",
    chooseIn: "Vælg en indstilling på listen ”{field}”.",
    typeValue: "Skriv ”{value}”.",
    type: "Skriv teksten.",
    typeValueInCell: "Skriv ”{value}” i celle {cell}.",
    typeInCell: "Udfyld celle {cell}.",
    press: "Tryk på {keys}.",
    goTo: "Gå til {site}.",
    open: "Åbn {app}.",
    runIn: "Kør følgende kommando i {where}.",
    runInTerminal: "Kør følgende kommando i terminalen.",
    formulaInCell: "Skriv følgende formel i celle {cell}.",
    formulaInSelected: "Skriv følgende formel i den markerede celle.",
    code: "Skriv følgende kode.",
    missed: {
      one: "{count} klik blev ikke optaget her.",
      other: "{count} klik blev ikke optaget her.",
    },
    touch: {
      one: "Berørings- eller peninput er muligvis ikke optaget her ({count} rapport).",
      other: "Berørings- eller peninput er muligvis ikke optaget her ({count} rapporter).",
    },
    captureNow: "Gennemse denne skærm.",
  },
  terminals: { powershell: "PowerShell", cmd: "Kommandoprompt", bash: "Bash" },
};
