import type { LanguagePhrases } from "../phrase.ts";

/**
 * Deutsch: German quotation marks („…“) round names and values; the casual tone uses the short
 * infinitive of German step lists („Speichern“ anklicken), plain language a neutral „auswählen“
 * with everyday names for things, and formal the "Sie" sentences of Microsoft's German procedure
 * documentation. Terminals are named with their article ("in der Eingabeaufforderung").
 */
export const de: LanguagePhrases = {
  casual: {
    click: {
      field: "Feld „{name}“ anklicken",
      namedField: "„{name}“ anklicken",
      textArea: "„{name}“ anklicken",
      other: "„{name}“ anklicken",
    },
    clickIn: "In „{title}“ klicken",
    clickBare: "Klicken",
    clickTaskbar: "„{name}“ auf der Taskleiste anklicken",
    rightClick: "„{name}“ mit der rechten Maustaste anklicken",
    rightClickIn: "In „{title}“ mit der rechten Maustaste klicken",
    rightClickBare: "Mit der rechten Maustaste klicken",
    selectRange: "„{range}“ auswählen",
    fillDown: "„{from}“ nach unten bis „{to}“ ausfüllen",
    fillTo: "„{from}“ bis „{to}“ ausfüllen",
    fillColumn: "„{from}“ in der Spalte nach unten ausfüllen",
    typeValueInField: "„{value}“ in Feld „{field}“ eingeben",
    typeInField: "In Feld „{field}“ eingeben",
    chooseValueIn: "„{value}“ in „{field}“ auswählen",
    chooseIn: "In „{field}“ auswählen",
    typeValue: "„{value}“ eingeben",
    type: "Text eingeben",
    typeValueInCell: "„{value}“ in Zelle {cell} eingeben",
    typeInCell: "In Zelle {cell} eingeben",
    press: "„{keys}“ drücken",
    pressNamed: "„{keys}“ ({name}) drücken",
    goTo: "„{site}“ aufrufen",
    open: "„{app}“ öffnen",
    runIn: "In der {where} ausführen",
    runInTerminal: "Im Terminal ausführen",
    formulaInCell: "Formel in Zelle {cell} eingeben",
    formulaInSelected: "Formel in die ausgewählte Zelle eingeben",
    code: "Diesen Code eingeben",
    missed: { one: "{count} Klick hier verpasst", other: "{count} Klicks hier verpasst" },
    touch: {
      one: "Touch- oder Stifteingaben eventuell nicht aufgezeichnet ({count} Meldung)",
      other: "Touch- oder Stifteingaben eventuell nicht aufgezeichnet ({count} Meldungen)",
    },
    captureNow: "Diesen Bildschirm erfassen",
  },
  plain: {
    click: {
      button: "Schaltfläche „{name}“ auswählen",
      link: "Link „{name}“ auswählen",
      menuItem: "Im Menü „{name}“ auswählen",
      tab: "Registerkarte „{name}“ auswählen",
      field: "Feld „{name}“ auswählen",
      checkbox: "Häkchen bei „{name}“ setzen",
      radio: "„{name}“ wählen",
      dropdown: "Liste „{name}“ öffnen",
      switch: "Schalter „{name}“ auswählen",
      picture: "Bild „{name}“ auswählen",
      other: "„{name}“ auswählen",
    },
    clickIn: "Im Fenster „{title}“ auswählen",
    clickBare: "Hier auswählen",
    clickTaskbar: "„{name}“ auf der Taskleiste auswählen",
    rightClick: "„{name}“ mit der rechten Maustaste anklicken",
    rightClickIn: "Im Fenster „{title}“ mit der rechten Maustaste klicken",
    rightClickBare: "Hier mit der rechten Maustaste klicken",
    selectRange: "Zellen {range} auswählen",
    fillDown: "Zelle {from} nach unten bis Zelle {to} ausfüllen",
    fillTo: "Zelle {from} bis Zelle {to} ausfüllen",
    fillColumn: "Zelle {from} in der Spalte nach unten ausfüllen",
    typeValueInField: "„{value}“ in das Feld „{field}“ eingeben",
    typeInField: "Feld „{field}“ ausfüllen",
    chooseValueIn: "„{value}“ in der Liste „{field}“ auswählen",
    chooseIn: "In der Liste „{field}“ auswählen",
    typeValue: "„{value}“ eingeben",
    type: "Den Text eingeben",
    typeValueInCell: "„{value}“ in Zelle {cell} eingeben",
    typeInCell: "Zelle {cell} ausfüllen",
    press: "{keys} drücken",
    pressNamed: "{keys} ({name}) drücken",
    goTo: "{site} aufrufen",
    open: "{app} öffnen",
    runIn: "Diesen Befehl in der {where} ausführen",
    runInTerminal: "Diesen Befehl im Terminal ausführen",
    formulaInCell: "Diese Formel in Zelle {cell} eingeben",
    formulaInSelected: "Diese Formel in die ausgewählte Zelle eingeben",
    code: "Diesen Code eingeben",
    missed: {
      one: "{count} Klick wurde hier nicht erfasst",
      other: "{count} Klicks wurden hier nicht erfasst",
    },
    touch: {
      one: "Hier fehlen vielleicht Touch- oder Stifteingaben ({count} Meldung)",
      other: "Hier fehlen vielleicht Touch- oder Stifteingaben ({count} Meldungen)",
    },
    captureNow: "Diesen Bildschirm ansehen",
  },
  formal: {
    click: {
      button: "Klicken Sie auf die Schaltfläche „{name}“.",
      link: "Klicken Sie auf den Link „{name}“.",
      menuItem: "Klicken Sie im Menü auf „{name}“.",
      tab: "Klicken Sie auf die Registerkarte „{name}“.",
      field: "Klicken Sie in das Feld „{name}“.",
      checkbox: "Aktivieren Sie das Kontrollkästchen „{name}“.",
      radio: "Wählen Sie die Option „{name}“ aus.",
      dropdown: "Klicken Sie auf die Dropdownliste „{name}“.",
      switch: "Klicken Sie auf den Schalter „{name}“.",
      picture: "Klicken Sie auf das Bild „{name}“.",
      other: "Klicken Sie auf „{name}“.",
    },
    clickIn: "Klicken Sie in das Fenster „{title}“.",
    clickBare: "Klicken Sie hier.",
    clickTaskbar: "Klicken Sie auf der Taskleiste auf „{name}“.",
    rightClick: "Klicken Sie mit der rechten Maustaste auf „{name}“.",
    rightClickIn: "Klicken Sie mit der rechten Maustaste in das Fenster „{title}“.",
    rightClickBare: "Klicken Sie mit der rechten Maustaste.",
    selectRange: "Wählen Sie die Zellen {range} aus.",
    fillDown: "Füllen Sie Zelle {from} nach unten bis Zelle {to} aus.",
    fillTo: "Füllen Sie Zelle {from} bis Zelle {to} aus.",
    fillColumn: "Füllen Sie Zelle {from} in der Spalte nach unten aus.",
    typeValueInField: "Geben Sie in das Feld „{field}“ den Wert „{value}“ ein.",
    typeInField: "Füllen Sie das Feld „{field}“ aus.",
    chooseValueIn: "Wählen Sie in der Liste „{field}“ den Eintrag „{value}“ aus.",
    chooseIn: "Wählen Sie in der Liste „{field}“ einen Eintrag aus.",
    typeValue: "Geben Sie „{value}“ ein.",
    type: "Geben Sie den Text ein.",
    typeValueInCell: "Geben Sie in Zelle {cell} den Wert „{value}“ ein.",
    typeInCell: "Füllen Sie Zelle {cell} aus.",
    press: "Drücken Sie {keys}.",
    pressNamed: "Drücken Sie {keys} ({name}).",
    goTo: "Rufen Sie {site} auf.",
    open: "Öffnen Sie {app}.",
    runIn: "Führen Sie den folgenden Befehl in der {where} aus.",
    runInTerminal: "Führen Sie den folgenden Befehl im Terminal aus.",
    formulaInCell: "Geben Sie in Zelle {cell} die folgende Formel ein.",
    formulaInSelected: "Geben Sie in der ausgewählten Zelle die folgende Formel ein.",
    code: "Geben Sie den folgenden Code ein.",
    missed: {
      one: "{count} Klick wurde hier nicht aufgezeichnet.",
      other: "{count} Klicks wurden hier nicht aufgezeichnet.",
    },
    touch: {
      one: "Touch- oder Stifteingaben wurden hier möglicherweise nicht aufgezeichnet ({count} Meldung).",
      other:
        "Touch- oder Stifteingaben wurden hier möglicherweise nicht aufgezeichnet ({count} Meldungen).",
    },
    captureNow: "Prüfen Sie diesen Bildschirm.",
  },
  terminals: { powershell: "PowerShell", cmd: "Eingabeaufforderung", bash: "Bash" },
  shortcuts: {
    selectAll: "Alles auswählen",
    copy: "Kopieren",
    cut: "Ausschneiden",
    paste: "Einfügen",
    save: "Speichern",
    print: "Drucken",
    find: "Suchen",
    close: "Schließen",
    taskManager: "Task-Manager",
    showDesktop: "Desktop anzeigen",
    fileExplorer: "Explorer",
    settings: "Einstellungen",
    lock: "Sperren",
    run: "Ausführen",
    clipboardHistory: "Zwischenablageverlauf",
    snippingTool: "Snipping Tool",
  },
};
