import type { LanguagePhrases } from "../phrase.ts";

/**
 * Ελληνικά: Greek quotation marks («…»), the polite plural Microsoft uses in Windows ("Κάντε
 * κλικ", "Πληκτρολογήστε"); casual is as short as a step label can be ("Κλικ στο «Αποθήκευση»"),
 * plain uses "Επιλέξτε" and everyday words, formal follows Microsoft's procedure documentation.
 * Names of unknown gender are introduced by a noun (κουμπί, εφαρμογή, στοιχείο) where Greek needs
 * an article that agrees with them.
 */
export const el: LanguagePhrases = {
  casual: {
    click: {
      field: "Κλικ στο πεδίο «{name}»",
      namedField: "Κλικ στο «{name}»",
      textArea: "Κλικ στο «{name}»",
      other: "Κλικ στο «{name}»",
    },
    clickIn: "Κλικ μέσα στο «{title}»",
    clickBare: "Κλικ",
    clickTaskbar: "Κλικ στο «{name}» στη γραμμή εργασιών",
    rightClick: "Δεξί κλικ στο «{name}»",
    rightClickIn: "Δεξί κλικ μέσα στο «{title}»",
    rightClickBare: "Δεξί κλικ",
    selectRange: "Επιλέξτε «{range}»",
    typeValueInField: "Πληκτρολογήστε «{value}» στο πεδίο «{field}»",
    typeInField: "Πληκτρολογήστε στο πεδίο «{field}»",
    chooseValueIn: "Επιλέξτε «{value}» στο «{field}»",
    chooseIn: "Επιλέξτε στο «{field}»",
    typeValue: "Πληκτρολογήστε «{value}»",
    type: "Πληκτρολογήστε",
    typeValueInCell: "Πληκτρολογήστε «{value}» στο κελί {cell}",
    typeInCell: "Πληκτρολογήστε στο κελί {cell}",
    press: "Πατήστε «{keys}»",
    goTo: "Μεταβείτε στο «{site}»",
    open: "Ανοίξτε το «{app}»",
    runIn: "Εκτελέστε σε {where}",
    runInTerminal: "Εκτελέστε στο τερματικό",
    formulaInCell: "Πληκτρολογήστε τον τύπο στο κελί {cell}",
    formulaInSelected: "Πληκτρολογήστε τον τύπο στο επιλεγμένο κελί",
    code: "Πληκτρολογήστε αυτόν τον κώδικα",
    missed: { one: "{count} κλικ χάθηκε εδώ", other: "{count} κλικ χάθηκαν εδώ" },
    touch: {
      one: "Η αφή ή η γραφίδα ίσως δεν καταγράφηκε ({count} αναφορά)",
      other: "Η αφή ή η γραφίδα ίσως δεν καταγράφηκε ({count} αναφορές)",
    },
    captureNow: "Αποτυπώστε αυτήν την οθόνη",
  },
  plain: {
    click: {
      button: "Επιλέξτε το κουμπί «{name}»",
      link: "Επιλέξτε τον σύνδεσμο «{name}»",
      menuItem: "Επιλέξτε «{name}» στο μενού",
      tab: "Επιλέξτε την καρτέλα «{name}»",
      field: "Επιλέξτε το πλαίσιο «{name}»",
      checkbox: "Επιλέξτε το πλαίσιο ελέγχου «{name}»",
      radio: "Διαλέξτε «{name}»",
      dropdown: "Ανοίξτε τη λίστα «{name}»",
      switch: "Επιλέξτε τον διακόπτη «{name}»",
      picture: "Επιλέξτε την εικόνα «{name}»",
      other: "Επιλέξτε «{name}»",
    },
    clickIn: "Επιλέξτε μέσα στο παράθυρο «{title}»",
    clickBare: "Επιλέξτε εδώ",
    clickTaskbar: "Επιλέξτε «{name}» στη γραμμή εργασιών",
    rightClick: "Κάντε δεξί κλικ στο «{name}»",
    rightClickIn: "Κάντε δεξί κλικ μέσα στο παράθυρο «{title}»",
    rightClickBare: "Κάντε δεξί κλικ εδώ",
    selectRange: "Επιλέξτε τα κελιά {range}",
    typeValueInField: "Γράψτε «{value}» στο πλαίσιο «{field}»",
    typeInField: "Συμπληρώστε το πλαίσιο «{field}»",
    chooseValueIn: "Επιλέξτε «{value}» από τη λίστα «{field}»",
    chooseIn: "Επιλέξτε από τη λίστα «{field}»",
    typeValue: "Γράψτε «{value}»",
    type: "Γράψτε το κείμενο",
    typeValueInCell: "Γράψτε «{value}» στο κελί {cell}",
    typeInCell: "Συμπληρώστε το κελί {cell}",
    press: "Πατήστε {keys}",
    goTo: "Μεταβείτε στη διεύθυνση {site}",
    open: "Ανοίξτε την εφαρμογή {app}",
    runIn: "Εκτελέστε την εντολή σε {where}",
    runInTerminal: "Εκτελέστε την εντολή στο τερματικό",
    formulaInCell: "Γράψτε αυτόν τον τύπο στο κελί {cell}",
    formulaInSelected: "Γράψτε αυτόν τον τύπο στο επιλεγμένο κελί",
    code: "Γράψτε αυτόν τον κώδικα",
    missed: { one: "Χάθηκε {count} κλικ εδώ", other: "Χάθηκαν {count} κλικ εδώ" },
    touch: {
      one: "Ίσως λείπει εδώ χρήση αφής ή γραφίδας ({count} αναφορά)",
      other: "Ίσως λείπει εδώ χρήση αφής ή γραφίδας ({count} αναφορές)",
    },
    captureNow: "Δείτε αυτήν την οθόνη",
  },
  formal: {
    click: {
      button: "Κάντε κλικ στο κουμπί «{name}».",
      link: "Κάντε κλικ στον σύνδεσμο «{name}».",
      menuItem: "Κάντε κλικ στην επιλογή «{name}» του μενού.",
      tab: "Κάντε κλικ στην καρτέλα «{name}».",
      field: "Κάντε κλικ στο πεδίο «{name}».",
      checkbox: "Επιλέξτε το πλαίσιο ελέγχου «{name}».",
      radio: "Ενεργοποιήστε την επιλογή «{name}».",
      dropdown: "Κάντε κλικ στην αναπτυσσόμενη λίστα «{name}».",
      switch: "Κάντε κλικ στον διακόπτη «{name}».",
      picture: "Κάντε κλικ στην εικόνα «{name}».",
      other: "Κάντε κλικ στο στοιχείο «{name}».",
    },
    clickIn: "Κάντε κλικ μέσα στο παράθυρο «{title}».",
    clickBare: "Κάντε κλικ.",
    clickTaskbar: "Κάντε κλικ στο στοιχείο «{name}» στη γραμμή εργασιών.",
    rightClick: "Κάντε δεξί κλικ στο στοιχείο «{name}».",
    rightClickIn: "Κάντε δεξί κλικ μέσα στο παράθυρο «{title}».",
    rightClickBare: "Κάντε δεξί κλικ.",
    selectRange: "Επιλέξτε τα κελιά {range}.",
    typeValueInField: "Στο πεδίο «{field}», πληκτρολογήστε «{value}».",
    typeInField: "Συμπληρώστε το πεδίο «{field}».",
    chooseValueIn: "Στη λίστα «{field}», επιλέξτε «{value}».",
    chooseIn: "Επιλέξτε μια επιλογή στη λίστα «{field}».",
    typeValue: "Πληκτρολογήστε «{value}».",
    type: "Πληκτρολογήστε το κείμενο.",
    typeValueInCell: "Στο κελί {cell}, πληκτρολογήστε «{value}».",
    typeInCell: "Συμπληρώστε το κελί {cell}.",
    press: "Πατήστε {keys}.",
    goTo: "Μεταβείτε στη διεύθυνση {site}.",
    open: "Ανοίξτε την εφαρμογή {app}.",
    runIn: "Εκτελέστε την παρακάτω εντολή σε {where}.",
    runInTerminal: "Εκτελέστε την παρακάτω εντολή στο τερματικό.",
    formulaInCell: "Στο κελί {cell}, πληκτρολογήστε τον παρακάτω τύπο.",
    formulaInSelected: "Στο επιλεγμένο κελί, πληκτρολογήστε τον παρακάτω τύπο.",
    code: "Πληκτρολογήστε τον παρακάτω κώδικα.",
    missed: {
      one: "{count} κλικ δεν καταγράφηκε εδώ.",
      other: "{count} κλικ δεν καταγράφηκαν εδώ.",
    },
    touch: {
      one: "Η είσοδος μέσω αφής ή γραφίδας ενδέχεται να μην έχει καταγραφεί εδώ ({count} αναφορά).",
      other:
        "Η είσοδος μέσω αφής ή γραφίδας ενδέχεται να μην έχει καταγραφεί εδώ ({count} αναφορές).",
    },
    captureNow: "Εξετάστε αυτήν την οθόνη.",
  },
  terminals: { powershell: "PowerShell", cmd: "Γραμμή εντολών", bash: "Bash" },
};
