import type { LanguagePhrases } from "../phrase.ts";

/**
 * English. The casual tone is the wording Steps has always written, word for word
 * (wording.test.ts holds it to that); plain language follows GOV.UK's style ("Select", everyday
 * names for things, no quotation marks round keys and web addresses); formal writes full
 * sentences in the style of Microsoft's procedure documentation.
 */
export const en: LanguagePhrases = {
  casual: {
    click: {
      // Only a box named by its label says "field"; one with its own accessible name, or a
      // multi-line box, is called by its name alone, as Steps always has.
      field: 'Click "{name}" field',
      namedField: 'Click "{name}"',
      textArea: 'Click "{name}"',
      other: 'Click "{name}"',
    },
    clickIn: 'Click in "{title}"',
    clickBare: "Click",
    clickTaskbar: 'Click "{name}" on the taskbar',
    rightClick: 'Right-click "{name}"',
    rightClickIn: 'Right-click in "{title}"',
    rightClickBare: "Right-click",
    selectRange: 'Select "{range}"',
    fillDown: 'Fill "{from}" down to "{to}"',
    fillTo: 'Fill "{from}" to "{to}"',
    fillColumn: 'Fill "{from}" down the column',
    typeValueInField: 'Type "{value}" in "{field}" field',
    typeInField: 'Type in "{field}" field',
    chooseValueIn: 'Choose "{value}" in "{field}"',
    chooseIn: 'Choose in "{field}"',
    typeValue: 'Type "{value}"',
    type: "Type",
    typeValueInCell: 'Type "{value}" in cell {cell}',
    typeInCell: "Type in cell {cell}",
    press: 'Press "{keys}"',
    pressNamed: 'Press "{keys}" ({name})',
    goTo: 'Go to "{site}"',
    open: 'Open "{app}"',
    runIn: "Run in {where}",
    runInTerminal: "Run in the terminal",
    formulaInCell: "Type the formula in cell {cell}",
    formulaInSelected: "Type the formula in the selected cell",
    code: "Type this code",
    missed: { one: "{count} click missed here", other: "{count} clicks missed here" },
    touch: {
      one: "Touch or pen activity may not have been recorded ({count} report)",
      other: "Touch or pen activity may not have been recorded ({count} reports)",
    },
    captureNow: "Capture this screen",
  },
  plain: {
    click: {
      button: 'Select the "{name}" button',
      link: 'Select the "{name}" link',
      menuItem: 'Select "{name}" in the menu',
      tab: 'Select the "{name}" tab',
      field: 'Select the "{name}" box',
      checkbox: 'Select the "{name}" tick box',
      radio: 'Choose "{name}"',
      dropdown: 'Open the "{name}" list',
      switch: 'Select the "{name}" switch',
      picture: 'Select the "{name}" picture',
      other: 'Select "{name}"',
    },
    clickIn: 'Select inside the "{title}" window',
    clickBare: "Select here",
    clickTaskbar: 'Select "{name}" on the taskbar',
    rightClick: 'Right-click "{name}"',
    rightClickIn: 'Right-click inside the "{title}" window',
    rightClickBare: "Right-click here",
    selectRange: "Select cells {range}",
    fillDown: "Fill cell {from} down to cell {to}",
    fillTo: "Fill cell {from} to cell {to}",
    fillColumn: "Fill cell {from} down the column",
    typeValueInField: 'Enter "{value}" in the "{field}" box',
    typeInField: 'Fill in the "{field}" box',
    chooseValueIn: 'Choose "{value}" from the "{field}" list',
    chooseIn: 'Choose from the "{field}" list',
    typeValue: 'Enter "{value}"',
    type: "Enter the text",
    typeValueInCell: 'Enter "{value}" in cell {cell}',
    typeInCell: "Fill in cell {cell}",
    press: "Press {keys}",
    pressNamed: "Press {keys} ({name})",
    goTo: "Go to {site}",
    open: "Open {app}",
    runIn: "Run this in {where}",
    runInTerminal: "Run this in the terminal",
    formulaInCell: "Enter this formula in cell {cell}",
    formulaInSelected: "Enter this formula in the selected cell",
    code: "Type this code",
    missed: {
      one: "{count} click was missed here",
      other: "{count} clicks were missed here",
    },
    touch: {
      one: "Touch or pen use may be missing here ({count} report)",
      other: "Touch or pen use may be missing here ({count} reports)",
    },
    captureNow: "Look at this screen",
  },
  formal: {
    click: {
      button: 'Click the "{name}" button.',
      link: 'Click the "{name}" link.',
      menuItem: 'Click "{name}" on the menu.',
      tab: 'Click the "{name}" tab.',
      field: 'Click in the "{name}" field.',
      checkbox: 'Select the "{name}" check box.',
      radio: 'Select the "{name}" option.',
      dropdown: 'Click the "{name}" drop-down list.',
      switch: 'Click the "{name}" switch.',
      picture: 'Click the "{name}" image.',
      other: 'Click "{name}".',
    },
    clickIn: 'Click inside the "{title}" window.',
    clickBare: "Click.",
    clickTaskbar: 'Click "{name}" on the taskbar.',
    rightClick: 'Right-click "{name}".',
    rightClickIn: 'Right-click inside the "{title}" window.',
    rightClickBare: "Right-click.",
    selectRange: "Select cells {range}.",
    fillDown: "Fill cell {from} down to cell {to}.",
    fillTo: "Fill cell {from} to cell {to}.",
    fillColumn: "Fill cell {from} down the column.",
    typeValueInField: 'In the "{field}" field, type "{value}".',
    typeInField: 'Complete the "{field}" field.',
    chooseValueIn: 'In the "{field}" list, select "{value}".',
    chooseIn: 'Select an option in the "{field}" list.',
    typeValue: 'Type "{value}".',
    type: "Type the text.",
    typeValueInCell: 'In cell {cell}, type "{value}".',
    typeInCell: "Complete cell {cell}.",
    press: "Press {keys}.",
    pressNamed: "Press {keys} ({name}).",
    goTo: "Navigate to {site}.",
    open: "Open {app}.",
    runIn: "Run the following command in {where}.",
    runInTerminal: "Run the following command in the terminal.",
    formulaInCell: "In cell {cell}, type the following formula.",
    formulaInSelected: "In the selected cell, type the following formula.",
    code: "Type the following code.",
    missed: {
      one: "{count} click was not recorded here.",
      other: "{count} clicks were not recorded here.",
    },
    touch: {
      one: "Touch or pen input may not have been recorded here ({count} report).",
      other: "Touch or pen input may not have been recorded here ({count} reports).",
    },
    captureNow: "Review this screen.",
  },
  terminals: { powershell: "PowerShell", cmd: "Command Prompt", bash: "Bash" },
  shortcuts: {
    selectAll: "Select all",
    copy: "Copy",
    cut: "Cut",
    paste: "Paste",
    save: "Save",
    print: "Print",
    find: "Find",
    close: "Close",
    taskManager: "Task Manager",
    showDesktop: "Show desktop",
    fileExplorer: "File Explorer",
    settings: "Settings",
    lock: "Lock",
    run: "Run",
    clipboardHistory: "Clipboard history",
    snippingTool: "Snipping Tool",
  },
};
