import type { LanguagePhrases } from "../phrase.ts";

/**
 * Español: comillas “…” as Microsoft's Spanish documentation uses; casual and plain speak to the
 * reader as "tú" (the app's own form), casual in short imperatives ("Haz clic en “Guardar”") and
 * plain with the neutral "Selecciona"; formal writes full sentences with "usted", as Microsoft's
 * Spanish procedure documentation does.
 */
export const es: LanguagePhrases = {
  casual: {
    click: {
      field: "Haz clic en el campo “{name}”",
      namedField: "Haz clic en “{name}”",
      textArea: "Haz clic en “{name}”",
      other: "Haz clic en “{name}”",
    },
    clickIn: "Haz clic en “{title}”",
    clickBare: "Haz clic",
    clickTaskbar: "Haz clic en “{name}” en la barra de tareas",
    rightClick: "Haz clic con el botón derecho en “{name}”",
    rightClickIn: "Haz clic con el botón derecho en “{title}”",
    rightClickBare: "Haz clic con el botón derecho",
    selectRange: "Selecciona “{range}”",
    typeValueInField: "Escribe “{value}” en el campo “{field}”",
    typeInField: "Escribe en el campo “{field}”",
    chooseValueIn: "Elige “{value}” en “{field}”",
    chooseIn: "Elige en “{field}”",
    typeValue: "Escribe “{value}”",
    type: "Escribe",
    typeValueInCell: "Escribe “{value}” en la celda {cell}",
    typeInCell: "Escribe en la celda {cell}",
    press: "Pulsa “{keys}”",
    goTo: "Ve a “{site}”",
    open: "Abre “{app}”",
    runIn: "Ejecuta en {where}",
    runInTerminal: "Ejecuta en el terminal",
    formulaInCell: "Escribe la fórmula en la celda {cell}",
    formulaInSelected: "Escribe la fórmula en la celda seleccionada",
    code: "Escribe este código",
    missed: {
      one: "{count} clic perdido aquí",
      many: "{count} clics perdidos aquí",
      other: "{count} clics perdidos aquí",
    },
    touch: {
      one: "Puede que no se haya grabado la actividad táctil o del lápiz ({count} aviso)",
      many: "Puede que no se haya grabado la actividad táctil o del lápiz ({count} avisos)",
      other: "Puede que no se haya grabado la actividad táctil o del lápiz ({count} avisos)",
    },
    captureNow: "Captura esta pantalla",
  },
  plain: {
    click: {
      button: "Selecciona el botón “{name}”",
      link: "Selecciona el vínculo “{name}”",
      menuItem: "Selecciona “{name}” en el menú",
      tab: "Selecciona la pestaña “{name}”",
      field: "Selecciona el cuadro “{name}”",
      checkbox: "Selecciona la casilla “{name}”",
      radio: "Elige “{name}”",
      dropdown: "Abre la lista “{name}”",
      switch: "Selecciona el interruptor “{name}”",
      picture: "Selecciona la imagen “{name}”",
      other: "Selecciona “{name}”",
    },
    clickIn: "Selecciona dentro de la ventana “{title}”",
    clickBare: "Selecciona aquí",
    clickTaskbar: "Selecciona “{name}” en la barra de tareas",
    rightClick: "Haz clic con el botón derecho en “{name}”",
    rightClickIn: "Haz clic con el botón derecho dentro de la ventana “{title}”",
    rightClickBare: "Haz clic con el botón derecho aquí",
    selectRange: "Selecciona las celdas {range}",
    typeValueInField: "Escribe “{value}” en el cuadro “{field}”",
    typeInField: "Rellena el cuadro “{field}”",
    chooseValueIn: "Elige “{value}” en la lista “{field}”",
    chooseIn: "Elige en la lista “{field}”",
    typeValue: "Escribe “{value}”",
    type: "Escribe el texto",
    typeValueInCell: "Escribe “{value}” en la celda {cell}",
    typeInCell: "Rellena la celda {cell}",
    press: "Pulsa {keys}",
    goTo: "Ve a {site}",
    open: "Abre {app}",
    runIn: "Ejecuta esto en {where}",
    runInTerminal: "Ejecuta esto en el terminal",
    formulaInCell: "Escribe esta fórmula en la celda {cell}",
    formulaInSelected: "Escribe esta fórmula en la celda seleccionada",
    code: "Escribe este código",
    missed: {
      one: "Aquí se perdió {count} clic",
      many: "Aquí se perdieron {count} clics",
      other: "Aquí se perdieron {count} clics",
    },
    touch: {
      one: "Puede que aquí falte el uso táctil o del lápiz ({count} aviso)",
      many: "Puede que aquí falte el uso táctil o del lápiz ({count} avisos)",
      other: "Puede que aquí falte el uso táctil o del lápiz ({count} avisos)",
    },
    captureNow: "Mira esta pantalla",
  },
  formal: {
    click: {
      button: "Haga clic en el botón “{name}”.",
      link: "Haga clic en el vínculo “{name}”.",
      menuItem: "Haga clic en “{name}” en el menú.",
      tab: "Haga clic en la pestaña “{name}”.",
      field: "Haga clic en el campo “{name}”.",
      checkbox: "Active la casilla “{name}”.",
      radio: "Seleccione la opción “{name}”.",
      dropdown: "Haga clic en la lista desplegable “{name}”.",
      switch: "Haga clic en el modificador “{name}”.",
      picture: "Haga clic en la imagen “{name}”.",
      other: "Haga clic en “{name}”.",
    },
    clickIn: "Haga clic en la ventana “{title}”.",
    clickBare: "Haga clic.",
    clickTaskbar: "Haga clic en “{name}” en la barra de tareas.",
    rightClick: "Haga clic con el botón derecho en “{name}”.",
    rightClickIn: "Haga clic con el botón derecho dentro de la ventana “{title}”.",
    rightClickBare: "Haga clic con el botón derecho.",
    selectRange: "Seleccione las celdas {range}.",
    typeValueInField: "En el campo “{field}”, escriba “{value}”.",
    typeInField: "Complete el campo “{field}”.",
    chooseValueIn: "En la lista “{field}”, seleccione “{value}”.",
    chooseIn: "En la lista “{field}”, seleccione una opción.",
    typeValue: "Escriba “{value}”.",
    type: "Escriba el texto.",
    typeValueInCell: "En la celda {cell}, escriba “{value}”.",
    typeInCell: "Complete la celda {cell}.",
    press: "Presione {keys}.",
    goTo: "Vaya a {site}.",
    open: "Abra {app}.",
    runIn: "Ejecute el siguiente comando en una ventana de {where}.",
    runInTerminal: "Ejecute el siguiente comando en el terminal.",
    formulaInCell: "En la celda {cell}, escriba la siguiente fórmula.",
    formulaInSelected: "En la celda seleccionada, escriba la siguiente fórmula.",
    code: "Escriba el siguiente código.",
    missed: {
      one: "Aquí no se grabó {count} clic.",
      many: "Aquí no se grabaron {count} clics.",
      other: "Aquí no se grabaron {count} clics.",
    },
    touch: {
      one: "Es posible que aquí no se haya grabado la entrada táctil o con lápiz ({count} aviso).",
      many: "Es posible que aquí no se haya grabado la entrada táctil o con lápiz ({count} avisos).",
      other:
        "Es posible que aquí no se haya grabado la entrada táctil o con lápiz ({count} avisos).",
    },
    captureNow: "Revise esta pantalla.",
  },
  terminals: { powershell: "PowerShell", cmd: "Símbolo del sistema", bash: "Bash" },
};
