import type { LanguagePhrases } from "../phrase.ts";

/**
 * Eesti: tavalised alamkomad „…“ nagu Microsofti eestikeelses dokumentatsioonis. Vaba toon kasutab
 * lühikest käskivat ainsuse 2. pööret (Klõpsa …), selge keel ja ametlik toon pöörduvad teietamisega
 * (Valige …, Klõpsake …), nagu Windowsi eestikeelne liides.
 */
export const et: LanguagePhrases = {
  casual: {
    click: {
      field: "Klõpsa välja „{name}“",
      namedField: "Klõpsa „{name}“",
      textArea: "Klõpsa „{name}“",
      other: "Klõpsa „{name}“",
    },
    clickIn: "Klõpsa aknas „{title}“",
    clickBare: "Klõpsa",
    clickTaskbar: "Klõpsa tegumiribal „{name}“",
    rightClick: "Paremklõpsa „{name}“",
    rightClickIn: "Paremklõpsa aknas „{title}“",
    rightClickBare: "Paremklõpsa",
    selectRange: "Vali „{range}“",
    typeValueInField: "Sisesta „{value}“ väljale „{field}“",
    typeInField: "Sisesta väljale „{field}“ tekst",
    chooseValueIn: "Vali loendis „{field}“ „{value}“",
    chooseIn: "Vali loendis „{field}“",
    typeValue: "Sisesta „{value}“",
    type: "Sisesta tekst",
    typeValueInCell: "Sisesta „{value}“ lahtrisse {cell}",
    typeInCell: "Sisesta lahtrisse {cell} tekst",
    press: "Vajuta „{keys}“",
    goTo: "Mine saidile „{site}“",
    open: "Ava „{app}“",
    runIn: "Käivita siin: {where}",
    runInTerminal: "Käivita terminalis",
    formulaInCell: "Sisesta valem lahtrisse {cell}",
    formulaInSelected: "Sisesta valem valitud lahtrisse",
    code: "Sisesta see kood",
    missed: { one: "{count} klõps jäi siin vahele", other: "{count} klõpsu jäi siin vahele" },
    touch: {
      one: "Puute- või pliiatsikasutus võib olla lindistamata ({count} teade)",
      other: "Puute- või pliiatsikasutus võib olla lindistamata ({count} teadet)",
    },
    captureNow: "Jäädvusta see ekraan",
  },
  plain: {
    click: {
      button: "Valige nupp „{name}“",
      link: "Valige link „{name}“",
      menuItem: "Valige menüüst „{name}“",
      tab: "Valige vahekaart „{name}“",
      field: "Valige väli „{name}“",
      checkbox: "Märkige ruut „{name}“",
      radio: "Valige „{name}“",
      dropdown: "Avage loend „{name}“",
      switch: "Valige lüliti „{name}“",
      picture: "Valige pilt „{name}“",
      other: "Valige „{name}“",
    },
    clickIn: "Valige koht aknas „{title}“",
    clickBare: "Valige siin",
    clickTaskbar: "Valige tegumiribal „{name}“",
    rightClick: "Paremklõpsake „{name}“",
    rightClickIn: "Paremklõpsake akna „{title}“ sees",
    rightClickBare: "Paremklõpsake siin",
    selectRange: "Valige lahtrid {range}",
    typeValueInField: "Sisestage väljale „{field}“ {value}",
    typeInField: "Täitke väli „{field}“",
    chooseValueIn: "Valige loendist „{field}“ „{value}“",
    chooseIn: "Valige loendist „{field}“",
    typeValue: "Sisestage {value}",
    type: "Sisestage tekst",
    typeValueInCell: "Sisestage lahtrisse {cell} {value}",
    typeInCell: "Täitke lahter {cell}",
    press: "Vajutage {keys}",
    goTo: "Minge saidile {site}",
    open: "Avage {app}",
    runIn: "Käivitage see siin: {where}",
    runInTerminal: "Käivitage see terminalis",
    formulaInCell: "Sisestage see valem lahtrisse {cell}",
    formulaInSelected: "Sisestage see valem valitud lahtrisse",
    code: "Sisestage see kood",
    missed: {
      one: "Siin jäi {count} klõps vahele",
      other: "Siin jäi {count} klõpsu vahele",
    },
    touch: {
      one: "Puute- või pliiatsikasutus võib siin puududa ({count} teade)",
      other: "Puute- või pliiatsikasutus võib siin puududa ({count} teadet)",
    },
    captureNow: "Vaadake seda ekraani",
  },
  formal: {
    click: {
      button: "Klõpsake nuppu „{name}“.",
      link: "Klõpsake linki „{name}“.",
      menuItem: "Klõpsake menüüs käsku „{name}“.",
      tab: "Klõpsake vahekaarti „{name}“.",
      field: "Klõpsake väljal „{name}“.",
      checkbox: "Märkige ruut „{name}“.",
      radio: "Valige suvand „{name}“.",
      dropdown: "Klõpsake ripploendit „{name}“.",
      switch: "Klõpsake lülitit „{name}“.",
      picture: "Klõpsake pilti „{name}“.",
      other: "Klõpsake „{name}“.",
    },
    clickIn: "Klõpsake aknas „{title}“.",
    clickBare: "Klõpsake.",
    clickTaskbar: "Klõpsake tegumiribal „{name}“.",
    rightClick: "Paremklõpsake „{name}“.",
    rightClickIn: "Paremklõpsake akna „{title}“ sees.",
    rightClickBare: "Paremklõpsake.",
    selectRange: "Valige lahtrid {range}.",
    typeValueInField: "Tippige väljale „{field}“ „{value}“.",
    typeInField: "Täitke väli „{field}“.",
    chooseValueIn: "Valige loendis „{field}“ „{value}“.",
    chooseIn: "Valige loendis „{field}“ suvand.",
    typeValue: "Tippige „{value}“.",
    type: "Tippige tekst.",
    typeValueInCell: "Tippige lahtrisse {cell} „{value}“.",
    typeInCell: "Täitke lahter {cell}.",
    press: "Vajutage {keys}.",
    goTo: "Avage sait {site}.",
    open: "Avage {app}.",
    runIn: "Käivitage järgmine käsk siin: {where}.",
    runInTerminal: "Käivitage järgmine käsk terminalis.",
    formulaInCell: "Tippige lahtrisse {cell} järgmine valem.",
    formulaInSelected: "Tippige valitud lahtrisse järgmine valem.",
    code: "Tippige järgmine kood.",
    missed: {
      one: "Siin jäi {count} klõps lindistamata.",
      other: "Siin jäi {count} klõpsu lindistamata.",
    },
    touch: {
      one: "Puute- või pliiatsisisendit ei pruugita siin olla lindistatud ({count} teade).",
      other: "Puute- või pliiatsisisendit ei pruugita siin olla lindistatud ({count} teadet).",
    },
    captureNow: "Vaadake see ekraan üle.",
  },
  terminals: { powershell: "PowerShell", cmd: "Käsuviip", bash: "Bash" },
};
