import type { LanguagePhrases } from "../phrase.ts";

/**
 * Suomi: names in Finnish quotation marks (”Tallenna”), the user addressed in the imperative
 * singular as Microsoft's Finnish style does; casual is the short "Napsauta ”…”", plain uses the
 * neutral "Valitse", formal follows Microsoft's procedure documentation (”…”-painiketta.).
 */
export const fi: LanguagePhrases = {
  casual: {
    click: {
      field: "Napsauta kenttää ”{name}”",
      namedField: "Napsauta ”{name}”",
      textArea: "Napsauta ”{name}”",
      other: "Napsauta ”{name}”",
    },
    clickIn: "Napsauta ikkunassa ”{title}”",
    clickBare: "Napsauta",
    clickTaskbar: "Napsauta tehtäväpalkissa ”{name}”",
    typeValueInField: "Kirjoita ”{value}” kenttään ”{field}”",
    typeInField: "Kirjoita kenttään ”{field}”",
    chooseValueIn: "Valitse ”{value}” kohdasta ”{field}”",
    chooseIn: "Valitse kohdasta ”{field}”",
    typeValue: "Kirjoita ”{value}”",
    type: "Kirjoita",
    typeValueInCell: "Kirjoita ”{value}” soluun {cell}",
    typeInCell: "Kirjoita soluun {cell}",
    press: "Paina ”{keys}”",
    goTo: "Siirry osoitteeseen ”{site}”",
    open: "Avaa ”{app}”",
    runIn: "Suorita sovelluksessa {where}",
    runInTerminal: "Suorita päätteessä",
    formulaInCell: "Kirjoita kaava soluun {cell}",
    formulaInSelected: "Kirjoita kaava valittuun soluun",
    code: "Kirjoita tämä koodi",
    missed: {
      one: "{count} napsautus ohitettu tässä",
      other: "{count} napsautusta ohitettu tässä",
    },
    touch: {
      one: "Kosketus- tai kynätoimintoja ei ehkä nauhoitettu ({count} ilmoitus)",
      other: "Kosketus- tai kynätoimintoja ei ehkä nauhoitettu ({count} ilmoitusta)",
    },
    captureNow: "Kaappaa tämä näyttö",
  },
  plain: {
    click: {
      button: "Valitse painike ”{name}”",
      link: "Valitse linkki ”{name}”",
      menuItem: "Valitse valikosta ”{name}”",
      tab: "Valitse välilehti ”{name}”",
      field: "Valitse kenttä ”{name}”",
      checkbox: "Valitse valintaruutu ”{name}”",
      radio: "Valitse ”{name}”",
      dropdown: "Avaa luettelo ”{name}”",
      switch: "Valitse kytkin ”{name}”",
      picture: "Valitse kuva ”{name}”",
      other: "Valitse ”{name}”",
    },
    clickIn: "Valitse kohta ikkunassa ”{title}”",
    clickBare: "Valitse tämä kohta",
    clickTaskbar: "Valitse tehtäväpalkista ”{name}”",
    typeValueInField: "Kirjoita ”{value}” kenttään ”{field}”",
    typeInField: "Täytä kenttä ”{field}”",
    chooseValueIn: "Valitse ”{value}” luettelosta ”{field}”",
    chooseIn: "Valitse luettelosta ”{field}”",
    typeValue: "Kirjoita ”{value}”",
    type: "Kirjoita teksti",
    typeValueInCell: "Kirjoita ”{value}” soluun {cell}",
    typeInCell: "Täytä solu {cell}",
    press: "Paina {keys}",
    goTo: "Siirry osoitteeseen {site}",
    open: "Avaa {app}",
    runIn: "Suorita tämä sovelluksessa {where}",
    runInTerminal: "Suorita tämä päätteessä",
    formulaInCell: "Kirjoita tämä kaava soluun {cell}",
    formulaInSelected: "Kirjoita tämä kaava valittuun soluun",
    code: "Kirjoita tämä koodi",
    missed: {
      one: "{count} napsautus jäi tallentamatta tässä",
      other: "{count} napsautusta jäi tallentamatta tässä",
    },
    touch: {
      one: "Kosketus- tai kynäkäyttöä voi puuttua tästä ({count} ilmoitus)",
      other: "Kosketus- tai kynäkäyttöä voi puuttua tästä ({count} ilmoitusta)",
    },
    captureNow: "Katso tätä näyttöä",
  },
  formal: {
    click: {
      button: "Napsauta ”{name}”-painiketta.",
      link: "Napsauta ”{name}”-linkkiä.",
      menuItem: "Valitse valikosta ”{name}”.",
      tab: "Napsauta ”{name}”-välilehteä.",
      field: "Napsauta ”{name}”-kenttää.",
      checkbox: "Valitse ”{name}”-valintaruutu.",
      radio: "Valitse ”{name}”-vaihtoehto.",
      dropdown: "Napsauta ”{name}”-avattavaa luetteloa.",
      switch: "Napsauta ”{name}”-vaihtokytkintä.",
      picture: "Napsauta ”{name}”-kuvaa.",
      other: "Napsauta ”{name}”.",
    },
    clickIn: "Napsauta ikkunassa ”{title}”.",
    clickBare: "Napsauta.",
    clickTaskbar: "Napsauta tehtäväpalkissa ”{name}”.",
    typeValueInField: "Kirjoita ”{field}”-kenttään ”{value}”.",
    typeInField: "Täytä ”{field}”-kenttä.",
    chooseValueIn: "Valitse ”{value}” luettelosta ”{field}”.",
    chooseIn: "Valitse luettelosta ”{field}” jokin vaihtoehto.",
    typeValue: "Kirjoita ”{value}”.",
    type: "Kirjoita teksti.",
    typeValueInCell: "Kirjoita soluun {cell} ”{value}”.",
    typeInCell: "Täytä solu {cell}.",
    press: "Paina {keys}.",
    goTo: "Siirry osoitteeseen {site}.",
    open: "Avaa {app}.",
    runIn: "Suorita seuraava komento sovelluksessa {where}.",
    runInTerminal: "Suorita seuraava komento päätteessä.",
    formulaInCell: "Kirjoita soluun {cell} seuraava kaava.",
    formulaInSelected: "Kirjoita valittuun soluun seuraava kaava.",
    code: "Kirjoita seuraava koodi.",
    missed: {
      one: "Tässä kohdassa jäi tallentamatta {count} napsautus.",
      other: "Tässä kohdassa jäi tallentamatta {count} napsautusta.",
    },
    touch: {
      one: "Kosketus- tai kynäsyötettä ei ehkä tallennettu tässä kohdassa ({count} ilmoitus).",
      other: "Kosketus- tai kynäsyötettä ei ehkä tallennettu tässä kohdassa ({count} ilmoitusta).",
    },
    captureNow: "Tarkista tämä näyttö.",
  },
  terminals: { powershell: "PowerShell", cmd: "Komentokehote", bash: "Bash" },
};
