import type { LanguagePhrases } from "../phrase.ts";

/**
 * Français: « … » with no-break spaces inside, as Microsoft's French documentation quotes; the
 * casual tone uses the infinitive ("Cliquer sur « Enregistrer »"), plain language addresses the
 * reader as "vous" with the neutral "Sélectionnez", and formal writes full "vous" sentences in the
 * style of Microsoft's procedures. Keys and web addresses aren't quoted outside the casual tone.
 */
export const fr: LanguagePhrases = {
  casual: {
    click: {
      field: "Cliquer sur le champ « {name} »",
      namedField: "Cliquer sur « {name} »",
      textArea: "Cliquer sur « {name} »",
      other: "Cliquer sur « {name} »",
    },
    clickIn: "Cliquer dans « {title} »",
    clickBare: "Cliquer",
    clickTaskbar: "Cliquer sur « {name} » dans la barre des tâches",
    rightClick: "Cliquer avec le bouton droit sur « {name} »",
    rightClickIn: "Cliquer avec le bouton droit dans « {title} »",
    rightClickBare: "Cliquer avec le bouton droit",
    selectRange: "Sélectionner « {range} »",
    typeValueInField: "Taper « {value} » dans le champ « {field} »",
    typeInField: "Taper dans le champ « {field} »",
    chooseValueIn: "Choisir « {value} » dans « {field} »",
    chooseIn: "Choisir dans « {field} »",
    typeValue: "Taper « {value} »",
    type: "Taper",
    typeValueInCell: "Taper « {value} » dans la cellule {cell}",
    typeInCell: "Taper dans la cellule {cell}",
    press: "Appuyer sur {keys}",
    pressNamed: "Appuyer sur {keys} ({name})",
    goTo: "Aller à « {site} »",
    open: "Ouvrir « {app} »",
    runIn: "Exécuter dans {where}",
    runInTerminal: "Exécuter dans le terminal",
    formulaInCell: "Taper la formule dans la cellule {cell}",
    formulaInSelected: "Taper la formule dans la cellule sélectionnée",
    code: "Taper ce code",
    missed: {
      one: "{count} clic manqué ici",
      many: "{count} clics manqués ici",
      other: "{count} clics manqués ici",
    },
    touch: {
      one: "Activité tactile ou au stylet peut-être non enregistrée ({count} signalement)",
      many: "Activité tactile ou au stylet peut-être non enregistrée ({count} signalements)",
      other: "Activité tactile ou au stylet peut-être non enregistrée ({count} signalements)",
    },
    captureNow: "Capturer cet écran",
  },
  plain: {
    click: {
      button: "Sélectionnez le bouton « {name} »",
      link: "Sélectionnez le lien « {name} »",
      menuItem: "Sélectionnez « {name} » dans le menu",
      tab: "Sélectionnez l'onglet « {name} »",
      field: "Sélectionnez la zone « {name} »",
      checkbox: "Cochez la case « {name} »",
      radio: "Choisissez « {name} »",
      dropdown: "Ouvrez la liste « {name} »",
      switch: "Sélectionnez l'interrupteur « {name} »",
      picture: "Sélectionnez l'image « {name} »",
      other: "Sélectionnez « {name} »",
    },
    clickIn: "Sélectionnez cet endroit de la fenêtre « {title} »",
    clickBare: "Sélectionnez cet endroit",
    clickTaskbar: "Sélectionnez « {name} » dans la barre des tâches",
    rightClick: "Cliquez avec le bouton droit sur « {name} »",
    rightClickIn: "Cliquez avec le bouton droit à l'intérieur de la fenêtre « {title} »",
    rightClickBare: "Cliquez ici avec le bouton droit",
    selectRange: "Sélectionnez les cellules {range}",
    typeValueInField: "Entrez « {value} » dans la zone « {field} »",
    typeInField: "Remplissez la zone « {field} »",
    chooseValueIn: "Choisissez « {value} » dans la liste « {field} »",
    chooseIn: "Choisissez dans la liste « {field} »",
    typeValue: "Entrez « {value} »",
    type: "Entrez le texte",
    typeValueInCell: "Entrez « {value} » dans la cellule {cell}",
    typeInCell: "Remplissez la cellule {cell}",
    press: "Appuyez sur {keys}",
    pressNamed: "Appuyez sur {keys} ({name})",
    goTo: "Allez sur {site}",
    open: "Ouvrez {app}",
    runIn: "Exécutez ceci dans {where}",
    runInTerminal: "Exécutez ceci dans le terminal",
    formulaInCell: "Entrez cette formule dans la cellule {cell}",
    formulaInSelected: "Entrez cette formule dans la cellule sélectionnée",
    code: "Tapez ce code",
    missed: {
      one: "{count} clic a été manqué ici",
      many: "{count} clics ont été manqués ici",
      other: "{count} clics ont été manqués ici",
    },
    touch: {
      one: "Une action tactile ou au stylet manque peut-être ici ({count} signalement)",
      many: "Des actions tactiles ou au stylet manquent peut-être ici ({count} signalements)",
      other: "Des actions tactiles ou au stylet manquent peut-être ici ({count} signalements)",
    },
    captureNow: "Regardez cet écran",
  },
  formal: {
    click: {
      button: "Cliquez sur le bouton « {name} ».",
      link: "Cliquez sur le lien « {name} ».",
      menuItem: "Dans le menu, cliquez sur « {name} ».",
      tab: "Cliquez sur l'onglet « {name} ».",
      field: "Cliquez dans le champ « {name} ».",
      checkbox: "Activez la case à cocher « {name} ».",
      radio: "Sélectionnez l'option « {name} ».",
      dropdown: "Cliquez sur la liste déroulante « {name} ».",
      switch: "Cliquez sur le bouton bascule « {name} ».",
      picture: "Cliquez sur l'image « {name} ».",
      other: "Cliquez sur « {name} ».",
    },
    clickIn: "Cliquez dans la fenêtre « {title} ».",
    clickBare: "Cliquez à cet endroit.",
    clickTaskbar: "Cliquez sur « {name} » dans la barre des tâches.",
    rightClick: "Cliquez avec le bouton droit sur « {name} ».",
    rightClickIn: "Cliquez avec le bouton droit à l'intérieur de la fenêtre « {title} ».",
    rightClickBare: "Cliquez avec le bouton droit.",
    selectRange: "Sélectionnez les cellules {range}.",
    typeValueInField: "Dans le champ « {field} », tapez « {value} ».",
    typeInField: "Renseignez le champ « {field} ».",
    chooseValueIn: "Dans la liste « {field} », sélectionnez « {value} ».",
    chooseIn: "Dans la liste « {field} », sélectionnez une option.",
    typeValue: "Tapez « {value} ».",
    type: "Tapez le texte.",
    typeValueInCell: "Dans la cellule {cell}, tapez « {value} ».",
    typeInCell: "Renseignez la cellule {cell}.",
    press: "Appuyez sur {keys}.",
    pressNamed: "Appuyez sur {keys} ({name}).",
    goTo: "Accédez à {site}.",
    open: "Ouvrez {app}.",
    runIn: "Exécutez la commande suivante dans {where}.",
    runInTerminal: "Exécutez la commande suivante dans le terminal.",
    formulaInCell: "Dans la cellule {cell}, tapez la formule suivante.",
    formulaInSelected: "Dans la cellule sélectionnée, tapez la formule suivante.",
    code: "Tapez le code suivant.",
    missed: {
      one: "{count} clic n'a pas été enregistré ici.",
      many: "{count} clics n'ont pas été enregistrés ici.",
      other: "{count} clics n'ont pas été enregistrés ici.",
    },
    touch: {
      one: "Il est possible qu'une saisie tactile ou au stylet n'ait pas été enregistrée ici ({count} signalement).",
      many: "Il est possible que des saisies tactiles ou au stylet n'aient pas été enregistrées ici ({count} signalements).",
      other:
        "Il est possible que des saisies tactiles ou au stylet n'aient pas été enregistrées ici ({count} signalements).",
    },
    captureNow: "Examinez cet écran.",
  },
  terminals: { powershell: "PowerShell", cmd: "l'Invite de commandes", bash: "Bash" },
  shortcuts: {
    selectAll: "Tout sélectionner",
    copy: "Copier",
    cut: "Couper",
    paste: "Coller",
    save: "Enregistrer",
    print: "Imprimer",
    find: "Rechercher",
    close: "Fermer",
    taskManager: "Gestionnaire des tâches",
    showDesktop: "Afficher le Bureau",
    fileExplorer: "Explorateur de fichiers",
    settings: "Paramètres",
    lock: "Verrouiller",
    run: "Exécuter",
    clipboardHistory: "Historique du Presse-papiers",
    snippingTool: "Outil Capture d'écran",
  },
};
