import type { LanguagePhrases } from "../phrase.ts";

/**
 * Gaeilge: quotation marks “…”, the singular imperative as Microsoft's Irish Windows uses it;
 * casual says "Cliceáil", plain the neutral "Roghnaigh" and everyday words, formal full sentences
 * in the style of Microsoft's Irish procedures; counted nouns take the mutation each number needs.
 */
export const ga: LanguagePhrases = {
  casual: {
    click: {
      field: "Cliceáil an réimse “{name}”",
      namedField: "Cliceáil “{name}”",
      textArea: "Cliceáil “{name}”",
      other: "Cliceáil “{name}”",
    },
    clickIn: "Cliceáil in “{title}”",
    clickBare: "Cliceáil",
    clickTaskbar: "Cliceáil “{name}” ar an tascbharra",
    typeValueInField: "Clóscríobh “{value}” sa réimse “{field}”",
    typeInField: "Clóscríobh sa réimse “{field}”",
    chooseValueIn: "Roghnaigh “{value}” i “{field}”",
    chooseIn: "Roghnaigh i “{field}”",
    typeValue: "Clóscríobh “{value}”",
    type: "Clóscríobh",
    typeValueInCell: "Clóscríobh “{value}” i gcill {cell}",
    typeInCell: "Clóscríobh i gcill {cell}",
    press: "Brúigh “{keys}”",
    goTo: "Téigh go “{site}”",
    open: "Oscail “{app}”",
    runIn: "Rith i {where}",
    runInTerminal: "Rith sa teirminéal",
    formulaInCell: "Clóscríobh an fhoirmle i gcill {cell}",
    formulaInSelected: "Clóscríobh an fhoirmle sa chill roghnaithe",
    code: "Clóscríobh an cód seo",
    missed: {
      one: "Cliceáil amháin caillte anseo",
      two: "{count} chliceáil caillte anseo",
      few: "{count} chliceáil caillte anseo",
      many: "{count} gcliceáil caillte anseo",
      other: "{count} cliceáil caillte anseo",
    },
    touch: {
      one: "Seans nár taifeadadh gníomhaíocht tadhaill nó pinn ({count} tuairisc)",
      two: "Seans nár taifeadadh gníomhaíocht tadhaill nó pinn ({count} thuairisc)",
      few: "Seans nár taifeadadh gníomhaíocht tadhaill nó pinn ({count} thuairisc)",
      many: "Seans nár taifeadadh gníomhaíocht tadhaill nó pinn ({count} dtuairisc)",
      other: "Seans nár taifeadadh gníomhaíocht tadhaill nó pinn ({count} tuairisc)",
    },
    captureNow: "Gabh an scáileán seo",
  },
  plain: {
    click: {
      button: "Roghnaigh an cnaipe “{name}”",
      link: "Roghnaigh an nasc “{name}”",
      menuItem: "Roghnaigh “{name}” sa roghchlár",
      tab: "Roghnaigh an cluaisín “{name}”",
      field: "Roghnaigh an bosca “{name}”",
      checkbox: "Roghnaigh an ticbhosca “{name}”",
      radio: "Roghnaigh “{name}”",
      dropdown: "Oscail an liosta “{name}”",
      switch: "Roghnaigh an lasc “{name}”",
      picture: "Roghnaigh an pictiúr “{name}”",
      other: "Roghnaigh “{name}”",
    },
    clickIn: "Roghnaigh áit taobh istigh den fhuinneog “{title}”",
    clickBare: "Roghnaigh anseo",
    clickTaskbar: "Roghnaigh “{name}” ar an tascbharra",
    typeValueInField: "Cuir isteach “{value}” sa bhosca “{field}”",
    typeInField: "Líon isteach an bosca “{field}”",
    chooseValueIn: "Roghnaigh “{value}” ón liosta “{field}”",
    chooseIn: "Roghnaigh ón liosta “{field}”",
    typeValue: "Cuir isteach “{value}”",
    type: "Cuir isteach an téacs",
    typeValueInCell: "Cuir isteach “{value}” i gcill {cell}",
    typeInCell: "Líon isteach cill {cell}",
    press: "Brúigh {keys}",
    goTo: "Téigh go {site}",
    open: "Oscail {app}",
    runIn: "Rith é seo i {where}",
    runInTerminal: "Rith é seo sa teirminéal",
    formulaInCell: "Cuir isteach an fhoirmle seo i gcill {cell}",
    formulaInSelected: "Cuir isteach an fhoirmle seo sa chill roghnaithe",
    code: "Clóscríobh an cód seo",
    missed: {
      one: "Cailleadh cliceáil amháin anseo",
      two: "Cailleadh {count} chliceáil anseo",
      few: "Cailleadh {count} chliceáil anseo",
      many: "Cailleadh {count} gcliceáil anseo",
      other: "Cailleadh {count} cliceáil anseo",
    },
    touch: {
      one: "D’fhéadfadh úsáid tadhaill nó pinn a bheith in easnamh anseo ({count} tuairisc)",
      two: "D’fhéadfadh úsáid tadhaill nó pinn a bheith in easnamh anseo ({count} thuairisc)",
      few: "D’fhéadfadh úsáid tadhaill nó pinn a bheith in easnamh anseo ({count} thuairisc)",
      many: "D’fhéadfadh úsáid tadhaill nó pinn a bheith in easnamh anseo ({count} dtuairisc)",
      other: "D’fhéadfadh úsáid tadhaill nó pinn a bheith in easnamh anseo ({count} tuairisc)",
    },
    captureNow: "Féach ar an scáileán seo",
  },
  formal: {
    click: {
      button: "Cliceáil an cnaipe “{name}”.",
      link: "Cliceáil an nasc “{name}”.",
      menuItem: "Cliceáil “{name}” ar an roghchlár.",
      tab: "Cliceáil an cluaisín “{name}”.",
      field: "Cliceáil sa réimse “{name}”.",
      checkbox: "Roghnaigh an ticbhosca “{name}”.",
      radio: "Roghnaigh an rogha “{name}”.",
      dropdown: "Cliceáil an liosta anuas “{name}”.",
      switch: "Cliceáil an lasc “{name}”.",
      picture: "Cliceáil an íomhá “{name}”.",
      other: "Cliceáil “{name}”.",
    },
    clickIn: "Cliceáil san fhuinneog “{title}”.",
    clickBare: "Cliceáil.",
    clickTaskbar: "Cliceáil “{name}” ar an tascbharra.",
    typeValueInField: "Sa réimse “{field}”, clóscríobh “{value}”.",
    typeInField: "Comhlánaigh an réimse “{field}”.",
    chooseValueIn: "Sa liosta “{field}”, roghnaigh “{value}”.",
    chooseIn: "Roghnaigh rogha sa liosta “{field}”.",
    typeValue: "Clóscríobh “{value}”.",
    type: "Clóscríobh an téacs.",
    typeValueInCell: "I gcill {cell}, clóscríobh “{value}”.",
    typeInCell: "Comhlánaigh cill {cell}.",
    press: "Brúigh {keys}.",
    goTo: "Téigh chuig {site}.",
    open: "Oscail {app}.",
    runIn: "Rith an t-ordú seo a leanas i {where}.",
    runInTerminal: "Rith an t-ordú seo a leanas sa teirminéal.",
    formulaInCell: "I gcill {cell}, clóscríobh an fhoirmle seo a leanas.",
    formulaInSelected: "Sa chill roghnaithe, clóscríobh an fhoirmle seo a leanas.",
    code: "Clóscríobh an cód seo a leanas.",
    missed: {
      one: "Níor taifeadadh cliceáil amháin anseo.",
      two: "Níor taifeadadh {count} chliceáil anseo.",
      few: "Níor taifeadadh {count} chliceáil anseo.",
      many: "Níor taifeadadh {count} gcliceáil anseo.",
      other: "Níor taifeadadh {count} cliceáil anseo.",
    },
    touch: {
      one: "Seans nár taifeadadh ionchur tadhaill nó pinn anseo ({count} tuairisc).",
      two: "Seans nár taifeadadh ionchur tadhaill nó pinn anseo ({count} thuairisc).",
      few: "Seans nár taifeadadh ionchur tadhaill nó pinn anseo ({count} thuairisc).",
      many: "Seans nár taifeadadh ionchur tadhaill nó pinn anseo ({count} dtuairisc).",
      other: "Seans nár taifeadadh ionchur tadhaill nó pinn anseo ({count} tuairisc).",
    },
    captureNow: "Athbhreithnigh an scáileán seo.",
  },
  terminals: { powershell: "PowerShell", cmd: "Leid Ordaithe", bash: "Bash" },
};
