import type { LanguagePhrases } from "../phrase.ts";

/**
 * Hrvatski: names in „…”, the reader addressed as „vi” as in Microsoft's Croatian (Kliknite,
 * Upišite); casual is the shortest instruction with no full stop, plain uses the neutral
 * „Odaberite” and everyday names for things, formal writes full sentences in the style of
 * Microsoft's Croatian procedure documentation.
 */
export const hr: LanguagePhrases = {
  casual: {
    click: {
      field: "Kliknite polje „{name}”",
      namedField: "Kliknite „{name}”",
      textArea: "Kliknite „{name}”",
      other: "Kliknite „{name}”",
    },
    clickIn: "Kliknite u „{title}”",
    clickBare: "Kliknite",
    clickTaskbar: "Kliknite „{name}” na programskoj traci",
    rightClick: "Desnom tipkom miša kliknite „{name}”",
    rightClickIn: "Desnom tipkom miša kliknite u „{title}”",
    rightClickBare: "Desnom tipkom miša kliknite",
    selectRange: "Odaberite „{range}”",
    fillDown: "Popunite „{from}” prema dolje do „{to}”",
    fillTo: "Popunite „{from}” do „{to}”",
    fillColumn: "Popunite „{from}” prema dolje niz stupac",
    typeValueInField: "Upišite „{value}” u polje „{field}”",
    typeInField: "Upišite u polje „{field}”",
    chooseValueIn: "Odaberite „{value}” u polju „{field}”",
    chooseIn: "Odaberite u polju „{field}”",
    typeValue: "Upišite „{value}”",
    type: "Upišite tekst",
    typeValueInCell: "Upišite „{value}” u ćeliju {cell}",
    typeInCell: "Upišite u ćeliju {cell}",
    press: "Pritisnite „{keys}”",
    pressNamed: "Pritisnite „{keys}” ({name})",
    goTo: "Idite na „{site}”",
    open: "Otvorite „{app}”",
    runIn: "Pokrenite u prozoru {where}",
    runInTerminal: "Pokrenite u terminalu",
    formulaInCell: "Upišite formulu u ćeliju {cell}",
    formulaInSelected: "Upišite formulu u odabranu ćeliju",
    code: "Upišite ovaj kôd",
    missed: {
      one: "{count} propušten klik",
      few: "{count} propuštena klika",
      other: "{count} propuštenih klikova",
    },
    touch: {
      one: "Dodir ili olovka možda nisu snimljeni ({count} izvješće)",
      few: "Dodir ili olovka možda nisu snimljeni ({count} izvješća)",
      other: "Dodir ili olovka možda nisu snimljeni ({count} izvješća)",
    },
    captureNow: "Snimite ovaj zaslon",
  },
  plain: {
    click: {
      button: "Odaberite gumb „{name}”",
      link: "Odaberite vezu „{name}”",
      menuItem: "Odaberite „{name}” na izborniku",
      tab: "Odaberite karticu „{name}”",
      field: "Odaberite polje „{name}”",
      checkbox: "Odaberite potvrdni okvir „{name}”",
      radio: "Odaberite „{name}”",
      dropdown: "Otvorite popis „{name}”",
      switch: "Odaberite prekidač „{name}”",
      picture: "Odaberite sliku „{name}”",
      other: "Odaberite „{name}”",
    },
    clickIn: "Odaberite mjesto u prozoru „{title}”",
    clickBare: "Odaberite ovdje",
    clickTaskbar: "Odaberite „{name}” na programskoj traci",
    rightClick: "Desnom tipkom miša kliknite „{name}”",
    rightClickIn: "Desnom tipkom miša kliknite unutar prozora „{title}”",
    rightClickBare: "Desnom tipkom miša kliknite ovdje",
    selectRange: "Odaberite ćelije {range}",
    fillDown: "Popunite ćeliju {from} prema dolje do ćelije {to}",
    fillTo: "Popunite ćeliju {from} do ćelije {to}",
    fillColumn: "Popunite ćeliju {from} prema dolje niz stupac",
    typeValueInField: "Unesite „{value}” u polje „{field}”",
    typeInField: "Ispunite polje „{field}”",
    chooseValueIn: "Odaberite „{value}” s popisa „{field}”",
    chooseIn: "Odaberite s popisa „{field}”",
    typeValue: "Unesite „{value}”",
    type: "Unesite tekst",
    typeValueInCell: "Unesite „{value}” u ćeliju {cell}",
    typeInCell: "Ispunite ćeliju {cell}",
    press: "Pritisnite {keys}",
    pressNamed: "Pritisnite {keys} ({name})",
    goTo: "Idite na {site}",
    open: "Otvorite {app}",
    runIn: "Pokrenite ovo u prozoru {where}",
    runInTerminal: "Pokrenite ovo u terminalu",
    formulaInCell: "Unesite ovu formulu u ćeliju {cell}",
    formulaInSelected: "Unesite ovu formulu u odabranu ćeliju",
    code: "Upišite ovaj kôd",
    missed: {
      one: "Ovdje je propušten {count} klik",
      few: "Ovdje su propuštena {count} klika",
      other: "Ovdje je propušteno {count} klikova",
    },
    touch: {
      one: "Ovdje možda nedostaje dodir ili olovka ({count} izvješće)",
      few: "Ovdje možda nedostaje dodir ili olovka ({count} izvješća)",
      other: "Ovdje možda nedostaje dodir ili olovka ({count} izvješća)",
    },
    captureNow: "Pogledajte ovaj zaslon",
  },
  formal: {
    click: {
      button: "Kliknite gumb „{name}”.",
      link: "Kliknite vezu „{name}”.",
      menuItem: "Na izborniku kliknite „{name}”.",
      tab: "Kliknite karticu „{name}”.",
      field: "Kliknite u polje „{name}”.",
      checkbox: "Potvrdite okvir „{name}”.",
      radio: "Odaberite mogućnost „{name}”.",
      dropdown: "Kliknite padajući popis „{name}”.",
      switch: "Kliknite prekidač „{name}”.",
      picture: "Kliknite sliku „{name}”.",
      other: "Kliknite „{name}”.",
    },
    clickIn: "Kliknite u prozoru „{title}”.",
    clickBare: "Kliknite.",
    clickTaskbar: "Kliknite „{name}” na programskoj traci.",
    rightClick: "Desnom tipkom miša kliknite „{name}”.",
    rightClickIn: "Desnom tipkom miša kliknite unutar prozora „{title}”.",
    rightClickBare: "Desnom tipkom miša kliknite.",
    selectRange: "Odaberite ćelije {range}.",
    fillDown: "Popunite ćeliju {from} prema dolje do ćelije {to}.",
    fillTo: "Popunite ćeliju {from} do ćelije {to}.",
    fillColumn: "Popunite ćeliju {from} prema dolje niz stupac.",
    typeValueInField: "U polje „{field}” upišite „{value}”.",
    typeInField: "Ispunite polje „{field}”.",
    chooseValueIn: "Na popisu „{field}” odaberite „{value}”.",
    chooseIn: "Odaberite opciju na popisu „{field}”.",
    typeValue: "Upišite „{value}”.",
    type: "Upišite tekst.",
    typeValueInCell: "U ćeliju {cell} upišite „{value}”.",
    typeInCell: "Ispunite ćeliju {cell}.",
    press: "Pritisnite {keys}.",
    pressNamed: "Pritisnite {keys} ({name}).",
    goTo: "Idite na {site}.",
    open: "Otvorite {app}.",
    runIn: "Pokrenite sljedeću naredbu u prozoru {where}.",
    runInTerminal: "Pokrenite sljedeću naredbu u terminalu.",
    formulaInCell: "U ćeliju {cell} upišite sljedeću formulu.",
    formulaInSelected: "U odabranu ćeliju upišite sljedeću formulu.",
    code: "Upišite sljedeći kôd.",
    missed: {
      one: "Ovdje nije snimljen {count} klik.",
      few: "Ovdje nisu snimljena {count} klika.",
      other: "Ovdje nije snimljeno {count} klikova.",
    },
    touch: {
      one: "Unos dodirom ili olovkom ovdje možda nije snimljen ({count} izvješće).",
      few: "Unos dodirom ili olovkom ovdje možda nije snimljen ({count} izvješća).",
      other: "Unos dodirom ili olovkom ovdje možda nije snimljen ({count} izvješća).",
    },
    captureNow: "Pregledajte ovaj zaslon.",
  },
  terminals: { powershell: "PowerShell", cmd: "Naredbeni redak", bash: "Bash" },
  shortcuts: {
    selectAll: "Odaberi sve",
    copy: "Kopiraj",
    cut: "Izreži",
    paste: "Zalijepi",
    save: "Spremi",
    print: "Ispis",
    find: "Pronađi",
    close: "Zatvori",
    taskManager: "Upravitelj zadataka",
    showDesktop: "Prikaži radnu površinu",
    fileExplorer: "File Explorer",
    settings: "Postavke",
    lock: "Zaključaj",
    run: "Pokreni",
    clipboardHistory: "Povijest međuspremnika",
    snippingTool: "Alat za izrezivanje",
  },
};
