import type { LanguagePhrases } from "../phrase.ts";

/**
 * Magyar: names in Hungarian quotation marks („Mentés”), with "a(z)" before a quoted name as
 * Microsoft's Hungarian messages do; the user is addressed formally (magázás). Casual is the
 * short noun form ("Kattintás: „Mentés”"), plain uses the neutral "Válassza", formal follows
 * Microsoft's procedure documentation ("Kattintson a(z) „Mentés” gombra.").
 */
export const hu: LanguagePhrases = {
  casual: {
    click: {
      field: "Kattintás a(z) „{name}” mezőbe",
      namedField: "Kattintás: „{name}”",
      textArea: "Kattintás: „{name}”",
      other: "Kattintás: „{name}”",
    },
    clickIn: "Kattintás a(z) „{title}” ablakban",
    clickBare: "Kattintás",
    clickTaskbar: "Kattintás a tálcán: „{name}”",
    rightClick: "Jobb gombbal kattintás a(z) „{name}” elemen",
    rightClickIn: "Jobb gombbal kattintás a(z) „{title}” ablakban",
    rightClickBare: "Jobb gombbal kattintás",
    selectRange: "„{range}” kijelölése",
    typeValueInField: "„{value}” beírása a(z) „{field}” mezőbe",
    typeInField: "Beírás a(z) „{field}” mezőbe",
    chooseValueIn: "„{value}” kiválasztása a(z) „{field}” mezőben",
    chooseIn: "Kiválasztás a(z) „{field}” mezőben",
    typeValue: "„{value}” beírása",
    type: "Beírás",
    typeValueInCell: "„{value}” beírása a(z) {cell} cellába",
    typeInCell: "Beírás a(z) {cell} cellába",
    press: "„{keys}” lenyomása",
    pressNamed: "„{keys}” ({name}) lenyomása",
    goTo: "Ugrás ide: „{site}”",
    open: "„{app}” megnyitása",
    runIn: "Futtatás itt: {where}",
    runInTerminal: "Futtatás a terminálban",
    formulaInCell: "Képlet beírása a(z) {cell} cellába",
    formulaInSelected: "Képlet beírása a kijelölt cellába",
    code: "Kód beírása",
    missed: {
      one: "{count} kattintás kimaradt itt",
      other: "{count} kattintás kimaradt itt",
    },
    touch: {
      one: "Érintéses vagy tollas művelet rögzítése elmaradhatott ({count} jelzés)",
      other: "Érintéses vagy tollas művelet rögzítése elmaradhatott ({count} jelzés)",
    },
    captureNow: "A képernyő rögzítése",
  },
  plain: {
    click: {
      button: "Válassza a(z) „{name}” gombot",
      link: "Válassza a(z) „{name}” hivatkozást",
      menuItem: "Válassza a(z) „{name}” menüpontot",
      tab: "Válassza a(z) „{name}” lapot",
      field: "Válassza a(z) „{name}” mezőt",
      checkbox: "Jelölje be a(z) „{name}” négyzetet",
      radio: "Válassza a(z) „{name}” lehetőséget",
      dropdown: "Nyissa meg a(z) „{name}” listát",
      switch: "Válassza a(z) „{name}” kapcsolót",
      picture: "Válassza a(z) „{name}” képet",
      other: "Válassza ezt: „{name}”",
    },
    clickIn: "Válasszon egy helyet a(z) „{title}” ablakban",
    clickBare: "Válassza ezt a helyet",
    clickTaskbar: "Válassza a tálcán ezt: „{name}”",
    rightClick: "Kattintson a jobb gombbal a(z) „{name}” elemen",
    rightClickIn: "Kattintson a jobb gombbal a(z) „{title}” ablak belsejében",
    rightClickBare: "Kattintson ide a jobb gombbal",
    selectRange: "Jelölje ki a(z) {range} cellatartományt",
    typeValueInField: "Írja be a(z) „{field}” mezőbe: „{value}”",
    typeInField: "Töltse ki a(z) „{field}” mezőt",
    chooseValueIn: "Válassza ki a(z) „{field}” listából: „{value}”",
    chooseIn: "Válasszon a(z) „{field}” listából",
    typeValue: "Írja be: „{value}”",
    type: "Írja be a szöveget",
    typeValueInCell: "Írja be a(z) {cell} cellába: „{value}”",
    typeInCell: "Töltse ki a(z) {cell} cellát",
    press: "Nyomja le: {keys}",
    pressNamed: "Nyomja le: {keys} ({name})",
    goTo: "Lépjen ide: {site}",
    open: "Nyissa meg: {app}",
    runIn: "Futtassa ezt itt: {where}",
    runInTerminal: "Futtassa ezt a terminálban",
    formulaInCell: "Írja be ezt a képletet a(z) {cell} cellába",
    formulaInSelected: "Írja be ezt a képletet a kijelölt cellába",
    code: "Írja be ezt a kódot",
    missed: {
      one: "Itt {count} kattintás kimaradt",
      other: "Itt {count} kattintás kimaradt",
    },
    touch: {
      one: "Itt hiányozhat érintéses vagy tollas művelet ({count} jelzés)",
      other: "Itt hiányozhat érintéses vagy tollas művelet ({count} jelzés)",
    },
    captureNow: "Nézze meg ezt a képernyőt",
  },
  formal: {
    click: {
      button: "Kattintson a(z) „{name}” gombra.",
      link: "Kattintson a(z) „{name}” hivatkozásra.",
      menuItem: "Kattintson a menü „{name}” parancsára.",
      tab: "Kattintson a(z) „{name}” lapra.",
      field: "Kattintson a(z) „{name}” mezőbe.",
      checkbox: "Jelölje be a(z) „{name}” jelölőnégyzetet.",
      radio: "Válassza a(z) „{name}” lehetőséget.",
      dropdown: "Kattintson a(z) „{name}” legördülő listára.",
      switch: "Kattintson a(z) „{name}” kapcsolóra.",
      picture: "Kattintson a(z) „{name}” képre.",
      other: "Kattintson a következőre: „{name}”.",
    },
    clickIn: "Kattintson a(z) „{title}” ablakba.",
    clickBare: "Kattintson.",
    clickTaskbar: "Kattintson a tálcán a következőre: „{name}”.",
    rightClick: "Kattintson a jobb gombbal a(z) „{name}” elemen.",
    rightClickIn: "Kattintson a jobb gombbal a(z) „{title}” ablak belsejében.",
    rightClickBare: "Kattintson a jobb gombbal.",
    selectRange: "Jelölje ki a(z) {range} cellatartományt.",
    typeValueInField: "A(z) „{field}” mezőbe írja be a következőt: „{value}”.",
    typeInField: "Töltse ki a(z) „{field}” mezőt.",
    chooseValueIn: "A(z) „{field}” listából válassza ki a következőt: „{value}”.",
    chooseIn: "Válasszon egy lehetőséget a(z) „{field}” listából.",
    typeValue: "Írja be a következőt: „{value}”.",
    type: "Írja be a szöveget.",
    typeValueInCell: "A(z) {cell} cellába írja be a következőt: „{value}”.",
    typeInCell: "Töltse ki a(z) {cell} cellát.",
    press: "Nyomja le a következőt: {keys}.",
    pressNamed: "Nyomja le a következőt: {keys} ({name}).",
    goTo: "Nyissa meg a következő webhelyet: {site}.",
    open: "Nyissa meg a következő alkalmazást: {app}.",
    runIn: "Futtassa a következő parancsot a(z) {where} alkalmazásban.",
    runInTerminal: "Futtassa a következő parancsot a terminálban.",
    formulaInCell: "A(z) {cell} cellába írja be a következő képletet.",
    formulaInSelected: "A kijelölt cellába írja be a következő képletet.",
    code: "Írja be a következő kódot.",
    missed: {
      one: "Ezen a ponton {count} kattintás rögzítése elmaradt.",
      other: "Ezen a ponton {count} kattintás rögzítése elmaradt.",
    },
    touch: {
      one: "Előfordulhat, hogy az érintéses vagy tollbevitel itt nem lett rögzítve ({count} jelzés).",
      other:
        "Előfordulhat, hogy az érintéses vagy tollbevitel itt nem lett rögzítve ({count} jelzés).",
    },
    captureNow: "Tekintse át ezt a képernyőt.",
  },
  terminals: { powershell: "PowerShell", cmd: "Parancssor", bash: "Bash" },
  shortcuts: {
    selectAll: "Összes kijelölése",
    copy: "Másolás",
    cut: "Kivágás",
    paste: "Beillesztés",
    save: "Mentés",
    print: "Nyomtatás",
    find: "Keresés",
    close: "Bezárás",
    taskManager: "Feladatkezelő",
    showDesktop: "Asztal megjelenítése",
    fileExplorer: "Fájlkezelő",
    settings: "Beállítások",
    lock: "Zárolás",
    run: "Futtatás",
    clipboardHistory: "Vágólap-előzmények",
    snippingTool: "Képkivágó eszköz",
  },
};
