import type { LanguagePhrases } from "../phrase.ts";

/**
 * Bahasa Indonesia: names in “…”, and plain imperatives ("Klik", "Ketik", "Tekan") as Microsoft's
 * Indonesian documentation writes them, addressing the reader as "Anda" only where a sentence
 * needs it. Casual is the short "Klik “Simpan”"; plain uses the neutral "Pilih" for a click and
 * "Masukkan" for typing; formal writes full sentences naming the control, ending in a full stop.
 */
export const id: LanguagePhrases = {
  casual: {
    click: {
      field: "Klik bidang “{name}”",
      namedField: "Klik “{name}”",
      textArea: "Klik “{name}”",
      other: "Klik “{name}”",
    },
    clickIn: "Klik di “{title}”",
    clickBare: "Klik",
    clickTaskbar: "Klik “{name}” di bilah tugas",
    rightClick: "Klik kanan “{name}”",
    rightClickIn: "Klik kanan di “{title}”",
    rightClickBare: "Klik kanan",
    selectRange: "Pilih “{range}”",
    typeValueInField: "Ketik “{value}” di bidang “{field}”",
    typeInField: "Ketik di bidang “{field}”",
    chooseValueIn: "Pilih “{value}” di “{field}”",
    chooseIn: "Pilih di “{field}”",
    typeValue: "Ketik “{value}”",
    type: "Ketik",
    typeValueInCell: "Ketik “{value}” di sel {cell}",
    typeInCell: "Ketik di sel {cell}",
    press: "Tekan “{keys}”",
    goTo: "Kunjungi “{site}”",
    open: "Buka “{app}”",
    runIn: "Jalankan di {where}",
    runInTerminal: "Jalankan di terminal",
    formulaInCell: "Ketik rumus di sel {cell}",
    formulaInSelected: "Ketik rumus di sel yang dipilih",
    code: "Ketik kode ini",
    missed: { other: "{count} klik terlewat di sini" },
    touch: { other: "Aktivitas sentuh atau pena mungkin tidak terekam ({count} laporan)" },
    captureNow: "Tangkap layar ini",
  },
  plain: {
    click: {
      button: "Pilih tombol “{name}”",
      link: "Pilih tautan “{name}”",
      menuItem: "Pilih “{name}” di menu",
      tab: "Pilih tab “{name}”",
      field: "Pilih kotak “{name}”",
      checkbox: "Pilih kotak centang “{name}”",
      radio: "Pilih opsi “{name}”",
      dropdown: "Buka daftar “{name}”",
      switch: "Pilih sakelar “{name}”",
      picture: "Pilih gambar “{name}”",
      other: "Pilih “{name}”",
    },
    clickIn: "Pilih di dalam jendela “{title}”",
    clickBare: "Pilih di sini",
    clickTaskbar: "Pilih “{name}” di bilah tugas",
    rightClick: "Klik kanan “{name}”",
    rightClickIn: "Klik kanan di dalam jendela “{title}”",
    rightClickBare: "Klik kanan di sini",
    selectRange: "Pilih sel {range}",
    typeValueInField: "Masukkan “{value}” di kotak “{field}”",
    typeInField: "Isi kotak “{field}”",
    chooseValueIn: "Pilih “{value}” dari daftar “{field}”",
    chooseIn: "Pilih dari daftar “{field}”",
    typeValue: "Masukkan “{value}”",
    type: "Masukkan teks",
    typeValueInCell: "Masukkan “{value}” di sel {cell}",
    typeInCell: "Isi sel {cell}",
    press: "Tekan {keys}",
    goTo: "Kunjungi {site}",
    open: "Buka {app}",
    runIn: "Jalankan ini di {where}",
    runInTerminal: "Jalankan ini di terminal",
    formulaInCell: "Masukkan rumus ini di sel {cell}",
    formulaInSelected: "Masukkan rumus ini di sel yang dipilih",
    code: "Ketik kode ini",
    missed: { other: "{count} klik terlewat di sini" },
    touch: {
      other: "Penggunaan sentuh atau pena mungkin tidak tercatat di sini ({count} laporan)",
    },
    captureNow: "Lihat layar ini",
  },
  formal: {
    click: {
      button: "Klik tombol “{name}”.",
      link: "Klik tautan “{name}”.",
      menuItem: "Klik “{name}” pada menu.",
      tab: "Klik tab “{name}”.",
      field: "Klik di dalam bidang “{name}”.",
      checkbox: "Pilih kotak centang “{name}”.",
      radio: "Pilih opsi “{name}”.",
      dropdown: "Klik daftar turun bawah “{name}”.",
      switch: "Klik sakelar “{name}”.",
      picture: "Klik gambar “{name}”.",
      other: "Klik “{name}”.",
    },
    clickIn: "Klik di dalam jendela “{title}”.",
    clickBare: "Klik.",
    clickTaskbar: "Klik “{name}” pada bilah tugas.",
    rightClick: "Klik kanan “{name}”.",
    rightClickIn: "Klik kanan di dalam jendela “{title}”.",
    rightClickBare: "Klik kanan.",
    selectRange: "Pilih sel {range}.",
    typeValueInField: "Di bidang “{field}”, ketik “{value}”.",
    typeInField: "Lengkapi bidang “{field}”.",
    chooseValueIn: "Di daftar “{field}”, pilih “{value}”.",
    chooseIn: "Pilih satu opsi di daftar “{field}”.",
    typeValue: "Ketik “{value}”.",
    type: "Ketik teks.",
    typeValueInCell: "Di sel {cell}, ketik “{value}”.",
    typeInCell: "Lengkapi sel {cell}.",
    press: "Tekan {keys}.",
    goTo: "Navigasikan ke {site}.",
    open: "Buka {app}.",
    runIn: "Jalankan perintah berikut di {where}.",
    runInTerminal: "Jalankan perintah berikut di terminal.",
    formulaInCell: "Di sel {cell}, ketik rumus berikut.",
    formulaInSelected: "Di sel yang dipilih, ketik rumus berikut.",
    code: "Ketik kode berikut.",
    missed: { other: "{count} klik tidak terekam di sini." },
    touch: { other: "Input sentuh atau pena mungkin tidak terekam di sini ({count} laporan)." },
    captureNow: "Tinjau layar ini.",
  },
  terminals: { powershell: "PowerShell", cmd: "Prompt Perintah", bash: "Bash" },
};
