import type { LanguagePhrases } from "../phrase.ts";

/**
 * Italiano: virgolette “…”; casual and plain speak to the reader as "tu" (the app's own form),
 * casual in short imperatives ("Fai clic su “Salva”") and plain with the neutral "Seleziona";
 * formal writes full sentences in the impersonal infinitive ("Fare clic sul pulsante “Salva”."),
 * as Microsoft's Italian procedure documentation does.
 */
export const it: LanguagePhrases = {
  casual: {
    click: {
      field: "Fai clic sul campo “{name}”",
      namedField: "Fai clic su “{name}”",
      textArea: "Fai clic su “{name}”",
      other: "Fai clic su “{name}”",
    },
    clickIn: "Fai clic in “{title}”",
    clickBare: "Fai clic",
    clickTaskbar: "Fai clic su “{name}” sulla barra delle applicazioni",
    rightClick: "Fai clic con il pulsante destro del mouse su “{name}”",
    rightClickIn: "Fai clic con il pulsante destro del mouse in “{title}”",
    rightClickBare: "Fai clic con il pulsante destro del mouse",
    selectRange: "Seleziona “{range}”",
    fillDown: "Riempi “{from}” in basso fino a “{to}”",
    fillTo: "Riempi “{from}” fino a “{to}”",
    fillColumn: "Riempi “{from}” in basso lungo la colonna",
    typeValueInField: "Digita “{value}” nel campo “{field}”",
    typeInField: "Digita nel campo “{field}”",
    chooseValueIn: "Scegli “{value}” in “{field}”",
    chooseIn: "Scegli in “{field}”",
    typeValue: "Digita “{value}”",
    type: "Digita",
    typeValueInCell: "Digita “{value}” nella cella {cell}",
    typeInCell: "Digita nella cella {cell}",
    press: "Premi “{keys}”",
    pressNamed: "Premi “{keys}” ({name})",
    goTo: "Vai a “{site}”",
    open: "Apri “{app}”",
    runIn: "Esegui in {where}",
    runInTerminal: "Esegui nel terminale",
    formulaInCell: "Digita la formula nella cella {cell}",
    formulaInSelected: "Digita la formula nella cella selezionata",
    code: "Digita questo codice",
    missed: {
      one: "{count} clic perso qui",
      many: "{count} clic persi qui",
      other: "{count} clic persi qui",
    },
    touch: {
      one: "L'attività touch o penna potrebbe non essere stata registrata ({count} segnalazione)",
      many: "L'attività touch o penna potrebbe non essere stata registrata ({count} segnalazioni)",
      other: "L'attività touch o penna potrebbe non essere stata registrata ({count} segnalazioni)",
    },
    captureNow: "Acquisisci questa schermata",
  },
  plain: {
    click: {
      button: "Seleziona il pulsante “{name}”",
      link: "Seleziona il collegamento “{name}”",
      menuItem: "Seleziona “{name}” nel menu",
      tab: "Seleziona la scheda “{name}”",
      field: "Seleziona la casella “{name}”",
      checkbox: "Seleziona la casella di controllo “{name}”",
      radio: "Scegli “{name}”",
      dropdown: "Apri l'elenco “{name}”",
      switch: "Seleziona l'interruttore “{name}”",
      picture: "Seleziona l'immagine “{name}”",
      other: "Seleziona “{name}”",
    },
    clickIn: "Seleziona all'interno della finestra “{title}”",
    clickBare: "Seleziona qui",
    clickTaskbar: "Seleziona “{name}” sulla barra delle applicazioni",
    rightClick: "Fai clic con il pulsante destro del mouse su “{name}”",
    rightClickIn: "Fai clic con il pulsante destro del mouse all'interno della finestra “{title}”",
    rightClickBare: "Fai clic qui con il pulsante destro del mouse",
    selectRange: "Seleziona le celle {range}",
    fillDown: "Riempi la cella {from} in basso fino alla cella {to}",
    fillTo: "Riempi la cella {from} fino alla cella {to}",
    fillColumn: "Riempi la cella {from} in basso lungo la colonna",
    typeValueInField: "Scrivi “{value}” nella casella “{field}”",
    typeInField: "Compila la casella “{field}”",
    chooseValueIn: "Scegli “{value}” dall'elenco “{field}”",
    chooseIn: "Scegli dall'elenco “{field}”",
    typeValue: "Scrivi “{value}”",
    type: "Scrivi il testo",
    typeValueInCell: "Scrivi “{value}” nella cella {cell}",
    typeInCell: "Compila la cella {cell}",
    press: "Premi {keys}",
    pressNamed: "Premi {keys} ({name})",
    goTo: "Vai a {site}",
    open: "Apri {app}",
    runIn: "Esegui questo comando in {where}",
    runInTerminal: "Esegui questo comando nel terminale",
    formulaInCell: "Scrivi questa formula nella cella {cell}",
    formulaInSelected: "Scrivi questa formula nella cella selezionata",
    code: "Scrivi questo codice",
    missed: {
      one: "Qui è stato perso {count} clic",
      many: "Qui sono stati persi {count} clic",
      other: "Qui sono stati persi {count} clic",
    },
    touch: {
      one: "Qui potrebbe mancare l'uso del touch o della penna ({count} segnalazione)",
      many: "Qui potrebbe mancare l'uso del touch o della penna ({count} segnalazioni)",
      other: "Qui potrebbe mancare l'uso del touch o della penna ({count} segnalazioni)",
    },
    captureNow: "Guarda questa schermata",
  },
  formal: {
    click: {
      button: "Fare clic sul pulsante “{name}”.",
      link: "Fare clic sul collegamento “{name}”.",
      menuItem: "Fare clic su “{name}” nel menu.",
      tab: "Fare clic sulla scheda “{name}”.",
      field: "Fare clic nel campo “{name}”.",
      checkbox: "Selezionare la casella di controllo “{name}”.",
      radio: "Selezionare l'opzione “{name}”.",
      dropdown: "Fare clic sull'elenco a discesa “{name}”.",
      switch: "Fare clic sull'interruttore “{name}”.",
      picture: "Fare clic sull'immagine “{name}”.",
      other: "Fare clic su “{name}”.",
    },
    clickIn: "Fare clic nella finestra “{title}”.",
    clickBare: "Fare clic.",
    clickTaskbar: "Fare clic su “{name}” sulla barra delle applicazioni.",
    rightClick: "Fare clic con il pulsante destro del mouse su “{name}”.",
    rightClickIn: "Fare clic con il pulsante destro del mouse nella finestra “{title}”.",
    rightClickBare: "Fare clic con il pulsante destro del mouse.",
    selectRange: "Selezionare le celle {range}.",
    fillDown: "Riempire la cella {from} in basso fino alla cella {to}.",
    fillTo: "Riempire la cella {from} fino alla cella {to}.",
    fillColumn: "Riempire la cella {from} in basso lungo la colonna.",
    typeValueInField: "Nel campo “{field}” digitare “{value}”.",
    typeInField: "Compilare il campo “{field}”.",
    chooseValueIn: "Nell'elenco “{field}”, selezionare “{value}”.",
    chooseIn: "Nell'elenco “{field}”, selezionare un'opzione.",
    typeValue: "Digitare “{value}”.",
    type: "Digitare il testo.",
    typeValueInCell: "Nella cella {cell} digitare “{value}”.",
    typeInCell: "Compilare la cella {cell}.",
    press: "Premere {keys}.",
    pressNamed: "Premere {keys} ({name}).",
    goTo: "Passare a {site}.",
    open: "Aprire {app}.",
    runIn: "Eseguire il comando seguente in una finestra di {where}.",
    runInTerminal: "Eseguire il comando seguente nel terminale.",
    formulaInCell: "Nella cella {cell} digitare la formula seguente.",
    formulaInSelected: "Nella cella selezionata digitare la formula seguente.",
    code: "Digitare il codice seguente.",
    missed: {
      one: "Qui non è stato registrato {count} clic.",
      many: "Qui non sono stati registrati {count} clic.",
      other: "Qui non sono stati registrati {count} clic.",
    },
    touch: {
      one: "Qui l'input tocco o penna potrebbe non essere stato registrato ({count} segnalazione).",
      many: "Qui l'input tocco o penna potrebbe non essere stato registrato ({count} segnalazioni).",
      other:
        "Qui l'input tocco o penna potrebbe non essere stato registrato ({count} segnalazioni).",
    },
    captureNow: "Esaminare questa schermata.",
  },
  terminals: { powershell: "PowerShell", cmd: "Prompt dei comandi", bash: "Bash" },
  shortcuts: {
    selectAll: "Seleziona tutto",
    copy: "Copia",
    cut: "Taglia",
    paste: "Incolla",
    save: "Salva",
    print: "Stampa",
    find: "Trova",
    close: "Chiudi",
    taskManager: "Gestione attività",
    showDesktop: "Mostra desktop",
    fileExplorer: "Esplora file",
    settings: "Impostazioni",
    lock: "Blocca",
    run: "Esegui",
    clipboardHistory: "Cronologia degli Appunti",
    snippingTool: "Strumento di cattura",
  },
};
