import type { LanguagePhrases } from "../phrase.ts";

/**
 * 日本語: names in 「」 as Microsoft's Japanese documentation quotes them, keys without quotes
 * ("Ctrl+S キーを押す"). Casual is the short label ending in a noun or plain verb, with no 。
 * (「保存」をクリック); plain uses everyday polite verbs (押します, 選びます) with no full stop;
 * formal is Microsoft's procedure style in です/ます form, ending in 。.
 */
export const ja: LanguagePhrases = {
  casual: {
    click: {
      field: "「{name}」フィールドをクリック",
      namedField: "「{name}」をクリック",
      textArea: "「{name}」をクリック",
      other: "「{name}」をクリック",
    },
    clickIn: "「{title}」内をクリック",
    clickBare: "クリック",
    clickTaskbar: "タスク バーの「{name}」をクリック",
    rightClick: "「{name}」を右クリック",
    rightClickIn: "「{title}」内を右クリック",
    rightClickBare: "右クリック",
    selectRange: "「{range}」を選択",
    typeValueInField: "「{field}」フィールドに「{value}」と入力",
    typeInField: "「{field}」フィールドに入力",
    chooseValueIn: "「{field}」で「{value}」を選択",
    chooseIn: "「{field}」で選択",
    typeValue: "「{value}」と入力",
    type: "入力",
    typeValueInCell: "セル {cell} に「{value}」と入力",
    typeInCell: "セル {cell} に入力",
    press: "{keys} キーを押す",
    goTo: "{site} に移動",
    open: "「{app}」を開く",
    runIn: "{where} で実行",
    runInTerminal: "ターミナルで実行",
    formulaInCell: "セル {cell} に数式を入力",
    formulaInSelected: "選択したセルに数式を入力",
    code: "このコードを入力",
    missed: { other: "ここでクリック {count} 回の記録漏れ" },
    touch: { other: "タッチまたはペンの操作が記録されていない可能性あり（報告 {count} 件）" },
    captureNow: "この画面をキャプチャ",
  },
  plain: {
    click: {
      button: "「{name}」ボタンを押します",
      link: "「{name}」リンクを選びます",
      menuItem: "メニューの「{name}」を選びます",
      tab: "「{name}」タブを選びます",
      field: "「{name}」の入力欄を選びます",
      checkbox: "「{name}」のチェックボックスを選びます",
      radio: "「{name}」を選びます",
      dropdown: "「{name}」の一覧を開きます",
      switch: "「{name}」のスイッチを押します",
      picture: "「{name}」の画像を選びます",
      other: "「{name}」を選びます",
    },
    clickIn: "「{title}」ウィンドウの中を選びます",
    clickBare: "ここを選びます",
    clickTaskbar: "タスク バーの「{name}」を選びます",
    rightClick: "「{name}」を右クリックします",
    rightClickIn: "「{title}」ウィンドウの中を右クリックします",
    rightClickBare: "ここを右クリックします",
    selectRange: "セル {range} を選択します",
    typeValueInField: "「{field}」の入力欄に「{value}」と入力します",
    typeInField: "「{field}」の入力欄に入力します",
    chooseValueIn: "「{field}」の一覧から「{value}」を選びます",
    chooseIn: "「{field}」の一覧から選びます",
    typeValue: "「{value}」と入力します",
    type: "文字を入力します",
    typeValueInCell: "セル {cell} に「{value}」と入力します",
    typeInCell: "セル {cell} に入力します",
    press: "{keys} キーを押します",
    goTo: "{site} を開きます",
    open: "{app} を開きます",
    runIn: "{where} でこれを実行します",
    runInTerminal: "ターミナルでこれを実行します",
    formulaInCell: "セル {cell} にこの数式を入力します",
    formulaInSelected: "選んだセルにこの数式を入力します",
    code: "このコードを入力します",
    missed: { other: "ここで {count} 回のクリックが記録されませんでした" },
    touch: { other: "ここでタッチやペンの操作が抜けているかもしれません（報告 {count} 件）" },
    captureNow: "この画面を見ます",
  },
  formal: {
    click: {
      button: "「{name}」ボタンをクリックします。",
      link: "「{name}」リンクをクリックします。",
      menuItem: "メニューの「{name}」をクリックします。",
      tab: "「{name}」タブをクリックします。",
      field: "「{name}」ボックス内をクリックします。",
      checkbox: "「{name}」チェック ボックスをオンにします。",
      radio: "「{name}」オプションを選択します。",
      dropdown: "「{name}」ドロップダウン リストをクリックします。",
      switch: "「{name}」スイッチをクリックします。",
      picture: "「{name}」画像をクリックします。",
      other: "「{name}」をクリックします。",
    },
    clickIn: "「{title}」ウィンドウ内をクリックします。",
    clickBare: "クリックします。",
    clickTaskbar: "タスク バーの「{name}」をクリックします。",
    rightClick: "「{name}」を右クリックします。",
    rightClickIn: "「{title}」ウィンドウ内を右クリックします。",
    rightClickBare: "右クリックします。",
    selectRange: "セル {range} を選択します。",
    typeValueInField: "「{field}」ボックスに「{value}」と入力します。",
    typeInField: "「{field}」ボックスに必要事項を入力します。",
    chooseValueIn: "「{field}」の一覧で「{value}」を選択します。",
    chooseIn: "「{field}」の一覧で項目を選択します。",
    typeValue: "「{value}」と入力します。",
    type: "テキストを入力します。",
    typeValueInCell: "セル {cell} に「{value}」と入力します。",
    typeInCell: "セル {cell} に必要事項を入力します。",
    press: "{keys} キーを押します。",
    goTo: "{site} に移動します。",
    open: "{app} を開きます。",
    runIn: "{where} で次のコマンドを実行します。",
    runInTerminal: "ターミナルで次のコマンドを実行します。",
    formulaInCell: "セル {cell} に次の数式を入力します。",
    formulaInSelected: "選択したセルに次の数式を入力します。",
    code: "次のコードを入力します。",
    missed: { other: "ここで {count} 回のクリックが記録されませんでした。" },
    touch: {
      other:
        "ここでのタッチまたはペンによる入力が記録されていない可能性があります（報告 {count} 件）。",
    },
    captureNow: "この画面を確認します。",
  },
  terminals: { powershell: "PowerShell", cmd: "コマンド プロンプト", bash: "Bash" },
};
