import type { LanguagePhrases } from "../phrase.ts";

/**
 * 한국어: names in “…”, with Microsoft's 을(를)/(으)로 particle forms after a filled-in name; casual
 * is the short noun form of a step label (“저장” 클릭), plain the polite 하세요 form with the
 * neutral 선택 (select), and formal the 합니다 sentences of Microsoft's Korean procedures.
 */
export const ko: LanguagePhrases = {
  casual: {
    click: {
      field: "“{name}” 필드 클릭",
      namedField: "“{name}” 클릭",
      textArea: "“{name}” 클릭",
      other: "“{name}” 클릭",
    },
    clickIn: "“{title}”에서 클릭",
    clickBare: "클릭",
    clickTaskbar: "작업 표시줄에서 “{name}” 클릭",
    rightClick: "“{name}” 우클릭",
    rightClickIn: "“{title}”에서 우클릭",
    rightClickBare: "우클릭",
    selectRange: "“{range}” 선택",
    fillDown: "“{from}”에서 “{to}”까지 아래로 채우기",
    fillTo: "“{from}”에서 “{to}”까지 채우기",
    fillColumn: "“{from}”에서 열 아래로 채우기",
    typeValueInField: "“{field}” 필드에 “{value}” 입력",
    typeInField: "“{field}” 필드에 입력",
    chooseValueIn: "“{field}”에서 “{value}” 선택",
    chooseIn: "“{field}”에서 선택",
    typeValue: "“{value}” 입력",
    type: "입력",
    typeValueInCell: "{cell} 셀에 “{value}” 입력",
    typeInCell: "{cell} 셀에 입력",
    press: "{keys} 누르기",
    pressNamed: "{keys} ({name}) 누르기",
    goTo: "“{site}”(으)로 이동",
    open: "“{app}” 열기",
    runIn: "{where}에서 실행",
    runInTerminal: "터미널에서 실행",
    formulaInCell: "{cell} 셀에 수식 입력",
    formulaInSelected: "선택한 셀에 수식 입력",
    code: "이 코드 입력",
    missed: { other: "여기서 클릭 {count}번 놓침" },
    touch: { other: "터치 또는 펜 동작이 녹화되지 않았을 수 있음(보고 {count}건)" },
    captureNow: "이 화면 캡처",
  },
  plain: {
    click: {
      button: "“{name}” 단추를 선택하세요",
      link: "“{name}” 링크를 선택하세요",
      menuItem: "메뉴에서 “{name}” 항목을 선택하세요",
      tab: "“{name}” 탭을 선택하세요",
      field: "“{name}” 상자를 선택하세요",
      checkbox: "“{name}” 확인란을 선택하세요",
      radio: "“{name}” 옵션을 고르세요",
      dropdown: "“{name}” 목록을 여세요",
      switch: "“{name}” 스위치를 선택하세요",
      picture: "“{name}” 그림을 선택하세요",
      listItem: "“{name}” 항목을 선택하세요",
      other: "“{name}”을(를) 선택하세요",
    },
    clickIn: "“{title}” 창에서 선택하세요",
    clickBare: "여기를 선택하세요",
    clickTaskbar: "작업 표시줄에서 “{name}”을(를) 선택하세요",
    rightClick: "“{name}”을(를) 마우스 오른쪽 단추로 클릭하세요",
    rightClickIn: "“{title}” 창에서 마우스 오른쪽 단추로 클릭하세요",
    rightClickBare: "여기를 마우스 오른쪽 단추로 클릭하세요",
    selectRange: "셀 {range}을(를) 선택하세요",
    fillDown: "{from} 셀에서 {to} 셀까지 아래로 채우세요",
    fillTo: "{from} 셀에서 {to} 셀까지 채우세요",
    fillColumn: "{from} 셀에서 열 아래로 채우세요",
    typeValueInField: "“{field}” 상자에 “{value}”을(를) 입력하세요",
    typeInField: "“{field}” 상자에 입력하세요",
    chooseValueIn: "“{field}” 목록에서 “{value}”을(를) 선택하세요",
    chooseIn: "“{field}” 목록에서 선택하세요",
    typeValue: "“{value}”을(를) 입력하세요",
    type: "텍스트를 입력하세요",
    typeValueInCell: "{cell} 셀에 “{value}”을(를) 입력하세요",
    typeInCell: "{cell} 셀에 입력하세요",
    press: "{keys} 키를 누르세요",
    pressNamed: "{keys} ({name}) 키를 누르세요",
    goTo: "{site}에 접속하세요",
    open: "{app} 앱을 여세요",
    runIn: "{where}에서 실행하세요",
    runInTerminal: "터미널에서 실행하세요",
    formulaInCell: "{cell} 셀에 이 수식을 입력하세요",
    formulaInSelected: "선택한 셀에 이 수식을 입력하세요",
    code: "이 코드를 입력하세요",
    missed: { other: "여기서 클릭 {count}번을 놓쳤습니다" },
    touch: { other: "여기서 터치나 펜 사용이 빠졌을 수 있습니다(보고 {count}건)" },
    captureNow: "이 화면을 보세요",
  },
  formal: {
    click: {
      button: "“{name}” 단추를 클릭합니다.",
      link: "“{name}” 링크를 클릭합니다.",
      menuItem: "메뉴에서 “{name}”을(를) 클릭합니다.",
      tab: "“{name}” 탭을 클릭합니다.",
      field: "“{name}” 필드를 클릭합니다.",
      checkbox: "“{name}” 확인란을 선택합니다.",
      radio: "“{name}” 옵션을 선택합니다.",
      dropdown: "“{name}” 드롭다운 목록을 클릭합니다.",
      switch: "“{name}” 스위치를 클릭합니다.",
      picture: "“{name}” 이미지를 클릭합니다.",
      other: "“{name}”을(를) 클릭합니다.",
    },
    clickIn: "“{title}” 창 안을 클릭합니다.",
    clickBare: "클릭합니다.",
    clickTaskbar: "작업 표시줄에서 “{name}”을(를) 클릭합니다.",
    rightClick: "“{name}”을(를) 마우스 오른쪽 단추로 클릭합니다.",
    rightClickIn: "“{title}” 창 안을 마우스 오른쪽 단추로 클릭합니다.",
    rightClickBare: "마우스 오른쪽 단추로 클릭합니다.",
    selectRange: "셀 {range}을(를) 선택합니다.",
    fillDown: "{from} 셀에서 {to} 셀까지 아래로 채웁니다.",
    fillTo: "{from} 셀에서 {to} 셀까지 채웁니다.",
    fillColumn: "{from} 셀에서 열 아래로 채웁니다.",
    typeValueInField: "“{field}” 필드에 “{value}”을(를) 입력합니다.",
    typeInField: "“{field}” 필드에 입력합니다.",
    chooseValueIn: "“{field}” 목록에서 “{value}”을(를) 선택합니다.",
    chooseIn: "“{field}” 목록에서 옵션을 선택합니다.",
    typeValue: "“{value}”을(를) 입력합니다.",
    type: "텍스트를 입력합니다.",
    typeValueInCell: "{cell} 셀에 “{value}”을(를) 입력합니다.",
    typeInCell: "{cell} 셀에 입력합니다.",
    press: "{keys} 키를 누릅니다.",
    pressNamed: "{keys} ({name}) 키를 누릅니다.",
    goTo: "{site}(으)로 이동합니다.",
    open: "{app}을(를) 엽니다.",
    runIn: "{where}에서 다음 명령을 실행합니다.",
    runInTerminal: "터미널에서 다음 명령을 실행합니다.",
    formulaInCell: "{cell} 셀에 다음 수식을 입력합니다.",
    formulaInSelected: "선택한 셀에 다음 수식을 입력합니다.",
    code: "다음 코드를 입력합니다.",
    missed: { other: "여기서 클릭 {count}번이 기록되지 않았습니다." },
    touch: { other: "여기서 터치 또는 펜 입력이 기록되지 않았을 수 있습니다(보고 {count}건)." },
    captureNow: "이 화면을 검토합니다.",
  },
  terminals: { powershell: "PowerShell", cmd: "명령 프롬프트", bash: "Bash" },
  shortcuts: {
    selectAll: "모두 선택",
    copy: "복사",
    cut: "잘라내기",
    paste: "붙여넣기",
    save: "저장",
    print: "인쇄",
    find: "찾기",
    close: "닫기",
    taskManager: "작업 관리자",
    showDesktop: "바탕 화면 표시",
    fileExplorer: "파일 탐색기",
    settings: "설정",
    lock: "잠금",
    run: "실행",
    clipboardHistory: "클립보드 기록",
    snippingTool: "캡처 도구",
  },
};
