import type { LanguagePhrases } from "../phrase.ts";

/**
 * Lietuvių: Lithuanian quotation marks („…“) and the polite plural imperative (Spustelėkite) in
 * every tone, as Microsoft's Lithuanian documentation writes; casual is the bare instruction,
 * plain uses "Pasirinkite" and everyday words, formal full sentences naming each kind of control.
 */
export const lt: LanguagePhrases = {
  casual: {
    click: {
      field: "Spustelėkite lauką „{name}“",
      namedField: "Spustelėkite „{name}“",
      textArea: "Spustelėkite „{name}“",
      other: "Spustelėkite „{name}“",
    },
    clickIn: "Spustelėkite lange „{title}“",
    clickBare: "Spustelėkite",
    clickTaskbar: "Spustelėkite „{name}“ užduočių juostoje",
    rightClick: "Dešiniuoju pelės mygtuku spustelėkite „{name}“",
    rightClickIn: "Dešiniuoju pelės mygtuku spustelėkite lange „{title}“",
    rightClickBare: "Dešiniuoju pelės mygtuku spustelėkite",
    selectRange: "Pasirinkite „{range}“",
    typeValueInField: "Įveskite „{value}“ lauke „{field}“",
    typeInField: "Įveskite tekstą lauke „{field}“",
    chooseValueIn: "Pasirinkite „{value}“ lauke „{field}“",
    chooseIn: "Pasirinkite lauke „{field}“",
    typeValue: "Įveskite „{value}“",
    type: "Įveskite tekstą",
    typeValueInCell: "Įveskite „{value}“ langelyje {cell}",
    typeInCell: "Įveskite tekstą langelyje {cell}",
    press: "Paspauskite „{keys}“",
    pressNamed: "Paspauskite „{keys}“ ({name})",
    goTo: "Eikite į „{site}“",
    open: "Atidarykite „{app}“",
    runIn: "Vykdykite programoje „{where}“",
    runInTerminal: "Vykdykite terminale",
    formulaInCell: "Įveskite formulę langelyje {cell}",
    formulaInSelected: "Įveskite formulę pažymėtame langelyje",
    code: "Įveskite šį kodą",
    missed: {
      one: "Čia praleistas {count} spustelėjimas",
      few: "Čia praleisti {count} spustelėjimai",
      many: "Čia praleista {count} spustelėjimų",
      other: "Čia praleista {count} spustelėjimų",
    },
    touch: {
      one: "Lietimo ar rašiklio veiksmai galėjo būti neįrašyti ({count} pranešimas)",
      few: "Lietimo ar rašiklio veiksmai galėjo būti neįrašyti ({count} pranešimai)",
      many: "Lietimo ar rašiklio veiksmai galėjo būti neįrašyti ({count} pranešimų)",
      other: "Lietimo ar rašiklio veiksmai galėjo būti neįrašyti ({count} pranešimų)",
    },
    captureNow: "Užfiksuokite šį ekraną",
  },
  plain: {
    click: {
      button: "Pasirinkite mygtuką „{name}“",
      link: "Pasirinkite nuorodą „{name}“",
      menuItem: "Meniu pasirinkite „{name}“",
      tab: "Pasirinkite skirtuką „{name}“",
      field: "Pasirinkite laukelį „{name}“",
      checkbox: "Pažymėkite langelį „{name}“",
      radio: "Pasirinkite „{name}“",
      dropdown: "Atidarykite sąrašą „{name}“",
      switch: "Pasirinkite jungiklį „{name}“",
      picture: "Pasirinkite paveikslėlį „{name}“",
      other: "Pasirinkite „{name}“",
    },
    clickIn: "Pasirinkite vietą lange „{title}“",
    clickBare: "Pasirinkite čia",
    clickTaskbar: "Užduočių juostoje pasirinkite „{name}“",
    rightClick: "Dešiniuoju pelės mygtuku spustelėkite „{name}“",
    rightClickIn: "Dešiniuoju pelės mygtuku spustelėkite lango „{title}“ viduje",
    rightClickBare: "Dešiniuoju pelės mygtuku spustelėkite čia",
    selectRange: "Pasirinkite langelius {range}",
    typeValueInField: "Įveskite „{value}“ laukelyje „{field}“",
    typeInField: "Užpildykite laukelį „{field}“",
    chooseValueIn: "Pasirinkite „{value}“ iš sąrašo „{field}“",
    chooseIn: "Pasirinkite iš sąrašo „{field}“",
    typeValue: "Įveskite „{value}“",
    type: "Įveskite tekstą",
    typeValueInCell: "Įveskite „{value}“ langelyje {cell}",
    typeInCell: "Užpildykite langelį {cell}",
    press: "Paspauskite {keys}",
    pressNamed: "Paspauskite {keys} ({name})",
    goTo: "Eikite į {site}",
    open: "Atidarykite {app}",
    runIn: "Paleiskite tai programoje „{where}“",
    runInTerminal: "Paleiskite tai terminale",
    formulaInCell: "Įveskite šią formulę langelyje {cell}",
    formulaInSelected: "Įveskite šią formulę pažymėtame langelyje",
    code: "Įveskite šį kodą",
    missed: {
      one: "Čia nebuvo užfiksuotas {count} spustelėjimas",
      few: "Čia nebuvo užfiksuoti {count} spustelėjimai",
      many: "Čia nebuvo užfiksuota {count} spustelėjimų",
      other: "Čia nebuvo užfiksuota {count} spustelėjimų",
    },
    touch: {
      one: "Čia gali trūkti lietimo ar rašiklio veiksmų ({count} pranešimas)",
      few: "Čia gali trūkti lietimo ar rašiklio veiksmų ({count} pranešimai)",
      many: "Čia gali trūkti lietimo ar rašiklio veiksmų ({count} pranešimų)",
      other: "Čia gali trūkti lietimo ar rašiklio veiksmų ({count} pranešimų)",
    },
    captureNow: "Pažiūrėkite į šį ekraną",
  },
  formal: {
    click: {
      button: "Spustelėkite mygtuką „{name}“.",
      link: "Spustelėkite saitą „{name}“.",
      menuItem: "Meniu spustelėkite „{name}“.",
      tab: "Spustelėkite skirtuką „{name}“.",
      field: "Spustelėkite lauką „{name}“.",
      checkbox: "Pažymėkite žymės langelį „{name}“.",
      radio: "Pasirinkite parinktį „{name}“.",
      dropdown: "Spustelėkite išplečiamąjį sąrašą „{name}“.",
      switch: "Spustelėkite jungiklį „{name}“.",
      picture: "Spustelėkite vaizdą „{name}“.",
      other: "Spustelėkite „{name}“.",
    },
    clickIn: "Spustelėkite lange „{title}“.",
    clickBare: "Spustelėkite.",
    clickTaskbar: "Užduočių juostoje spustelėkite „{name}“.",
    rightClick: "Dešiniuoju pelės mygtuku spustelėkite „{name}“.",
    rightClickIn: "Dešiniuoju pelės mygtuku spustelėkite lango „{title}“ viduje.",
    rightClickBare: "Dešiniuoju pelės mygtuku spustelėkite.",
    selectRange: "Pasirinkite langelius {range}.",
    typeValueInField: "Lauke „{field}“ įveskite „{value}“.",
    typeInField: "Užpildykite lauką „{field}“.",
    chooseValueIn: "Sąraše „{field}“ pasirinkite „{value}“.",
    chooseIn: "Pasirinkite parinktį sąraše „{field}“.",
    typeValue: "Įveskite „{value}“.",
    type: "Įveskite tekstą.",
    typeValueInCell: "Langelyje {cell} įveskite „{value}“.",
    typeInCell: "Užpildykite langelį {cell}.",
    press: "Paspauskite {keys}.",
    pressNamed: "Paspauskite {keys} ({name}).",
    goTo: "Eikite į {site}.",
    open: "Atidarykite {app}.",
    runIn: "Vykdykite šią komandą programoje „{where}“.",
    runInTerminal: "Vykdykite šią komandą terminale.",
    formulaInCell: "Langelyje {cell} įveskite šią formulę.",
    formulaInSelected: "Pažymėtame langelyje įveskite šią formulę.",
    code: "Įveskite šį kodą.",
    missed: {
      one: "Čia neįrašytas {count} spustelėjimas.",
      few: "Čia neįrašyti {count} spustelėjimai.",
      many: "Čia neįrašyta {count} spustelėjimų.",
      other: "Čia neįrašyta {count} spustelėjimų.",
    },
    touch: {
      one: "Čia galėjo būti neįrašyta lietimo ar rašiklio įvestis ({count} pranešimas).",
      few: "Čia galėjo būti neįrašyta lietimo ar rašiklio įvestis ({count} pranešimai).",
      many: "Čia galėjo būti neįrašyta lietimo ar rašiklio įvestis ({count} pranešimų).",
      other: "Čia galėjo būti neįrašyta lietimo ar rašiklio įvestis ({count} pranešimų).",
    },
    captureNow: "Peržiūrėkite šį ekraną.",
  },
  terminals: { powershell: "PowerShell", cmd: "Komandų eilutė", bash: "Bash" },
  shortcuts: {
    selectAll: "Pasirinkti viską",
    copy: "Kopijuoti",
    cut: "Iškirpti",
    paste: "Įklijuoti",
    save: "Įrašyti",
    print: "Spausdinti",
    find: "Rasti",
    close: "Uždaryti",
    taskManager: "Užduočių tvarkytuvė",
    showDesktop: "Rodyti darbalaukį",
    fileExplorer: "Failų naršyklė",
    settings: "Parametrai",
    lock: "Užrakinti",
    run: "Vykdyti",
    clipboardHistory: "Iškarpinės istorija",
    snippingTool: "Iškarpymo įrankis",
  },
};
