import type { LanguagePhrases } from "../phrase.ts";

/**
 * Latviešu: quotation marks “…” and the polite plural imperative (Noklikšķiniet) in every tone,
 * as Microsoft's Latvian documentation writes; casual is the bare instruction, plain uses
 * "Izvēlieties" and everyday words, formal full sentences naming each kind of control.
 */
export const lv: LanguagePhrases = {
  casual: {
    click: {
      field: "Noklikšķiniet laukā “{name}”",
      namedField: "Noklikšķiniet uz “{name}”",
      textArea: "Noklikšķiniet uz “{name}”",
      other: "Noklikšķiniet uz “{name}”",
    },
    clickIn: "Noklikšķiniet logā “{title}”",
    clickBare: "Noklikšķiniet",
    clickTaskbar: "Noklikšķiniet uz “{name}” uzdevumjoslā",
    rightClick: "Ar peles labo pogu noklikšķiniet uz “{name}”",
    rightClickIn: "Ar peles labo pogu noklikšķiniet logā “{title}”",
    rightClickBare: "Ar peles labo pogu noklikšķiniet",
    selectRange: "Atlasiet “{range}”",
    typeValueInField: "Ievadiet “{value}” laukā “{field}”",
    typeInField: "Ievadiet tekstu laukā “{field}”",
    chooseValueIn: "Izvēlieties “{value}” laukā “{field}”",
    chooseIn: "Izvēlieties laukā “{field}”",
    typeValue: "Ievadiet “{value}”",
    type: "Ievadiet tekstu",
    typeValueInCell: "Ievadiet “{value}” šūnā {cell}",
    typeInCell: "Ievadiet tekstu šūnā {cell}",
    press: "Nospiediet “{keys}”",
    goTo: "Dodieties uz “{site}”",
    open: "Atveriet “{app}”",
    runIn: "Izpildiet programmā “{where}”",
    runInTerminal: "Izpildiet terminālī",
    formulaInCell: "Ievadiet formulu šūnā {cell}",
    formulaInSelected: "Ievadiet formulu atlasītajā šūnā",
    code: "Ievadiet šo kodu",
    missed: {
      zero: "Šeit izlaisti {count} klikšķi",
      one: "Šeit izlaists {count} klikšķis",
      other: "Šeit izlaisti {count} klikšķi",
    },
    touch: {
      zero: "Skāriena vai pildspalvas darbības, iespējams, netika ierakstītas ({count} ziņojumu)",
      one: "Skāriena vai pildspalvas darbības, iespējams, netika ierakstītas ({count} ziņojums)",
      other: "Skāriena vai pildspalvas darbības, iespējams, netika ierakstītas ({count} ziņojumi)",
    },
    captureNow: "Uzņemiet šo ekrānu",
  },
  plain: {
    click: {
      button: "Izvēlieties pogu “{name}”",
      link: "Izvēlieties saiti “{name}”",
      menuItem: "Izvēlnē izvēlieties “{name}”",
      tab: "Izvēlieties cilni “{name}”",
      field: "Izvēlieties lauku “{name}”",
      checkbox: "Atzīmējiet rūtiņu “{name}”",
      radio: "Izvēlieties “{name}”",
      dropdown: "Atveriet sarakstu “{name}”",
      switch: "Izvēlieties slēdzi “{name}”",
      picture: "Izvēlieties attēlu “{name}”",
      other: "Izvēlieties “{name}”",
    },
    clickIn: "Izvēlieties vietu logā “{title}”",
    clickBare: "Izvēlieties šeit",
    clickTaskbar: "Uzdevumjoslā izvēlieties “{name}”",
    rightClick: "Ar peles labo pogu noklikšķiniet uz “{name}”",
    rightClickIn: "Ar peles labo pogu noklikšķiniet logā “{title}”",
    rightClickBare: "Ar peles labo pogu noklikšķiniet šeit",
    selectRange: "Atlasiet šūnas {range}",
    typeValueInField: "Ievadiet “{value}” laukā “{field}”",
    typeInField: "Aizpildiet lauku “{field}”",
    chooseValueIn: "Izvēlieties “{value}” no saraksta “{field}”",
    chooseIn: "Izvēlieties no saraksta “{field}”",
    typeValue: "Ievadiet “{value}”",
    type: "Ievadiet tekstu",
    typeValueInCell: "Ievadiet “{value}” šūnā {cell}",
    typeInCell: "Aizpildiet šūnu {cell}",
    press: "Nospiediet {keys}",
    goTo: "Dodieties uz {site}",
    open: "Atveriet {app}",
    runIn: "Palaidiet to programmā “{where}”",
    runInTerminal: "Palaidiet to terminālī",
    formulaInCell: "Ievadiet šo formulu šūnā {cell}",
    formulaInSelected: "Ievadiet šo formulu atlasītajā šūnā",
    code: "Ievadiet šo kodu",
    missed: {
      zero: "Šeit netika uztverti {count} klikšķi",
      one: "Šeit netika uztverts {count} klikšķis",
      other: "Šeit netika uztverti {count} klikšķi",
    },
    touch: {
      zero: "Šeit var trūkt skāriena vai pildspalvas darbību ({count} ziņojumu)",
      one: "Šeit var trūkt skāriena vai pildspalvas darbību ({count} ziņojums)",
      other: "Šeit var trūkt skāriena vai pildspalvas darbību ({count} ziņojumi)",
    },
    captureNow: "Apskatiet šo ekrānu",
  },
  formal: {
    click: {
      button: "Noklikšķiniet uz pogas “{name}”.",
      link: "Noklikšķiniet uz saites “{name}”.",
      menuItem: "Izvēlnē noklikšķiniet uz “{name}”.",
      tab: "Noklikšķiniet uz cilnes “{name}”.",
      field: "Noklikšķiniet laukā “{name}”.",
      checkbox: "Atzīmējiet izvēles rūtiņu “{name}”.",
      radio: "Atlasiet opciju “{name}”.",
      dropdown: "Noklikšķiniet uz nolaižamā saraksta “{name}”.",
      switch: "Noklikšķiniet uz slēdža “{name}”.",
      picture: "Noklikšķiniet uz attēla “{name}”.",
      other: "Noklikšķiniet uz “{name}”.",
    },
    clickIn: "Noklikšķiniet logā “{title}”.",
    clickBare: "Noklikšķiniet.",
    clickTaskbar: "Uzdevumjoslā noklikšķiniet uz “{name}”.",
    rightClick: "Ar peles labo pogu noklikšķiniet uz “{name}”.",
    rightClickIn: "Ar peles labo pogu noklikšķiniet logā “{title}”.",
    rightClickBare: "Ar peles labo pogu noklikšķiniet.",
    selectRange: "Atlasiet šūnas {range}.",
    typeValueInField: "Laukā “{field}” ievadiet “{value}”.",
    typeInField: "Aizpildiet lauku “{field}”.",
    chooseValueIn: "Sarakstā “{field}” izvēlieties “{value}”.",
    chooseIn: "Sarakstā “{field}” izvēlieties opciju.",
    typeValue: "Ievadiet “{value}”.",
    type: "Ievadiet tekstu.",
    typeValueInCell: "Šūnā {cell} ievadiet “{value}”.",
    typeInCell: "Aizpildiet šūnu {cell}.",
    press: "Nospiediet {keys}.",
    goTo: "Pārejiet uz {site}.",
    open: "Atveriet {app}.",
    runIn: "Izpildiet tālāk norādīto komandu programmā “{where}”.",
    runInTerminal: "Izpildiet tālāk norādīto komandu terminālī.",
    formulaInCell: "Šūnā {cell} ievadiet tālāk norādīto formulu.",
    formulaInSelected: "Atlasītajā šūnā ievadiet tālāk norādīto formulu.",
    code: "Ievadiet tālāk norādīto kodu.",
    missed: {
      zero: "Šeit netika ierakstīti {count} klikšķi.",
      one: "Šeit netika ierakstīts {count} klikšķis.",
      other: "Šeit netika ierakstīti {count} klikšķi.",
    },
    touch: {
      zero: "Šeit, iespējams, netika ierakstīta skāriena vai pildspalvas ievade ({count} ziņojumu).",
      one: "Šeit, iespējams, netika ierakstīta skāriena vai pildspalvas ievade ({count} ziņojums).",
      other:
        "Šeit, iespējams, netika ierakstīta skāriena vai pildspalvas ievade ({count} ziņojumi).",
    },
    captureNow: "Pārskatiet šo ekrānu.",
  },
  terminals: { powershell: "PowerShell", cmd: "Komandu uzvedne", bash: "Bash" },
};
