import type { LanguagePhrases } from "../phrase.ts";

/**
 * Malti: the imperative singular ("Ikklikkja"), as Microsoft's Maltese documentation addresses
 * the user; quotation marks are “…”. Casual is the shortest instruction, plain uses neutral
 * verbs ("Agħżel") and no marks round keys and addresses, formal is full sentences.
 */
export const mt: LanguagePhrases = {
  casual: {
    click: {
      field: "Ikklikkja l-għalqa “{name}”",
      namedField: "Ikklikkja “{name}”",
      textArea: "Ikklikkja “{name}”",
      other: "Ikklikkja “{name}”",
    },
    clickIn: "Ikklikkja f’“{title}”",
    clickBare: "Ikklikkja",
    clickTaskbar: "Ikklikkja “{name}” fit-taskbar",
    typeValueInField: "Ittajpja “{value}” fl-għalqa “{field}”",
    typeInField: "Ittajpja fl-għalqa “{field}”",
    chooseValueIn: "Agħżel “{value}” f’“{field}”",
    chooseIn: "Agħżel f’“{field}”",
    typeValue: "Ittajpja “{value}”",
    type: "Ittajpja",
    typeValueInCell: "Ittajpja “{value}” fiċ-ċellola {cell}",
    typeInCell: "Ittajpja fiċ-ċellola {cell}",
    press: "Agħfas “{keys}”",
    goTo: "Mur fuq “{site}”",
    open: "Iftaħ “{app}”",
    runIn: "Mexxi f’{where}",
    runInTerminal: "Mexxi fit-terminal",
    formulaInCell: "Ittajpja l-formula fiċ-ċellola {cell}",
    formulaInSelected: "Ittajpja l-formula fiċ-ċellola magħżula",
    code: "Ittajpja dan il-kodiċi",
    missed: {
      one: "Klikk wieħed nieqes hawn",
      two: "Żewġ klikkijiet neqsin hawn",
      few: "{count} klikkijiet neqsin hawn",
      many: "{count}-il klikk neqsin hawn",
      other: "{count} klikk neqsin hawn",
    },
    touch: {
      one: "Jista’ jkun li l-ħoss jew il-pinna ma ġewx irreġistrati ({count} rapport)",
      two: "Jista’ jkun li l-ħoss jew il-pinna ma ġewx irreġistrati ({count} rapporti)",
      few: "Jista’ jkun li l-ħoss jew il-pinna ma ġewx irreġistrati ({count} rapporti)",
      many: "Jista’ jkun li l-ħoss jew il-pinna ma ġewx irreġistrati ({count}-il rapport)",
      other: "Jista’ jkun li l-ħoss jew il-pinna ma ġewx irreġistrati ({count} rapport)",
    },
    captureNow: "Ikkattura dan l-iskrin",
  },
  plain: {
    click: {
      button: "Agħżel il-buttuna “{name}”",
      link: "Agħżel il-link “{name}”",
      menuItem: "Agħżel “{name}” fil-menu",
      tab: "Agħżel it-tab “{name}”",
      field: "Agħżel il-kaxxa “{name}”",
      checkbox: "Agħżel il-kaxxa tat-tiċkjar “{name}”",
      radio: "Agħżel “{name}”",
      dropdown: "Iftaħ il-lista “{name}”",
      switch: "Agħżel is-swiċċ “{name}”",
      picture: "Agħżel l-istampa “{name}”",
      other: "Agħżel “{name}”",
    },
    clickIn: "Agħżel ġewwa t-tieqa “{title}”",
    clickBare: "Agħżel hawn",
    clickTaskbar: "Agħżel “{name}” fit-taskbar",
    typeValueInField: "Daħħal “{value}” fil-kaxxa “{field}”",
    typeInField: "Imla l-kaxxa “{field}”",
    chooseValueIn: "Agħżel “{value}” mil-lista “{field}”",
    chooseIn: "Agħżel mil-lista “{field}”",
    typeValue: "Daħħal “{value}”",
    type: "Daħħal it-test",
    typeValueInCell: "Daħħal “{value}” fiċ-ċellola {cell}",
    typeInCell: "Imla ċ-ċellola {cell}",
    press: "Agħfas {keys}",
    goTo: "Mur fuq {site}",
    open: "Iftaħ {app}",
    runIn: "Mexxi dan f’{where}",
    runInTerminal: "Mexxi dan fit-terminal",
    formulaInCell: "Daħħal din il-formula fiċ-ċellola {cell}",
    formulaInSelected: "Daħħal din il-formula fiċ-ċellola magħżula",
    code: "Ittajpja dan il-kodiċi",
    missed: {
      one: "Klikk wieħed ma ġiex irreġistrat hawn",
      two: "Żewġ klikkijiet ma ġewx irreġistrati hawn",
      few: "{count} klikkijiet ma ġewx irreġistrati hawn",
      many: "{count}-il klikk ma ġewx irreġistrati hawn",
      other: "{count} klikk ma ġewx irreġistrati hawn",
    },
    touch: {
      one: "Jista’ jkun li l-użu tal-ħoss jew tal-pinna jonqos hawn ({count} rapport)",
      two: "Jista’ jkun li l-użu tal-ħoss jew tal-pinna jonqos hawn ({count} rapporti)",
      few: "Jista’ jkun li l-użu tal-ħoss jew tal-pinna jonqos hawn ({count} rapporti)",
      many: "Jista’ jkun li l-użu tal-ħoss jew tal-pinna jonqos hawn ({count}-il rapport)",
      other: "Jista’ jkun li l-użu tal-ħoss jew tal-pinna jonqos hawn ({count} rapport)",
    },
    captureNow: "Ħares lejn dan l-iskrin",
  },
  formal: {
    click: {
      button: "Ikklikkja l-buttuna “{name}”.",
      link: "Ikklikkja l-link “{name}”.",
      menuItem: "Ikklikkja “{name}” fil-menu.",
      tab: "Ikklikkja t-tab “{name}”.",
      field: "Ikklikkja fl-għalqa “{name}”.",
      checkbox: "Agħżel il-kaxxa tat-tiċkjar “{name}”.",
      radio: "Agħżel l-għażla “{name}”.",
      dropdown: "Ikklikkja l-lista drop-down “{name}”.",
      switch: "Ikklikkja s-swiċċ “{name}”.",
      picture: "Ikklikkja l-immaġni “{name}”.",
      other: "Ikklikkja “{name}”.",
    },
    clickIn: "Ikklikkja fit-tieqa “{title}”.",
    clickBare: "Ikklikkja.",
    clickTaskbar: "Ikklikkja “{name}” fit-taskbar.",
    typeValueInField: "Fl-għalqa “{field}”, ittajpja “{value}”.",
    typeInField: "Imla l-għalqa “{field}”.",
    chooseValueIn: "Fil-lista “{field}”, agħżel “{value}”.",
    chooseIn: "Agħżel għażla fil-lista “{field}”.",
    typeValue: "Ittajpja “{value}”.",
    type: "Ittajpja t-test.",
    typeValueInCell: "Fiċ-ċellola {cell}, ittajpja “{value}”.",
    typeInCell: "Imla ċ-ċellola {cell}.",
    press: "Agħfas {keys}.",
    goTo: "Mur fuq {site}.",
    open: "Iftaħ {app}.",
    runIn: "Mexxi l-kmand li ġej f’{where}.",
    runInTerminal: "Mexxi l-kmand li ġej fit-terminal.",
    formulaInCell: "Fiċ-ċellola {cell}, ittajpja l-formula li ġejja.",
    formulaInSelected: "Fiċ-ċellola magħżula, ittajpja l-formula li ġejja.",
    code: "Ittajpja l-kodiċi li ġej.",
    missed: {
      one: "Klikk wieħed ma ġiex irreġistrat hawn.",
      two: "Żewġ klikkijiet ma ġewx irreġistrati hawn.",
      few: "{count} klikkijiet ma ġewx irreġistrati hawn.",
      many: "{count}-il klikk ma ġewx irreġistrati hawn.",
      other: "{count} klikk ma ġewx irreġistrati hawn.",
    },
    touch: {
      one: "Jista’ jkun li l-input bil-ħoss jew bil-pinna ma ġiex irreġistrat hawn ({count} rapport).",
      two: "Jista’ jkun li l-input bil-ħoss jew bil-pinna ma ġiex irreġistrat hawn ({count} rapporti).",
      few: "Jista’ jkun li l-input bil-ħoss jew bil-pinna ma ġiex irreġistrat hawn ({count} rapporti).",
      many: "Jista’ jkun li l-input bil-ħoss jew bil-pinna ma ġiex irreġistrat hawn ({count}-il rapport).",
      other:
        "Jista’ jkun li l-input bil-ħoss jew bil-pinna ma ġiex irreġistrat hawn ({count} rapport).",
    },
    captureNow: "Irrevedi dan l-iskrin.",
  },
  terminals: { powershell: "PowerShell", cmd: "Command Prompt", bash: "Bash" },
};
