import type { LanguagePhrases } from "../phrase.ts";

/**
 * Norsk bokmål: Norwegian quotation marks «…» and the imperative with "du" implied throughout;
 * casual is short ("Klikk på «Lagre»"), plain follows klarspråk with the neutral "Velg" and
 * everyday words ("lenke"), and formal writes full sentences as Microsoft's Norwegian procedures
 * do ("Klikk på knappen «Lagre».").
 */
export const nb: LanguagePhrases = {
  casual: {
    click: {
      field: "Klikk i feltet «{name}»",
      namedField: "Klikk på «{name}»",
      textArea: "Klikk på «{name}»",
      other: "Klikk på «{name}»",
    },
    clickIn: "Klikk i «{title}»",
    clickBare: "Klikk",
    clickTaskbar: "Klikk på «{name}» på oppgavelinjen",
    typeValueInField: "Skriv «{value}» i feltet «{field}»",
    typeInField: "Skriv i feltet «{field}»",
    chooseValueIn: "Velg «{value}» i «{field}»",
    chooseIn: "Velg i «{field}»",
    typeValue: "Skriv «{value}»",
    type: "Skriv",
    typeValueInCell: "Skriv «{value}» i celle {cell}",
    typeInCell: "Skriv i celle {cell}",
    press: "Trykk på «{keys}»",
    goTo: "Gå til «{site}»",
    open: "Åpne «{app}»",
    runIn: "Kjør i {where}",
    runInTerminal: "Kjør i terminalen",
    formulaInCell: "Skriv formelen i celle {cell}",
    formulaInSelected: "Skriv formelen i den merkede cellen",
    code: "Skriv denne koden",
    missed: { one: "{count} klikk oversett her", other: "{count} klikk oversett her" },
    touch: {
      one: "Berørings- eller pennaktivitet ble kanskje ikke tatt opp ({count} rapport)",
      other: "Berørings- eller pennaktivitet ble kanskje ikke tatt opp ({count} rapporter)",
    },
    captureNow: "Ta bilde av denne skjermen",
  },
  plain: {
    click: {
      button: "Velg knappen «{name}»",
      link: "Velg lenken «{name}»",
      menuItem: "Velg «{name}» i menyen",
      tab: "Velg fanen «{name}»",
      field: "Velg feltet «{name}»",
      checkbox: "Velg avmerkingsboksen «{name}»",
      radio: "Velg «{name}»",
      dropdown: "Åpne listen «{name}»",
      switch: "Velg bryteren «{name}»",
      picture: "Velg bildet «{name}»",
      other: "Velg «{name}»",
    },
    clickIn: "Velg i vinduet «{title}»",
    clickBare: "Velg her",
    clickTaskbar: "Velg «{name}» på oppgavelinjen",
    typeValueInField: "Skriv «{value}» i feltet «{field}»",
    typeInField: "Fyll ut feltet «{field}»",
    chooseValueIn: "Velg «{value}» fra listen «{field}»",
    chooseIn: "Velg fra listen «{field}»",
    typeValue: "Skriv «{value}»",
    type: "Skriv inn teksten",
    typeValueInCell: "Skriv «{value}» i celle {cell}",
    typeInCell: "Fyll ut celle {cell}",
    press: "Trykk på {keys}",
    goTo: "Gå til {site}",
    open: "Åpne {app}",
    runIn: "Kjør dette i {where}",
    runInTerminal: "Kjør dette i terminalen",
    formulaInCell: "Skriv denne formelen i celle {cell}",
    formulaInSelected: "Skriv denne formelen i den merkede cellen",
    code: "Skriv denne koden",
    missed: { one: "{count} klikk ble oversett her", other: "{count} klikk ble oversett her" },
    touch: {
      one: "Bruk av berøring eller penn kan mangle her ({count} rapport)",
      other: "Bruk av berøring eller penn kan mangle her ({count} rapporter)",
    },
    captureNow: "Se på denne skjermen",
  },
  formal: {
    click: {
      button: "Klikk på knappen «{name}».",
      link: "Klikk på koblingen «{name}».",
      menuItem: "Klikk på «{name}» på menyen.",
      tab: "Klikk på fanen «{name}».",
      field: "Klikk i feltet «{name}».",
      checkbox: "Merk av for «{name}».",
      radio: "Velg alternativet «{name}».",
      dropdown: "Klikk på rullegardinlisten «{name}».",
      switch: "Klikk på veksleknappen «{name}».",
      picture: "Klikk på bildet «{name}».",
      other: "Klikk på «{name}».",
    },
    clickIn: "Klikk i vinduet «{title}».",
    clickBare: "Klikk.",
    clickTaskbar: "Klikk på «{name}» på oppgavelinjen.",
    typeValueInField: "Skriv inn «{value}» i feltet «{field}».",
    typeInField: "Fyll ut feltet «{field}».",
    chooseValueIn: "Velg «{value}» i listen «{field}».",
    chooseIn: "Velg et alternativ i listen «{field}».",
    typeValue: "Skriv inn «{value}».",
    type: "Skriv inn teksten.",
    typeValueInCell: "Skriv inn «{value}» i celle {cell}.",
    typeInCell: "Fyll ut celle {cell}.",
    press: "Trykk på {keys}.",
    goTo: "Gå til {site}.",
    open: "Åpne {app}.",
    runIn: "Kjør følgende kommando i {where}.",
    runInTerminal: "Kjør følgende kommando i terminalen.",
    formulaInCell: "Skriv inn følgende formel i celle {cell}.",
    formulaInSelected: "Skriv inn følgende formel i den merkede cellen.",
    code: "Skriv inn følgende kode.",
    missed: {
      one: "{count} klikk ble ikke tatt opp her.",
      other: "{count} klikk ble ikke tatt opp her.",
    },
    touch: {
      one: "Berørings- eller penninndata er kanskje ikke tatt opp her ({count} rapport).",
      other: "Berørings- eller penninndata er kanskje ikke tatt opp her ({count} rapporter).",
    },
    captureNow: "Gå gjennom denne skjermen.",
  },
  terminals: { powershell: "PowerShell", cmd: "Ledetekst", bash: "Bash" },
};
