import type { LanguagePhrases } from "../phrase.ts";

/**
 * Nederlands: curly double quotes (“…”) round names and values; every tone uses the imperative,
 * as Dutch instructions do, so no form of address is needed: casual is Steps' short "Klik op",
 * plain language the everyday "Kies" and "Vul in" of Dutch plain-language guidance, and formal
 * the full sentences of Microsoft's Dutch procedure documentation ("Schakel het selectievakje in").
 */
export const nl: LanguagePhrases = {
  casual: {
    click: {
      field: "Klik op veld “{name}”",
      namedField: "Klik op “{name}”",
      textArea: "Klik op “{name}”",
      other: "Klik op “{name}”",
    },
    clickIn: "Klik in “{title}”",
    clickBare: "Klik",
    clickTaskbar: "Klik op “{name}” op de taakbalk",
    rightClick: "Klik met de rechtermuisknop op “{name}”",
    rightClickIn: "Klik met de rechtermuisknop in “{title}”",
    rightClickBare: "Klik met de rechtermuisknop",
    selectRange: "Selecteer “{range}”",
    fillDown: "Voer “{from}” omlaag door tot “{to}”",
    fillTo: "Voer “{from}” door tot “{to}”",
    fillColumn: "Voer “{from}” omlaag door in de kolonne",
    typeValueInField: "Typ “{value}” in veld “{field}”",
    typeInField: "Typ in veld “{field}”",
    chooseValueIn: "Kies “{value}” in “{field}”",
    chooseIn: "Kies in “{field}”",
    typeValue: "Typ “{value}”",
    type: "Typ",
    typeValueInCell: "Typ “{value}” in cel {cell}",
    typeInCell: "Typ in cel {cell}",
    press: "Druk op “{keys}”",
    pressNamed: "Druk op “{keys}” ({name})",
    goTo: "Ga naar “{site}”",
    open: "Open “{app}”",
    runIn: "Uitvoeren in {where}",
    runInTerminal: "Uitvoeren in de terminal",
    formulaInCell: "Typ de formule in cel {cell}",
    formulaInSelected: "Typ de formule in de geselecteerde cel",
    code: "Typ deze code",
    missed: { one: "{count} klik hier gemist", other: "{count} klikken hier gemist" },
    touch: {
      one: "Aanraak- of penactiviteit mogelijk niet opgenomen ({count} melding)",
      other: "Aanraak- of penactiviteit mogelijk niet opgenomen ({count} meldingen)",
    },
    captureNow: "Leg dit scherm vast",
  },
  plain: {
    click: {
      button: "Kies de knop “{name}”",
      link: "Kies de link “{name}”",
      menuItem: "Kies “{name}” in het menu",
      tab: "Kies het tabblad “{name}”",
      field: "Kies het vak “{name}”",
      checkbox: "Vink “{name}” aan",
      radio: "Kies “{name}”",
      dropdown: "Open de lijst “{name}”",
      switch: "Kies de schakelaar “{name}”",
      picture: "Kies de afbeelding “{name}”",
      other: "Kies “{name}”",
    },
    clickIn: "Kies binnen het venster “{title}”",
    clickBare: "Kies hier",
    clickTaskbar: "Kies “{name}” op de taakbalk",
    rightClick: "Klik met de rechtermuisknop op “{name}”",
    rightClickIn: "Klik met de rechtermuisknop in het venster “{title}”",
    rightClickBare: "Klik hier met de rechtermuisknop",
    selectRange: "Selecteer de cellen {range}",
    fillDown: "Voer cel {from} omlaag door tot cel {to}",
    fillTo: "Voer cel {from} door tot cel {to}",
    fillColumn: "Voer cel {from} omlaag door in de kolonne",
    typeValueInField: "Vul “{value}” in bij “{field}”",
    typeInField: "Vul het vak “{field}” in",
    chooseValueIn: "Kies “{value}” in de lijst “{field}”",
    chooseIn: "Kies in de lijst “{field}”",
    typeValue: "Vul “{value}” in",
    type: "Vul de tekst in",
    typeValueInCell: "Zet “{value}” in cel {cell}",
    typeInCell: "Vul cel {cell} in",
    press: "Druk op {keys}",
    pressNamed: "Druk op {keys} ({name})",
    goTo: "Ga naar {site}",
    open: "Open {app}",
    runIn: "Voer dit uit in {where}",
    runInTerminal: "Voer dit uit in de terminal",
    formulaInCell: "Zet deze formule in cel {cell}",
    formulaInSelected: "Zet deze formule in de gekozen cel",
    code: "Typ deze code",
    missed: {
      one: "{count} klik is hier gemist",
      other: "{count} klikken zijn hier gemist",
    },
    touch: {
      one: "Aanraken of pen ontbreekt hier misschien ({count} melding)",
      other: "Aanraken of pen ontbreekt hier misschien ({count} meldingen)",
    },
    captureNow: "Bekijk dit scherm",
  },
  formal: {
    click: {
      button: "Klik op de knop “{name}”.",
      link: "Klik op de koppeling “{name}”.",
      menuItem: "Klik in het menu op “{name}”.",
      tab: "Klik op het tabblad “{name}”.",
      field: "Klik in het veld “{name}”.",
      checkbox: "Schakel het selectievakje “{name}” in.",
      radio: "Selecteer de optie “{name}”.",
      dropdown: "Klik op de vervolgkeuzelijst “{name}”.",
      switch: "Klik op de schakelaar “{name}”.",
      picture: "Klik op de afbeelding “{name}”.",
      other: "Klik op “{name}”.",
    },
    clickIn: "Klik in het venster “{title}”.",
    clickBare: "Klik hier.",
    clickTaskbar: "Klik op de taakbalk op “{name}”.",
    rightClick: "Klik met de rechtermuisknop op “{name}”.",
    rightClickIn: "Klik met de rechtermuisknop in het venster “{title}”.",
    rightClickBare: "Klik met de rechtermuisknop.",
    selectRange: "Selecteer de cellen {range}.",
    fillDown: "Voer cel {from} omlaag door tot cel {to}.",
    fillTo: "Voer cel {from} door tot cel {to}.",
    fillColumn: "Voer cel {from} omlaag door in de kolonne.",
    typeValueInField: "Typ “{value}” in het veld “{field}”.",
    typeInField: "Vul het veld “{field}” in.",
    chooseValueIn: "Selecteer in de lijst “{field}” de optie “{value}”.",
    chooseIn: "Selecteer een optie in de lijst “{field}”.",
    typeValue: "Typ “{value}”.",
    type: "Typ de tekst.",
    typeValueInCell: "Typ “{value}” in cel {cell}.",
    typeInCell: "Vul cel {cell} in.",
    press: "Druk op {keys}.",
    pressNamed: "Druk op {keys} ({name}).",
    goTo: "Ga naar {site}.",
    open: "Open {app}.",
    runIn: "Voer de volgende opdracht uit in {where}.",
    runInTerminal: "Voer de volgende opdracht uit in de terminal.",
    formulaInCell: "Typ de volgende formule in cel {cell}.",
    formulaInSelected: "Typ de volgende formule in de geselecteerde cel.",
    code: "Typ de volgende code.",
    missed: {
      one: "{count} klik is hier niet opgenomen.",
      other: "{count} klikken zijn hier niet opgenomen.",
    },
    touch: {
      one: "Aanraak- of peninvoer is hier mogelijk niet opgenomen ({count} melding).",
      other: "Aanraak- of peninvoer is hier mogelijk niet opgenomen ({count} meldingen).",
    },
    captureNow: "Controleer dit scherm.",
  },
  terminals: { powershell: "PowerShell", cmd: "Opdrachtprompt", bash: "Bash" },
  shortcuts: {
    selectAll: "Alles selecteren",
    copy: "Kopiëren",
    cut: "Knippen",
    paste: "Plakken",
    save: "Opslaan",
    print: "Afdrukken",
    find: "Zoeken",
    close: "Sluiten",
    taskManager: "Taakbeheer",
    showDesktop: "Bureaublad weergeven",
    fileExplorer: "Verkenner",
    settings: "Instellingen",
    lock: "Vergrendelen",
    run: "Uitvoeren",
    clipboardHistory: "Klembordgeschiedenis",
    snippingTool: "Knipprogramma",
  },
};
