import type { LanguagePhrases } from "../phrase.ts";

/**
 * Polski: names in „…”; casual and plain address the reader with the imperative as Windows does
 * („Kliknij”, plain „Wybierz”), and formal uses the impersonal infinitive of Polish procedures
 * („Kliknąć przycisk „Zapisz”.”).
 */
export const pl: LanguagePhrases = {
  casual: {
    click: {
      field: "Kliknij pole „{name}”",
      namedField: "Kliknij „{name}”",
      textArea: "Kliknij „{name}”",
      other: "Kliknij „{name}”",
    },
    clickIn: "Kliknij w oknie „{title}”",
    clickBare: "Kliknij",
    clickTaskbar: "Kliknij „{name}” na pasku zadań",
    rightClick: "Kliknij prawym przyciskiem myszy „{name}”",
    rightClickIn: "Kliknij prawym przyciskiem myszy w oknie „{title}”",
    rightClickBare: "Kliknij prawym przyciskiem myszy",
    selectRange: "Zaznacz „{range}”",
    typeValueInField: "Wpisz „{value}” w polu „{field}”",
    typeInField: "Wpisz tekst w polu „{field}”",
    chooseValueIn: "Wybierz „{value}” w polu „{field}”",
    chooseIn: "Wybierz w polu „{field}”",
    typeValue: "Wpisz „{value}”",
    type: "Wpisz tekst",
    typeValueInCell: "Wpisz „{value}” w komórce {cell}",
    typeInCell: "Wpisz tekst w komórce {cell}",
    press: "Naciśnij „{keys}”",
    goTo: "Przejdź do „{site}”",
    open: "Otwórz „{app}”",
    runIn: "Uruchom w oknie {where}",
    runInTerminal: "Uruchom w terminalu",
    formulaInCell: "Wpisz formułę w komórce {cell}",
    formulaInSelected: "Wpisz formułę w zaznaczonej komórce",
    code: "Wpisz ten kod",
    missed: {
      one: "Pominięto tu {count} kliknięcie",
      few: "Pominięto tu {count} kliknięcia",
      many: "Pominięto tu {count} kliknięć",
      other: "Pominięto tu {count} kliknięć",
    },
    touch: {
      one: "Dotyk lub pióro mogły nie zostać nagrane ({count} zgłoszenie)",
      few: "Dotyk lub pióro mogły nie zostać nagrane ({count} zgłoszenia)",
      many: "Dotyk lub pióro mogły nie zostać nagrane ({count} zgłoszeń)",
      other: "Dotyk lub pióro mogły nie zostać nagrane ({count} zgłoszeń)",
    },
    captureNow: "Przechwyć ten ekran",
  },
  plain: {
    click: {
      button: "Wybierz przycisk „{name}”",
      link: "Wybierz link „{name}”",
      menuItem: "Wybierz „{name}” w menu",
      tab: "Wybierz kartę „{name}”",
      field: "Wybierz pole „{name}”",
      checkbox: "Zaznacz pole „{name}”",
      radio: "Wybierz opcję „{name}”",
      dropdown: "Otwórz listę „{name}”",
      switch: "Wybierz przełącznik „{name}”",
      picture: "Wybierz obraz „{name}”",
      other: "Wybierz „{name}”",
    },
    clickIn: "Wybierz miejsce w oknie „{title}”",
    clickBare: "Wybierz to miejsce",
    clickTaskbar: "Wybierz „{name}” na pasku zadań",
    rightClick: "Kliknij prawym przyciskiem myszy „{name}”",
    rightClickIn: "Kliknij prawym przyciskiem myszy w oknie „{title}”",
    rightClickBare: "Kliknij prawym przyciskiem myszy w tym miejscu",
    selectRange: "Zaznacz komórki {range}",
    typeValueInField: "Wpisz „{value}” w polu „{field}”",
    typeInField: "Wypełnij pole „{field}”",
    chooseValueIn: "Wybierz „{value}” z listy „{field}”",
    chooseIn: "Wybierz opcję z listy „{field}”",
    typeValue: "Wpisz „{value}”",
    type: "Wpisz tekst",
    typeValueInCell: "Wpisz „{value}” w komórce {cell}",
    typeInCell: "Wypełnij komórkę {cell}",
    press: "Naciśnij {keys}",
    goTo: "Przejdź do {site}",
    open: "Otwórz {app}",
    runIn: "Uruchom to w oknie {where}",
    runInTerminal: "Uruchom to w terminalu",
    formulaInCell: "Wpisz tę formułę w komórce {cell}",
    formulaInSelected: "Wpisz tę formułę w zaznaczonej komórce",
    code: "Wpisz ten kod",
    missed: {
      one: "W tym miejscu pominięto {count} kliknięcie",
      few: "W tym miejscu pominięto {count} kliknięcia",
      many: "W tym miejscu pominięto {count} kliknięć",
      other: "W tym miejscu pominięto {count} kliknięć",
    },
    touch: {
      one: "Może tu brakować użycia dotyku lub pióra ({count} zgłoszenie)",
      few: "Może tu brakować użycia dotyku lub pióra ({count} zgłoszenia)",
      many: "Może tu brakować użycia dotyku lub pióra ({count} zgłoszeń)",
      other: "Może tu brakować użycia dotyku lub pióra ({count} zgłoszeń)",
    },
    captureNow: "Zobacz ten ekran",
  },
  formal: {
    click: {
      button: "Kliknąć przycisk „{name}”.",
      link: "Kliknąć link „{name}”.",
      menuItem: "Kliknąć polecenie „{name}” w menu.",
      tab: "Kliknąć kartę „{name}”.",
      field: "Kliknąć pole „{name}”.",
      checkbox: "Zaznaczyć pole wyboru „{name}”.",
      radio: "Wybrać opcję „{name}”.",
      dropdown: "Kliknąć listę rozwijaną „{name}”.",
      switch: "Kliknąć przełącznik „{name}”.",
      picture: "Kliknąć obraz „{name}”.",
      other: "Kliknąć „{name}”.",
    },
    clickIn: "Kliknąć w oknie „{title}”.",
    clickBare: "Kliknąć.",
    clickTaskbar: "Kliknąć „{name}” na pasku zadań.",
    rightClick: "Kliknąć prawym przyciskiem myszy „{name}”.",
    rightClickIn: "Kliknąć prawym przyciskiem myszy w oknie „{title}”.",
    rightClickBare: "Kliknąć prawym przyciskiem myszy.",
    selectRange: "Zaznaczyć komórki {range}.",
    typeValueInField: "W polu „{field}” wpisać „{value}”.",
    typeInField: "Wypełnić pole „{field}”.",
    chooseValueIn: "Na liście „{field}” wybrać „{value}”.",
    chooseIn: "Wybrać opcję na liście „{field}”.",
    typeValue: "Wpisać „{value}”.",
    type: "Wpisać tekst.",
    typeValueInCell: "W komórce {cell} wpisać „{value}”.",
    typeInCell: "Wypełnić komórkę {cell}.",
    press: "Nacisnąć {keys}.",
    goTo: "Przejść do witryny {site}.",
    open: "Otworzyć aplikację {app}.",
    runIn: "Uruchomić następujące polecenie w oknie {where}.",
    runInTerminal: "Uruchomić następujące polecenie w terminalu.",
    formulaInCell: "W komórce {cell} wpisać następującą formułę.",
    formulaInSelected: "W zaznaczonej komórce wpisać następującą formułę.",
    code: "Wpisać następujący kod.",
    missed: {
      one: "W tym miejscu nie zarejestrowano {count} kliknięcia.",
      few: "W tym miejscu nie zarejestrowano {count} kliknięć.",
      many: "W tym miejscu nie zarejestrowano {count} kliknięć.",
      other: "W tym miejscu nie zarejestrowano {count} kliknięć.",
    },
    touch: {
      one: "Dotyk lub pióro mogły nie zostać tu zarejestrowane ({count} zgłoszenie).",
      few: "Dotyk lub pióro mogły nie zostać tu zarejestrowane ({count} zgłoszenia).",
      many: "Dotyk lub pióro mogły nie zostać tu zarejestrowane ({count} zgłoszeń).",
      other: "Dotyk lub pióro mogły nie zostać tu zarejestrowane ({count} zgłoszeń).",
    },
    captureNow: "Przejrzeć ten ekran.",
  },
  terminals: { powershell: "PowerShell", cmd: "Wiersz polecenia", bash: "Bash" },
};
