import type { LanguagePhrases } from "../phrase.ts";

/**
 * Português (Brasil): names in curly quotes (“Salvar”), the reader addressed with the imperative
 * as Microsoft's Brazilian style does ("Clique", "Digite"); casual is the shortest imperative with
 * no full stop, plain uses the neutral "Selecione" and everyday words, formal writes full sentences
 * as Microsoft's procedure documentation does.
 */
export const ptBR: LanguagePhrases = {
  casual: {
    click: {
      field: "Clique no campo “{name}”",
      namedField: "Clique em “{name}”",
      textArea: "Clique em “{name}”",
      other: "Clique em “{name}”",
    },
    clickIn: "Clique na janela “{title}”",
    clickBare: "Clique",
    clickTaskbar: "Clique em “{name}” na barra de tarefas",
    rightClick: "Clique com o botão direito em “{name}”",
    rightClickIn: "Clique com o botão direito na janela “{title}”",
    rightClickBare: "Clique com o botão direito",
    selectRange: "Selecione “{range}”",
    typeValueInField: "Digite “{value}” no campo “{field}”",
    typeInField: "Digite no campo “{field}”",
    chooseValueIn: "Escolha “{value}” em “{field}”",
    chooseIn: "Escolha em “{field}”",
    typeValue: "Digite “{value}”",
    type: "Digite",
    typeValueInCell: "Digite “{value}” na célula {cell}",
    typeInCell: "Digite na célula {cell}",
    press: "Pressione “{keys}”",
    goTo: "Acesse “{site}”",
    open: "Abra “{app}”",
    runIn: "Execute no {where}",
    runInTerminal: "Execute no terminal",
    formulaInCell: "Digite a fórmula na célula {cell}",
    formulaInSelected: "Digite a fórmula na célula selecionada",
    code: "Digite este código",
    missed: {
      one: "{count} clique perdido aqui",
      many: "{count} cliques perdidos aqui",
      other: "{count} cliques perdidos aqui",
    },
    touch: {
      one: "O toque ou a caneta podem não ter sido gravados ({count} aviso)",
      many: "O toque ou a caneta podem não ter sido gravados ({count} avisos)",
      other: "O toque ou a caneta podem não ter sido gravados ({count} avisos)",
    },
    captureNow: "Capture esta tela",
  },
  plain: {
    click: {
      button: "Selecione o botão “{name}”",
      link: "Selecione o link “{name}”",
      menuItem: "Selecione “{name}” no menu",
      tab: "Selecione a aba “{name}”",
      field: "Selecione a caixa “{name}”",
      checkbox: "Selecione a caixa de seleção “{name}”",
      radio: "Escolha “{name}”",
      dropdown: "Abra a lista “{name}”",
      switch: "Selecione a chave “{name}”",
      picture: "Selecione a imagem “{name}”",
      other: "Selecione “{name}”",
    },
    clickIn: "Selecione aqui na janela “{title}”",
    clickBare: "Selecione aqui",
    clickTaskbar: "Selecione “{name}” na barra de tarefas",
    rightClick: "Clique com o botão direito em “{name}”",
    rightClickIn: "Clique com o botão direito aqui na janela “{title}”",
    rightClickBare: "Clique com o botão direito aqui",
    selectRange: "Selecione as células {range}",
    typeValueInField: "Digite “{value}” na caixa “{field}”",
    typeInField: "Preencha a caixa “{field}”",
    chooseValueIn: "Escolha “{value}” na lista “{field}”",
    chooseIn: "Escolha na lista “{field}”",
    typeValue: "Digite “{value}”",
    type: "Digite o texto",
    typeValueInCell: "Digite “{value}” na célula {cell}",
    typeInCell: "Preencha a célula {cell}",
    press: "Pressione {keys}",
    goTo: "Acesse {site}",
    open: "Abra {app}",
    runIn: "Execute isto no {where}",
    runInTerminal: "Execute isto no terminal",
    formulaInCell: "Digite esta fórmula na célula {cell}",
    formulaInSelected: "Digite esta fórmula na célula selecionada",
    code: "Digite este código",
    missed: {
      one: "{count} clique foi perdido aqui",
      many: "{count} cliques foram perdidos aqui",
      other: "{count} cliques foram perdidos aqui",
    },
    touch: {
      one: "Pode faltar aqui o uso de toque ou caneta ({count} aviso)",
      many: "Pode faltar aqui o uso de toque ou caneta ({count} avisos)",
      other: "Pode faltar aqui o uso de toque ou caneta ({count} avisos)",
    },
    captureNow: "Veja esta tela",
  },
  formal: {
    click: {
      button: "Clique no botão “{name}”.",
      link: "Clique no link “{name}”.",
      menuItem: "Clique em “{name}” no menu.",
      tab: "Clique na guia “{name}”.",
      field: "Clique no campo “{name}”.",
      checkbox: "Marque a caixa de seleção “{name}”.",
      radio: "Selecione a opção “{name}”.",
      dropdown: "Clique na lista suspensa “{name}”.",
      switch: "Clique no botão de alternância “{name}”.",
      picture: "Clique na imagem “{name}”.",
      other: "Clique em “{name}”.",
    },
    clickIn: "Clique na janela “{title}”.",
    clickBare: "Clique.",
    clickTaskbar: "Clique em “{name}” na barra de tarefas.",
    rightClick: "Clique com o botão direito em “{name}”.",
    rightClickIn: "Clique com o botão direito na janela “{title}”.",
    rightClickBare: "Clique com o botão direito.",
    selectRange: "Selecione as células {range}.",
    typeValueInField: "No campo “{field}”, digite “{value}”.",
    typeInField: "Preencha o campo “{field}”.",
    chooseValueIn: "Na lista “{field}”, selecione “{value}”.",
    chooseIn: "Na lista “{field}”, selecione uma opção.",
    typeValue: "Digite “{value}”.",
    type: "Digite o texto.",
    typeValueInCell: "Na célula {cell}, digite “{value}”.",
    typeInCell: "Preencha a célula {cell}.",
    press: "Pressione {keys}.",
    goTo: "Navegue até {site}.",
    open: "Abra {app}.",
    runIn: "Execute o seguinte comando no {where}.",
    runInTerminal: "Execute o seguinte comando no terminal.",
    formulaInCell: "Na célula {cell}, digite a seguinte fórmula.",
    formulaInSelected: "Na célula selecionada, digite a seguinte fórmula.",
    code: "Digite o seguinte código.",
    missed: {
      one: "{count} clique não foi registrado aqui.",
      many: "{count} cliques não foram registrados aqui.",
      other: "{count} cliques não foram registrados aqui.",
    },
    touch: {
      one: "A entrada por toque ou caneta pode não ter sido registrada aqui ({count} aviso).",
      many: "A entrada por toque ou caneta pode não ter sido registrada aqui ({count} avisos).",
      other: "A entrada por toque ou caneta pode não ter sido registrada aqui ({count} avisos).",
    },
    captureNow: "Revise esta tela.",
  },
  terminals: { powershell: "PowerShell", cmd: "Prompt de Comando", bash: "Bash" },
};
