import type { LanguagePhrases } from "../phrase.ts";

/**
 * Português (Portugal): names in angle quotes («Guardar»), the reader addressed with the formal
 * imperative and no "você", as Microsoft's European Portuguese style does ("Clique", "Escreva",
 * "Prima"); casual is the shortest imperative with no full stop, plain uses the neutral
 * "Selecione" and everyday words (linguagem clara), formal writes full sentences as Microsoft's
 * procedure documentation does.
 */
export const ptPT: LanguagePhrases = {
  casual: {
    click: {
      field: "Clique no campo «{name}»",
      namedField: "Clique em «{name}»",
      textArea: "Clique em «{name}»",
      other: "Clique em «{name}»",
    },
    clickIn: "Clique na janela «{title}»",
    clickBare: "Clique",
    clickTaskbar: "Clique em «{name}» na barra de tarefas",
    rightClick: "Clique com o botão direito do rato em «{name}»",
    rightClickIn: "Clique com o botão direito do rato na janela «{title}»",
    rightClickBare: "Clique com o botão direito do rato",
    selectRange: "Selecione «{range}»",
    typeValueInField: "Escreva «{value}» no campo «{field}»",
    typeInField: "Escreva no campo «{field}»",
    chooseValueIn: "Escolha «{value}» em «{field}»",
    chooseIn: "Escolha em «{field}»",
    typeValue: "Escreva «{value}»",
    type: "Escreva",
    typeValueInCell: "Escreva «{value}» na célula {cell}",
    typeInCell: "Escreva na célula {cell}",
    press: "Prima «{keys}»",
    goTo: "Aceda a «{site}»",
    open: "Abra «{app}»",
    runIn: "Execute em {where}",
    runInTerminal: "Execute no terminal",
    formulaInCell: "Escreva a fórmula na célula {cell}",
    formulaInSelected: "Escreva a fórmula na célula selecionada",
    code: "Escreva este código",
    missed: {
      one: "{count} clique perdido aqui",
      many: "{count} cliques perdidos aqui",
      other: "{count} cliques perdidos aqui",
    },
    touch: {
      one: "O toque ou a caneta podem não ter sido gravados ({count} aviso)",
      many: "O toque ou a caneta podem não ter sido gravados ({count} avisos)",
      other: "O toque ou a caneta podem não ter sido gravados ({count} avisos)",
    },
    captureNow: "Capture este ecrã",
  },
  plain: {
    click: {
      button: "Selecione o botão «{name}»",
      link: "Selecione a ligação «{name}»",
      menuItem: "Selecione «{name}» no menu",
      tab: "Selecione o separador «{name}»",
      field: "Selecione a caixa «{name}»",
      checkbox: "Selecione a caixa de verificação «{name}»",
      radio: "Escolha «{name}»",
      dropdown: "Abra a lista «{name}»",
      switch: "Selecione o interruptor «{name}»",
      picture: "Selecione a imagem «{name}»",
      other: "Selecione «{name}»",
    },
    clickIn: "Selecione aqui na janela «{title}»",
    clickBare: "Selecione aqui",
    clickTaskbar: "Selecione «{name}» na barra de tarefas",
    rightClick: "Clique com o botão direito do rato em «{name}»",
    rightClickIn: "Clique com o botão direito do rato aqui na janela «{title}»",
    rightClickBare: "Clique com o botão direito do rato aqui",
    selectRange: "Selecione as células {range}",
    typeValueInField: "Escreva «{value}» na caixa «{field}»",
    typeInField: "Preencha a caixa «{field}»",
    chooseValueIn: "Escolha «{value}» na lista «{field}»",
    chooseIn: "Escolha na lista «{field}»",
    typeValue: "Escreva «{value}»",
    type: "Escreva o texto",
    typeValueInCell: "Escreva «{value}» na célula {cell}",
    typeInCell: "Preencha a célula {cell}",
    press: "Prima {keys}",
    goTo: "Aceda a {site}",
    open: "Abra {app}",
    runIn: "Execute isto em {where}",
    runInTerminal: "Execute isto no terminal",
    formulaInCell: "Escreva esta fórmula na célula {cell}",
    formulaInSelected: "Escreva esta fórmula na célula selecionada",
    code: "Escreva este código",
    missed: {
      one: "Perdeu-se {count} clique aqui",
      many: "Perderam-se {count} cliques aqui",
      other: "Perderam-se {count} cliques aqui",
    },
    touch: {
      one: "Pode faltar aqui a utilização de toque ou caneta ({count} aviso)",
      many: "Pode faltar aqui a utilização de toque ou caneta ({count} avisos)",
      other: "Pode faltar aqui a utilização de toque ou caneta ({count} avisos)",
    },
    captureNow: "Veja este ecrã",
  },
  formal: {
    click: {
      button: "Clique no botão «{name}».",
      link: "Clique na ligação «{name}».",
      menuItem: "Clique em «{name}» no menu.",
      tab: "Clique no separador «{name}».",
      field: "Clique no campo «{name}».",
      checkbox: "Selecione a caixa de verificação «{name}».",
      radio: "Selecione a opção «{name}».",
      dropdown: "Clique na lista pendente «{name}».",
      switch: "Clique no botão de alternar «{name}».",
      picture: "Clique na imagem «{name}».",
      other: "Clique em «{name}».",
    },
    clickIn: "Clique na janela «{title}».",
    clickBare: "Clique.",
    clickTaskbar: "Clique em «{name}» na barra de tarefas.",
    rightClick: "Clique com o botão direito do rato em «{name}».",
    rightClickIn: "Clique com o botão direito do rato na janela «{title}».",
    rightClickBare: "Clique com o botão direito do rato.",
    selectRange: "Selecione as células {range}.",
    typeValueInField: "No campo «{field}», escreva «{value}».",
    typeInField: "Preencha o campo «{field}».",
    chooseValueIn: "Na lista «{field}», selecione «{value}».",
    chooseIn: "Na lista «{field}», selecione uma opção.",
    typeValue: "Escreva «{value}».",
    type: "Escreva o texto.",
    typeValueInCell: "Na célula {cell}, escreva «{value}».",
    typeInCell: "Preencha a célula {cell}.",
    press: "Prima {keys}.",
    goTo: "Navegue até {site}.",
    open: "Abra {app}.",
    runIn: "Execute o seguinte comando em {where}.",
    runInTerminal: "Execute o seguinte comando no terminal.",
    formulaInCell: "Na célula {cell}, escreva a seguinte fórmula.",
    formulaInSelected: "Na célula selecionada, escreva a seguinte fórmula.",
    code: "Escreva o seguinte código.",
    missed: {
      one: "{count} clique não foi registado aqui.",
      many: "{count} cliques não foram registados aqui.",
      other: "{count} cliques não foram registados aqui.",
    },
    touch: {
      one: "A entrada por toque ou caneta pode não ter sido registada aqui ({count} aviso).",
      many: "A entrada por toque ou caneta pode não ter sido registada aqui ({count} avisos).",
      other: "A entrada por toque ou caneta pode não ter sido registada aqui ({count} avisos).",
    },
    captureNow: "Reveja este ecrã.",
  },
  terminals: { powershell: "PowerShell", cmd: "Linha de Comandos", bash: "Bash" },
};
