import type { LanguagePhrases } from "../phrase.ts";

/**
 * Română: Romanian quotation marks („…”), the polite plural imperative Microsoft uses in Windows
 * ("Faceți clic", "Tastați"); casual is as short as a step label can be ("Clic pe „Salvare”"),
 * plain uses "Selectați" and everyday words, formal follows Microsoft's procedure documentation.
 * Counted forms follow Romanian's three plural categories ("2 clicuri", "20 de clicuri").
 */
export const ro: LanguagePhrases = {
  casual: {
    click: {
      field: "Clic pe câmpul „{name}”",
      namedField: "Clic pe „{name}”",
      textArea: "Clic pe „{name}”",
      other: "Clic pe „{name}”",
    },
    clickIn: "Clic în „{title}”",
    clickBare: "Clic",
    clickTaskbar: "Clic pe „{name}” în bara de activități",
    typeValueInField: "Tastați „{value}” în câmpul „{field}”",
    typeInField: "Tastați în câmpul „{field}”",
    chooseValueIn: "Alegeți „{value}” în câmpul „{field}”",
    chooseIn: "Alegeți în câmpul „{field}”",
    typeValue: "Tastați „{value}”",
    type: "Tastați",
    typeValueInCell: "Tastați „{value}” în celula {cell}",
    typeInCell: "Tastați în celula {cell}",
    press: "Apăsați „{keys}”",
    goTo: "Accesați „{site}”",
    open: "Deschideți „{app}”",
    runIn: "Rulați în {where}",
    runInTerminal: "Rulați în terminal",
    formulaInCell: "Tastați formula în celula {cell}",
    formulaInSelected: "Tastați formula în celula selectată",
    code: "Tastați acest cod",
    missed: {
      one: "{count} clic omis aici",
      few: "{count} clicuri omise aici",
      other: "{count} de clicuri omise aici",
    },
    touch: {
      one: "Atingerile sau stiloul pot să nu fi fost înregistrate ({count} raport)",
      few: "Atingerile sau stiloul pot să nu fi fost înregistrate ({count} rapoarte)",
      other: "Atingerile sau stiloul pot să nu fi fost înregistrate ({count} de rapoarte)",
    },
    captureNow: "Capturați acest ecran",
  },
  plain: {
    click: {
      button: "Selectați butonul „{name}”",
      link: "Selectați linkul „{name}”",
      menuItem: "Selectați „{name}” din meniu",
      tab: "Selectați fila „{name}”",
      field: "Selectați caseta „{name}”",
      checkbox: "Bifați caseta „{name}”",
      radio: "Alegeți „{name}”",
      dropdown: "Deschideți lista „{name}”",
      switch: "Selectați comutatorul „{name}”",
      picture: "Selectați imaginea „{name}”",
      other: "Selectați „{name}”",
    },
    clickIn: "Selectați un loc în fereastra „{title}”",
    clickBare: "Selectați aici",
    clickTaskbar: "Selectați „{name}” în bara de activități",
    typeValueInField: "Introduceți „{value}” în caseta „{field}”",
    typeInField: "Completați caseta „{field}”",
    chooseValueIn: "Alegeți „{value}” din lista „{field}”",
    chooseIn: "Alegeți din lista „{field}”",
    typeValue: "Introduceți „{value}”",
    type: "Introduceți textul",
    typeValueInCell: "Introduceți „{value}” în celula {cell}",
    typeInCell: "Completați celula {cell}",
    press: "Apăsați {keys}",
    goTo: "Accesați {site}",
    open: "Deschideți {app}",
    runIn: "Rulați comanda în {where}",
    runInTerminal: "Rulați comanda în terminal",
    formulaInCell: "Introduceți această formulă în celula {cell}",
    formulaInSelected: "Introduceți această formulă în celula selectată",
    code: "Tastați acest cod",
    missed: {
      one: "{count} clic a fost omis aici",
      few: "{count} clicuri au fost omise aici",
      other: "{count} de clicuri au fost omise aici",
    },
    touch: {
      one: "Este posibil să lipsească aici atingeri sau stilou ({count} raport)",
      few: "Este posibil să lipsească aici atingeri sau stilou ({count} rapoarte)",
      other: "Este posibil să lipsească aici atingeri sau stilou ({count} de rapoarte)",
    },
    captureNow: "Priviți acest ecran",
  },
  formal: {
    click: {
      button: "Faceți clic pe butonul „{name}”.",
      link: "Faceți clic pe linkul „{name}”.",
      menuItem: "Faceți clic pe „{name}” în meniu.",
      tab: "Faceți clic pe fila „{name}”.",
      field: "Faceți clic în câmpul „{name}”.",
      checkbox: "Bifați caseta de selectare „{name}”.",
      radio: "Selectați opțiunea „{name}”.",
      dropdown: "Faceți clic pe lista verticală „{name}”.",
      switch: "Faceți clic pe comutatorul „{name}”.",
      picture: "Faceți clic pe imaginea „{name}”.",
      other: "Faceți clic pe „{name}”.",
    },
    clickIn: "Faceți clic în fereastra „{title}”.",
    clickBare: "Faceți clic.",
    clickTaskbar: "Faceți clic pe „{name}” în bara de activități.",
    typeValueInField: "În câmpul „{field}”, tastați „{value}”.",
    typeInField: "Completați câmpul „{field}”.",
    chooseValueIn: "În lista „{field}”, selectați „{value}”.",
    chooseIn: "Selectați o opțiune din lista „{field}”.",
    typeValue: "Tastați „{value}”.",
    type: "Tastați textul.",
    typeValueInCell: "În celula {cell}, tastați „{value}”.",
    typeInCell: "Completați celula {cell}.",
    press: "Apăsați {keys}.",
    goTo: "Navigați la {site}.",
    open: "Deschideți {app}.",
    runIn: "Rulați următoarea comandă în {where}.",
    runInTerminal: "Rulați următoarea comandă în terminal.",
    formulaInCell: "În celula {cell}, tastați următoarea formulă.",
    formulaInSelected: "În celula selectată, tastați următoarea formulă.",
    code: "Tastați următorul cod.",
    missed: {
      one: "{count} clic nu a fost înregistrat aici.",
      few: "{count} clicuri nu au fost înregistrate aici.",
      other: "{count} de clicuri nu au fost înregistrate aici.",
    },
    touch: {
      one: "Este posibil ca intrarea prin atingere sau stilou să nu fi fost înregistrată aici ({count} raport).",
      few: "Este posibil ca intrarea prin atingere sau stilou să nu fi fost înregistrată aici ({count} rapoarte).",
      other:
        "Este posibil ca intrarea prin atingere sau stilou să nu fi fost înregistrată aici ({count} de rapoarte).",
    },
    captureNow: "Examinați acest ecran.",
  },
  terminals: { powershell: "PowerShell", cmd: "Linie de comandă", bash: "Bash" },
};
