import type { LanguagePhrases } from "../phrase.ts";

/**
 * Русский: «ёлочки» round names, the polite "вы" imperative in every tone (as Microsoft's Russian
 * documentation addresses the reader, without "ё"); casual is the shortest label ("Нажмите «…»"),
 * plain uses the neutral "Выберите" and everyday words, formal follows Microsoft's procedures.
 * Terminals are named as their windows are, so "в окне «Командная строка»" needs no declension.
 */
export const ru: LanguagePhrases = {
  casual: {
    click: {
      field: "Щелкните поле «{name}»",
      namedField: "Щелкните «{name}»",
      textArea: "Щелкните «{name}»",
      other: "Нажмите «{name}»",
    },
    clickIn: "Щелкните в окне «{title}»",
    clickBare: "Щелкните",
    clickTaskbar: "Нажмите «{name}» на панели задач",
    rightClick: "Щелкните правой кнопкой мыши «{name}»",
    rightClickIn: "Щелкните правой кнопкой мыши в окне «{title}»",
    rightClickBare: "Щелкните правой кнопкой мыши",
    selectRange: "Выделите «{range}»",
    typeValueInField: "Введите «{value}» в поле «{field}»",
    typeInField: "Введите текст в поле «{field}»",
    chooseValueIn: "Выберите «{value}» в поле «{field}»",
    chooseIn: "Выберите в поле «{field}»",
    typeValue: "Введите «{value}»",
    type: "Введите текст",
    typeValueInCell: "Введите «{value}» в ячейку {cell}",
    typeInCell: "Введите данные в ячейку {cell}",
    press: "Нажмите «{keys}»",
    goTo: "Перейдите на «{site}»",
    open: "Откройте «{app}»",
    runIn: "Выполните в окне «{where}»",
    runInTerminal: "Выполните в терминале",
    formulaInCell: "Введите формулу в ячейку {cell}",
    formulaInSelected: "Введите формулу в выделенную ячейку",
    code: "Введите этот код",
    missed: {
      one: "Здесь пропущен {count} щелчок",
      few: "Здесь пропущено {count} щелчка",
      many: "Здесь пропущено {count} щелчков",
      other: "Здесь пропущено {count} щелчков",
    },
    touch: {
      one: "Касания или ввод пером могли не записаться ({count} событие)",
      few: "Касания или ввод пером могли не записаться ({count} события)",
      many: "Касания или ввод пером могли не записаться ({count} событий)",
      other: "Касания или ввод пером могли не записаться ({count} событий)",
    },
    captureNow: "Сделайте снимок этого экрана",
  },
  plain: {
    click: {
      button: "Выберите кнопку «{name}»",
      link: "Выберите ссылку «{name}»",
      menuItem: "Выберите «{name}» в меню",
      tab: "Выберите вкладку «{name}»",
      field: "Выберите поле «{name}»",
      checkbox: "Отметьте пункт «{name}»",
      radio: "Выберите вариант «{name}»",
      dropdown: "Откройте список «{name}»",
      switch: "Выберите переключатель «{name}»",
      picture: "Выберите изображение «{name}»",
      other: "Выберите «{name}»",
    },
    clickIn: "Нажмите в окне «{title}»",
    clickBare: "Нажмите здесь",
    clickTaskbar: "Выберите «{name}» на панели задач",
    rightClick: "Щелкните правой кнопкой мыши «{name}»",
    rightClickIn: "Щелкните правой кнопкой мыши в окне «{title}»",
    rightClickBare: "Щелкните правой кнопкой мыши здесь",
    selectRange: "Выделите ячейки {range}",
    typeValueInField: "Введите «{value}» в поле «{field}»",
    typeInField: "Заполните поле «{field}»",
    chooseValueIn: "Выберите «{value}» в списке «{field}»",
    chooseIn: "Выберите значение в списке «{field}»",
    typeValue: "Введите «{value}»",
    type: "Введите текст",
    typeValueInCell: "Введите «{value}» в ячейку {cell}",
    typeInCell: "Заполните ячейку {cell}",
    press: "Нажмите {keys}",
    goTo: "Перейдите на {site}",
    open: "Откройте {app}",
    runIn: "Выполните это в окне «{where}»",
    runInTerminal: "Выполните это в терминале",
    formulaInCell: "Введите эту формулу в ячейку {cell}",
    formulaInSelected: "Введите эту формулу в выделенную ячейку",
    code: "Введите этот код",
    missed: {
      one: "Здесь не записан {count} щелчок",
      few: "Здесь не записано {count} щелчка",
      many: "Здесь не записано {count} щелчков",
      other: "Здесь не записано {count} щелчков",
    },
    touch: {
      one: "Здесь может не хватать касаний или ввода пером ({count} событие)",
      few: "Здесь может не хватать касаний или ввода пером ({count} события)",
      many: "Здесь может не хватать касаний или ввода пером ({count} событий)",
      other: "Здесь может не хватать касаний или ввода пером ({count} событий)",
    },
    captureNow: "Посмотрите на этот экран",
  },
  formal: {
    click: {
      button: "Нажмите кнопку «{name}».",
      link: "Щелкните ссылку «{name}».",
      menuItem: "Выберите в меню пункт «{name}».",
      tab: "Откройте вкладку «{name}».",
      field: "Щелкните поле «{name}».",
      checkbox: "Установите флажок «{name}».",
      radio: "Выберите параметр «{name}».",
      dropdown: "Откройте раскрывающийся список «{name}».",
      switch: "Щелкните переключатель «{name}».",
      picture: "Щелкните изображение «{name}».",
      listItem: "Выберите элемент «{name}».",
      other: "Щелкните «{name}».",
    },
    clickIn: "Щелкните в окне «{title}».",
    clickBare: "Щелкните.",
    clickTaskbar: "Нажмите «{name}» на панели задач.",
    rightClick: "Щелкните правой кнопкой мыши «{name}».",
    rightClickIn: "Щелкните правой кнопкой мыши в окне «{title}».",
    rightClickBare: "Щелкните правой кнопкой мыши.",
    selectRange: "Выделите ячейки {range}.",
    typeValueInField: "В поле «{field}» введите «{value}».",
    typeInField: "Заполните поле «{field}».",
    chooseValueIn: "В списке «{field}» выберите «{value}».",
    chooseIn: "Выберите значение в списке «{field}».",
    typeValue: "Введите «{value}».",
    type: "Введите текст.",
    typeValueInCell: "В ячейке {cell} введите «{value}».",
    typeInCell: "Заполните ячейку {cell}.",
    press: "Нажмите {keys}.",
    goTo: "Перейдите на {site}.",
    open: "Откройте {app}.",
    runIn: "Выполните следующую команду в окне «{where}».",
    runInTerminal: "Выполните следующую команду в терминале.",
    formulaInCell: "В ячейке {cell} введите следующую формулу.",
    formulaInSelected: "В выделенной ячейке введите следующую формулу.",
    code: "Введите следующий код.",
    missed: {
      one: "Здесь не записан {count} щелчок.",
      few: "Здесь не записано {count} щелчка.",
      many: "Здесь не записано {count} щелчков.",
      other: "Здесь не записано {count} щелчков.",
    },
    touch: {
      one: "Касания или ввод пером здесь могли не записаться ({count} событие).",
      few: "Касания или ввод пером здесь могли не записаться ({count} события).",
      many: "Касания или ввод пером здесь могли не записаться ({count} событий).",
      other: "Касания или ввод пером здесь могли не записаться ({count} событий).",
    },
    captureNow: "Просмотрите этот экран.",
  },
  terminals: { powershell: "PowerShell", cmd: "Командная строка", bash: "Bash" },
};
