import type { LanguagePhrases } from "../phrase.ts";

/**
 * Slovenčina: names in „…“; every tone addresses the reader formally (vykanie) as Windows does,
 * with the imperative: casual „Kliknite na …“, plain the neutral „Vyberte …“, formal full
 * sentences in the style of Microsoft's procedures.
 */
export const sk: LanguagePhrases = {
  casual: {
    click: {
      field: "Kliknite do poľa „{name}“",
      namedField: "Kliknite na „{name}“",
      textArea: "Kliknite na „{name}“",
      other: "Kliknite na „{name}“",
    },
    clickIn: "Kliknite do okna „{title}“",
    clickBare: "Kliknite",
    clickTaskbar: "Kliknite na „{name}“ na paneli úloh",
    rightClick: "Kliknite pravým tlačidlom myši na „{name}“",
    rightClickIn: "Kliknite pravým tlačidlom myši do okna „{title}“",
    rightClickBare: "Kliknite pravým tlačidlom myši",
    selectRange: "Označte „{range}“",
    typeValueInField: "Zadajte „{value}“ do poľa „{field}“",
    typeInField: "Zadajte text do poľa „{field}“",
    chooseValueIn: "Vyberte „{value}“ v poli „{field}“",
    chooseIn: "Vyberte v poli „{field}“",
    typeValue: "Zadajte „{value}“",
    type: "Zadajte text",
    typeValueInCell: "Zadajte „{value}“ do bunky {cell}",
    typeInCell: "Zadajte text do bunky {cell}",
    press: "Stlačte „{keys}“",
    pressNamed: "Stlačte „{keys}“ ({name})",
    goTo: "Prejdite na „{site}“",
    open: "Otvorte „{app}“",
    runIn: "Spustite v aplikácii {where}",
    runInTerminal: "Spustite v termináli",
    formulaInCell: "Zadajte vzorec do bunky {cell}",
    formulaInSelected: "Zadajte vzorec do vybranej bunky",
    code: "Zadajte tento kód",
    missed: {
      one: "Tu sa vynechalo {count} kliknutie",
      few: "Tu sa vynechali {count} kliknutia",
      many: "Tu sa vynechalo {count} kliknutia",
      other: "Tu sa vynechalo {count} kliknutí",
    },
    touch: {
      one: "Dotyk alebo pero sa možno nenahrali ({count} hlásenie)",
      few: "Dotyk alebo pero sa možno nenahrali ({count} hlásenia)",
      many: "Dotyk alebo pero sa možno nenahrali ({count} hlásenia)",
      other: "Dotyk alebo pero sa možno nenahrali ({count} hlásení)",
    },
    captureNow: "Zachyťte túto obrazovku",
  },
  plain: {
    click: {
      button: "Vyberte tlačidlo „{name}“",
      link: "Vyberte odkaz „{name}“",
      menuItem: "V ponuke vyberte „{name}“",
      tab: "Vyberte kartu „{name}“",
      field: "Vyberte pole „{name}“",
      checkbox: "Začiarknite políčko „{name}“",
      radio: "Zvoľte „{name}“",
      dropdown: "Otvorte zoznam „{name}“",
      switch: "Vyberte prepínač „{name}“",
      picture: "Vyberte obrázok „{name}“",
      other: "Vyberte „{name}“",
    },
    clickIn: "Vyberte miesto v okne „{title}“",
    clickBare: "Vyberte toto miesto",
    clickTaskbar: "Vyberte „{name}“ na paneli úloh",
    rightClick: "Kliknite pravým tlačidlom myši na „{name}“",
    rightClickIn: "Kliknite pravým tlačidlom myši v okne „{title}“",
    rightClickBare: "Kliknite pravým tlačidlom myši na toto miesto",
    selectRange: "Označte bunky {range}",
    typeValueInField: "Do poľa „{field}“ napíšte „{value}“",
    typeInField: "Vyplňte pole „{field}“",
    chooseValueIn: "Zo zoznamu „{field}“ vyberte „{value}“",
    chooseIn: "Vyberte zo zoznamu „{field}“",
    typeValue: "Napíšte „{value}“",
    type: "Napíšte text",
    typeValueInCell: "Do bunky {cell} napíšte „{value}“",
    typeInCell: "Vyplňte bunku {cell}",
    press: "Stlačte {keys}",
    pressNamed: "Stlačte {keys} ({name})",
    goTo: "Prejdite na {site}",
    open: "Otvorte {app}",
    runIn: "Spustite to v aplikácii {where}",
    runInTerminal: "Spustite to v termináli",
    formulaInCell: "Do bunky {cell} napíšte tento vzorec",
    formulaInSelected: "Do vybranej bunky napíšte tento vzorec",
    code: "Napíšte tento kód",
    missed: {
      one: "Tu sa vynechalo {count} kliknutie",
      few: "Tu sa vynechali {count} kliknutia",
      many: "Tu sa vynechalo {count} kliknutia",
      other: "Tu sa vynechalo {count} kliknutí",
    },
    touch: {
      one: "Tu môže chýbať použitie dotyku alebo pera ({count} hlásenie)",
      few: "Tu môže chýbať použitie dotyku alebo pera ({count} hlásenia)",
      many: "Tu môže chýbať použitie dotyku alebo pera ({count} hlásenia)",
      other: "Tu môže chýbať použitie dotyku alebo pera ({count} hlásení)",
    },
    captureNow: "Pozrite si túto obrazovku",
  },
  formal: {
    click: {
      button: "Kliknite na tlačidlo „{name}“.",
      link: "Kliknite na odkaz „{name}“.",
      menuItem: "V ponuke kliknite na položku „{name}“.",
      tab: "Kliknite na kartu „{name}“.",
      field: "Kliknite do poľa „{name}“.",
      checkbox: "Začiarknite políčko „{name}“.",
      radio: "Vyberte možnosť „{name}“.",
      dropdown: "Kliknite na rozbaľovací zoznam „{name}“.",
      switch: "Kliknite na prepínač „{name}“.",
      picture: "Kliknite na obrázok „{name}“.",
      other: "Kliknite na „{name}“.",
    },
    clickIn: "Kliknite do okna „{title}“.",
    clickBare: "Kliknite.",
    clickTaskbar: "Na paneli úloh kliknite na „{name}“.",
    rightClick: "Kliknite pravým tlačidlom myši na „{name}“.",
    rightClickIn: "Kliknite pravým tlačidlom myši do okna „{title}“.",
    rightClickBare: "Kliknite pravým tlačidlom myši.",
    selectRange: "Označte bunky {range}.",
    typeValueInField: "Do poľa „{field}“ zadajte „{value}“.",
    typeInField: "Vyplňte pole „{field}“.",
    chooseValueIn: "V zozname „{field}“ vyberte „{value}“.",
    chooseIn: "Vyberte možnosť v zozname „{field}“.",
    typeValue: "Zadajte „{value}“.",
    type: "Zadajte text.",
    typeValueInCell: "Do bunky {cell} zadajte „{value}“.",
    typeInCell: "Vyplňte bunku {cell}.",
    press: "Stlačte {keys}.",
    pressNamed: "Stlačte {keys} ({name}).",
    goTo: "Prejdite na {site}.",
    open: "Otvorte {app}.",
    runIn: "V aplikácii {where} spustite nasledujúci príkaz.",
    runInTerminal: "V termináli spustite nasledujúci príkaz.",
    formulaInCell: "Do bunky {cell} zadajte nasledujúci vzorec.",
    formulaInSelected: "Do vybranej bunky zadajte nasledujúci vzorec.",
    code: "Zadajte nasledujúci kód.",
    missed: {
      one: "Tu sa nenahralo {count} kliknutie.",
      few: "Tu sa nenahrali {count} kliknutia.",
      many: "Tu sa nenahralo {count} kliknutia.",
      other: "Tu sa nenahralo {count} kliknutí.",
    },
    touch: {
      one: "Dotykový alebo perový vstup sa tu možno nenahral ({count} hlásenie).",
      few: "Dotykový alebo perový vstup sa tu možno nenahral ({count} hlásenia).",
      many: "Dotykový alebo perový vstup sa tu možno nenahral ({count} hlásenia).",
      other: "Dotykový alebo perový vstup sa tu možno nenahral ({count} hlásení).",
    },
    captureNow: "Skontrolujte túto obrazovku.",
  },
  terminals: { powershell: "PowerShell", cmd: "Príkazový riadok", bash: "Bash" },
  shortcuts: {
    selectAll: "Vybrať všetko",
    copy: "Kopírovať",
    cut: "Vystrihnúť",
    paste: "Prilepiť",
    save: "Uložiť",
    print: "Tlačiť",
    find: "Hľadať",
    close: "Zavrieť",
    taskManager: "Správca úloh",
    showDesktop: "Zobraziť plochu",
    fileExplorer: "Prieskumník",
    settings: "Nastavenia",
    lock: "Zamknúť",
    run: "Spustiť",
    clipboardHistory: "História schránky",
    snippingTool: "Nástroj na vystrihovanie",
  },
};
