import type { LanguagePhrases } from "../phrase.ts";

/**
 * Slovenščina: „narekovaji“ as in Microsoft's Slovenian documentation, and the polite plural
 * imperative ("Kliknite") that Windows uses. Casual is the shortest instruction; plain language
 * says "Izberite" and names things simply; formal writes full sentences ending in a full stop.
 */
export const sl: LanguagePhrases = {
  casual: {
    click: {
      field: "Kliknite polje „{name}“",
      namedField: "Kliknite „{name}“",
      textArea: "Kliknite „{name}“",
      other: "Kliknite „{name}“",
    },
    clickIn: "Kliknite v „{title}“",
    clickBare: "Kliknite",
    clickTaskbar: "Kliknite „{name}“ v opravilni vrstici",
    rightClick: "Z desno tipko miške kliknite „{name}“",
    rightClickIn: "Z desno tipko miške kliknite v „{title}“",
    rightClickBare: "Z desno tipko miške kliknite",
    selectRange: "Izberite „{range}“",
    typeValueInField: "Vnesite „{value}“ v polje „{field}“",
    typeInField: "Vnesite besedilo v polje „{field}“",
    chooseValueIn: "Izberite „{value}“ v polju „{field}“",
    chooseIn: "Izberite v polju „{field}“",
    typeValue: "Vnesite „{value}“",
    type: "Vnesite besedilo",
    typeValueInCell: "Vnesite „{value}“ v celico {cell}",
    typeInCell: "Vnesite besedilo v celico {cell}",
    press: "Pritisnite „{keys}“",
    goTo: "Pojdite na „{site}“",
    open: "Odprite „{app}“",
    runIn: "Zaženite v: {where}",
    runInTerminal: "Zaženite v terminalu",
    formulaInCell: "Vnesite formulo v celico {cell}",
    formulaInSelected: "Vnesite formulo v izbrano celico",
    code: "Vnesite to kodo",
    missed: {
      one: "Tu je zgrešen {count} klik",
      two: "Tu sta zgrešena {count} klika",
      few: "Tu so zgrešeni {count} kliki",
      other: "Tu je zgrešenih {count} klikov",
    },
    touch: {
      one: "Dotik ali uporaba pisala morda nista posneta ({count} poročilo)",
      two: "Dotik ali uporaba pisala morda nista posneta ({count} poročili)",
      few: "Dotik ali uporaba pisala morda nista posneta ({count} poročila)",
      other: "Dotik ali uporaba pisala morda nista posneta ({count} poročil)",
    },
    captureNow: "Posnemite ta zaslon",
  },
  plain: {
    click: {
      button: "Izberite gumb „{name}“",
      link: "Izberite povezavo „{name}“",
      menuItem: "Izberite „{name}“ v meniju",
      tab: "Izberite zavihek „{name}“",
      field: "Izberite polje „{name}“",
      checkbox: "Označite potrditveno polje „{name}“",
      radio: "Izberite možnost „{name}“",
      dropdown: "Odprite seznam „{name}“",
      switch: "Preklopite stikalo „{name}“",
      picture: "Izberite sliko „{name}“",
      other: "Izberite „{name}“",
    },
    clickIn: "Izberite mesto v oknu „{title}“",
    clickBare: "Izberite tukaj",
    clickTaskbar: "Izberite „{name}“ v opravilni vrstici",
    rightClick: "Z desno tipko miške kliknite „{name}“",
    rightClickIn: "Z desno tipko miške kliknite v oknu „{title}“",
    rightClickBare: "Z desno tipko miške kliknite tukaj",
    selectRange: "Izberite celice {range}",
    typeValueInField: "V polje „{field}“ vnesite „{value}“",
    typeInField: "Izpolnite polje „{field}“",
    chooseValueIn: "Izberite „{value}“ s seznama „{field}“",
    chooseIn: "Izberite s seznama „{field}“",
    typeValue: "Vnesite „{value}“",
    type: "Vnesite besedilo",
    typeValueInCell: "V celico {cell} vnesite „{value}“",
    typeInCell: "Izpolnite celico {cell}",
    press: "Pritisnite {keys}",
    goTo: "Pojdite na {site}",
    open: "Odprite {app}",
    runIn: "To zaženite v: {where}",
    runInTerminal: "To zaženite v terminalu",
    formulaInCell: "To formulo vnesite v celico {cell}",
    formulaInSelected: "To formulo vnesite v izbrano celico",
    code: "Vnesite to kodo",
    missed: {
      one: "Tu je bil zgrešen {count} klik",
      two: "Tu sta bila zgrešena {count} klika",
      few: "Tu so bili zgrešeni {count} kliki",
      other: "Tu je bilo zgrešenih {count} klikov",
    },
    touch: {
      one: "Dotik ali uporaba pisala tu morda manjkata ({count} poročilo)",
      two: "Dotik ali uporaba pisala tu morda manjkata ({count} poročili)",
      few: "Dotik ali uporaba pisala tu morda manjkata ({count} poročila)",
      other: "Dotik ali uporaba pisala tu morda manjkata ({count} poročil)",
    },
    captureNow: "Poglejte ta zaslon",
  },
  formal: {
    click: {
      button: "Kliknite gumb „{name}“.",
      link: "Kliknite povezavo „{name}“.",
      menuItem: "V meniju kliknite „{name}“.",
      tab: "Kliknite zavihek „{name}“.",
      field: "Kliknite polje „{name}“.",
      checkbox: "Potrdite polje „{name}“.",
      radio: "Izberite možnost „{name}“.",
      dropdown: "Kliknite spustni seznam „{name}“.",
      switch: "Kliknite stikalo „{name}“.",
      picture: "Kliknite sliko „{name}“.",
      other: "Kliknite „{name}“.",
    },
    clickIn: "Kliknite v oknu „{title}“.",
    clickBare: "Kliknite.",
    clickTaskbar: "V opravilni vrstici kliknite „{name}“.",
    rightClick: "Z desno tipko miške kliknite „{name}“.",
    rightClickIn: "Z desno tipko miške kliknite v oknu „{title}“.",
    rightClickBare: "Z desno tipko miške kliknite.",
    selectRange: "Izberite celice {range}.",
    typeValueInField: "V polje „{field}“ vnesite „{value}“.",
    typeInField: "Izpolnite polje „{field}“.",
    chooseValueIn: "Na seznamu „{field}“ izberite „{value}“.",
    chooseIn: "Izberite možnost na seznamu „{field}“.",
    typeValue: "Vnesite „{value}“.",
    type: "Vnesite besedilo.",
    typeValueInCell: "V celico {cell} vnesite „{value}“.",
    typeInCell: "Izpolnite celico {cell}.",
    press: "Pritisnite {keys}.",
    goTo: "Odprite {site}.",
    open: "Odprite {app}.",
    runIn: "V programu {where} zaženite naslednji ukaz.",
    runInTerminal: "V terminalu zaženite naslednji ukaz.",
    formulaInCell: "V celico {cell} vnesite naslednjo formulo.",
    formulaInSelected: "V izbrano celico vnesite naslednjo formulo.",
    code: "Vnesite naslednjo kodo.",
    missed: {
      one: "Tu ni bil posnet {count} klik.",
      two: "Tu nista bila posneta {count} klika.",
      few: "Tu niso bili posneti {count} kliki.",
      other: "Tu ni bilo posnetih {count} klikov.",
    },
    touch: {
      one: "Dotik ali vnos s pisalom tu morda nista posneta ({count} poročilo).",
      two: "Dotik ali vnos s pisalom tu morda nista posneta ({count} poročili).",
      few: "Dotik ali vnos s pisalom tu morda nista posneta ({count} poročila).",
      other: "Dotik ali vnos s pisalom tu morda nista posneta ({count} poročil).",
    },
    captureNow: "Preglejte ta zaslon.",
  },
  terminals: { powershell: "PowerShell", cmd: "Ukazni poziv", bash: "Bash" },
};
