import type { LanguagePhrases } from "../phrase.ts";

/**
 * Српски (ћирилица): names in „…“, the reader addressed as „ви“ as in Microsoft's Serbian
 * (Кликните, Откуцајте); casual is the shortest instruction with no full stop, plain uses the
 * neutral „Изаберите“ and everyday names for things, formal writes full sentences in the style of
 * Microsoft's Serbian procedure documentation.
 */
export const srCyrl: LanguagePhrases = {
  casual: {
    click: {
      field: "Кликните на поље „{name}“",
      namedField: "Кликните на „{name}“",
      textArea: "Кликните на „{name}“",
      other: "Кликните на „{name}“",
    },
    clickIn: "Кликните у „{title}“",
    clickBare: "Кликните",
    clickTaskbar: "Кликните на „{name}“ на траци задатака",
    rightClick: "Кликните десним тастером миша на „{name}“",
    rightClickIn: "Кликните десним тастером миша у „{title}“",
    rightClickBare: "Кликните десним тастером миша",
    selectRange: "Изаберите „{range}“",
    typeValueInField: "Откуцајте „{value}“ у поље „{field}“",
    typeInField: "Откуцајте у поље „{field}“",
    chooseValueIn: "Изаберите „{value}“ у пољу „{field}“",
    chooseIn: "Изаберите у пољу „{field}“",
    typeValue: "Откуцајте „{value}“",
    type: "Откуцајте текст",
    typeValueInCell: "Откуцајте „{value}“ у ћелију {cell}",
    typeInCell: "Откуцајте у ћелију {cell}",
    press: "Притисните „{keys}“",
    goTo: "Идите на „{site}“",
    open: "Отворите „{app}“",
    runIn: "Покрените у прозору {where}",
    runInTerminal: "Покрените у терминалу",
    formulaInCell: "Откуцајте формулу у ћелију {cell}",
    formulaInSelected: "Откуцајте формулу у изабрану ћелију",
    code: "Откуцајте овај кôд",
    missed: {
      one: "{count} пропуштени клик",
      few: "{count} пропуштена клика",
      other: "{count} пропуштених кликова",
    },
    touch: {
      one: "Додир или оловка можда нису снимљени ({count} извештај)",
      few: "Додир или оловка можда нису снимљени ({count} извештаја)",
      other: "Додир или оловка можда нису снимљени ({count} извештаја)",
    },
    captureNow: "Снимите овај екран",
  },
  plain: {
    click: {
      button: "Изаберите дугме „{name}“",
      link: "Изаберите везу „{name}“",
      menuItem: "Изаберите „{name}“ у менију",
      tab: "Изаберите картицу „{name}“",
      field: "Изаберите поље „{name}“",
      checkbox: "Изаберите поље за потврду „{name}“",
      radio: "Изаберите „{name}“",
      dropdown: "Отворите листу „{name}“",
      switch: "Изаберите прекидач „{name}“",
      picture: "Изаберите слику „{name}“",
      other: "Изаберите „{name}“",
    },
    clickIn: "Изаберите место у прозору „{title}“",
    clickBare: "Изаберите овде",
    clickTaskbar: "Изаберите „{name}“ на траци задатака",
    rightClick: "Кликните десним тастером миша на „{name}“",
    rightClickIn: "Кликните десним тастером миша у прозору „{title}“",
    rightClickBare: "Кликните десним тастером миша овде",
    selectRange: "Изаберите ћелије {range}",
    typeValueInField: "Унесите „{value}“ у поље „{field}“",
    typeInField: "Попуните поље „{field}“",
    chooseValueIn: "Изаберите „{value}“ са листе „{field}“",
    chooseIn: "Изаберите са листе „{field}“",
    typeValue: "Унесите „{value}“",
    type: "Унесите текст",
    typeValueInCell: "Унесите „{value}“ у ћелију {cell}",
    typeInCell: "Попуните ћелију {cell}",
    press: "Притисните {keys}",
    goTo: "Идите на {site}",
    open: "Отворите {app}",
    runIn: "Покрените ово у прозору {where}",
    runInTerminal: "Покрените ово у терминалу",
    formulaInCell: "Унесите ову формулу у ћелију {cell}",
    formulaInSelected: "Унесите ову формулу у изабрану ћелију",
    code: "Откуцајте овај кôд",
    missed: {
      one: "Овде је пропуштен {count} клик",
      few: "Овде су пропуштена {count} клика",
      other: "Овде је пропуштено {count} кликова",
    },
    touch: {
      one: "Овде можда недостаје додир или оловка ({count} извештај)",
      few: "Овде можда недостаје додир или оловка ({count} извештаја)",
      other: "Овде можда недостаје додир или оловка ({count} извештаја)",
    },
    captureNow: "Погледајте овај екран",
  },
  formal: {
    click: {
      button: "Кликните на дугме „{name}“.",
      link: "Кликните на везу „{name}“.",
      menuItem: "У менију кликните на „{name}“.",
      tab: "Кликните на картицу „{name}“.",
      field: "Кликните у поље „{name}“.",
      checkbox: "Потврдите избор у пољу за потврду „{name}“.",
      radio: "Изаберите опцију „{name}“.",
      dropdown: "Кликните на падајућу листу „{name}“.",
      switch: "Кликните на прекидач „{name}“.",
      picture: "Кликните на слику „{name}“.",
      other: "Кликните на „{name}“.",
    },
    clickIn: "Кликните у прозору „{title}“.",
    clickBare: "Кликните.",
    clickTaskbar: "Кликните на „{name}“ на траци задатака.",
    rightClick: "Кликните десним тастером миша на „{name}“.",
    rightClickIn: "Кликните десним тастером миша у прозору „{title}“.",
    rightClickBare: "Кликните десним тастером миша.",
    selectRange: "Изаберите ћелије {range}.",
    typeValueInField: "У поље „{field}“ откуцајте „{value}“.",
    typeInField: "Попуните поље „{field}“.",
    chooseValueIn: "На листи „{field}“ изаберите „{value}“.",
    chooseIn: "Изаберите опцију на листи „{field}“.",
    typeValue: "Откуцајте „{value}“.",
    type: "Откуцајте текст.",
    typeValueInCell: "У ћелију {cell} откуцајте „{value}“.",
    typeInCell: "Попуните ћелију {cell}.",
    press: "Притисните {keys}.",
    goTo: "Идите на {site}.",
    open: "Отворите {app}.",
    runIn: "Покрените следећу команду у прозору {where}.",
    runInTerminal: "Покрените следећу команду у терминалу.",
    formulaInCell: "У ћелију {cell} откуцајте следећу формулу.",
    formulaInSelected: "У изабрану ћелију откуцајте следећу формулу.",
    code: "Откуцајте следећи кôд.",
    missed: {
      one: "Овде није снимљен {count} клик.",
      few: "Овде нису снимљена {count} клика.",
      other: "Овде није снимљено {count} кликова.",
    },
    touch: {
      one: "Унос додиром или оловком овде можда није снимљен ({count} извештај).",
      few: "Унос додиром или оловком овде можда није снимљен ({count} извештаја).",
      other: "Унос додиром или оловком овде можда није снимљен ({count} извештаја).",
    },
    captureNow: "Прегледајте овај екран.",
  },
  terminals: { powershell: "PowerShell", cmd: "Командна линија", bash: "Bash" },
};
