import type { LanguagePhrases } from "../phrase.ts";

/**
 * Srpski (latinica): names in „…“, the reader addressed as „vi“ as in Microsoft's Serbian
 * (Kliknite, Otkucajte); casual is the shortest instruction with no full stop, plain uses the
 * neutral „Izaberite“ and everyday names for things, formal writes full sentences in the style of
 * Microsoft's Serbian procedure documentation.
 */
export const srLatn: LanguagePhrases = {
  casual: {
    click: {
      field: "Kliknite na polje „{name}“",
      namedField: "Kliknite na „{name}“",
      textArea: "Kliknite na „{name}“",
      other: "Kliknite na „{name}“",
    },
    clickIn: "Kliknite u „{title}“",
    clickBare: "Kliknite",
    clickTaskbar: "Kliknite na „{name}“ na traci zadataka",
    rightClick: "Kliknite desnim tasterom miša na „{name}“",
    rightClickIn: "Kliknite desnim tasterom miša u „{title}“",
    rightClickBare: "Kliknite desnim tasterom miša",
    selectRange: "Izaberite „{range}“",
    typeValueInField: "Otkucajte „{value}“ u polje „{field}“",
    typeInField: "Otkucajte u polje „{field}“",
    chooseValueIn: "Izaberite „{value}“ u polju „{field}“",
    chooseIn: "Izaberite u polju „{field}“",
    typeValue: "Otkucajte „{value}“",
    type: "Otkucajte tekst",
    typeValueInCell: "Otkucajte „{value}“ u ćeliju {cell}",
    typeInCell: "Otkucajte u ćeliju {cell}",
    press: "Pritisnite „{keys}“",
    goTo: "Idite na „{site}“",
    open: "Otvorite „{app}“",
    runIn: "Pokrenite u prozoru {where}",
    runInTerminal: "Pokrenite u terminalu",
    formulaInCell: "Otkucajte formulu u ćeliju {cell}",
    formulaInSelected: "Otkucajte formulu u izabranu ćeliju",
    code: "Otkucajte ovaj kôd",
    missed: {
      one: "{count} propušteni klik",
      few: "{count} propuštena klika",
      other: "{count} propuštenih klikova",
    },
    touch: {
      one: "Dodir ili olovka možda nisu snimljeni ({count} izveštaj)",
      few: "Dodir ili olovka možda nisu snimljeni ({count} izveštaja)",
      other: "Dodir ili olovka možda nisu snimljeni ({count} izveštaja)",
    },
    captureNow: "Snimite ovaj ekran",
  },
  plain: {
    click: {
      button: "Izaberite dugme „{name}“",
      link: "Izaberite vezu „{name}“",
      menuItem: "Izaberite „{name}“ u meniju",
      tab: "Izaberite karticu „{name}“",
      field: "Izaberite polje „{name}“",
      checkbox: "Izaberite polje za potvrdu „{name}“",
      radio: "Izaberite „{name}“",
      dropdown: "Otvorite listu „{name}“",
      switch: "Izaberite prekidač „{name}“",
      picture: "Izaberite sliku „{name}“",
      other: "Izaberite „{name}“",
    },
    clickIn: "Izaberite mesto u prozoru „{title}“",
    clickBare: "Izaberite ovde",
    clickTaskbar: "Izaberite „{name}“ na traci zadataka",
    rightClick: "Kliknite desnim tasterom miša na „{name}“",
    rightClickIn: "Kliknite desnim tasterom miša u prozoru „{title}“",
    rightClickBare: "Kliknite desnim tasterom miša ovde",
    selectRange: "Izaberite ćelije {range}",
    typeValueInField: "Unesite „{value}“ u polje „{field}“",
    typeInField: "Popunite polje „{field}“",
    chooseValueIn: "Izaberite „{value}“ sa liste „{field}“",
    chooseIn: "Izaberite sa liste „{field}“",
    typeValue: "Unesite „{value}“",
    type: "Unesite tekst",
    typeValueInCell: "Unesite „{value}“ u ćeliju {cell}",
    typeInCell: "Popunite ćeliju {cell}",
    press: "Pritisnite {keys}",
    goTo: "Idite na {site}",
    open: "Otvorite {app}",
    runIn: "Pokrenite ovo u prozoru {where}",
    runInTerminal: "Pokrenite ovo u terminalu",
    formulaInCell: "Unesite ovu formulu u ćeliju {cell}",
    formulaInSelected: "Unesite ovu formulu u izabranu ćeliju",
    code: "Otkucajte ovaj kôd",
    missed: {
      one: "Ovde je propušten {count} klik",
      few: "Ovde su propuštena {count} klika",
      other: "Ovde je propušteno {count} klikova",
    },
    touch: {
      one: "Ovde možda nedostaje dodir ili olovka ({count} izveštaj)",
      few: "Ovde možda nedostaje dodir ili olovka ({count} izveštaja)",
      other: "Ovde možda nedostaje dodir ili olovka ({count} izveštaja)",
    },
    captureNow: "Pogledajte ovaj ekran",
  },
  formal: {
    click: {
      button: "Kliknite na dugme „{name}“.",
      link: "Kliknite na vezu „{name}“.",
      menuItem: "U meniju kliknite na „{name}“.",
      tab: "Kliknite na karticu „{name}“.",
      field: "Kliknite u polje „{name}“.",
      checkbox: "Potvrdite izbor u polju za potvrdu „{name}“.",
      radio: "Izaberite opciju „{name}“.",
      dropdown: "Kliknite na padajuću listu „{name}“.",
      switch: "Kliknite na prekidač „{name}“.",
      picture: "Kliknite na sliku „{name}“.",
      other: "Kliknite na „{name}“.",
    },
    clickIn: "Kliknite u prozoru „{title}“.",
    clickBare: "Kliknite.",
    clickTaskbar: "Kliknite na „{name}“ na traci zadataka.",
    rightClick: "Kliknite desnim tasterom miša na „{name}“.",
    rightClickIn: "Kliknite desnim tasterom miša u prozoru „{title}“.",
    rightClickBare: "Kliknite desnim tasterom miša.",
    selectRange: "Izaberite ćelije {range}.",
    typeValueInField: "U polje „{field}“ otkucajte „{value}“.",
    typeInField: "Popunite polje „{field}“.",
    chooseValueIn: "Na listi „{field}“ izaberite „{value}“.",
    chooseIn: "Izaberite opciju na listi „{field}“.",
    typeValue: "Otkucajte „{value}“.",
    type: "Otkucajte tekst.",
    typeValueInCell: "U ćeliju {cell} otkucajte „{value}“.",
    typeInCell: "Popunite ćeliju {cell}.",
    press: "Pritisnite {keys}.",
    goTo: "Idite na {site}.",
    open: "Otvorite {app}.",
    runIn: "Pokrenite sledeću komandu u prozoru {where}.",
    runInTerminal: "Pokrenite sledeću komandu u terminalu.",
    formulaInCell: "U ćeliju {cell} otkucajte sledeću formulu.",
    formulaInSelected: "U izabranu ćeliju otkucajte sledeću formulu.",
    code: "Otkucajte sledeći kôd.",
    missed: {
      one: "Ovde nije snimljen {count} klik.",
      few: "Ovde nisu snimljena {count} klika.",
      other: "Ovde nije snimljeno {count} klikova.",
    },
    touch: {
      one: "Unos dodirom ili olovkom ovde možda nije snimljen ({count} izveštaj).",
      few: "Unos dodirom ili olovkom ovde možda nije snimljen ({count} izveštaja).",
      other: "Unos dodirom ili olovkom ovde možda nije snimljen ({count} izveštaja).",
    },
    captureNow: "Pregledajte ovaj ekran.",
  },
  terminals: { powershell: "PowerShell", cmd: "Komandna linija", bash: "Bash" },
};
