import type { LanguagePhrases } from "../phrase.ts";

/**
 * Svenska: Swedish quotation marks ”…” (as Microsoft's Swedish documentation writes them) and
 * the imperative with "du" implied throughout; casual is short ("Klicka på ”Spara”"), plain
 * follows Swedish klarspråk with the neutral "Välj", and formal writes full sentences as
 * Microsoft's Swedish procedures do ("Klicka på knappen ”Spara”.").
 */
export const sv: LanguagePhrases = {
  casual: {
    click: {
      field: "Klicka i fältet ”{name}”",
      namedField: "Klicka på ”{name}”",
      textArea: "Klicka på ”{name}”",
      other: "Klicka på ”{name}”",
    },
    clickIn: "Klicka i ”{title}”",
    clickBare: "Klicka",
    clickTaskbar: "Klicka på ”{name}” i aktivitetsfältet",
    rightClick: "Högerklicka på ”{name}”",
    rightClickIn: "Högerklicka i ”{title}”",
    rightClickBare: "Högerklicka",
    selectRange: "Markera ”{range}”",
    fillDown: "Fyll ”{from}” nedåt till ”{to}”",
    fillTo: "Fyll ”{from}” till ”{to}”",
    fillColumn: "Fyll ”{from}” nedåt i kolumnen",
    typeValueInField: "Skriv ”{value}” i fältet ”{field}”",
    typeInField: "Skriv i fältet ”{field}”",
    chooseValueIn: "Välj ”{value}” i ”{field}”",
    chooseIn: "Välj i ”{field}”",
    typeValue: "Skriv ”{value}”",
    type: "Skriv",
    typeValueInCell: "Skriv ”{value}” i cell {cell}",
    typeInCell: "Skriv i cell {cell}",
    press: "Tryck på ”{keys}”",
    pressNamed: "Tryck på ”{keys}” ({name})",
    goTo: "Gå till ”{site}”",
    open: "Öppna ”{app}”",
    runIn: "Kör i {where}",
    runInTerminal: "Kör i terminalen",
    formulaInCell: "Skriv formeln i cell {cell}",
    formulaInSelected: "Skriv formeln i den markerade cellen",
    code: "Skriv den här koden",
    missed: { one: "{count} klick missades här", other: "{count} klick missades här" },
    touch: {
      one: "Pek- eller pennaktivitet kanske inte spelades in ({count} rapport)",
      other: "Pek- eller pennaktivitet kanske inte spelades in ({count} rapporter)",
    },
    captureNow: "Ta en bild av den här skärmen",
  },
  plain: {
    click: {
      button: "Välj knappen ”{name}”",
      link: "Välj länken ”{name}”",
      menuItem: "Välj ”{name}” i menyn",
      tab: "Välj fliken ”{name}”",
      field: "Välj rutan ”{name}”",
      checkbox: "Välj kryssrutan ”{name}”",
      radio: "Välj ”{name}”",
      dropdown: "Öppna listan ”{name}”",
      switch: "Välj reglaget ”{name}”",
      picture: "Välj bilden ”{name}”",
      other: "Välj ”{name}”",
    },
    clickIn: "Välj i fönstret ”{title}”",
    clickBare: "Välj här",
    clickTaskbar: "Välj ”{name}” i aktivitetsfältet",
    rightClick: "Högerklicka på ”{name}”",
    rightClickIn: "Högerklicka i fönstret ”{title}”",
    rightClickBare: "Högerklicka här",
    selectRange: "Markera cellerna {range}",
    fillDown: "Fyll cell {from} nedåt till cell {to}",
    fillTo: "Fyll cell {from} till cell {to}",
    fillColumn: "Fyll cell {from} nedåt i kolumnen",
    typeValueInField: "Skriv ”{value}” i rutan ”{field}”",
    typeInField: "Fyll i rutan ”{field}”",
    chooseValueIn: "Välj ”{value}” i listan ”{field}”",
    chooseIn: "Välj i listan ”{field}”",
    typeValue: "Skriv ”{value}”",
    type: "Skriv texten",
    typeValueInCell: "Skriv ”{value}” i cell {cell}",
    typeInCell: "Fyll i cell {cell}",
    press: "Tryck på {keys}",
    pressNamed: "Tryck på {keys} ({name})",
    goTo: "Gå till {site}",
    open: "Öppna {app}",
    runIn: "Kör det här i {where}",
    runInTerminal: "Kör det här i terminalen",
    formulaInCell: "Skriv den här formeln i cell {cell}",
    formulaInSelected: "Skriv den här formeln i den markerade cellen",
    code: "Skriv den här koden",
    missed: { one: "{count} klick missades här", other: "{count} klick missades här" },
    touch: {
      one: "Pek- eller pennanvändning kan saknas här ({count} rapport)",
      other: "Pek- eller pennanvändning kan saknas här ({count} rapporter)",
    },
    captureNow: "Titta på den här skärmen",
  },
  formal: {
    click: {
      button: "Klicka på knappen ”{name}”.",
      link: "Klicka på länken ”{name}”.",
      menuItem: "Klicka på ”{name}” på menyn.",
      tab: "Klicka på fliken ”{name}”.",
      field: "Klicka i fältet ”{name}”.",
      checkbox: "Markera kryssrutan ”{name}”.",
      radio: "Välj alternativet ”{name}”.",
      dropdown: "Klicka på listrutan ”{name}”.",
      switch: "Klicka på reglaget ”{name}”.",
      picture: "Klicka på bilden ”{name}”.",
      other: "Klicka på ”{name}”.",
    },
    clickIn: "Klicka i fönstret ”{title}”.",
    clickBare: "Klicka.",
    clickTaskbar: "Klicka på ”{name}” i aktivitetsfältet.",
    rightClick: "Högerklicka på ”{name}”.",
    rightClickIn: "Högerklicka i fönstret ”{title}”.",
    rightClickBare: "Högerklicka.",
    selectRange: "Markera cellerna {range}.",
    fillDown: "Fyll cell {from} nedåt till cell {to}.",
    fillTo: "Fyll cell {from} till cell {to}.",
    fillColumn: "Fyll cell {from} nedåt i kolumnen.",
    typeValueInField: "Skriv ”{value}” i fältet ”{field}”.",
    typeInField: "Fyll i fältet ”{field}”.",
    chooseValueIn: "Välj ”{value}” i listan ”{field}”.",
    chooseIn: "Välj ett alternativ i listan ”{field}”.",
    typeValue: "Skriv ”{value}”.",
    type: "Skriv texten.",
    typeValueInCell: "Skriv ”{value}” i cell {cell}.",
    typeInCell: "Fyll i cell {cell}.",
    press: "Tryck på {keys}.",
    pressNamed: "Tryck på {keys} ({name}).",
    goTo: "Gå till {site}.",
    open: "Öppna {app}.",
    runIn: "Kör följande kommando i {where}.",
    runInTerminal: "Kör följande kommando i terminalen.",
    formulaInCell: "Skriv följande formel i cell {cell}.",
    formulaInSelected: "Skriv följande formel i den markerade cellen.",
    code: "Skriv följande kod.",
    missed: {
      one: "{count} klick spelades inte in här.",
      other: "{count} klick spelades inte in här.",
    },
    touch: {
      one: "Pek- eller pennindata kanske inte har spelats in här ({count} rapport).",
      other: "Pek- eller pennindata kanske inte har spelats in här ({count} rapporter).",
    },
    captureNow: "Granska den här skärmen.",
  },
  terminals: { powershell: "PowerShell", cmd: "Kommandotolken", bash: "Bash" },
  shortcuts: {
    selectAll: "Markera alla",
    copy: "Kopiera",
    cut: "Klipp ut",
    paste: "Klistra in",
    save: "Spara",
    print: "Skriv ut",
    find: "Sök",
    close: "Stäng",
    taskManager: "Aktivitetshanteraren",
    showDesktop: "Visa skrivbordet",
    fileExplorer: "Utforskaren",
    settings: "Inställningar",
    lock: "Lås",
    run: "Kör",
    clipboardHistory: "Urklippshistorik",
    snippingTool: "Skärmklipp",
  },
};
