import type { LanguagePhrases } from "../phrase.ts";

/**
 * Türkçe: names in “…”, and the polite "siz" imperative (-in/-ın) throughout, as Microsoft's
 * Turkish style does. A suffix never touches a name: it goes on a word after it ("öğesine",
 * "alanına", "düğmesine"), since the name's last vowel can't be known. Casual is the short
 * "“Kaydet” üzerine tıklayın"; plain uses the neutral "seçin" for a click; formal writes full
 * sentences naming the control, as Microsoft's Turkish procedures do.
 */
export const tr: LanguagePhrases = {
  casual: {
    click: {
      field: "“{name}” alanına tıklayın",
      namedField: "“{name}” üzerine tıklayın",
      textArea: "“{name}” üzerine tıklayın",
      other: "“{name}” üzerine tıklayın",
    },
    clickIn: "“{title}” içinde tıklayın",
    clickBare: "Tıklayın",
    clickTaskbar: "Görev çubuğunda “{name}” üzerine tıklayın",
    rightClick: "“{name}” üzerine sağ tıklayın",
    rightClickIn: "“{title}” içinde sağ tıklayın",
    rightClickBare: "Sağ tıklayın",
    selectRange: "“{range}” aralığını seçin",
    fillDown: "“{from}” hücresini “{to}” hücresine kadar aşağı doldurun",
    fillTo: "“{from}” hücresini “{to}” hücresine kadar doldurun",
    fillColumn: "“{from}” hücresini sütun boyunca aşağı doldurun",
    typeValueInField: "“{field}” alanına “{value}” yazın",
    typeInField: "“{field}” alanına yazın",
    chooseValueIn: "“{field}” içinde “{value}” seçin",
    chooseIn: "“{field}” içinde seçim yapın",
    typeValue: "“{value}” yazın",
    type: "Yazın",
    typeValueInCell: "{cell} hücresine “{value}” yazın",
    typeInCell: "{cell} hücresine yazın",
    press: "“{keys}” tuşuna basın",
    pressNamed: "“{keys}” ({name}) tuşuna basın",
    goTo: "“{site}” adresine gidin",
    open: "“{app}” uygulamasını açın",
    runIn: "{where} içinde çalıştırın",
    runInTerminal: "Terminalde çalıştırın",
    formulaInCell: "{cell} hücresine formülü yazın",
    formulaInSelected: "Seçili hücreye formülü yazın",
    code: "Bu kodu yazın",
    missed: { one: "Burada {count} tıklama kaçırıldı", other: "Burada {count} tıklama kaçırıldı" },
    touch: {
      one: "Dokunma veya kalem etkinliği kaydedilmemiş olabilir ({count} bildirim)",
      other: "Dokunma veya kalem etkinliği kaydedilmemiş olabilir ({count} bildirim)",
    },
    captureNow: "Bu ekranı yakalayın",
  },
  plain: {
    click: {
      button: "“{name}” düğmesini seçin",
      link: "“{name}” bağlantısını seçin",
      menuItem: "Menüden “{name}” öğesini seçin",
      tab: "“{name}” sekmesini seçin",
      field: "“{name}” kutusunu seçin",
      checkbox: "“{name}” onay kutusunu seçin",
      radio: "“{name}” seçeneğini belirleyin",
      dropdown: "“{name}” listesini açın",
      switch: "“{name}” anahtarını seçin",
      picture: "“{name}” resmini seçin",
      other: "“{name}” öğesini seçin",
    },
    clickIn: "“{title}” penceresinin içinde seçim yapın",
    clickBare: "Burayı seçin",
    clickTaskbar: "Görev çubuğunda “{name}” öğesini seçin",
    rightClick: "“{name}” öğesine sağ tıklayın",
    rightClickIn: "“{title}” penceresinin içinde sağ tıklayın",
    rightClickBare: "Burada sağ tıklayın",
    selectRange: "{range} hücrelerini seçin",
    fillDown: "{from} hücresini {to} hücresine kadar aşağı doldurun",
    fillTo: "{from} hücresini {to} hücresine kadar doldurun",
    fillColumn: "{from} hücresini sütun boyunca aşağı doldurun",
    typeValueInField: "“{field}” kutusuna “{value}” girin",
    typeInField: "“{field}” kutusunu doldurun",
    chooseValueIn: "“{field}” listesinden “{value}” seçin",
    chooseIn: "“{field}” listesinden seçim yapın",
    typeValue: "“{value}” girin",
    type: "Metni girin",
    typeValueInCell: "{cell} hücresine “{value}” girin",
    typeInCell: "{cell} hücresini doldurun",
    press: "{keys} tuşuna basın",
    pressNamed: "{keys} ({name}) tuşuna basın",
    goTo: "{site} adresine gidin",
    open: "{app} uygulamasını açın",
    runIn: "Bunu {where} içinde çalıştırın",
    runInTerminal: "Bunu terminalde çalıştırın",
    formulaInCell: "{cell} hücresine bu formülü girin",
    formulaInSelected: "Seçili hücreye bu formülü girin",
    code: "Bu kodu yazın",
    missed: { one: "Burada {count} tıklama kaçırıldı", other: "Burada {count} tıklama kaçırıldı" },
    touch: {
      one: "Burada dokunma veya kalem kullanımı eksik olabilir ({count} bildirim)",
      other: "Burada dokunma veya kalem kullanımı eksik olabilir ({count} bildirim)",
    },
    captureNow: "Bu ekrana bakın",
  },
  formal: {
    click: {
      button: "“{name}” düğmesine tıklayın.",
      link: "“{name}” bağlantısına tıklayın.",
      menuItem: "Menüde “{name}” öğesine tıklayın.",
      tab: "“{name}” sekmesine tıklayın.",
      field: "“{name}” alanının içine tıklayın.",
      checkbox: "“{name}” onay kutusunu seçin.",
      radio: "“{name}” seçeneğini belirleyin.",
      dropdown: "“{name}” açılan listesine tıklayın.",
      switch: "“{name}” anahtarına tıklayın.",
      picture: "“{name}” resmine tıklayın.",
      other: "“{name}” öğesine tıklayın.",
    },
    clickIn: "“{title}” penceresinin içine tıklayın.",
    clickBare: "Tıklayın.",
    clickTaskbar: "Görev çubuğunda “{name}” öğesine tıklayın.",
    rightClick: "“{name}” öğesine sağ tıklayın.",
    rightClickIn: "“{title}” penceresinin içine sağ tıklayın.",
    rightClickBare: "Sağ tıklayın.",
    selectRange: "{range} hücrelerini seçin.",
    fillDown: "{from} hücresini {to} hücresine kadar aşağı doldurun.",
    fillTo: "{from} hücresini {to} hücresine kadar doldurun.",
    fillColumn: "{from} hücresini sütun boyunca aşağı doldurun.",
    typeValueInField: "“{field}” alanına “{value}” yazın.",
    typeInField: "“{field}” alanını doldurun.",
    chooseValueIn: "“{field}” listesinde “{value}” öğesini seçin.",
    chooseIn: "“{field}” listesinde bir seçenek belirleyin.",
    typeValue: "“{value}” yazın.",
    type: "Metni yazın.",
    typeValueInCell: "{cell} hücresine “{value}” yazın.",
    typeInCell: "{cell} hücresini doldurun.",
    press: "{keys} tuşuna basın.",
    pressNamed: "{keys} ({name}) tuşuna basın.",
    goTo: "{site} adresine gidin.",
    open: "{app} uygulamasını açın.",
    runIn: "Aşağıdaki komutu {where} içinde çalıştırın.",
    runInTerminal: "Aşağıdaki komutu terminalde çalıştırın.",
    formulaInCell: "{cell} hücresine aşağıdaki formülü yazın.",
    formulaInSelected: "Seçili hücreye aşağıdaki formülü yazın.",
    code: "Aşağıdaki kodu yazın.",
    missed: {
      one: "Burada {count} tıklama kaydedilmedi.",
      other: "Burada {count} tıklama kaydedilmedi.",
    },
    touch: {
      one: "Burada dokunma veya kalem girişi kaydedilmemiş olabilir ({count} bildirim).",
      other: "Burada dokunma veya kalem girişi kaydedilmemiş olabilir ({count} bildirim).",
    },
    captureNow: "Bu ekranı inceleyin.",
  },
  terminals: { powershell: "PowerShell", cmd: "Komut İstemi", bash: "Bash" },
  shortcuts: {
    selectAll: "Tümünü seç",
    copy: "Kopyala",
    cut: "Kes",
    paste: "Yapıştır",
    save: "Kaydet",
    print: "Yazdır",
    find: "Bul",
    close: "Kapat",
    taskManager: "Görev Yöneticisi",
    showDesktop: "Masaüstünü göster",
    fileExplorer: "Dosya Gezgini",
    settings: "Ayarlar",
    lock: "Kilitle",
    run: "Çalıştır",
    clipboardHistory: "Pano geçmişi",
    snippingTool: "Ekran Alıntısı Aracı",
  },
};
