import type { LanguagePhrases } from "../phrase.ts";

/**
 * Українська: «ялинки» round names, the polite "ви" imperative in every tone (as Microsoft's
 * Ukrainian documentation addresses the reader); casual is the shortest label ("Натисніть «…»"),
 * plain uses the neutral "Виберіть" and everyday words, formal follows Microsoft's procedures.
 * Terminals are named as their windows are, so "у вікні «Командний рядок»" needs no declension.
 */
export const uk: LanguagePhrases = {
  casual: {
    click: {
      field: "Клацніть поле «{name}»",
      namedField: "Клацніть «{name}»",
      textArea: "Клацніть «{name}»",
      other: "Натисніть «{name}»",
    },
    clickIn: "Клацніть у вікні «{title}»",
    clickBare: "Клацніть",
    clickTaskbar: "Натисніть «{name}» на панелі завдань",
    typeValueInField: "Введіть «{value}» у поле «{field}»",
    typeInField: "Введіть текст у поле «{field}»",
    chooseValueIn: "Виберіть «{value}» у полі «{field}»",
    chooseIn: "Виберіть у полі «{field}»",
    typeValue: "Введіть «{value}»",
    type: "Введіть текст",
    typeValueInCell: "Введіть «{value}» у клітинку {cell}",
    typeInCell: "Введіть дані в клітинку {cell}",
    press: "Натисніть «{keys}»",
    goTo: "Перейдіть на «{site}»",
    open: "Відкрийте «{app}»",
    runIn: "Виконайте у вікні «{where}»",
    runInTerminal: "Виконайте в терміналі",
    formulaInCell: "Введіть формулу в клітинку {cell}",
    formulaInSelected: "Введіть формулу у вибрану клітинку",
    code: "Введіть цей код",
    missed: {
      one: "Тут пропущено {count} клацання",
      few: "Тут пропущено {count} клацання",
      many: "Тут пропущено {count} клацань",
      other: "Тут пропущено {count} клацань",
    },
    touch: {
      one: "Дії сенсором або пером могли не записатися ({count} подія)",
      few: "Дії сенсором або пером могли не записатися ({count} події)",
      many: "Дії сенсором або пером могли не записатися ({count} подій)",
      other: "Дії сенсором або пером могли не записатися ({count} подій)",
    },
    captureNow: "Зробіть знімок цього екрана",
  },
  plain: {
    click: {
      button: "Виберіть кнопку «{name}»",
      link: "Виберіть посилання «{name}»",
      menuItem: "Виберіть «{name}» у меню",
      tab: "Виберіть вкладку «{name}»",
      field: "Виберіть поле «{name}»",
      checkbox: "Позначте пункт «{name}»",
      radio: "Виберіть варіант «{name}»",
      dropdown: "Відкрийте список «{name}»",
      switch: "Виберіть перемикач «{name}»",
      picture: "Виберіть зображення «{name}»",
      other: "Виберіть «{name}»",
    },
    clickIn: "Натисніть у вікні «{title}»",
    clickBare: "Натисніть тут",
    clickTaskbar: "Виберіть «{name}» на панелі завдань",
    typeValueInField: "Введіть «{value}» у поле «{field}»",
    typeInField: "Заповніть поле «{field}»",
    chooseValueIn: "Виберіть «{value}» у списку «{field}»",
    chooseIn: "Виберіть значення у списку «{field}»",
    typeValue: "Введіть «{value}»",
    type: "Введіть текст",
    typeValueInCell: "Введіть «{value}» у клітинку {cell}",
    typeInCell: "Заповніть клітинку {cell}",
    press: "Натисніть {keys}",
    goTo: "Перейдіть на {site}",
    open: "Відкрийте {app}",
    runIn: "Виконайте це у вікні «{where}»",
    runInTerminal: "Виконайте це в терміналі",
    formulaInCell: "Введіть цю формулу в клітинку {cell}",
    formulaInSelected: "Введіть цю формулу у вибрану клітинку",
    code: "Введіть цей код",
    missed: {
      one: "Тут не записано {count} клацання",
      few: "Тут не записано {count} клацання",
      many: "Тут не записано {count} клацань",
      other: "Тут не записано {count} клацань",
    },
    touch: {
      one: "Тут може бракувати дотиків або дій пером ({count} подія)",
      few: "Тут може бракувати дотиків або дій пером ({count} події)",
      many: "Тут може бракувати дотиків або дій пером ({count} подій)",
      other: "Тут може бракувати дотиків або дій пером ({count} подій)",
    },
    captureNow: "Подивіться на цей екран",
  },
  formal: {
    click: {
      button: "Натисніть кнопку «{name}».",
      link: "Клацніть посилання «{name}».",
      menuItem: "Виберіть у меню пункт «{name}».",
      tab: "Відкрийте вкладку «{name}».",
      field: "Клацніть поле «{name}».",
      checkbox: "Установіть прапорець «{name}».",
      radio: "Виберіть параметр «{name}».",
      dropdown: "Відкрийте розкривний список «{name}».",
      switch: "Клацніть перемикач «{name}».",
      picture: "Клацніть зображення «{name}».",
      listItem: "Виберіть елемент «{name}».",
      other: "Клацніть «{name}».",
    },
    clickIn: "Клацніть у вікні «{title}».",
    clickBare: "Клацніть.",
    clickTaskbar: "Натисніть «{name}» на панелі завдань.",
    typeValueInField: "У полі «{field}» введіть «{value}».",
    typeInField: "Заповніть поле «{field}».",
    chooseValueIn: "У списку «{field}» виберіть «{value}».",
    chooseIn: "Виберіть значення у списку «{field}».",
    typeValue: "Введіть «{value}».",
    type: "Введіть текст.",
    typeValueInCell: "У клітинці {cell} введіть «{value}».",
    typeInCell: "Заповніть клітинку {cell}.",
    press: "Натисніть {keys}.",
    goTo: "Перейдіть на {site}.",
    open: "Відкрийте {app}.",
    runIn: "Виконайте наведену нижче команду у вікні «{where}».",
    runInTerminal: "Виконайте наведену нижче команду в терміналі.",
    formulaInCell: "У клітинці {cell} введіть наведену нижче формулу.",
    formulaInSelected: "У вибраній клітинці введіть наведену нижче формулу.",
    code: "Введіть наведений нижче код.",
    missed: {
      one: "Тут не записано {count} клацання.",
      few: "Тут не записано {count} клацання.",
      many: "Тут не записано {count} клацань.",
      other: "Тут не записано {count} клацань.",
    },
    touch: {
      one: "Дії сенсором або пером тут могли не записатися ({count} подія).",
      few: "Дії сенсором або пером тут могли не записатися ({count} події).",
      many: "Дії сенсором або пером тут могли не записатися ({count} подій).",
      other: "Дії сенсором або пером тут могли не записатися ({count} подій).",
    },
    captureNow: "Перегляньте цей екран.",
  },
  terminals: { powershell: "PowerShell", cmd: "Командний рядок", bash: "Bash" },
};
