import type { LanguagePhrases } from "../phrase.ts";

/**
 * Tiếng Việt: names in “…”, imperatives with no pronoun as Microsoft's Vietnamese documentation
 * writes them; casual uses Microsoft's "Bấm" (click) in the shortest form, plain the neutral "Chọn"
 * (select) and everyday words, and formal full sentences ending in a full stop.
 */
export const vi: LanguagePhrases = {
  casual: {
    click: {
      field: "Bấm trường “{name}”",
      namedField: "Bấm “{name}”",
      textArea: "Bấm “{name}”",
      other: "Bấm “{name}”",
    },
    clickIn: "Bấm trong “{title}”",
    clickBare: "Bấm",
    clickTaskbar: "Bấm “{name}” trên thanh tác vụ",
    rightClick: "Bấm chuột phải vào “{name}”",
    rightClickIn: "Bấm chuột phải trong “{title}”",
    rightClickBare: "Bấm chuột phải",
    selectRange: "Chọn “{range}”",
    fillDown: "Điền “{from}” xuống đến “{to}”",
    fillTo: "Điền “{from}” đến “{to}”",
    fillColumn: "Điền “{from}” xuống hết cột",
    typeValueInField: "Nhập “{value}” vào trường “{field}”",
    typeInField: "Nhập vào trường “{field}”",
    chooseValueIn: "Chọn “{value}” trong “{field}”",
    chooseIn: "Chọn trong “{field}”",
    typeValue: "Nhập “{value}”",
    type: "Nhập",
    typeValueInCell: "Nhập “{value}” vào ô {cell}",
    typeInCell: "Nhập vào ô {cell}",
    press: "Nhấn {keys}",
    pressNamed: "Nhấn {keys} ({name})",
    goTo: "Đi tới “{site}”",
    open: "Mở “{app}”",
    runIn: "Chạy trong {where}",
    runInTerminal: "Chạy trong cửa sổ dòng lệnh",
    formulaInCell: "Nhập công thức vào ô {cell}",
    formulaInSelected: "Nhập công thức vào ô đang chọn",
    code: "Nhập đoạn mã này",
    missed: { other: "Bỏ sót {count} lần bấm ở đây" },
    touch: { other: "Thao tác chạm hoặc bút có thể chưa được ghi ({count} báo cáo)" },
    captureNow: "Chụp màn hình này",
  },
  plain: {
    click: {
      button: "Chọn nút “{name}”",
      link: "Chọn liên kết “{name}”",
      menuItem: "Chọn “{name}” trong menu",
      tab: "Chọn tab “{name}”",
      field: "Chọn ô “{name}”",
      checkbox: "Chọn ô đánh dấu “{name}”",
      radio: "Chọn phương án “{name}”",
      dropdown: "Mở danh sách “{name}”",
      switch: "Chọn công tắc “{name}”",
      picture: "Chọn hình “{name}”",
      other: "Chọn “{name}”",
    },
    clickIn: "Chọn bên trong cửa sổ “{title}”",
    clickBare: "Chọn ở đây",
    clickTaskbar: "Chọn “{name}” trên thanh tác vụ",
    rightClick: "Bấm chuột phải vào “{name}”",
    rightClickIn: "Bấm chuột phải bên trong cửa sổ “{title}”",
    rightClickBare: "Bấm chuột phải ở đây",
    selectRange: "Chọn các ô {range}",
    fillDown: "Điền ô {from} xuống đến ô {to}",
    fillTo: "Điền ô {from} đến ô {to}",
    fillColumn: "Điền ô {from} xuống hết cột",
    typeValueInField: "Nhập “{value}” vào ô “{field}”",
    typeInField: "Điền vào ô “{field}”",
    chooseValueIn: "Chọn “{value}” từ danh sách “{field}”",
    chooseIn: "Chọn từ danh sách “{field}”",
    typeValue: "Nhập “{value}”",
    type: "Nhập văn bản",
    typeValueInCell: "Nhập “{value}” vào ô {cell}",
    typeInCell: "Điền vào ô {cell}",
    press: "Nhấn {keys}",
    pressNamed: "Nhấn {keys} ({name})",
    goTo: "Truy cập {site}",
    open: "Mở {app}",
    runIn: "Chạy lệnh này trong {where}",
    runInTerminal: "Chạy lệnh này trong cửa sổ dòng lệnh",
    formulaInCell: "Nhập công thức này vào ô {cell}",
    formulaInSelected: "Nhập công thức này vào ô đang chọn",
    code: "Nhập đoạn mã này",
    missed: { other: "Có {count} lần bấm bị bỏ sót ở đây" },
    touch: { other: "Có thể thiếu thao tác chạm hoặc bút ở đây ({count} báo cáo)" },
    captureNow: "Xem màn hình này",
  },
  formal: {
    click: {
      button: "Bấm vào nút “{name}”.",
      link: "Bấm vào liên kết “{name}”.",
      menuItem: "Bấm vào “{name}” trên menu.",
      tab: "Bấm vào tab “{name}”.",
      field: "Bấm vào trường “{name}”.",
      checkbox: "Chọn hộp kiểm “{name}”.",
      radio: "Chọn tùy chọn “{name}”.",
      dropdown: "Bấm vào danh sách thả xuống “{name}”.",
      switch: "Bấm vào công tắc “{name}”.",
      picture: "Bấm vào hình ảnh “{name}”.",
      other: "Bấm vào “{name}”.",
    },
    clickIn: "Bấm vào bên trong cửa sổ “{title}”.",
    clickBare: "Bấm chuột.",
    clickTaskbar: "Bấm vào “{name}” trên thanh tác vụ.",
    rightClick: "Bấm chuột phải vào “{name}”.",
    rightClickIn: "Bấm chuột phải vào bên trong cửa sổ “{title}”.",
    rightClickBare: "Bấm chuột phải.",
    selectRange: "Chọn các ô {range}.",
    fillDown: "Điền ô {from} xuống đến ô {to}.",
    fillTo: "Điền ô {from} đến ô {to}.",
    fillColumn: "Điền ô {from} xuống hết cột.",
    typeValueInField: "Trong trường “{field}”, nhập “{value}”.",
    typeInField: "Điền vào trường “{field}”.",
    chooseValueIn: "Trong danh sách “{field}”, chọn “{value}”.",
    chooseIn: "Chọn một tùy chọn trong danh sách “{field}”.",
    typeValue: "Nhập “{value}”.",
    type: "Nhập văn bản.",
    typeValueInCell: "Trong ô {cell}, nhập “{value}”.",
    typeInCell: "Điền vào ô {cell}.",
    press: "Nhấn {keys}.",
    pressNamed: "Nhấn {keys} ({name}).",
    goTo: "Truy cập {site}.",
    open: "Mở {app}.",
    runIn: "Chạy lệnh sau trong {where}.",
    runInTerminal: "Chạy lệnh sau trong cửa sổ dòng lệnh.",
    formulaInCell: "Trong ô {cell}, nhập công thức sau.",
    formulaInSelected: "Trong ô đang chọn, nhập công thức sau.",
    code: "Nhập đoạn mã sau.",
    missed: { other: "Có {count} lần bấm không được ghi lại tại đây." },
    touch: {
      other: "Thao tác chạm hoặc bút có thể không được ghi lại tại đây ({count} báo cáo).",
    },
    captureNow: "Xem lại màn hình này.",
  },
  terminals: { powershell: "PowerShell", cmd: "Dấu nhắc Lệnh", bash: "Bash" },
  shortcuts: {
    selectAll: "Chọn tất cả",
    copy: "Sao chép",
    cut: "Cắt",
    paste: "Dán",
    save: "Lưu",
    print: "In",
    find: "Tìm",
    close: "Đóng",
    taskManager: "Trình quản lý Tác vụ",
    showDesktop: "Hiển thị màn hình nền",
    fileExplorer: "File Explorer",
    settings: "Cài đặt",
    lock: "Khóa",
    run: "Chạy",
    clipboardHistory: "Lịch sử Bảng nhớ tạm",
    snippingTool: "Snipping Tool",
  },
};
