import type { LanguagePhrases } from "../phrase.ts";

/**
 * 繁體中文 (Taiwan): names in corner brackets 「{name}」, Taiwan's own terms (欄位, 索引標籤,
 * 核取方塊, 工作列, 儲存格) and a space between Chinese and Latin text or numbers, as Microsoft's
 * zh-TW style guide asks; no pronoun, as Chinese instructions need none. Casual is Steps' short
 * wording with "按一下" and "輸入"; plain uses the neutral "選取" and everyday words; formal writes
 * full sentences ending in "。" in the style of Microsoft's zh-TW procedure documentation.
 */
export const zhHant: LanguagePhrases = {
  casual: {
    click: {
      field: "按一下「{name}」欄位",
      namedField: "按一下「{name}」",
      textArea: "按一下「{name}」",
      other: "按一下「{name}」",
    },
    clickIn: "在「{title}」中按一下",
    clickBare: "按一下",
    clickTaskbar: "按一下工作列上的「{name}」",
    typeValueInField: "在「{field}」欄位中輸入「{value}」",
    typeInField: "在「{field}」欄位中輸入",
    chooseValueIn: "在「{field}」中選取「{value}」",
    chooseIn: "在「{field}」中選取",
    typeValue: "輸入「{value}」",
    type: "輸入",
    typeValueInCell: "在儲存格 {cell} 中輸入「{value}」",
    typeInCell: "在儲存格 {cell} 中輸入",
    press: "按「{keys}」",
    goTo: "前往「{site}」",
    open: "開啟「{app}」",
    runIn: "在 {where} 中執行",
    runInTerminal: "在終端機中執行",
    formulaInCell: "在儲存格 {cell} 中輸入公式",
    formulaInSelected: "在選取的儲存格中輸入公式",
    code: "輸入此程式碼",
    missed: { other: "這裡遺漏了 {count} 次點按" },
    touch: { other: "可能未錄製到觸控或手寫筆操作（{count} 則報告）" },
    captureNow: "擷取此畫面",
  },
  plain: {
    click: {
      button: "選取「{name}」按鈕",
      link: "選取「{name}」連結",
      menuItem: "在功能表中選取「{name}」",
      tab: "選取「{name}」索引標籤",
      field: "選取「{name}」欄位",
      checkbox: "選取「{name}」核取方塊",
      radio: "選擇「{name}」",
      dropdown: "開啟「{name}」清單",
      switch: "選取「{name}」開關",
      picture: "選取「{name}」圖片",
      other: "選取「{name}」",
    },
    clickIn: "在「{title}」視窗中選取",
    clickBare: "選取這裡",
    clickTaskbar: "選取工作列上的「{name}」",
    typeValueInField: "在「{field}」欄位中輸入「{value}」",
    typeInField: "填寫「{field}」欄位",
    chooseValueIn: "從「{field}」清單中選取「{value}」",
    chooseIn: "從「{field}」清單中選取",
    typeValue: "輸入「{value}」",
    type: "輸入文字",
    typeValueInCell: "在儲存格 {cell} 中輸入「{value}」",
    typeInCell: "填寫儲存格 {cell}",
    press: "按 {keys}",
    goTo: "前往 {site}",
    open: "開啟 {app}",
    runIn: "在 {where} 中執行此命令",
    runInTerminal: "在終端機中執行此命令",
    formulaInCell: "在儲存格 {cell} 中輸入此公式",
    formulaInSelected: "在選取的儲存格中輸入此公式",
    code: "輸入此程式碼",
    missed: { other: "這裡遺漏了 {count} 次點按" },
    touch: { other: "這裡可能缺少觸控或手寫筆操作（{count} 則報告）" },
    captureNow: "查看此畫面",
  },
  formal: {
    click: {
      button: "按一下「{name}」按鈕。",
      link: "按一下「{name}」連結。",
      menuItem: "按一下功能表上的「{name}」。",
      tab: "按一下「{name}」索引標籤。",
      field: "在「{name}」欄位中按一下。",
      checkbox: "選取「{name}」核取方塊。",
      radio: "選取「{name}」選項。",
      dropdown: "按一下「{name}」下拉式清單。",
      switch: "按一下「{name}」切換開關。",
      picture: "按一下「{name}」影像。",
      other: "按一下「{name}」。",
    },
    clickIn: "在「{title}」視窗中按一下。",
    clickBare: "按一下。",
    clickTaskbar: "按一下工作列上的「{name}」。",
    typeValueInField: "在「{field}」欄位中，輸入「{value}」。",
    typeInField: "填寫「{field}」欄位。",
    chooseValueIn: "在「{field}」清單中，選取「{value}」。",
    chooseIn: "在「{field}」清單中選取一個選項。",
    typeValue: "輸入「{value}」。",
    type: "輸入文字。",
    typeValueInCell: "在儲存格 {cell} 中，輸入「{value}」。",
    typeInCell: "填寫儲存格 {cell}。",
    press: "按 {keys}。",
    goTo: "瀏覽至 {site}。",
    open: "開啟 {app}。",
    runIn: "在 {where} 中執行下列命令。",
    runInTerminal: "在終端機中執行下列命令。",
    formulaInCell: "在儲存格 {cell} 中，輸入下列公式。",
    formulaInSelected: "在選取的儲存格中，輸入下列公式。",
    code: "輸入下列程式碼。",
    missed: { other: "此處有 {count} 次點按未被錄製。" },
    touch: { other: "此處可能未錄製到觸控或手寫筆輸入（{count} 則報告）。" },
    captureNow: "檢視此畫面。",
  },
  terminals: { powershell: "PowerShell", cmd: "命令提示字元", bash: "Bash" },
};
