import type { LanguagePhrases } from "../phrase.ts";

/**
 * 简体中文: names in Chinese quotation marks “{name}”, with a space between Chinese and Latin
 * text or numbers, as Microsoft's zh-CN style guide asks; no pronoun, as Chinese instructions
 * need none. Casual is Steps' short wording with "单击" and "输入"; plain uses the neutral
 * "选择" and everyday words; formal writes full sentences ending in "。" in the style of
 * Microsoft's zh-CN procedure documentation ("单击", "键入", "选中…复选框").
 */
export const zhHans: LanguagePhrases = {
  casual: {
    click: {
      field: "单击“{name}”框",
      namedField: "单击“{name}”",
      textArea: "单击“{name}”",
      other: "单击“{name}”",
    },
    clickIn: "在“{title}”中单击",
    clickBare: "单击",
    clickTaskbar: "单击任务栏上的“{name}”",
    rightClick: "右键单击“{name}”",
    rightClickIn: "在“{title}”中右键单击",
    rightClickBare: "右键单击",
    selectRange: "选择“{range}”",
    fillDown: "将“{from}”向下填充到“{to}”",
    fillTo: "将“{from}”填充到“{to}”",
    fillColumn: "将“{from}”沿该列向下填充",
    typeValueInField: "在“{field}”框中输入“{value}”",
    typeInField: "在“{field}”框中输入",
    chooseValueIn: "在“{field}”中选择“{value}”",
    chooseIn: "在“{field}”中选择",
    typeValue: "输入“{value}”",
    type: "输入",
    typeValueInCell: "在单元格 {cell} 中输入“{value}”",
    typeInCell: "在单元格 {cell} 中输入",
    press: "按“{keys}”",
    pressNamed: "按“{keys}”（{name}）",
    goTo: "转到“{site}”",
    open: "打开“{app}”",
    runIn: "在 {where} 中运行",
    runInTerminal: "在终端中运行",
    formulaInCell: "在单元格 {cell} 中输入公式",
    formulaInSelected: "在所选单元格中输入公式",
    code: "输入此代码",
    missed: { other: "此处遗漏了 {count} 次单击" },
    touch: { other: "可能未录制到触摸或笔操作（{count} 次报告）" },
    captureNow: "截取此屏幕",
  },
  plain: {
    click: {
      button: "选择“{name}”按钮",
      link: "选择“{name}”链接",
      menuItem: "在菜单中选择“{name}”",
      tab: "选择“{name}”选项卡",
      field: "选择“{name}”框",
      checkbox: "选择“{name}”复选框",
      radio: "选择“{name}”",
      dropdown: "打开“{name}”列表",
      switch: "选择“{name}”开关",
      picture: "选择“{name}”图片",
      other: "选择“{name}”",
    },
    clickIn: "在“{title}”窗口中选择",
    clickBare: "选择此处",
    clickTaskbar: "选择任务栏上的“{name}”",
    rightClick: "右键单击“{name}”",
    rightClickIn: "在“{title}”窗口中右键单击",
    rightClickBare: "在此处右键单击",
    selectRange: "选择单元格{range}",
    fillDown: "将单元格 {from} 向下填充到单元格 {to}",
    fillTo: "将单元格 {from} 填充到单元格 {to}",
    fillColumn: "将单元格 {from} 沿该列向下填充",
    typeValueInField: "在“{field}”框中输入“{value}”",
    typeInField: "填写“{field}”框",
    chooseValueIn: "从“{field}”列表中选择“{value}”",
    chooseIn: "从“{field}”列表中选择",
    typeValue: "输入“{value}”",
    type: "输入文字",
    typeValueInCell: "在单元格 {cell} 中输入“{value}”",
    typeInCell: "填写单元格 {cell}",
    press: "按 {keys}",
    pressNamed: "按 {keys}（{name}）",
    goTo: "转到 {site}",
    open: "打开 {app}",
    runIn: "在 {where} 中运行此命令",
    runInTerminal: "在终端中运行此命令",
    formulaInCell: "在单元格 {cell} 中输入此公式",
    formulaInSelected: "在所选单元格中输入此公式",
    code: "输入此代码",
    missed: { other: "此处遗漏了 {count} 次单击" },
    touch: { other: "此处可能缺少触摸或笔操作（{count} 次报告）" },
    captureNow: "查看此屏幕",
  },
  formal: {
    click: {
      button: "单击“{name}”按钮。",
      link: "单击“{name}”链接。",
      menuItem: "在菜单上单击“{name}”。",
      tab: "单击“{name}”选项卡。",
      field: "在“{name}”框中单击。",
      checkbox: "选中“{name}”复选框。",
      radio: "选择“{name}”选项。",
      dropdown: "单击“{name}”下拉列表。",
      switch: "单击“{name}”开关。",
      picture: "单击“{name}”图像。",
      other: "单击“{name}”。",
    },
    clickIn: "在“{title}”窗口中单击。",
    clickBare: "单击。",
    clickTaskbar: "单击任务栏上的“{name}”。",
    rightClick: "右键单击“{name}”。",
    rightClickIn: "在“{title}”窗口中右键单击。",
    rightClickBare: "右键单击。",
    selectRange: "选择单元格{range}。",
    fillDown: "将单元格 {from} 向下填充到单元格 {to}。",
    fillTo: "将单元格 {from} 填充到单元格 {to}。",
    fillColumn: "将单元格 {from} 沿该列向下填充。",
    typeValueInField: "在“{field}”框中，键入“{value}”。",
    typeInField: "填写“{field}”框。",
    chooseValueIn: "在“{field}”列表中，选择“{value}”。",
    chooseIn: "在“{field}”列表中选择一个选项。",
    typeValue: "键入“{value}”。",
    type: "键入文本。",
    typeValueInCell: "在单元格 {cell} 中，键入“{value}”。",
    typeInCell: "填写单元格 {cell}。",
    press: "按 {keys}。",
    pressNamed: "按 {keys}（{name}）。",
    goTo: "导航到 {site}。",
    open: "打开 {app}。",
    runIn: "在 {where} 中运行以下命令。",
    runInTerminal: "在终端中运行以下命令。",
    formulaInCell: "在单元格 {cell} 中，键入以下公式。",
    formulaInSelected: "在所选单元格中，键入以下公式。",
    code: "键入以下代码。",
    missed: { other: "此处有 {count} 次单击未被录制。" },
    touch: { other: "此处可能未录制到触摸或笔输入（{count} 次报告）。" },
    captureNow: "查看此屏幕。",
  },
  terminals: { powershell: "PowerShell", cmd: "命令提示符", bash: "Bash" },
  shortcuts: {
    selectAll: "全选",
    copy: "复制",
    cut: "剪切",
    paste: "粘贴",
    save: "保存",
    print: "打印",
    find: "查找",
    close: "关闭",
    taskManager: "任务管理器",
    showDesktop: "显示桌面",
    fileExplorer: "文件资源管理器",
    settings: "设置",
    lock: "锁定",
    run: "运行",
    clipboardHistory: "剪贴板历史记录",
    snippingTool: "截图工具",
  },
};
