import { useState } from "react";
import { useTranslation } from "react-i18next";

import type { RecorderBridge } from "../recorder-bridge";
import attributions from "./attributions.json";

/** One open-source component Steps ships (generated by scripts/attributions.mjs). */
export interface Attribution {
  ecosystem: "cargo" | "npm";
  name: string;
  version: string;
  licence: string;
}

const COMPONENTS = attributions as Attribution[];

/** The list in two parts: the program itself (Rust), then its screens (JavaScript). */
const GROUPS = (["cargo", "npm"] as const).map((ecosystem) => ({
  ecosystem,
  components: COMPONENTS.filter((component) => component.ecosystem === ecosystem),
}));

/** "MIT/Apache-2.0" and "Apache-2.0 OR MIT" are the same choice of licences. */
export function licenceKey(licence: string): string {
  const parts = licence.split(/\s+OR\s+|\//).map((part) => part.trim());
  return parts.length > 1 ? parts.sort().join(" or ") : licence;
}

/** The most common licences, most first, and how many components use any other. */
export function licenceSummary(components: Attribution[], shown = 4) {
  const counts = new Map<string, number>();
  for (const component of components) {
    const key = licenceKey(component.licence);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  const sorted = [...counts].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  const top = sorted.slice(0, shown);
  const others = sorted.slice(shown).reduce((sum, [, count]) => sum + count, 0);
  return { top, others };
}

/** One ecosystem's components, folded away until opened; its rows are only built then. */
function Group({
  ecosystem,
  components,
  recorder,
}: {
  ecosystem: Attribution["ecosystem"];
  components: Attribution[];
  recorder: RecorderBridge | undefined;
}) {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);
  return (
    <details
      className="mt-3 rounded-lg border border-panel px-3 py-2"
      onToggle={(event) => setOpen(event.currentTarget.open)}
    >
      <summary className="cursor-pointer">
        <h4 id={`open-source-${ecosystem}`} className="inline text-sm font-semibold text-navy">
          {t(`settings.about.ecosystem.${ecosystem}.title`, { count: components.length })}
        </h4>
        <span className="block pl-4 text-[13px] text-secondary">
          {t(`settings.about.ecosystem.${ecosystem}.help`)}
        </span>
      </summary>
      {open && (
        <table
          aria-labelledby={`open-source-${ecosystem}`}
          className="mt-2 w-full table-fixed border-collapse text-left text-[13px]"
        >
          <colgroup>
            <col className="w-[45%]" />
            <col className="w-[20%]" />
            <col />
          </colgroup>
          <thead className="text-secondary">
            <tr>
              <th scope="col" className="py-1.5 pr-3 font-semibold">
                {t("settings.about.component")}
              </th>
              <th scope="col" className="py-1.5 pr-3 font-semibold">
                {t("settings.about.componentVersion")}
              </th>
              <th scope="col" className="py-1.5 font-semibold">
                {t("settings.about.componentLicence")}
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-panel">
            {components.map((component) => (
              <tr key={`${component.ecosystem}:${component.name}@${component.version}`}>
                <td className="py-1.5 pr-3">
                  <button
                    type="button"
                    className="text-left font-medium [overflow-wrap:anywhere] text-blue hover:underline disabled:text-navy disabled:no-underline"
                    disabled={!recorder}
                    aria-label={t("settings.about.componentPage", { name: component.name })}
                    onClick={() =>
                      void recorder
                        ?.openWebPage(
                          component.ecosystem === "cargo" ? "crate" : "npm",
                          component.name,
                        )
                        .catch(() => undefined)
                    }
                  >
                    {component.name}
                  </button>
                </td>
                <td className="py-1.5 pr-3 font-mono text-[12px] text-secondary">
                  {component.version}
                </td>
                <td className="py-1.5 text-secondary [overflow-wrap:anywhere]">
                  {component.licence}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </details>
  );
}

/** Settings > About: the open-source components in this version, and their licences. */
export function OpenSource({ recorder }: { recorder: RecorderBridge | undefined }) {
  const { t } = useTranslation();
  // Five hundred rows are only built once someone opens the list.
  const [open, setOpen] = useState(false);
  const { top, others } = licenceSummary(COMPONENTS);
  const licences = [
    ...top.map(([licence, count]) => `${count} ${licence}`),
    ...(others > 0 ? [t("settings.about.openSourceMore", { count: others })] : []),
  ].join(", ");
  return (
    <section aria-labelledby="open-source-title" className="mt-5">
      <h3 id="open-source-title" className="mb-1.5 text-sm font-semibold text-navy">
        {t("settings.about.openSource")}
      </h3>
      <p className="text-[13px] leading-relaxed text-secondary">
        {t("settings.about.openSourceIntro", { count: COMPONENTS.length, licences })}
      </p>
      <p className="mt-1.5 text-[13px] leading-relaxed text-secondary">
        {t("settings.about.openSourceNote")}
      </p>
      <details
        className="card mt-3 px-[18px] py-3"
        onToggle={(event) => setOpen(event.currentTarget.open)}
      >
        <summary className="cursor-pointer text-sm font-semibold text-navy">
          {t("settings.about.openSourceShow", { count: COMPONENTS.length })}
        </summary>
        {open &&
          GROUPS.map(({ ecosystem, components }) => (
            <Group
              key={ecosystem}
              ecosystem={ecosystem}
              components={components}
              recorder={recorder}
            />
          ))}
      </details>
    </section>
  );
}
